### ISSUE TITLE
LinuxConfig: Does it flush to disk on .set() ?

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDMarketConnector#1002]
Talking through how Frontier Authorisation works between EDMC.py and EDMarketConnector.py I realised that it only works on Windows because the Refresh Token obtained in one is saved to `fdev_apikeys` and thus to the Registry.  On Windows that will then be picked up by the other program by the simple `config.get_list()`.

But on Linux the config is in a `configparser` file.  Does that write to disk for each `config.set()` or is the config that a newly run EDMC.py gets going to be out of date, still seeing a stale Refresh Token ?  AFAIK Frontier only allows the latest Refresh Token to actually work.  We might need a `config.write()` adding in some key places for Linux to work in this regard ?

**Comment by A-UNDERSCORE-D** [comment]
Solved by the above PR
