### ISSUE TITLE
Review and update versions of build software we use

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDMarketConnector#1009]
- [x] py2exe is dependabot'd
- [x] Windows SDK version
- [x] WinSparkle
- [x] WiX (windows installer build)

**Comment by Athanasius** [comment]
1. WinSparkle - 0.7.0 is still latest.  I've added a GH 'watch' on their Releases so I'll know if there's newer.
2. Windows SDK and WiX are from GitHub workflow 'windows-2019', which is as in 'Windows Server 2019'.
3. https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md lists Windows10SDK 19041 as the newest that has.
4. And it lists 3.11.4516 as the newest WiX it has.

So right now we're all good, on the latest available (at least on GH).

**Comment by Rixxan** [comment]
As of 5.9.1, I don't even think we need to have the Windows SDK and WiX is completely gone. This would leave just winsparkle and py2exe.
