### ISSUE TITLE
Ensure monitor.state['Credits'] is as correct as possible

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDMarketConnector#1014]
Currently we only set this from the `LoadGame` current balance, never updating it for any transactions.

We could also update the balance from CAPI `/profile` data, which would partially address any issue with losing track due to e.g. NPC crew wages.

**Comment by Athanasius** [comment]
Added as part of #1017

**Comment by Athanasius** [comment]
I believe this as good as it can be given the current Journal events.  Might need to review if Odyssey release has added anything new beyond v30 doc.

**Comment by Athanasius** [comment]
See #1185 which should be able to resolve this even better.  There might still be an issue around NPC crew wages, depending on if Status.json is definitely written when docked for any transactions changing the balance.

**Comment by A-UNDERSCORE-D** [comment]
I think its about as good as its gonna get? pending maybe using status.json? though there were concerns about race conditions in that

**Comment by Athanasius** [comment]
Yeah, at this stage I think we consider it in perfect working order (as best Journal allows) until someone reports an issue.
