### ISSUE TITLE
infi.systray can't be packaged with py2exe

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDMarketConnector#1020]
1. infi.systray depends on `pkg_resources`, which in turn depends upon (and seems to include a copy of inside its `_vendor` directory) `packages`.
2. At least one of those two extra modules is doing direct loading of modules themselves, and thus py2exe can't track what it needs to include in the build.

It's possible we might just be able to use an edited copy of infi.systray that doesn't depend on `pkg_resources`, but ideally py2exe will find a way to make it work.

**Comment by Athanasius** [comment]
This has been resolved upstream in py2exe, but we'll wait for the next stable release that includes the fix.

Ref: https://github.com/py2exe/py2exe/issues/88#issuecomment-845452161

**Comment by SayakMukhopadhyay** [comment]
Good to know that systray is going to be viable now.

**Comment by Athanasius** [comment]
I've confirmed the packaging is now working.
