### ISSUE TITLE
View -> Status causes menu to become disabled on Mac

### ISSUE THREAD

**Issue by demonbane** [EDCD/EDMarketConnector#103]
When I manually go to View -> Status, the status screen comes up just fine, but after that **every** item on the dropdown menus becomes grayed out. At first I thought that this was a modal issue, but even after closing the status window the menu stays in the "disabled" state. The only way to quit the application is to right click in the dock and manually go to "Quit".

**Comment by Marginal** [comment]
Unfortunately this is a [known bug](http://bugs.python.org/issue21757) in the version of Tk that ships with OSX. If you interact with the menubar while the Status window is displayed then the menubar contents are greyed out and remain greyed out.

**Comment by Athanasius** [comment]
MacOS is no longer supported for EDMC.
