### ISSUE TITLE
My Fleet Carrier showing up in Inara, but not showing an owner

### ISSUE THREAD

**Issue by cupoe13** [EDCD/EDMarketConnector#1032]
- Version 4.2.7
 - Game Version = Horizons
 - OS: Windows 10
 - OS Locale: English

**Describe the bug**
When I looked at Inara under My Fleet, I didn't see my Fleet Carrier that I purchased last night.  I've moved my whole fleet onto my carrier, and EDMC looks like it shows my ships are on that FC.  However, when I look at that FC in Inara, it doesn't say who the owner of the FC is.  When I looked at EDMC status, I noticed that my FC isn't in the list of Ships.  I'm trying to figure out if EDMC is working properly, and why Inara doesn't say I'm the owner of the FC.

[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/6436610/EDMarketConnector-debug.log)
[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/6436615/EDMarketConnector.log)

**Comment by VAKazakov** [comment]
EDMC can't tell to Inara, who is owner of FC, cuz there is no such info in journals
You need on Inara in commander section enable Import Frontier data feature.
After that, Inara will catch your FC and all it's data from FDev's API directly

**Comment by cupoe13** [comment]
Awesome, thanks for the help.  I figured it was something that EDMC pulled in, which is why I came here first.  Thanks for pointing me in the right direction.

**Comment by Athanasius** [comment]
More pointedly, Inara's API doesn't have any way to tell it about a Fleet Carrier that you own.

<https://inara.cz/inara-api-docs/>
