### ISSUE TITLE
Allow easy use of other Shipyard providers without accessing Settings.

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDMarketConnector#1033]
This idea comes from https://github.com/EDCD/EDMarketConnector/discussions/1031 .

The simplest implementation is going to be the " (alt)" text / extra hyperlink.

I quite like the idea of holding ALT causing the 'other' provider to be used, if that's actually possible easily with tkinter.

Tapping ALT during mouse-over to toggle the provider also has merits, and then requires some indication of the currently active one.

**Comment by Exsomnis78** [comment]
It would be really cool if we could use this ALT menu feature for all hyperlinks (systems and stations, EDSM vs INARA etc.)

**Comment by A-UNDERSCORE-D** [comment]
Related discussion: https://github.com/EDCD/EDMarketConnector/discussions/1031

**Comment by Rixxan** [comment]
Closing in favor of #1173
