### ISSUE TITLE
Document running multiple instances on Linux

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDMarketConnector#1034]
It should be possible to set up a per-Cmdr directory and set both `XDG_CONFIG_HOME` (app config) and `XDG_DATA_HOME` (additional app files, including the EDDN replay file) in order to run multiple instances of EDMarketConnector.py under the same Linux user.

This needs testing and then https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting#multi-accounting updating with a Linux section.

**Comment by A-UNDERSCORE-D** [comment]
#1035 fixes a related bug and the wiki has been updated.
