### ISSUE TITLE
This error messages have to be translated

### ISSUE THREAD

**Issue by norohind** [EDCD/EDMarketConnector#1056]
https://github.com/EDCD/EDMarketConnector/blob/dc7f4bdd1cd4d33cfec2a34ae862c444537165b5/plugins/eddb.py#L99
https://github.com/EDCD/EDMarketConnector/blob/dc7f4bdd1cd4d33cfec2a34ae862c444537165b5/plugins/eddn.py#L746
https://github.com/EDCD/EDMarketConnector/blob/dc7f4bdd1cd4d33cfec2a34ae862c444537165b5/plugins/inara.py#L331

**Comment by Athanasius** [comment]
Addressed by b862f6b00ab399db78cdd834ccefd8fd2e9424b9 and there was edsm as well in 389a781de36f26b8f699b67665c314d76f54938a

Uploading translations to OneSky now ....
