### ISSUE TITLE
Ensure we are reproducing any necessary licenses

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDMarketConnector#1057]
When I was looking into `infi.systray` licensing with a view to either straight up including it in our source, possibly in an edited form, or picking out the necessary win32 API calls to implement it ourselves ... I found it is BSD 3-clause.  That means we'd need (even if only packaging with py2exe) to include a copy of its license.

We should review *all* the third-party software that we package for Windows builds and ensure we are carrying a copy of their license and/or a reference to it upstream.

I propose `docs/licenses/<package>/<file>` as the standard for this.

**Comment by SayakMukhopadhyay** [comment]
Sometimes it is even necessary for the end user to be able to see these licenses. I am no expert but I have seen some apps displaying the licenses of its dependencies.

**Comment by Athanasius** [comment]
I've just seen something neat that PyCharm does.

Their Help > About has a link "Powered by <open source software>".  Clicking that opens another pop-up with a list of the OSS they  use.  Clicking the names takes you to the home page for the project.  I wonder if that's good enough to fulfill license obligations.  Maybe we could do the same sort of thing but have a 'license (local copy)' link as well.

**Comment by Athanasius** [comment]
FAO: @Rixxan 

When I originally addressed this I neglected to add `docs/Licenses` to the installer builds, which it should have been.

That needs addressing, and also any changes since this work syncing up, i.e. PIL/pillow license needs adding, and if `infi.systray` got dropped then no need to carry its license.

Whilst some included python modules might have a license that requires no such, they still need to be checked to find out if that's the case.

**Comment by Rixxan** [comment]
Should be resolved by b8a2f48
