### ISSUE TITLE
make values from File -> Status copyable

### ISSUE THREAD

**Issue by norohind** [EDCD/EDMarketConnector#1060]
**Describe the enhancement**

In `Status` window (Main EDMC window -> `File` -> `Status`) I want to be able to copy values, as example: system, where a ship stored, balance.

**Expected behavior**

Can pick out and copy to clipboard by ctrl+c any values from any tab from `Status` window.

**Considered workarounds**

Retype needed value manually. It is slow and I don't like it.

**Additional context**

None

**Comment by Athanasius** [comment]
The basic "copy a single text cell at a time" code is now merged into `develop`.
