### ISSUE TITLE
edmc crash/close randomly

### ISSUE THREAD

**Issue by Fabbry68** [EDCD/EDMarketConnector#1063]
Edmc close itself or crash without message or nothing, simply close randomly

EDMC version 5.0.0+c6712a7  the last, but the proiblem happened also in the past version

Windows 10 English language 
Last Game version Horizon, i had installed the Alpha Odissey but in alpha i never used edmc

[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/6481220/EDMarketConnector-debug.log)
[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/6481222/EDMarketConnector.log)

**Comment by NoFoolLikeOne** [comment]
I'm guessing that you are running the EDMC-Canonn plugin. We think there is something in the patrols module that is causing the crashes as there is growing evidence that disabling the patrols stops the crashes, 

Its proven to be very hard to track down this issue but will be putting our efforts into that module. My current thinking is that it is the word wrapping causing the problem.

**Comment by Fabbry68** [comment]
Thanks with Canonn disabled all is ok.

**Comment by Athanasius** [comment]
As this seems to be a third-party plugin issue I'm closing this.

@Fabbry68 - open/check for an issue over on the [EDMC-Canonn github](https://github.com/canonn-science/EDMC-Canonn/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).
