### ISSUE TITLE
Bug with default shipyard on first launch under Linux

### ISSUE THREAD

**Issue by norohind** [EDCD/EDMarketConnector#1076]
**Please complete the following information:**
 - Version: 5.0.1+6ada384
 - Game Version: Live
 - OS: Ubuntu 20.04
 - OS Locale: Russian

[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/6510385/EDMarketConnector-debug.log)

**Describe the bug**
On first run under Linux EDMC shows `Shipyard` is `False` in settings. It's keeping shows it until select any valid shipyard.

**To Reproduce**
1. Remove an existing config file
2. Run EDMC
3. Go to settings -> Configuration
4. In preferred websites `Shipyard` will be `False`

**Expected behavior**
I think EDMC should choose one of existing shipyeards by default

**Screenshots**

![](https://cdn.discordapp.com/attachments/251742967927144449/844591486548967434/unknown.png)

![](https://cdn.discordapp.com/attachments/251742967927144449/844592109993852928/unknown.png)

**Additional context**
None

**Comment by A-UNDERSCORE-D** [comment]
Fixed in https://github.com/EDCD/EDMarketConnector/pull/1075
