### ISSUE TITLE
Failure to display correct Suit line for 'Select Loadout'

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDMarketConnector#1080]
I just bought a Dominator suit, weapons for it, make a loadout, and then still on that screen selected `Equip Loadout`.

`2021-05-19 20:37:56.365 - DEBUG - 15828:2556:2556 monitor.EDLogs.parse_entry:974: KeyError getting suit loadout after switch, bad slot: 1 (4293000001)`

and UI showing `Suit:    <Unknown>`. This is in `develop` head 29c873943291185ce2599f784a0d904703f4c8ae

**Comment by Athanasius** [comment]
> What about if CDMC doesn't even reconize that I am playing Odyssey?

I've just checked and ...

... no, I still don't have the ability to read minds.

Would you care to expand on what you think should happen, what is happening, and the indications that it's not the same ?

**Comment by Athanasius** [comment]
I should also note that I've fixed the actual bug this issue refers to, and it's merged into `develop` now.

**Comment by A-UNDERSCORE-D** [comment]
@fh-thudson Can you clarify please. Preferably in a new bug report.

**Comment by Athanasius** [comment]
They showed up elsewhere, and I believe we resolved their issue, ignore for this.

**Comment by A-UNDERSCORE-D** [comment]
Do we want to close this?
