### ISSUE TITLE
Inara setCommanderInventoryCargo Item type is missing

### ISSUE THREAD

**Issue by chennin** [EDCD/EDMarketConnector#1088]
**Please check the [Known Issues](https://github.com/EDCD/EDMarketConnector/issues/618) in case this has already been reported.**

**Please also check if the issue is covered in our [Troubleshooting Guide](https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting).** It might be something with a known work around, or where a third party (such as EDSM) is causing logging that is harmless.

**Please complete the following information:**
 - Version: 5.0.1
 - Game Version: Live Odyssey
 - OS: Windows 10
 - OS Locale: English
 - If applicable: Browser: N/A
 - Please attach **BOTH** log files, by dragging and dropping them into this input:
     1. `%TEMP%\EDMarketConnector.log` from *immediately* after the bug occurs (re-running the application overwrites this file).
     1. %TEMP%\EDMarketConnector\EDMarketConnector-debug.log`.  See [Debug Log File](https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting#debug-log-files).  NB: If you don't have this log file then you're not running the latest version of the application and should update first to see if we already fixed the bug you're reporting.

[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/6519156/EDMarketConnector.log)
[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/6519157/EDMarketConnector-debug.log)

**Describe the bug**
```
2021-05-20 19:19:17.123 - INFO - 17556:25732:25732 plugins.inara.new_worker:1256: sending 7 events for Winter Ihernglass
2021-05-20 19:19:17.123 - DEBUG - 17556:25732:25732 plugins.inara.try_send_data:1289: sending data to API, attempt #0
2021-05-20 19:19:17.575 - WARNING - 17556:25732:25732 plugins.inara.send_data:1324: Inara	200 Item type is missing.
2021-05-20 19:19:17.575 - DEBUG - 17556:25732:25732 plugins.inara.send_data:1325: JSON data:
{"eventName": "setCommanderInventoryCargo", "eventTimestamp": "2021-05-20T23:18:43Z", "eventData": []}
2021-05-20 19:19:17.576 - WARNING - 17556:25732:25732 plugins.inara.send_data:1324: Inara	200 Item type is missing.
2021-05-20 19:19:17.576 - DEBUG - 17556:25732:25732 plugins.inara.send_data:1325: JSON data:
{"eventName": "setCommanderInventoryCargo", "eventTimestamp": "2021-05-20T23:18:56Z", "eventData": [{"itemName": "hydrogenfuel", "itemCount": 1}]}
```

**To Reproduce**
Have Inara API key entered
Dock
Buy or sell a commodity
Wait for EDMC to update Inara

**Expected behavior**
No error, also Inara inventory updated

**Screenshots**
https://i.imgur.com/xfl4y9D.png

**Comment by A-UNDERSCORE-D** [comment]
Strange. Those calls look correct. Ive asked the INARA people about it.

**Comment by A-UNDERSCORE-D** [comment]
Appears to be an INARA side bug. Please check again in a few hours.

**Comment by Athanasius** [comment]
Closing this as it was an issue on Inara, fixed several days ago.
