### ISSUE TITLE
EDMarketConnector 5.0.2 no longer starts.

### ISSUE THREAD

**Issue by Oliver-1xok** [EDCD/EDMarketConnector#1103]
**Please complete the following information:**
 - Version 5.0.2
 - OS: Xubuntu 20.4
 - OS Locale: English
 
**Describe the bug**
Instead of starting, the following traceback appears:
 ```
Traceback (most recent call last):
  File "./EDMarketConnector.py", line 55, in <module>
    import killswitch
  File "/home/steam/EDMarketConnector/EDMarketConnector-Release-5.0.2/killswitch.py", line 14, in <module>
    _current_version: semantic_version.Version = config.appversion_nobuild()
  File "/home/steam/EDMarketConnector/EDMarketConnector-Release-5.0.2/config.py", line 163, in appversion_nobuild
    return appversion().truncate('prerelease')
  File "/home/steam/EDMarketConnector/EDMarketConnector-Release-5.0.2/config.py", line 147, in appversion
    shorthash = git_shorthash_from_head()
  File "/home/steam/EDMarketConnector/EDMarketConnector-Release-5.0.2/config.py", line 130, in git_shorthash_from_head
    return shorthash + ('-WORKING-DIR-IS-DIRTY' if dirty else '')
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**To Reproduce**
1. Go to EDMarketConnector directory
2. ./EDMarketConnector.py
3. See the Traceback above

**Expected behavior**
EDMarketConnector should start

**Additional context**
Python 3.8.5
(This is the default version of Ubuntu 20.4.)

EDMarketConnector 5.0.1 starts without problems. 

[EDMarketConnector_output.log](https://github.com/EDCD/EDMarketConnector/files/6527044/EDMarketConnector_output.log)

**Comment by Athanasius** [comment]
As per https://github.com/EDCD/EDMarketConnector/issues/618

Running from source will throw an error if you do not have `git` available.  This is fixed in https://github.com/EDCD/EDMarketConnector/tree/main and if you're using a zip file to install then try https://github.com/EDCD/EDMarketConnector/archive/refs/heads/main.zip .

**Comment by DigitalNikki** [comment]
Same thing on Windows from source, and git is available in the command line.

**Comment by Athanasius** [comment]
> Same thing on Windows from source, and git is available in the command line.

With our lates, [5.0.4](https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F5.0.4) ?

**Comment by Oliver-1xok** [comment]
I could test it now with 5.0.4. Runs without problems, even if I use the tar ball. From my point of view this can be closed. Thank you!
