### ISSUE TITLE
Cleanly close on SIGTERM

### ISSUE THREAD

**Issue by A-UNDERSCORE-D** [EDCD/EDMarketConnector#1104]
Currently it appears that we dont cleanly shut down when presented with SIGTERM. We should probably do that.

**Comment by Rixxan** [comment]
@A-UNDERSCORE-D Do you happen to remember if this was on builds running from source or from compiled/exe builds?

**Comment by A-UNDERSCORE-D** [comment]
Likely both, but as I made the issue it's most likely on source after I `^C`ed it in a terminal

**Comment by Rixxan** [comment]
Awesome, I think then we handled this with #2147! 

Moving to close :)
