### ISSUE TITLE
Can't open plugins folder when running EDMC under other user

### ISSUE THREAD

**Issue by norohind** [EDCD/EDMarketConnector#1113]
**Please complete the following information:**
 - Version 5.0.2+a04a31d
 - Game Version: Live
 - OS: Windows 10
 - OS Locale: Russian
 - Browser chrome
 - Please attach **BOTH** log files, by dragging and dropping them into this input:
     
[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/6548557/EDMarketConnector.log)
[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/6548560/EDMarketConnector-debug.log)

**Describe the bug**
Getting an error when running EDMC under other user (via `runas`) and trying press `Open` button in File -> Settings -> Plugins

**To Reproduce**
1. Run EDMC under other user
2. Go to File -> Settings -> Plugins and find `Open` button.
3. Press `Open` button

**Expected behavior**
EDMC says to me that it can't open this folder for me
Or
EDMC open this folder

**Screenshots**
Screenshot of the error
![image](https://user-images.githubusercontent.com/60548839/119704224-d55a1f80-be70-11eb-907d-e297ea780ecc.png)

**Additional context**
I use `runas /savecread /user:Computer_2 "C:\Program Files (x86)\EDMarketConnector\EDMarketConnector.exe --suppress-dupe-process-popup --force-localserver-for-auth"` for run EDMC under other user.

**Comment by Athanasius** [comment]
Probably the easiest work around for this is to give permissions on the other user's files to the main user you run as.  After all you're only doing this for the user separation so as to keep Journal files separate, right ?

**Comment by Athanasius** [comment]
Except now I test this myself:

1. I can get to the other user's plugins folder without issue using Windows File Explorer.
2. Yet, indeed, trying to open it from the `runas`'d EDMarketConnector.exe yields the error as seen above.

We use `webbrowser.open(f'file:///{plugdir.get()}')` to perform this.  So if Windows is doing something weird with that 🤷 I'm not sure what we could do to work around the issue.

As this is 'only' looking at the plugins folder I'm tempted to say "just do that via other means".  The selection of Journal folder in the Configuration tab does work under these circumstances.

**Comment by Athanasius** [comment]
Ah, this might be a case of the string version for the UI being misleading.  We do set `config.plugin_dir_path` to the full path of the user application directory with the appname appended.

So this might just be that the webbrowser.open() bit needs changing to use the full path, not the string version ?  What I'm blathering about is that the Settings > Plugins tab *shows* is `AppData\Local\EDMarketConnector\plugins`, as that's what's set into the **Tk** string variable, and we use the **Tk string variable** in that webbrowser call.

So this might be as simple as just using config.plugin_dir_path in that webbrowser call.

I'll take a look tomorrow.

**Comment by Athanasius** [comment]
Upon further investigation our code is (mostly) fine.

1. I can re-create the issue with `runas`
2. But if I actually login to that other user it works perfectly fine.

Ergo this is something to do with `webbrowser.open()` and/or Windows itself causing different behaviour under `runas`.  I'm not inclined to investigate this very niche case any further, so I'll be marking this as "OS Issue" and "won't fix".

I'll document it in Known Issues/Troubleshooting, probably with some advice to just go find the folder manually.

**Comment by Athanasius** [comment]
See https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting#opening-plugins-location-doesn-39-t-work-under-39-runas-39

**Comment by Athanasius** [comment]
Note that this:
```python
    def __plugin_dir_open(self) -> None:
        # When running from a 'runas' command the simply webbrowser.open() fails
        # on Windows.
        if platform == 'win32':
            os.system(f'explorer.exe {config.plugin_dir_path}')

        else:
            webbrowser.open(f'file:///{config.plugin_dir_path}')
```
Does *NOT* solve the issue.  When not runas (but from installed .exe) this works as well as the webbrowser.open() version (excepting that you'll briefly see what looks like a cmd.exe window appear and disappear before the explorer.exe window opens).  Under runas you get the cmd.exe flicker, but no explorer.exe window.  So definitely an OS Issue.
