### ISSUE TITLE
Implement new/changed Inara events 2021-05

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDMarketConnector#1127]
From Discord:

> Artie (Inara):@Robby (EDDiscovery) @Athanasius (EDMC, ed.miggy.org) @T'kael (EDDI) and anybody who may be interested in it. :wink:

Inara API update for Odyssey:
- The header property isDeveloped was renamed to less confusing isBeingDeveloped. You don't need to change anything on your end though, the old property will still work.
- A new event addCommanderTravelLand for commanders landing on the celestial body was added (should be triggered at journal's Touchdown, DropShipDeploy and similar).
- The events addCommanderTravelCarrierJump, addCommanderTravelDock, addCommanderTravelFSDJump and setCommanderTravelLocation now contain optional properties for the star system coordinates, celestial body and celestial body coordinates. It's not required to set, it may however help to further precise commander's location when the star system is not in the database, etc.
- The events addCommanderTravelDock, addCommanderTravelFSDJump and addCommanderTravelLand are now having boolean properties isTaxiShuttle and isTaxiDropship for travelling with Apex or Frontline Solutions ships.
- New events setCommanderInventory, resetCommanderInventory, setCommanderInventoryItem, addCommanderInventoryItem and delCommanderInventoryItem added. Those are supposed for handling the new Odyssey events like ShipLockerMaterials and similar, you can however use it also for the existing engineering materials or ship cargo instead of the existing dedicated events (but you do not need to, they are not going anywhere).
- New events setCommanderSuitLoadout, updateCommanderSuitLoadout and delCommanderSuitLoadout for the suit loadouts added.

The documentation is as usually here: https://inara.cz/inara-api-docs/

**Comment by Athanasius** [comment]
Re: setCommanderTravelLocation - there might be a bug at the Inara end with not updating Cmdr profiles from this.  See https://discord.com/channels/102002327619121152/376773926220595201/850326733843857428 (Inara Discord)

**Comment by A-UNDERSCORE-D** [comment]
Should be fixed now I believe
