### ISSUE TITLE
String doesn't shown as translated but exists in .strings file

### ISSUE THREAD

**Issue by norohind** [EDCD/EDMarketConnector#1146]
- Version: 5.1.0+87da6af
 - Game Version: live
 - OS: Windows 10
 - OS Locale: Russian

[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/6601318/EDMarketConnector.log)
[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/6601320/EDMarketConnector-debug.log)

**Describe the bug**
Getting `Missing translation: 'Override Beta/Normal selection'`  in logs and untranslated string when open Coriolis settings, but this string is present in `ru.strings`.

**To Reproduce**
1. Set Russian language in EDMC (or any other not english language)
2. Open EDMC settings window
3. Open coriolis's settings tab
4. See untranslated `Override Beta/Normal selection` string
4-a. Open the log file and see there `l10n._Translations.translate:172: Missing translation: 'Override Beta/Normal selection'` message.

**Expected behavior**
Since this translated string is present in `ru.strings` I expected to see it in the program.

**Screenshots**
Screenshot of untranslated string in the program
![image](https://user-images.githubusercontent.com/60548839/120864444-a6952500-c5a5-11eb-90bd-5abf97b52adb.png)

**Additional context**
I have done some tests and figured out that l10n is bad with `/` symbol in key strings.

**Comment by mIRCon** [comment]
It affects all languages as it seems.

**Comment by Athanasius** [comment]
It was a typo in the code referencing the phrase; 'selection' instead of 'Selection'.  It'll work in the next release.
