### ISSUE TITLE
Request: Notes

### ISSUE THREAD

**Issue by DRA6N** [EDCD/EDMarketConnector#1156]
It would be nice to have a simple "add a note" command. This would create a .txt file where you can save important notes to come back to later.

**Comment by Athanasius** [comment]
This sounds like something a plugin could be written to do.

**Comment by DRA6N** [comment]
I agree, I just don't know how to write it.

**Comment by Rixxan** [comment]
Going to close this as "not planned", not because I think that this is necessarily a bad idea, but because it's out of scope for this repo. 

Though, if someone does end up making such a plugin, I think it might be neat!
