### ISSUE TITLE
No longer shows nice icon on taskbar.

### ISSUE THREAD

**Issue by Computer-Man** [EDCD/EDMarketConnector#1164]
Title really says it all.

![image](https://user-images.githubusercontent.com/6434260/121632684-c0ae9600-cac4-11eb-8e4a-820a361c482e.png)

**Comment by Athanasius** [comment]
What your bug report doesn't do is provide any of the information asked for in the [Bug Report Template](https://github.com/EDCD/EDMarketConnector/issues/new?assignees=&labels=bug%2C+unconfirmed&template=bug_report.md&title=).

This is working fine for me (literally just tested it) on Windows 10 Home 20H2, with all June 2021 updates.  So what OS, version and updates are you running ?

I do wonder if it might be related to #387

**Comment by Computer-Man** [comment]
The only fix is to make a shortcut to the exe on my desktop. Removing that shortcut reverts back to the start menu shortcut showing what I mentioned before.

This is the most weird interaction since while the shortcut is on my desktop the start menu one works fine with showing the correct icon.

**Comment by Athanasius** [comment]
> The only fix is to make a shortcut to the exe on my desktop. Removing that shortcut reverts back to the start menu shortcut showing what I mentioned before.
> 
> This is the most weird interaction since while the shortcut is on my desktop the start menu one works fine with showing the correct icon.
> 
> I really dislike this fix due to liking a clean empty desktop :(
> 
> Update: Deleting and replacing the shortcut in the C:\ProgramData\Microsoft\Windows\Start Menu\Programs directory fixed the problem and my clean desktop :D

Ah yes, I do have a shortcut for EDMarketConnector.exe on my desktop.  I think it's a manually made user-specific one.

At *some* stage I'll entirely redo the installer from scratch to be sure I consider all the options, and it might address this.  But that's low priority.

**Comment by NoFoolLikeOne** [comment]
I get this after every EDMC upgrade. Its a minor annoyance. I usually just remove it and then re-add it

**Comment by Rixxan** [comment]
Closing as fixed by the new installer logic. If this is not the case, please open a new ticket and I'll gladly look into it!
