### ISSUE TITLE
Feature request: Right click ship for Coriolis / EDSY

### ISSUE THREAD

**Issue by danielschill** [EDCD/EDMarketConnector#1173]
**Describe the enhancement**

Right click ship for Coriolis / EDSY

**Expected behavior**

When you right click on the ship name you are given a right click menu with both sites.

**Considered workarounds**

A plugin could add this same functionality

**Additional context**

Right click context menu with 2+ options; dont remove existing 1-click link or settings functionality

**Comment by A-UNDERSCORE-D** [comment]
Duplicate of #1033 somewhat. But its on the list. rclick might actually be better
