### ISSUE TITLE
Errors in parse_entry()

### ISSUE THREAD

**Issue by norohind** [EDCD/EDMarketConnector#1175]
- Version: 5.1.1+89edd84
 - Game Version: Live and Odyssey
 - OS: Windows 10
 - OS Locale: Russian
 - Please attach **BOTH** log files, by dragging and dropping them into this input:
[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/6680736/5.1.1_00.log)
[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/6680739/EDMarketConnector-debug.log)

**Describe the bug**
Got that errors in logs, I'm not sure if it is a bug

**To Reproduce**
1. Run EDMC
2. Run elite dangerous odyssey
3. Manage to get `LoadoutEquipModule` event in journal
4. Restart EDMC
5. Check EDMC logs for error

**Expected behavior**
No errors

**Screenshots**
None

**Additional context**
None

**Comment by A-UNDERSCORE-D** [comment]
These logs dont appear to have any errors related in them. Please check again for reprod.

**Comment by norohind** [comment]
Now I can't reproduce it too, so, I think, there is no problem, you can close the issue.
