### ISSUE TITLE
EDMC.exe is a threat for Windows Defender

### ISSUE THREAD

**Issue by Eventure-TCE** [EDCD/EDMarketConnector#1179]
- Version: 5.11
 - Game Version: Latest
 - OS: Windows 10
 - OS Locale: German

**Describe the bug**
Since yesterday, the EDMC.exe file is declared as a threat from Windows Defender and got moved into quarantine.

So the commandline executable is no longer usable for TCE Mk.II

Regards,
Eventure

**Comment by Athanasius** [comment]
Confirmed and now submitted to MicroSoft as a false positive (yes, I'm certain it doesn't actually contain malware).

**Comment by Athanasius** [comment]
Bad Microsoft didn't send me any notification when they reviewed this, nor does the web page for the report show *when* they re-assessed and cleared it.

Anyway, it will no longer be detected as malware by Windows Defender.

**Comment by hudak** [comment]
Maybe related, version 5.1.1 was quarantined by MalwareBytes. It also shows up on VIrusTotal as a trojan: https://www.virustotal.com/gui/file/6cbc90e1de74ff7eab5eeb84a57a04311b79097910fac359486ad772e5291989/detection

Do you super-duper promise it's not a malware? 😉

**Comment by hudak** [comment]
MalwareBytes Fingerprint:

> Malware.AI.3673790454, C:\PROGRAM FILES (X86)\EDMARKETCONNECTOR\EDMC.EXE, Quarantined, 1000000, 0, 1.0.42953, 4FD8A11435A9424ADAF997F6, dds, 01328424, 245BA0B991D2CC7682416CFACF483231, 4B83FF61235EEF1FEEF50724E849205156FEA232D09CA556E4A5398FCAE8B570

**Comment by Athanasius** [comment]
This is getting so tiring.

Our working theory is that authors of malware sometimes use python packaged to .exe using py2exe.  Then that malware gets picked up by the AV vendors and their process gets over-enthusiastic in choosing to identify parts of the .exe that are actually just standard py2exe code as being a part of the malware itself.

Then when they see out py2exe produced .exe files they think we're also malware.

There's a teeny, tiny chance that either py2exe itself has been trojanned, or even less likely that GitHub's servers (where the builds are done) has been compromised.  I really don't think that's likely.

The onus should *not* be on us to submit all our .exe files to many, many AV vendors for every release.

And, no, signing them wouldn't help that much.  There have been recent reports of actual malware being signed **by Microsoft**, so it really doesn't buy the end user much.  Even if it did, that's a cost of ~US$300 per year to have an Extended Validation certificate and keep renewing it.

**Comment by hudak** [comment]
@Athanasius sorry mate 😟 didn't realize the full history of the issue and just found the [troubleshooting notes](https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting#installer-and-or-executables-flagged-as-malicious-viruses)
