### ISSUE TITLE
Consider a 4.2.8 with auto-update disabled/removed.

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDMarketConnector#1190]
People don't always pay attention to the changelog displayed during an auto-update.

Due to the wat the 5.0 release happened, before we were aware that Python 3.9 had dropped Windows 7 support, we did rather pull the rug out from under Windows 7 users.

We **will not be reverting 5.x releases to using Python 3.8.x**.  Don't be fooled by the "2024-10" for 'End of support' for 3.8 on https://www.python.org/downloads/ .  Look at how 3.7.x has '2023-06-27' for that, yet it's been in security-only release mode since 3.7.10, and that means **no windows binary packages are made available**.  I am not going to do the extra work of compiling python on Windows in order to continue using 3.8.

Thee official python.org poloicy is "[1½ year of full support, 3½ more years of security fixes](https://www.python.org/dev/peps/pep-0602/#year-of-full-support-312-more-years-of-security-fixes)".  Python 3.8.0 was released 2019-10-14, and could have already gone to security-only, no windows binaries, around 2021-04-14. It did get 3.8.10 with binaries on 2021-05-03 though, but I'll be surprised if there are more windows binary releases.

The only sane thing for us to do is to continue to follow the latest released python version, perhaps skipping the .0 releases out of paranoia.  We'll certainly move to, e.g. Python 3.10.x, before the next major or minor release, e.g. 3.11.x comes out.

So, given all of that it's probably worth putting out a 4.2.8, perhaps based on latest Python 3.8.x:

- [ ] Disable auto-updates if we detect Windows < 8.
- [ ] Consider a big pop-up on each run of the program.  Or at least periodic reminder.
- [ ] Really this would go well with #519 - but that's more work than just putting out a 4.2.8 with updates disabled.

**Comment by Athanasius** [comment]
To be 100% clear, this 4.2.8 release would at most have the changes outlined in the OP.  We will **not be back-porting any Odyssey related support**.  If/When Frontier merges the current EDO code into Horizons if anything is broken in 4.2.x users get to keep the pieces.

Upgrade to a supported OS and use a supported version of EDMC.

**Comment by Rixxan** [comment]
Going off the latest [EDDN software notes, ](https://eddn.edcd.io/#software), There are virtually no users still on 4.x. Thus, even if this had been something worth considering, the relevance of such a feature is long gone. With that, closing as not planned.
