### ISSUE TITLE
Handle invalid temperatures/values in Status.json better

### ISSUE THREAD

**Issue by chennin** [EDCD/EDMarketConnector#1194]
- Version: 5.1.1
 - Game Version: Odyssey
 - OS: Windows 10
 - OS Locale: English
 - Please attach **BOTH** log files, by dragging and dropping them into this input:
     1. [EDMarketConnector.log.txt](https://github.com/EDCD/EDMarketConnector/files/6804733/EDMarketConnector.log.txt)
     1. The debug log is just more spam of the same error

**Describe the bug**

My root problem is EDMC-Screenshot can't process some pictures. But the reason is that, on the body I am on, the game UI is flapping between `0K` and blank for a temperature, and in Status.json, the temperature is sometimes printed as `"Temperature":-nan(ind)`  (and sometimes as `0.000000`). This also causes EDMC itself to print errors.

Offending file: [BadStatus.json.txt](https://github.com/EDCD/EDMarketConnector/files/6804724/BadStatus.json.txt)

EDMC is continuously printing the following stack trace:

```
2021-07-12 18:29:27.164 - ERROR - 129116:129368:129368 dashboard.Dashboard.process:196: Processing Status.json
Traceback (most recent call last):
  File "dashboard.pyc", line 185, in process
  File "json\__init__.pyc", line 346, in loads
  File "json\decoder.pyc", line 337, in decode
  File "json\decoder.pyc", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 142 (char 141)
```

Here's what the game says the body's temperature is: https://cdn.discordapp.com/attachments/733041833000697937/864274111383863316/unknown.png

**Comment by Athanasius** [comment]
1. This is obviously a game bug.
2. That line 196 of EDMC code *is* catching the exception.  It's the logging of it in the 'except'.
3. Yes, this will mean that this particular data then doesn't get passed to plugins.

Report it as a bug to Frontier, we're not going to add a workaround for their bug.

**Comment by Athanasius** [comment]
Do you have specific situations that trigger this bug?  i.e. certain bodies/locations, or does it feel more like some sort of race condition that's difficult to trigger on demand ?

**Comment by Athanasius** [comment]
> Do you have specific situations that trigger this bug? i.e. certain bodies/locations, or does it feel more like some sort of race condition that's difficult to trigger on demand ?

Ah, d'oh, I didn't spot the linked screenshot.

**Comment by Rixxan** [comment]
Want to check if this is a fixed issue or not, will add to the things-to-check after 5.10.
