### ISSUE TITLE
Dead link in docs/Releasing.md on line 243

### ISSUE THREAD

**Issue by Olliroxx** [EDCD/EDMarketConnector#1196]
**Please complete the following information:**
 - Version: `main` branch as of 12/7
 - Game Version: N/A
 - OS: N/A
 - OS Locale: N/A
 - Browser: Chrome

**Describe the bug**
docs/Releasing.md has a dead link.
it links to https://github...docs/docs/Releasing.md instead of https://github...docs/Releasing.md

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to docs/Releasing.md
3. Scroll down to `Adding killswitches`
2. Click on 'docs/Killswitches.md'
3. 404

**Expected behaviour**
No 404

**Comment by Athanasius** [comment]
Not dead, brainfarted.  I didn't need the `docs/` prefix, given both files are in the `docs/` directory.

I've fixed it in `develop`, but need to check the merge from there into `main` before it'll be fixed there.

**Comment by Athanasius** [comment]
It's in `main` now.
