### ISSUE TITLE
EDMC 5.1.0 is being reported as infected with a trojan dropper by Windows Defender

### ISSUE THREAD

**Issue by toqueville** [EDCD/EDMarketConnector#1201]
**Please complete the following information:**
 - Version: 5.1.0 installer
 - OS: Windows 10
 - OS Locale: [e.g. English, French, Serbian...]

**Describe the bug**
Windows Defender is detecting Trojan:Win32/Zpevdo.B inside the EDMarketConnector 5.1.0 installer.

**To Reproduce**
1. Download EDMarketConnector_win_5.1.0.msi on windows 10
2. See threat blocked

**Expected behavior**
Expected EDMC to not be reported as infected.

**Screenshots**
![image](https://user-images.githubusercontent.com/650139/126662109-84820088-4536-4427-b711-5f1eed3a9c78.png)

**Comment by Athanasius** [comment]
https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting#installer-and-or-executables-flagged-as-malicious-viruses

**Comment by Athanasius** [comment]
I'm also wondering why you're not just trying the latest, 5.1.1, anyway.

Although it might encounter the same issue.

**Comment by toqueville** [comment]
5.1.1 isn't flagged, I had an older installer on my drive that got flagged this morning, and figured you'd want to know.  Did you manage to find time to submit the files to the av vendors to get un-flagged?

**Comment by toqueville** [comment]
https://www.microsoft.com/en-us/wdsi/submission/0a166d06-cf47-49fe-ac42-17b6f65d05be

Submitted it to Microsoft as a false positive

**Comment by toqueville** [comment]
Analyst comments:
We have removed the detection.
