### ISSUE TITLE
Some strange exceptions in logs when running from source code

### ISSUE THREAD

**Issue by norohind** [EDCD/EDMarketConnector#1207]
**Please complete the following information:**
 - Version: 5.1.3-beta0+c481aa0.DIRTY (running from sources)
 - Game Version: Live
 - OS: Windows 10
 - OS Locale: Russian
[5.1.2_00.log](https://github.com/EDCD/EDMarketConnector/files/6913514/5.1.2_00.log)
[EDMarketConnector-debug-5.1.2_[00,01].log](https://github.com/EDCD/EDMarketConnector/files/6913515/EDMarketConnector-debug-5.1.2_.00.01.log)

**Describe the bug**
When running EDMC from sources getting this about every second in logs
```
Exception ignored on calling ctypes callback function: <function EDLogs.game_running.<locals>.callback at 0x000002546C876D30>
Traceback (most recent call last):
  File "F:\ftpRoot\ED\EDMarketConnector\monitor.py", line 1917, in callback
    name = WindowTitle(hWnd)
  File "F:\ftpRoot\ED\EDMarketConnector\monitor.py", line 1910, in WindowTitle
    length = GetWindowTextLength(h) + 1
ctypes.ArgumentError: argument 1: <class 'OverflowError'>: int too long to convert
Exception ignored on calling ctypes callback function: <function EDLogs.game_running.<locals>.callback at 0x000002546C876D30>
Traceback (most recent call last):
  File "F:\ftpRoot\ED\EDMarketConnector\monitor.py", line 1917, in callback
    name = WindowTitle(hWnd)
  File "F:\ftpRoot\ED\EDMarketConnector\monitor.py", line 1910, in WindowTitle
    length = GetWindowTextLength(h) + 1
ctypes.ArgumentError: argument 1: <class 'OverflowError'>: int too long to convert
```

**To Reproduce**
1. Get EDMC source code (c481aa0 commit)
2. Install dependencies according to requirements.txt
3. Run EDMarketConnector.py
4. See this ignored exceptions in logs

**Expected behavior**
No exceptions in logs.

**Screenshots**
None

**Additional context**
I don't encounter with it when running from msi installed 5.1.2.

**Comment by A-UNDERSCORE-D** [comment]
Out of curiosity, how long had your machine been running previous to this?

**Comment by norohind** [comment]
5 days

**Comment by A-UNDERSCORE-D** [comment]
Okay well this is a bug that we cant exactly fix. either the API returned something _very_ weird. or you had a window with one HUGE title, to the point that _windows_ should break before python does, as that exception is thrown when the size is larger than `sys.maxsize`, which by default in the python versions we ship is `(1 << 63) - 1`, or, the maximum value of a 64bit int.

The thing is windows at that point probably would complain that something overflowed its long (or just silently corrupt it, either or). So one of a few things could happen here:

1. You _actually_ had a window with a title that has more than `9_223_372_036_854_775_807` characters long (I doubt it)
2. Some windows bug caused the string to maybe not end with a `\0` thus causing a buffer overrun (I doubt this too)
3. Some python bug caused the C FFI call to break somewhere, and THAT caused the above overrun (I'd believe this before a windows bug of that magnitude, but still, lolno)
4. Cosmic ray flipped a bit in memory causing the aforementioned overrun (This one I might actually believe)
5. The call errored in some way and python got fed garbage (This one is actually possible, but still unlikely)
6. You have been cursed by some IT god.

Take your pick of which of those you'd like, but none of them are EDMCs fault :D -- Im going to mark this as wontfix until someone else sees it and we get a reprod.

**Comment by Athanasius** [comment]
The plain log file, which is the only one of the two with the 'Overflow' error in it, on this issue starts:

```python
2021-08-02 00:27:28.333 - INFO - 244668:244672:244672 EDMarketConnector.__main__:1658: Startup v5.1.3-beta0+c481aa0.DIRTY : Running on Python v3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
```
i.e. 64-bit Python.

Our code, **specifically** the ctypes stuff for windows API calls, **does not work on 64-bit Python**.  This is noted in https://github.com/EDCD/EDMarketConnector/wiki/Running-from-source#ensure-python-is-installed

So, if you're going to run from source please ensure you're using a 32-bit version of Python.
