### ISSUE TITLE
EDMC wrong current status guess 

### ISSUE THREAD

**Issue by norohind** [EDCD/EDMarketConnector#1208]
**Please complete the following information:**
 - Version: 5.1.2+066bd60
 - Game Version: Live
 - OS: Windows 10
 - OS Locale: Russian
[5.1.2_01.log](https://github.com/EDCD/EDMarketConnector/files/6913532/5.1.2_01.log)
[EDMarketConnector-debug-5.1.2_[00,01].log](https://github.com/EDCD/EDMarketConnector/files/6913533/EDMarketConnector-debug-5.1.2_.00.01.log)
[Celaeno.2021-08-02T00.42.35-5.1.2_01.zip](https://github.com/EDCD/EDMarketConnector/files/6913535/Celaeno.2021-08-02T00.42.35-5.1.2_01.zip)

**Describe the bug**
Firstly about some conditions: game isn't running, last game session was in horizons, I left my ship in deep space, edmc was restarted since last game session. 
Now I'm pressing "Update" button and EDMC saying "Docked but unknown station: EDO Settlement?". I was told "?" in the end of message mean it's EDMC guess, but guess is wrong because:
1. I left my ship in space and I can't be docked. 
2. I can't be docked in EDO settlement because the last game session was in horizons.

**To Reproduce**
1. Run and play horizons with EDMC running, left ship in deep space, not docked
2. Exit the game, exit EDMC
3. Start EDMC
4. Press "Update" button
5. See a wrong guessing

**Expected behavior**
EDMC correctly detect my cmdr current status.

**Screenshots**
Screenshot where we can see the message with guessing
![image](https://user-images.githubusercontent.com/60548839/127787115-d3585699-d4a8-4310-b7d8-31c3a09a2294.png)

**Additional context**
I also performed "Save Raw Data", result file is attached under `Celaeno.2021-08-02T00.42.35-5.1.2_01.zip` name (I had to ziped it because GitHub don't allow uploading json files here).

**Comment by hgrahamcs** [comment]
I have encountered the same issue with the same steps for reproduction.
