### ISSUE TITLE
Bitdefender antivirus detected trojan in msi package in 5.0+ EDMC version

### ISSUE THREAD

**Issue by asyslinux** [EDCD/EDMarketConnector#1211]
- Version: 5.0+ 5.1+...
 - OS:Windows 10
 - OS Locale: English
 - Antivirus: Bitdefender

  All versions of EDMC (msi package) starting from 5.0+ is detected by Bitdefender antivirus as: Trojan.GenericKD.46724790
  Please fix it with Bitdefender developers.

**Comment by A-UNDERSCORE-D** [comment]
We know. Its not us, there isnt much we can do other than report false positives (which you should do as well)

**Comment by Athanasius** [comment]
Please read over https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting#installer-and-or-executables-flagged-as-malicious-viruse

As my colleague said, there's little *we* can do about these false positives other than report them as they happen.  It's much easier if any user finding such quickly checks with us and then does that.
