### ISSUE TITLE
config.get_bool doesn't return custom default value

### ISSUE THREAD

**Issue by norohind** [EDCD/EDMarketConnector#1222]
**Please complete the following information:**
 - Version: 5.1.3-beta0+6e7ef6d.DIRTY
 - Game Version: Live
 - OS: Windows 10
 - OS Locale: Russian

**Describe the bug**
I tried to perform `config.get_bool('key', default=True)` with non-existent key, but didn't get my custom default value. Instead of this, I'm getting 0 (int type). So, the problem: `config.get_bool` with custom `default` value doesn't return this default value if key doesn't exists.

**To Reproduce**
1. Execute in a user plugin `config.get_bool('key', default=True)` with definitely not existing key and with custom `default` keyword argument seted (in my case I seted it to `True`)
2. See how it will return you `0` (int type), not `True`

**Expected behavior**
Get my custom default value

**Screenshots**
None

**Additional context**
 I've done small research and figured out, `get_bool` relies to `get_int` (in windows config implementation, at least) and `get_int` indeed returning it default value (0, int) but since 0 isn't None, `get_bool` isn't going to give me default value and giving me useless 0.

**Comment by norohind** [comment]
I applied it as quick fix for plugin development purposes, FYI
```patch
diff --git a/config.py b/config.py
index 6b9d301..621e2b7 100644
--- a/config.py
+++ b/config.py
@@ -588,7 +588,7 @@ class WinConfig(AbstractConfig):

         Implements :meth:`AbstractConfig.get_bool`.
         """
-        res = self.get_int(key)
+        res = self.get_int(key, default=default)
         if res is None:
             return default  # type: ignore # Yes it could be None, but we're _assuming_ that people gave us a default


```

**Comment by inorton** [comment]
You could make it do "default=(default == True)" to always ensure a boolean
return

**Comment by A-UNDERSCORE-D** [comment]
> You could make it do "default=(default == True)" to always ensure a boolean return

Nope, would make things inconsistent, if you break it you get to keep the pieces
