### ISSUE TITLE
MalwareBytes flagged EDMC 5.1.3-1a0b4ae

### ISSUE THREAD

**Issue by SirWumpus** [EDCD/EDMarketConnector#1247]
This morning MalwareBytes classified EDMC as malware (report below).  I've been using this software for a few years 1st with ED Horizons now Odyssey.  Yesterday EDMC downloaded an update and this morning Malware bytes flagged it.  I've made similar report to MalwareBytes Support.

While I suspect its a false-positive on the part of MalwareBytes, I felt I should inform you in case something snuck in or maybe there is an outdated library with a security issue being used and it just needs a newer version, etc.

Thank you.
Anthony Howe

---MalwareBytes Report---
Malwarebytes
www.malwarebytes.com

-Log Details-
Scan Date: 8/15/21
Scan Time: 8:05 AM
Log File: 03e1105e-fdc1-11eb-92be-4ccc6a8150b4.json

-Software Information-
Version: 4.4.4.126
Components Version: 1.0.1413
Update Package Version: 1.0.44162
License: Premium

-System Information-
OS: Windows 10 (Build 19043.1165)
CPU: x64
File System: NTFS
User: System

-Scan Summary-
Scan Type: Threat Scan
Scan Initiated By: Scheduler
Result: Completed
Objects Scanned: 353961
Threats Detected: 1
Threats Quarantined: 0
Time Elapsed: 5 min, 31 sec

-Scan Options-
Memory: Enabled
Startup: Enabled
Filesystem: Enabled
Archives: Enabled
Rootkits: Disabled
Heuristics: Enabled
PUP: Detect
PUM: Detect

-Scan Details-
Process: 0
(No malicious items detected)

Module: 0
(No malicious items detected)

Registry Key: 0
(No malicious items detected)

Registry Value: 0
(No malicious items detected)

Registry Data: 0
(No malicious items detected)

Data Stream: 0
(No malicious items detected)

Folder: 0
(No malicious items detected)

File: 1
Malware.AI.3673790454, C:\PROGRAM FILES (X86)\EDMARKETCONNECTOR\EDMC.EXE, No Action By User, 1000000, 0, 1.0.44162, 4FD8A11435A9424ADAF997F6, dds, 01378684, C98EB5ADAFB89A51605DE9D472764F66, 90BFE8F033DFBC382131C8086EE2A0AC831A1BFEDFFCDE0BC6C7BDAEFE104B6F

Physical Sector: 0
(No malicious items detected)

WMI: 0
(No malicious items detected)

(end)

**Comment by norohind** [comment]
At the moment it is assumed that this is a false positive, see https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting#installer-and-or-executables-flagged-as-malicious-viruses.

**Comment by SirWumpus** [comment]
I've not seen any repeat alerts from MalwareBytes concerning this instance, so I'll assume they dealt with it. Thank you for your time and attention.
