### ISSUE TITLE
Compile py2exe runstubs from source

### ISSUE THREAD

**Issue by A-UNDERSCORE-D** [EDCD/EDMarketConnector#1248]
On the theory that by re-compiling py2exe rather than using their distributed binaries, we can avoid at least SOME AV detection, this will be something to try when I can figure out how _exactly_ to compile everything

**Comment by Rixxan** [comment]
Will need to re-review if this is worth doing - the last few releases + combined with code signing has made a bunch of AV's shut up.

**Comment by A-UNDERSCORE-D** [comment]
May or may not work; but if you're signing its likely not worth it.
