### ISSUE TITLE
"Always on top" causes the Software Update dialog to appear *behind* the main application window.

### ISSUE THREAD

**Issue by wegotourselvesareader** [EDCD/EDMarketConnector#1262]
- Version: 5.1.3+1a0b4ae

**Describe the bug**
If the Appearance option "Always on top" is enabled, and the user then triggers the update check manually (Help -> Check for Updates...), the spawned "Software Update" dialog appears *behind* the main application window, instead of in front of it; the main application window obscures the spawned dialog.

If "Always on top" is not enabled, then the spawned "Software Update" appears in front of the main application window as expected.

**To Reproduce**
1. Enable "Always on top"
2.  Manually check for updates
3. Disable "Always on top"
4. Manually check for updates

**Expected behavior**
Child windows and dialogs should inherit the z-order properties of their parents.

**Comment by Athanasius** [comment]
There's nothing we can do about this due to the updater checker using a third-party DLL.  We have no control over its window placement.

Perhaps in some theoretical future if we write our own full update checking and thus don't use that DLL any more.
