### ISSUE TITLE
Minor ResourceWarning in Inara plugin, unclosed SSLSocket

### ISSUE THREAD

**Issue by chennin** [EDCD/EDMarketConnector#1267]
- Version: 5.1.3+UNKNOWN

Running on 32-bit Python 3.9.6 on Windows, from the zip download and via Python, not the exe. ie:

```
C:\Users\Chris\Downloads\EDMarketConnector-stable>py -V
Python 3.9.6
C:\Users\Chris\Downloads\EDMarketConnector-stable>py -W all EDMarketConnector.py 1>EDMC.log 2>&1
```

 - Game Version: Odyssey
 - OS: Windows 10
 - OS Locale: English

 - Please attach **BOTH** log files, by dragging and dropping them into this input:

[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/7068483/EDMarketConnector-debug.log)
[EDMC.log](https://github.com/EDCD/EDMarketConnector/files/7068491/EDMC.log)

**Describe the bug**

ResourceWarning on shutdown from the Inara plugin (I assume). Minor, but was asked to open the issue.
```
sys:1: ResourceWarning: unclosed <ssl.SSLSocket fd=2144, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=0, laddr=('2601:18f:900:653:a88d:788:f25a:fd2', 54910, 0, 0), raddr=('2a01:28:ca:112::1:832', 443, 0, 0)>
```
```
$ dig +short aaaa inara.cz
2a01:28:ca:112::1:832
```

**To Reproduce**
1. Start EDMC
2. (I think this is needed) Start the game and log in
3. Close EDMC

**Comment by A-UNDERSCORE-D** [comment]
Yeah its on the list, plugins dont clean up their messes super well

**Comment by Rixxan** [comment]
Hello @chennin!

I know it's been quite a while since you opened this issue, but as one of the new maintainers I'm trying to take triage of various issues. I can't seem to recreate this error on 5.10.0, and I was wondering if it still appears to occur for you, or what steps or customizations may be needed to a default test setup to recreate this issue. 

Thanks!

**Comment by chennin** [comment]
I tried to retest and I don't *seem* to have the problem anymore, on v5.10.1+UNKNOWN (downloaded Windows zip from github) Running on Python v3.10.4. But, these days I am both on Linux primarily and not playing much Elite.

**Comment by Rixxan** [comment]
Thanks for the update. Given that, I'm going to close this one out. 

Of course, if someone does manage to recreate it, please reopen this report so we can take a look at it!
