### ISSUE TITLE
util_ships.py:ship_file_name() could use `pathlib.PureWindowsPath.is_reserved()`

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDMarketConnector#1268]
Rather than trying to maintain a list of 'reserved' file names ourselves.

**Comment by A-UNDERSCORE-D** [comment]
note that is_reserved is available on `Path` itself as well, which would be even cleaner than going directly to PureWindowsPath *and* would mean no need to a platform guard

**Comment by A-UNDERSCORE-D** [comment]
close != comment. Whoops.
