### ISSUE TITLE
EDMC Asking for Frontier re-auth more often that it should

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDMarketConnector#1330]
> during a single gaming session. EDMC will just decide it needs to re-auth and pops up a browser window for me to log in to the frontier API again. This can happen two or three times in a 6-7 hour gaming session.
https://forums.frontier.co.uk/threads/elite-dangerous-market-connector-edmc.548869/post-9589152

> Happy Daze: Since the last ED update every time I start ED when EDMC is running the ED website verifying data use is run. Very annoying. Is anyone else experiencing this, or perhaps a setting I missed?
https://discord.com/channels/164411426939600896/251742967927144449/905539874038353951

**Comment by Unknown-Zombie** [comment]
Here's my EDMC debug log, as requested from that forum thread:
[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/7487510/EDMarketConnector-debug.log)

Issues were observed with version 5.2.0.

Re-authentication requests seem to always happen upon docking or loading the game and I never manually press the Update button.

My account is a Steam account. When granting EDMC frontier API authorization I have used both the Steam oAuth login method and my Frontier account login method and the login method used does not seem to have any effect on frequency of re-auth requests.

**Comment by Athanasius** [comment]
> Here's my EDMC debug log, as requested from that forum thread: [EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/7487510/EDMarketConnector-debug.log)
> 
> Issues were observed with version 5.2.0.
> 
> Re-authentication requests seem to always happen upon docking or loading the game and I never manually press the Update button.
> 
> My account is a Steam account. When granting EDMC frontier API authorization I have used both the Steam oAuth login method and my Frontier account login method and the login method used does not seem to have any effect on frequency of re-auth requests.

Assuming it's a relevant timestamp, this is the CAPI literally saying "that Access Token is invalid" (probably due to being expired):

```python
2021-10-29 22:34:00.858 - ERROR - 14576:14552:14552 companion.capi_single_query:771: Frontier CAPI Auth: GET /profile
Traceback (most recent call last):
  File "companion.pyc", line 755, in capi_single_query
  File "requests\models.pyc", line 953, in raise_for_status
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://companion.orerve.net/profile
2021-10-29 22:34:00.864 - ERROR - 14576:14552:14552 companion.Session.dump:1007: Frontier CAPI Auth: https://companion.orerve.net/profile 401 Unauthorized {"status":401,"message":"JWT has incorrect\/unexpected fields","tag":"59f25w0zfjw0z"}```

I think we'll add some more logging around the auth, like what the expiry time on the token *is* when we get it.  Maybe the auth server is in some cases giving out short-term tokens ?

However, I just noticed that in response to that:

```python
2021-11-02 22:32:30.679 - DEBUG - 2404:18012:18012 companion.Session.invalidate:724: Forcing a full re-authentication```
when in that scenario we should be able to use the Refresh Token to get a new Access Token.  So we have a bug to fix.

**Comment by Unknown-Zombie** [comment]
I want to add that my use-case I have two different computers that I play on. When going from one computer to the other I _always_ have to re-auth when launching EDMC for the first time on the new computer.

So some of the auth requests in that log (which spans quite a period of time from the look of it) will be from switching computers.

Let me hook up my laptop, which is the other computer I play on, and upload the debug log from that too.

**Comment by Athanasius** [comment]
> I want to add that my use-case I have two different computers that I play on. When going from one computer to the other I _always_ have to re-auth when launching EDMC for the first time on the new computer.
> 
> So some of the auth requests in that log (which spans quite a period of time from the look of it) will be from switching computers.
> 
> Let me hook up my laptop, which is the other computer I play on, and upload the debug log from that too.

Well, I've found a clear bug that will very definitely be causing this issue.  I can only assume those not complaining are either mumbling to themselves about it, or are happy to re-auth once every 4 hours (the expiry time of the Access Token).

Once @A-UNDERSCORE-D has reviewed the linked PR I'll put together a 5.2.1-rc1 that you can try to see if it definitely fixes it for you.

**Comment by Unknown-Zombie** [comment]
Here's the log from my laptop. I apologize for the amount of spam in this log, I have the Canonn plugin installed on this computer and it seems to generate quite a lot of spam in the log.

Anyway, the log entries from today in this file are strictly from me opening the software, re-auth because it's the first launch on a different computer, and closing the program.

[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/7488045/EDMarketConnector-debug.log)

**Comment by Athanasius** [comment]
> Here's the log from my laptop. I apologize for the amount of spam in this log, I have the Canonn plugin installed on this computer and it seems to generate quite a lot of spam in the log.
> 
> Anyway, the log entries from today in this file are strictly from me opening the software, re-auth because it's the first launch on a different computer, and closing the program.
> 
> [EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/7488045/EDMarketConnector-debug.log)

This looks like only a reasonably normal re-auth on startup/first update attempt.  It doesn't contain the same 'CAPI said unauthorized, now let us do re-auth from scratch' sequence.

Anyway, as I said, we should have a release candidate available tomorrow latest for this.

**Comment by Unknown-Zombie** [comment]
5.2.1-rc2 seems to have solved the issue. Played most of the day and didn't have the API login pop up on me once.

Attaching log from today, just in case you wanted to see it.

[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/7491764/EDMarketConnector-debug.log)
