### ISSUE TITLE
Norton AV detecting  security issues in EDMC.exe

### ISSUE THREAD

**Issue by BZSm1ith** [EDCD/EDMarketConnector#1335]
Norton AV is detectin a couple of issues in the EDMC executable  file

![image](https://user-images.githubusercontent.com/79748272/140822042-5039d46e-f7b6-4994-9f90-badfd58049a7.png)

Am running EDMC 5.1.1+b589ac3

Not happened in the previous versions of EDMC

**Comment by A-UNDERSCORE-D** [comment]
https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting#installer-andor-executables-flagged-as-maliciousviruses

https://github.com/EDCD/EDMarketConnector/issues/1058
