### ISSUE TITLE
Auto-hide EDMC on FSS/DSS

### ISSUE THREAD

**Issue by ksga** [EDCD/EDMarketConnector#1338]
**Describe the enhancement**

Hide EDMC UI when using the Full Spectrum System Scanner or the Detailed Surface Scanner. Unhide when returning to regular flight.

**Expected behavior**

A similar behavior to The Trade Computer Extension Mk II

**Considered workarounds**

There must be something in the logs or API enabling TCE to do this trick. Monitor for event and hide/unhide UI accordingly

**Additional context**

Sort of covered by https://github.com/EDCD/EDMarketConnector/issues/889 - but I think this approach would be a bit smoother.

**Comment by norohind** [comment]
It can be taken from Status.json file.

**Comment by ksga** [comment]
> It can be taken from Status.json file, `GuiFocus` key.

So - already implemented? Or just that there is a way to accomplish it?
Sorry - but my coding skills are next to none :|

**Comment by norohind** [comment]
It's just note for implementaion if/when anybody will implement it

**Comment by alterNERDtive** [comment]
_I_ would say it’s out of scope for EMDC (not a maintainer, obviously). But you can use that key with e.g. AHK to build a script that does it for you.

**Comment by Athanasius** [comment]
Personally I'd be more in favour of ensuring plugins can hide/unhide the UI without adversely affecting anything, and then leave it up to third-party plugins to implement this for any scenario a user feels a need.

**Comment by ksga** [comment]
> 
> 
> Personally I'd be more in favour of ensuring plugins can hide/unhide the UI without adversely affecting anything, and then leave it up to third-party plugins to implement this for any scenario a user feels a need.

Probably the right way to do it 👍🏻
I'm pretty useless in Python - but looking at the plugin howto, examples and other plugins I feel I might be able to hack something...
Seems TKinter has functions for minimizing/restoring the window - so guess I should just monitor the GuiFocus in Status.json and act accordingly.
Is the GuiFocus values available through EDMC somehow, or would I have to monitor/parse the json file itself?

I noticed the GuiFocus statics in https://github.com/EDCD/EDMarketConnector/blob/main/edmc_data.py from line 439, but still have not found an overview of the values available through EDMC.

**Comment by norohind** [comment]
> Is the GuiFocus values available through EDMC somehow, or would I have to monitor/parse the json file itself?

Check out `Player Dashboard`  part of PLUGINS.md https://github.com/EDCD/EDMarketConnector/blob/main/PLUGINS.md#player-dashboard

**Comment by ksga** [comment]
Phew - the water is deep where I plunged in 🥵 Not easy being a total noob.

I created a simple plugin - first milestone is understanding how the GuiFocus info is structured...
Left the "hardpoints" from PLUGINS.md as a reference..

The plugin so far:
```
import edmc_data
import tkinter as tk
import logging
import os

from config import config, appname

plugin_name = os.path.basename(os.path.dirname(__file__))
logger = logging.getLogger(f'{appname}.{plugin_name}')
if not logger.hasHandlers():
    level = logging.INFO  # So logger.info(...) is equivalent to print()

    logger.setLevel(level)
    logger_channel = logging.StreamHandler()
    logger_formatter = logging.Formatter(f'%(asctime)s - %(name)s - %(levelname)s - %(module)s:%(lineno)d:%(funcName)s: %(message)s')
    logger_formatter.default_time_format = '%Y-%m-%d %H:%M:%S'
    logger_formatter.default_msec_format = '%s.%03d'
    logger_channel.setFormatter(logger_formatter)
    logger.addHandler(logger_channel)

def plugin_start3(plugin_dir: str) -> str:
   logger.info(f'I am loaded! My plugin dir is {plugin_dir}')
   logger.info(f'I am loaded! My plugin name is {plugin_name}')
   return "UI Hide Test"

def dashboard_entry(cmdr: str, is_beta: bool, entry: dict[str, any]):
    is_deployed = entry['Flags'] & edmc_data.FlagsHardpointsDeployed
    logger.info("Hardpoints {}\n".format(is_deployed and "deployed" or "stowed"))
    is_focused = entry['Flags'] & edmc_data.GuiFocusNoFocus
    #logger.info("GUI {}\n".format(is_focused and "focused" or "unfocused"))
    logger.info(f'GuiFocusNoFocus output is {edmc_data.GuiFocusNoFocus} - the is_focused variable value is {is_focused} - similarly the is_deployed value is {is_deployed}')
```

The output in EDMarketConnector-debug.log:
```
2021-11-10 19:23:45.186 - INFO - 3416:12684:12684 plug.Plugin.__init__:47: loading plugin "EDMCAutohide" from "C:\Users\ksga\AppData\Local\EDMarketConnector\plugins\EDMCAutohide\load.py"
2021-11-10 19:23:45.203 - INFO - 3416:12684:12684 <plugins>.EDMCAutohide.load.plugin_start3:26: I am loaded! My plugin dir is C:\Users\ksga\AppData\Local\EDMarketConnector\plugins\EDMCAutohide
2021-11-10 19:23:45.207 - INFO - 3416:12684:12684 <plugins>.EDMCAutohide.load.plugin_start3:27: I am loaded! My plugin name is EDMCAutohide
2021-11-10 19:25:32.311 - INFO - 3416:12684:12684 <plugins>.EDMCAutohide.load.dashboard_entry:42: Hardpoints deployed

2021-11-10 19:25:32.313 - INFO - 3416:12684:12684 <plugins>.EDMCAutohide.load.dashboard_entry:45: GuiFocusNoFocus output is 0 - the is_focused variable value is 0 - similarly the is_deployed value is 64
2021-11-10 19:25:34.491 - INFO - 3416:12684:12684 <plugins>.EDMCAutohide.load.dashboard_entry:42: Hardpoints stowed

2021-11-10 19:25:34.492 - INFO - 3416:12684:12684 <plugins>.EDMCAutohide.load.dashboard_entry:45: GuiFocusNoFocus output is 0 - the is_focused variable value is 0 - similarly the is_deployed value is 0
```

So - the hardpoint info varies according to the state (0 / 64) - but GuiFocusNoFocus is static regardless of what is in Status.json (switched to system map with it changing).
Is the actual GuiFocus state presented somewhere I can access?

**Comment by Athanasius** [comment]
> Is the actual GuiFocus state presented somewhere I can access?

It's right there in `entry['GuiFocus']`.  What you've done wrong is think that you should look at `entry['Flags']` for that, you don't.

**Comment by ksga** [comment]
So - made it to the point where I am ready to start minimizing/restoring the EDMC window.
I need help making the iconify/deiconify select the parent window.

The plugin looks like this right now:
```
import edmc_data
import tkinter as tk
from tkinter import ttk
import logging
import os

from config import config, appname

focus_state_old = 0
focus_state_now = 0

# How to select parent window???
root = tk.Tk(appname)

plugin_name = os.path.basename(os.path.dirname(__file__))
logger = logging.getLogger(f'{appname}.{plugin_name}')

# Change logger.info to logger.debug when plugin is working
def plugin_start3(plugin_dir: str) -> str:
   logger.info(f'I am loaded! My plugin name is {plugin_name}')
   return "EDMC UI Hide"

    
def dashboard_entry(cmdr: str, is_beta: bool, entry: dict[str, any]):
    global focus_state_old
    global focus_state_now
    focus_state_now = entry['GuiFocus']
    logger.info(f'Current focus state is {focus_state_now}')
    if focus_state_now != focus_state_old:
        focus_state_old = focus_state_now
        logger.info(f'Variable focus_state_old has been changed to {focus_state_old}')
        # Hide EDMC when GuiFocus is InternalPanel, SystemMap, Orrery, FSS, SAA or Codex
        if (focus_state_old == 1) or (focus_state_old == 7) or (focus_state_old == 8) or (focus_state_old == 9) or (focus_state_old == 10) or (focus_state_old == 11):
            logger.info(f'Now hiding EDMC')
            # iconify command not working yet
            root.iconify()
        else:
            logger.info(f'Now unhiding EDMC')
            # deiconify command not working yet
            root.deiconify()
    else:
        logger.info(f'Variable focus_state_old is unchanged at {focus_state_old} because focus_state_now is still {focus_state_now} - Doing nothing!') 
        pass
```

**Comment by ksga** [comment]
Decided to leave tkinter behind and focus on a Windows only solution :(

At least now it works for me...
```
import edmc_data
import tkinter as tk
from tkinter import ttk
import logging
import os
import ctypes

from config import config, appname
from builtins import object, str

focus_state_old = 0
focus_state_now = 0

plugin_name = os.path.basename(os.path.dirname(__file__))
logger = logging.getLogger(f'{appname}.{plugin_name}')

def plugin_start3(plugin_dir: str) -> str:
   logger.debug(f'I am loaded! My plugin name is {plugin_name}')
   return "EDMC UI Hide"

def dashboard_entry(cmdr: str, is_beta: bool, entry: dict[str, any]):
    global focus_state_old
    global focus_state_now
    focus_state_now = entry['GuiFocus']
    logger.debug(f'Current focus state is {focus_state_now}')
    if focus_state_now != focus_state_old:
        focus_state_old = focus_state_now
        logger.debug(f'Variable focus_state_old has been changed to {focus_state_old}')
        hideorshow()    
    else:
        logger.debug(f'Variable focus_state_old is unchanged at {focus_state_old} because focus_state_now is still {focus_state_now} - Doing nothing!') 
        pass

# Hide EDMC when GuiFocus is InternalPanel, SystemMap, Orrery, FSS, SAA or Codex
class hideorshow():
    def __init__(master: tk.Tk):
        edmc_handle = ctypes.windll.user32.FindWindowW(None, "E:D Market Connector")
        ed_handle = ctypes.windll.user32.FindWindowW(None, "Elite - Dangerous (CLIENT)")
        if (focus_state_old == 1) or (focus_state_old == 7) or (focus_state_old == 8) or (focus_state_old == 9) or (focus_state_old == 10) or (focus_state_old == 11):
            logger.debug(f'Now hiding EDMC')
            ctypes.windll.user32.ShowWindow(edmc_handle, 11)
        else:
            logger.debug(f'Now unhiding EDMC')
            ctypes.windll.user32.ShowWindow(edmc_handle, 4)
```

Created a repo for it as well if anybody feels like tidying up my mess :D

**Comment by Athanasius** [comment]
In theory you could start from the tk widget passed in to plugins and walk up with .parent() and then just .withdraw() it.  You'd .deiconify() the same root level window in order to show it again.

**Comment by ksga** [comment]
> In theory you could start from the tk widget passed in to plugins and walk up with .parent() and then just .withdraw() it. You'd .deiconify() the same root level window in order to show it again.

Sounds like a plan. If someone could make the tweaks it would be appreciated (I'm reaching my mental capacity on this one).
One thing - would .deiconify() return focus to the ED window? ShowWindow(xxxxx, 4) restores, but without activating which I would say is crucial in some situations.

**Comment by A-UNDERSCORE-D** [comment]
```
Traceback (most recent call last):
  File "plug.pyc", line 315, in notify_dashboard_entry
  File "C:\Users\ksga\AppData\Local\EDMarketConnector\plugins\EDMCAutohide\load.py", line 29, in dashboard_entry
    hideorshow()
  File "C:\Users\ksga\AppData\Local\EDMarketConnector\plugins\EDMCAutohide\load.py", line 37, in __init__
    self.w = master
NameError: name 'self' is not defined
```

Your `__init__` needs to either accept self and master, or master should be called self (its probably the first one)
