### ISSUE TITLE
EDDN not receiving/accepting updates from EDMC

### ISSUE THREAD

**Issue by DragoCubX** [EDCD/EDMarketConnector#1342]
**Please check the [Known Issues](https://github.com/EDCD/EDMarketConnector/issues/618) in case this has already been reported.**

**Please also check if the issue is covered in our [Troubleshooting Guide](https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting).** It might be something with a known work around, or where a third party (such as EDSM) is causing logging that is harmless.

**Please complete the following information:**
 - Version: 5.2.1
 - Game Version: Live (Horizons)
 - OS: Windows 10 Pro (21H1)
 - OS Locale: German (Germany)
 - If applicable: Opera GX (80.0.4170.91)
 - Please attach **BOTH** log files, by dragging and dropping them into this input:
     1. [EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/7527775/EDMarketConnector.log)
     1. [EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/7527777/EDMarketConnector-debug.log)

**Describe the bug**
EDMC is not updating system & station data via EDDN anymore. Sending CMDR & flight log data to other 3rd-party sites still works flawlessly, as does all the other functionality of EDMC.

**To Reproduce**
1. Enable sending system data to EDDN in settings
2. Jump between systems/dock at stations to trigger EDDN updates
3. EDDN doesn't get the updated info.

**Expected behavior**
System data, such as station owners, influence values and faction states should get updated on EDDN (and all connected 3rd-party sites).

**Screenshots**
Not applicable, I think.

**Additional context**
_Seems_ to have started happening after updating EDMC to 5.2.1 (should've been on the latest release from before that version). Logs show EDDN returning HTTP 400 errors ('Bad Request').

**Comment by Athanasius** [comment]
It looks like you somehow have/had a NavRoute.json file written without the `Route` array in it.  We obviously weren't paranoid enough in our handling of that.  You probably have the event stuck in your replay.json file now, so EDMC will keep on retrying it.

You do seem to have found a bug through, which is in the code that's trying to properly report that to you.  I'll go make the code more paranoid.

In the meantime, I'd:

1. remove the file `%USERPROFILE%\Saved Games\Frontier Developments\Elite Dangerous\NavRoute.json` (it will be recreated the next time you plot a route in-game).
2. Exit out of EDMarketConnector.
3. Remove the file `%LOCALAPPDATA%\EDMarketConnector\replay.jsonl`  **NB: If you have the option `EDDN` > `Delay sending until docked` active then you will lose all the delayed data**.  But as you seem to be expecting EDDN data to send straight away that seems unlikely.
4. Re-start EDMarketConnector.exe

**Comment by Athanasius** [comment]
Fixed in https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F5.2.2
