### ISSUE TITLE
Check if Python 3.10 works for us

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDMarketConnector#1349]
This, of course, means checking that py2exe works.  So this will also be where we test the 0.11.x.y releases of that.

**Comment by A-UNDERSCORE-D** [comment]
for code side just "does our code work", Ive been running 3.10 for a while now without issue

**Comment by Athanasius** [comment]
We don't have a Python 3.10 issue, we have a "WiX/msiexec is being a pain" issue.

1. Uninstall EDMarketConnector
2. Install 5.2.2 (yes, you read that right).
3. Install 5.2.3 over that, it works, all files installed/updated as they should be.
4. Install 5.3.0-beta0 over that, and for unknown reasons it doesn't install tcl86t.dll and tk86t.dll.

This happens both with the old hard-coded GUIDs for those files, and if I change EDMarketConnector.wxs to specify `"*"`, i.e. let WiX decide on the GUID (which presumably it bases on the path/filename).

Nothing in the verbose msiexec log file points to *why* it doesn't install them, it's just missing a `FileCopy` for both.

**Comment by Athanasius** [comment]
Log files from the installs, generated with e.g.

```
msiexec /l*vx 5.2.3-install-from-5.2.2.txt /i "EDMarketConnector_win_5.2.3.msi"
```

NB: the output is in UTF-16 (thanks MicroSoft!), so these were run through GNU `recode utf16..utf8 <file>`.

Installing 5.2.2 from not-installed: [5.2.2-install-from-nothing.txt](https://github.com/EDCD/EDMarketConnector/files/7653808/5.2.2-install-from-nothing.txt)

Installing 5.2.3 over that: 
[5.2.3-install-from-5.2.2.txt](https://github.com/EDCD/EDMarketConnector/files/7653811/5.2.3-install-from-5.2.2.txt)

Installing 5.3.0-beta0 over that (old hard-coded GUIDs): 
[5.3.0-beta0-install-from-5.2.3.txt](https://github.com/EDCD/EDMarketConnector/files/7653812/5.3.0-beta0-install-from-5.2.3.txt)

**Comment by Athanasius** [comment]
I've found the issue.

Python 3.9.9 was released on 2021-11-15 and has version 8.6.2.12 of these files.

Python 3.10.0 was released on 2021-10-04 and has version 8.6.2.10 of these files.

So, yes, the ones we try to ship in a Python 3.10 build are older and thus not installed.

I'm still wondering why msiexec therefore chooses to **remove** the newer, from 5.2.3 install, versions of the files though!

**Comment by Athanasius** [comment]
I've opened a [Python issue about this](https://bugs.python.org/issue45986).

**Comment by Athanasius** [comment]
3.10.1 fixed the specific issue with tcl/tk file versions.  5.3.0-beta2 has been running without issues for mIRCon for weeks now.  So I'm going to assume it's all OK and assign this to https://github.com/EDCD/EDMarketConnector/milestone/7 for closing once that's released.

**Comment by A-UNDERSCORE-D** [comment]
can we check for .2 as well, before this is marked "done"

**Comment by Athanasius** [comment]
> can we check for .2 as well, before this is marked "done"

I'm running a 5.3.0-beta4-<hash>.DIRTY built with 3.10.2 right now ;)

**Comment by A-UNDERSCORE-D** [comment]
Are we happy with this being closed?

**Comment by Athanasius** [comment]
> Are we happy with this being closed?

I, mostly, err on the side of not closing issues until the PR/commits addressing them are in a *release*.

Also, in this case we should get some proper wider testing, *with the py2exe Windows build*, before concluding it's definitely working.

Yes, of course a full suite of unit and functional tests would allow us to tick those boxes already.  Roll on the future decade when we have those.

**Comment by A-UNDERSCORE-D** [comment]
one day. at the very least we're doing that with new stuff, which is a start $tm

**Comment by Athanasius** [comment]
5.3.0-beta5
===

Installation from "I just uninstalled it in Windows" **versus** "I had 5.2.4 installed (which was installed from there being no version installed), and installed this" shows no functional difference in the resulting files in the installation directory:

1. Uninstall
2. Install 5.3.0-beta5 (verify it runs, exit)
3. `ls -alR /c/Program\ Files\ \(x86\)/EDMarketConnector/ > installed-edmc_5.3.0-beta5_from-noinstall_files.txt`
4. Uninstall
5. Install 5.2.4 (verify it runs, exit)
6. `ls -alR /c/Program\ Files\ \(x86\)/EDMarketConnector/ > installed-edmc_5.2.4_from-noinstall_files.txt`
7. Install 5.3.0-beta5 (verify it runs, exit)
8. `ls -alR /c/Program\ Files\ \(x86\)/EDMarketConnector/ > installed-edmc_5.3.0-beta5_from-5.2.4_files.txt`

`diff -u installed-edmc_5.3.0-beta5_from-* | egrep -v '^[-\+]drwx' | egrep '^[-\+]'` shows zero differences.  The `egrep -v ...` gets rid of the lines where the timestamp on a directory is naturaly different.  The output is:

```diff
0$ diff -u installed-edmc_5.3.0-beta5_from-* | egrep -v '^[-\+]drwx' | egrep '^[-\+]'
--- installed-edmc_5.3.0-beta5_from-5.2.4_files.txt     2022-01-31 16:21:44.542226300 +0000
+++ installed-edmc_5.3.0-beta5_from-noinstall_files.txt 2022-01-31 16:20:30.911114700 +0000
```

**Comment by Athanasius** [comment]
Likewise, to be sure of no issues for 5.3.0-beta2 testers:

```diff
diff -u installed-edmc_5.3.0-beta5_from-5.3.0-beta2_files.txt installed-edmc_5.3.0-beta5_from-noinstall_files.txt | egrep -v '^[-\+]drwx' | egrep '^[-\+]'
--- installed-edmc_5.3.0-beta5_from-5.3.0-beta2_files.txt       2022-01-31 16:29:32.290028900 +0000
+++ installed-edmc_5.3.0-beta5_from-noinstall_files.txt 2022-01-31 16:20:30.911114700 +0000
```

**Comment by A-UNDERSCORE-D** [comment]
Sounds good to close for me -- Do we maybe want to add some guards in for versions to warn that code may behave in unexpected ways outside of our currently supported versions?

**Comment by Athanasius** [comment]
> Sounds good to close for me -- Do we maybe want to add some guards in for versions to warn that code may behave in unexpected ways outside of our currently supported versions?

As discussed on Discord, there's no need.  People should be paying attention to our ChangeLog.md and/or `git log` output as applicable to their use case.
