### ISSUE TITLE
Update under Windows 11 failes

### ISSUE THREAD

**Issue by 2bbionic** [EDCD/EDMarketConnector#1370]
Tried to update to version 5.2.3 under Windows 11
Starting the update process from Market Connector nor from downloaded MSI was OK.
Standalone MSI installation did not show up at all except a short flickering.

**Comment by Athanasius** [comment]
Try it with this in a cmd.exe window:

`msiexec /l*vx %TEMP%\edmc-5.2.3-win11-install.log.txt <path to EDMarketConnector_win_5.2.3.msi`

And then drag the resulting log file into a comment here.  You might want to check if there's anything in it you want to censor first (user name, sensitive paths and the like).

**Comment by 2bbionic** [comment]
[edmc-5.2.3-win11-install.log.txt](https://github.com/EDCD/EDMarketConnector/files/7703409/edmc-5.2.3-win11-install.log.txt)

See attached

**Comment by Athanasius** [comment]
That *looks* to be saying it installed OK.

Add in our log files:

`%TEMP%\EDMarketConnector.log`
`%TEMP%\EDMarketConnector\EDMarketConnector-debug.log`

**Comment by 2bbionic** [comment]
strange....bc:
![grafik](https://user-images.githubusercontent.com/74859375/145809738-fa1a44e6-fbe3-417b-81db-262e5d68da62.png)

[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/7703616/EDMarketConnector-debug.log)
[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/7703617/EDMarketConnector.log)

**Comment by Athanasius** [comment]
Ah, my mistake, you need a `/i` on that command-line as well:

`msiexec /l*vx %TEMP%\edmc-5.2.3-win11-install.log.txt /i <path to EDMarketConnector_win_5.2.3.msi>`

**Comment by 2bbionic** [comment]
Sure, but I added it by myself :)
C:\Users\andreas\tmp>msiexec /i c:\Users\andreas\Downloads\EDMarketConnector_win_5.2.3.msi /l*vx  ./edmc-5.2.3-win11-install.log.txt.
The install.log.txt file is from that installation. Only the GUI for the MSIinstaller pops up for a thenth of a second, that's all

**Comment by Athanasius** [comment]
Given the lack of an actual error in the installer log I'm at a loss then.

I can only suggest you uninstall the app From Settings > Apps and then re-install with the 5.2.3 installer.

**Comment by 2bbionic** [comment]
Ok, I'll give it a try
