### ISSUE TITLE
CAPI query aborted: Cmdr name unknown

### ISSUE THREAD

**Issue by aKawaiiLizard** [EDCD/EDMarketConnector#1387]
I have unistalled and reinstalled this app after it wouldnt connect to Frontier any more and now im getting an error saying it cannot find my cmdr despite my save game folder being set correctly
![image](https://user-images.githubusercontent.com/96970236/147868078-b1c68606-cf08-4797-b63a-f61a4dd6cc7a.png)
![image](https://user-images.githubusercontent.com/96970236/147868091-9a51f840-65a2-43fc-9dfd-e624a713c65d.png)

**Comment by klightspeed** [comment]
This suggests that your most recent session only landed on the main menu, and that you had not logged in.
