### ISSUE TITLE
EDMC is flagged as Virus (unsafe)

### ISSUE THREAD

**Issue by JonasBVS** [EDCD/EDMarketConnector#1396]
I don't know if it's just because the binary executable is unsigned, but the file EDMC.exe is marked as unsafe.
https://www.virustotal.com/gui/file/850e4d380c7aee534f7d7ac56daac35deea6a3832dc6db03154d34cc8903cc4a?nocache=1
![image](https://user-images.githubusercontent.com/14073593/148692398-2023f569-9d17-46cf-9795-40fd6f487a41.png)

**Comment by Athanasius** [comment]
Our statement about this scenario is https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting#installer-and-or-executables-flagged-as-malicious-viruses

So long as you're only downloading EDMC installers from here on GitHub we have no reason to believe any of the versions actually contain malware.

**Comment by VAKazakov** [comment]
Hello
that issue is known, you can see details here https://github.com/EDCD/EDMarketConnector/issues/1058
