### ISSUE TITLE
Close (X) button in Settings doesn't discard changes (No "Cancel" button)

### ISSUE THREAD

**Issue by mIRCon** [EDCD/EDMarketConnector#1406]
**Please complete the following information:**
 - Version: 5.3.0-beta2
 - Game Version: Odyssey
 - OS: Windows 10
 - OS Locale: English

**Describe the bug**
When you make some changes in Settings window and you press close (X) button those changes are still saved.
Due to lack of "Cancel" button one might expect Close (X) does the classic "discard changes" function but it's acting as if "OK" was pressed.

**To Reproduce**
1. Go to File -> Settings.
2. Make some changes (add api key, select some options etc).
3. Press Close (X) button in order to discard changes.

**Expected behavior**
Discard changes you made when you press close (X) button in Options window.

**Screenshots**
N/A

**Additional context**
Maybe to consider a true "Cancel" button which does what it usually does and just have Close (X) button follow the same function.

**Comment by Rixxan** [comment]
Hello @mIRCon!

Just reaching out to ask if this issue report is still valid, or if it has been fixed since 5.3.0?

If it is still occurring, let us know so we can get it included with 5.10.1 or if there is a different behavior wanted.

**Comment by mIRCon** [comment]
> Hello @mIRCon!
> 
> Just reaching out to ask if this issue report is still valid, or if it has been fixed since 5.3.0?
> 
> If it is still occurring, let us know so we can get it included with 5.10.1 or if there is a different behavior wanted.

I confirm that this issue is no longer present (at least in 5.10.0 version which I just tested).
When you click "X" all changes you made in settings are discarded as expected.

p.s. Though this is not related to this case: pressing "ESC" does nothing and one would expect it would act as a close/cancel option but it's also matter of personal opinion as well.

**Comment by Rixxan** [comment]
Given that the reported issue doesn't appear to still be an issue (yay!) I'm going to close this issue. 

I'm personally not convinced that adding an ESC functionality would be in our best interests, stylistically speaking. Though if others disagree, please feel free to open a new issue and we can discuss further!
