### ISSUE TITLE
Web Page won't open, can't generate commander name, doesn't allow me to use service because of it

### ISSUE THREAD

**Issue by LepperoniMC1** [EDCD/EDMarketConnector#1418]
**Please check the [Known Issues](https://github.com/EDCD/EDMarketConnector/issues/618) in case this has already been reported.**

**Please also check if the issue is covered in our [Troubleshooting Guide](https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting).** It might be something with a known work around, or where a third party (such as EDSM) is causing logging that is harmless.

**Please complete the following information:**
 - Version: [e.g. 4.0.6 - See 'Help > About E:D Market Connector'.  If running from source using git then please paste the output of `git log --decorate=full | head -1`]
 - Game Version: [e.g. 'Live' or 'Odyssey']
 - OS: [e.g. Windows 10, Linux Debian 10.6, etc.]
 - OS Locale: [e.g. English, French, Serbian...]
 - If applicable: Browser [e.g. chrome, safari]
 - Please attach **BOTH** log files, by dragging and dropping them into this input:
     1. `%TEMP%\EDMarketConnector.log` from *immediately* after the bug occurs (re-running the application overwrites this file).
     1. `%TEMP%\EDMarketConnector\EDMarketConnector-debug.log`.  See [Debug Log File](https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting#debug-log-files).  NB: If you don't have this log file then you're not running the latest version of the application and should update first to see if we already fixed the bug you're reporting.

**Describe the bug**
Both Status and Update abort the query despite having the folder location set properly. Cannot generate the information needed because the program is unable to determine my Commander's name. Unsure how to reproduce because all I did was install the program as intended.

**To Reproduce**

**Expected [behavior**](url)

**Screenshots**
CAPI query aborted: https://i.imgur.com/hSTbhcP.png

**Additional context**
Add any other context 
[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/7966937/EDMarketConnector-debug.log)
about the problem here.
[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/7966938/EDMarketConnector-debug.log)

**Comment by VAKazakov** [comment]
Hello, in order to get your CMDR name, EDMC needs fully loaded game (Not to main menu, but to moment, when you staing on your feet/sitting in ship). Hope that helps.

**Comment by Athanasius** [comment]
> Hello, in order to get your CMDR name, EDMC needs fully loaded game (Not to main menu, but to moment, when you staing on your feet/sitting in ship). Hope that helps.

To expand on that, read the New User Guide -> https://github.com/EDCD/EDMarketConnector/wiki/New-user-guide#you-need-to-be-fully-logged-into-the-game-ie-opensolo-play
