### ISSUE TITLE
Inara: Review current API docs and ensure we send all that we can and should

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDMarketConnector#1433]
NB: Tagged as both an Enhancement *and* a Bug because I wouldn't be surprised if we do have unreported bugs due to not having done this.

With reference to #1395 we probably aren't making use of all the possible Inara API messages we could be.

We need to do a general review of the [Inara API Docs](https://inara.cz/inara-api-docs/) and implement anything that's possible to ensure we give users the best "sync with Inara" experience.

**Comment by Rixxan** [comment]
I think we are sending everything in the API to my knowledge. I don't see any further filtering we need to make at this time. At least, not until someone reports something missing to us. 

Last bits in #1735 and #2212 seem to cover everything. Adding Staged label and marking as resolved in 5.11.
