### ISSUE TITLE
Wiki: Hand-hold users who think installer is the program

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDMarketConnector#1444]
Took way too long to ascertain that "when I re-run the program nothing happens" was actually "I'm ignorant and think the *installer* is the actual program.  All this time I've been doing to the GitHub release page, and either letting my browser run the installer directly, or downloading it and then running the installer *and expecting that to always run the program*."

So, just such that there's a place to point such ignorant users, add something to the Wiki.  Maybe Troubleshooting, but at least a reference in other places like Home and the New User Guide.

First I thought Anti-Virus.  Then I wondered if something was so broken the program couldn't even start and at least give the "I can't write stdout to a file" popup.  Then it seemed like they weren't getting UAC prompt for the installer.  Only *eventually* did they give enough information to clue me in as to their ignorance.

Yes, I'm grumpy, and off to bed.

**Comment by Rixxan** [comment]
Given that the installer is now called an installer, I'm going to say the odds of this one being an ongoing issue is no longer present. Closing unless someone thinks of a reason we need to change things.
