### ISSUE TITLE
`load_module()` being deprecated for Python 3.12

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDMarketConnector#1462]
```python
2021-12-10 10:53:37.148 - INFO - 6264:1884:1884 plug.Plugin.__init__:47: loading plugin "coriolis" from "C:\Users\Athan\Documents\Devel\EDMarketConnector\plugins\coriolis.py"
<frozen importlib._bootstrap>:283: DeprecationWarning: the load_module() method is deprecated and slated for removal in Python 3.12; use exec_module() instead
```

**Comment by Rixxan** [comment]
It was, in fact, not quite so simple.

**Comment by Athanasius** [comment]
Checking on this again... `load_module()` is still marked as deprecated for **3.13**, i.e. it's still in there, never mind 3.12.  It's currently in the [list](https://docs.python.org/3/deprecations/index.html) as "Pending Removal in Python 3.15".

So that alone shouldn't block EDMC moving to 3.12.
