### ISSUE TITLE
EDMC shows warning when logging in while on-foot at a settlement

### ISSUE THREAD

**Issue by pwerken** [EDCD/EDMarketConnector#1482]
**Please complete the following information:**
 - Version: v5.3.1-beta1 running from source `commit 6a9645d43a600ec5fece9e9a0b0f13536841fae4 (HEAD -> refs/heads/develop, refs/remotes/origin/develop)`
 - Game Version: 'Odyssey'
 - OS: Linux Debian 12 (bookworm/sid)
 - OS Locale: English
 - Please attach **BOTH** log files:
     1. there is no `/tmp/EDMarketConnector.log`
     1. [/tmp/EDMarketConnector/EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/8103839/EDMarketConnector-debug.log)

**Describe the bug**
I am on-foot at a (odyssey ground-cz) settlement
I logout to the main menu, and then back in (to restart the ground-cz)
While the game is loading and shows the orange spinning cmdr, EDMC reports "passed-in system_name is empty, can't add System".
When I get in-game the message disappears (it gets overwritten by "sending EDDN data").

**To Reproduce**
1. be on-foot in a odyssey settlement
2. logout to main menu
3. log back into the game

**Expected behavior**
There should be no error's while logging in.

**Additional context**
I've added the [Journal.log](https://github.com/EDCD/EDMarketConnector/files/8103836/Journal.log) from around the same time as the EDMC-debug.log. It looks like the `ApproachSettlement` event (which contains a SystemAddress but no StarSystem/SystemName) is written before the `Location` event.

**Comment by Athanasius** [comment]
> **Additional context** I've added the [Journal.log](https://github.com/EDCD/EDMarketConnector/files/8103836/Journal.log) from around the same time as the EDMC-debug.log. It looks like the `ApproachSettlement` event (which contains a SystemAddress but no StarSystem/SystemName) is written before the `Location` event.

Yeah, that'll do it alright.  We know of other issues with "just logging in" `ApproachSettlement` events, so perhaps we should put some latch on that code to only progress if we know the `Location` event has already fired.

**Comment by Athanasius** [comment]
https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F5.3.1 has addressed this, auto-updates being enabled Soon[tm].
