### ISSUE TITLE
ED Market Connector doesn't work after update installed

### ISSUE THREAD

**Issue by VikMorroHun** [EDCD/EDMarketConnector#1487]
**Please complete the following information:**
 - Version: Current version is 5.3.1+24e8912
 - Game Version: 'Odyssey'
 - OS: Windows 10
 - OS Locale: Hungarian
 - If applicable: Browser Chrome
 - Please attach **BOTH** log files, by dragging and dropping them into this input:
(files attached)

**Describe the bug**
Finished updating. If I start ED Market Connector it is completely empty. No commander name, no ship, etc. The data is still there in the registry.

**To Reproduce**
1. Start the application.
 
**Expected behavior**
Show the data just like before the update.

**Screenshots**
(I could do that but it's just an empty ED Maket Connector window. Nothing special.

**Additional context**
At one point I received an error message that another EDMC process was already running. I've restarted Windows and the problem is still happening.

**Comment by Athanasius** [comment]
You didn't attach any log files.  With GitHub you can just drag them into a comment here.

**Comment by chennin** [comment]
Have you logged COMPLETELY in to the game?

**Comment by VikMorroHun** [comment]
[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/8111942/EDMarketConnector-debug.log)
[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/8111943/EDMarketConnector.log)

Ok, that was the problem. I haven't logged completely into the game.

**Comment by Athanasius** [comment]
Yeah, one of these days we'll get around to making that more obvious in the UI.
