### ISSUE TITLE
EDMC output huge log

### ISSUE THREAD

**Issue by jpotelle** [EDCD/EDMarketConnector#1488]
FYI, my C: drive just blew up with a 97.2 GB log, re: .\AppData\local\EDMarketConnector\edmcoverlay.log.  Top of log shows it was started on 2022/02/20. Sorry, I had to delete it since my SSD was full.

E:D Odyssey (Steam), v 2022.02.12.281100 0.4.6709.0 (0.4.6568.0 SERVER) FD
EDMC Version 5.3.1+24e8912. 

Running the following plugins:
EDR (latest) https://github.com/lekeno/edr/releases/tag/v1.9.3
exploration-progress-1.0.5 https://github.com/DlljsCodes/exploration-progress

OS: Windows 10 Pro version 21H2
OS Locale: English

Please attach **BOTH** log files, by dragging and dropping them into this input:

%TEMP%\EDMarketConnector.log ---> sorry, had to kill the app since SSD was full

%TEMP%\EDMarketConnector\EDMarketConnector-debug.log. ---> This form won't let me attach the log "Something went really wrong, and we can't process that file" oh well

**Describe the bug**
Log file fills SSD in short order.

**To Reproduce**
Play Elite Dangerous Odyssey using EDMC, and plugins listed above.

**Expected behavior**
A concise, not verbose, log file

**Comment by jpotelle** [comment]
It's either a bug in EDMC itself (unlikely I think) or it's verbose logging from exploration-progress, as I just added this a few days ago. I never had trouble with only EDMC+EDR. I've disabled exploration-progress for now...

**Comment by Athanasius** [comment]
> FYI, my C: drive just blew up with a 97.2 GB log, re: .\AppData\local\EDMarketConnector\edmcoverlay.log. Top of log shows it was started on 2022/02/20. Sorry, I had to delete it since my SSD was full.

The clue is in that filename.  The culprit is the EDCM-Overlay third-party plugin.  Be sure you're using the latest version from https://github.com/inorton/EDMCOverlay

**Comment by jpotelle** [comment]
Yes, that was it. Somehow 2 yrs ago I installed EDMCOverlay inside EDR's plugin folder and I didn't notice it. It was very old. Thanks for your help!
