### ISSUE TITLE
TypeError when running from source on stable branch

### ISSUE THREAD

**Issue by Husky2490** [EDCD/EDMarketConnector#1497]
**Please check the [Known Issues](https://github.com/EDCD/EDMarketConnector/issues/618) in case this has already been reported.**

**Please also check if the issue is covered in our [Troubleshooting Guide](https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting).** It might be something with a known work around, or where a third party (such as EDSM) is causing logging that is harmless.

**Please complete the following information:**
 - Version: commit 1dc9f5b0bc7b9c126b09ad0800d5c892d2282b41 (HEAD -> refs/heads/stable, refs/remotes/origin/stable, refs/remotes/origin/main, refs/remotes/origin/HEAD, refs/heads/main)
 - Game Version: Horizons
 - OS: Ubuntu 20.04
 - OS Locale: English
 - If applicable: Browser: Firefox
 - Please attach **BOTH** log files, by dragging and dropping them into this input:

```
$ python3 EDMarketConnector.py
Traceback (most recent call last):
  File "EDMarketConnector.py", line 390, in <module>
    import prefs
  File "/home/ruben/Games/EDMC/trouble/EDMarketConnector/prefs.py", line 21, in <module>
    from monitor import monitor
  File "/home/ruben/Games/EDMC/trouble/EDMarketConnector/monitor.py", line 75, in <module>
    class EDLogs(FileSystemEventHandler):  # type: ignore # See below
  File "/home/ruben/Games/EDMC/trouble/EDMarketConnector/monitor.py", line 2190, in EDLogs
    def _parse_navroute_file(self) -> Optional[dict[str, Any]]:
TypeError: 'type' object is not subscriptable
```

[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/8221479/EDMarketConnector-debug.log)

**Describe the bug**
On my computer, EDMC does not run and exits with `TypeError: 'type' object is not subscriptable`.  This happened when I tried to upgrade from an earlier version to the latest version using git fetch; git pull.  I have also followed the steps from [Running from source](https://github.com/EDCD/EDMarketConnector/wiki/Running-from-source) to install it to a second folder and it happened there as well.  I am running from source on the stable branch.

**To Reproduce**
1. Download latest source on Ubuntu 20.04
2. Attempt to run source
3. Error message

**Expected behavior**
Open the program

**Screenshots**

**Additional context**

**Comment by Athanasius** [comment]
Well, it looks like it's time to change:

> `main` is now targeted against Python 3.9, although should also work under 3.8.

This indeed no longer works with Python 3.8.10 after a `pip install -r requirements.txt`.  But it does still work with Python 3.9.10.

@Husky2490 You'll need to get at least Python 3.9 installed, if not 3.10.  See https://github.com/EDCD/EDMarketConnector/wiki/Running-from-source#using-a-non-distribution-python-on-eg-debian
