### ISSUE TITLE
Error: unable to get token

### ISSUE THREAD

**Issue by Hexvon** [EDCD/EDMarketConnector#1508]
- Version: 5.3.3
 - Game Version: Odyssey
 - OS: Windows 10
 - OS Locale: Russian
 - If applicable: Browser chrome
 - [EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/8256222/EDMarketConnector.log)
 - [EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/8256223/EDMarketConnector-debug.log)

**Describe the bug**
The inability to authorize the application in the Frontier api system.

**To Reproduce**
1. Start EDMC "EDMarketConnector - localserver-auth.bat" because otherwise infinite authorization.
2. The Frontier page opens in the browser and I log in.
3. Frontier reports successful authorization.
4. But there is an authorization error in the application itself.

**Expected behavior**
Successful EDMC authorization.

**Screenshots**
![image](https://user-images.githubusercontent.com/50929311/158446140-53c8d369-30ad-4395-b827-462582bb6468.png)
![image](https://user-images.githubusercontent.com/50929311/158446174-6c1ba614-8a0e-48fd-9edf-4813eec12b1d.png)

**Comment by Athanasius** [comment]
You've got some sort of firewall/proxy interfering:

```python
requests.exceptions.ProxyError: HTTPSConnectionPool(host='auth.frontierstore.net', port=443): Max retries exceeded with url: /token (Caused by ProxyError('Your proxy appears to only use HTTP and not HTTPS, try changing your proxy URL to be HTTP. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#https-proxy-error-http-proxy', SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)'))))
```

**Comment by Hexvon** [comment]
It turns out that EDMC does not work with Vpn, I'm sorry it didn't reach me.
