### ISSUE TITLE
Body not tracked properly when in a taxi

### ISSUE THREAD

**Issue by klightspeed** [EDCD/EDMarketConnector#1522]
- Version: 5.3.4
 - Game Version: Odyssey
 - OS: Windows
 - OS Locale: English

[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/8352913/EDMarketConnector.log)
[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/8352918/EDMarketConnector-debug.log)
EDDN events: [EDMC-taxi-2022-03-25.log](https://github.com/EDCD/EDMarketConnector/files/8352922/EDMC-taxi-2022-03-25.log)
Journal: [Journal.2022-03-26T033515.01.log](https://github.com/EDCD/EDMarketConnector/files/8352950/Journal.2022-03-26T033515.01.log)

**Describe the bug**
Incorrect body is sent in EDDN `Docked` event when in a taxi or starting in space outside the gravity well of a planet

**To Reproduce**
* Start on-foot on a planet
* Take an APEX shuttle to a station or a settlement on another planet in the same system

**Expected behavior**
EDDN `Docked` event has no `Body` (if an orbital station), or has the correct `Body` (if a planetary port)

**Actual behaviour**
EDDN `Docked` event has `Body` set to that of the starting location

**Comment by Athanasius** [comment]
Reproducing.

1. Start game, on-foot, at `Szameit's Inheritance` on `Rutena A 2`:
    1. J:BodyName: `Rutena A 2`
    2. J:BodyID: `9`
    3. S:BodyName: `Rutena A 2`
2. Book taxi to `Weitz City` (orbits `Rutena A 1`) (no status changes).
3. Walk to taxi, not boarded yet - no status changes.
4. Board taxi - no status changes.
5. Taxi launched - no status changes.
6. Taxi enters Supercruise - no status changes.
7. Above Orbital Cruise - S:BodyName now None, no changes to J: tracking.
8. Drop out at `Weitz City` - no more status changes.
9. Taxi docked - No status changes.
10. Disembark - S:BodyName now `Weitz City`, no J: changes.
11. Walk to concourse - no status changes.

**Comment by Athanasius** [comment]
One difference, when starting at an orbital station.  On-foot Status.json has the station as its BodyName, when in-ship there is no Status BodyName.

**Comment by Athanasius** [comment]
Also, for an orbital station the `SupercruiseExit` lists the station as the Body(name) and ID.

**Comment by Athanasius** [comment]
So, yes, it does look like there's no way we could ever correctly report the BodyName/ID of an orbital station.  I shall look into a way to adjust the code to reflect this.

**Comment by Athanasius** [comment]
Should be fixed in just released 5.4.0.
