### ISSUE TITLE
Program hung on 'Logging in...', Authorization popup is unresponsive/does not complete

### ISSUE THREAD

**Issue by Avera9eJoe** [EDCD/EDMarketConnector#1534]
**User Information:**
 - Version: 4.3.4+693463d
 - Game Version: Odyssey
 - OS: Windows 10
 - OS Locale: English
 - Browser: Chrome
 -  Both files attached (I think)

**Bug description:**
After 25 days of perfect functionality with no interruptions, I am unable to complete the Frontier Authorization flow. When I launch the app, it opens a popup to the Frontier Authentication tab with my credentials auto-filled. Clicking 'LOGIN' however has no visible effect; the browser icon loads for a brief moment before returning to normal, and nothing happens. Clicking multiple times repeats the same observations; the icon loads for a moment, then nothing happens. Manual input of information has no noticeable difference either.

**To Reproduce**
1. Launch E:D Market Connector, observe the Frontier Authentication popup window
2. Click 'LOGIN' and observe that nothing happens

[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/8527719/EDMarketConnector.log)
[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/8527721/EDMarketConnector-debug.log)

**Expected behavior**
Frontier Authentication should work by simply clicking this link, yes? I cannot remember what the functionality was 25 days ago when I first set this up, but I don't think it was this.

**Additional context**
Issue only started occurring today, on my renewal of Frontier Authentication.
Loading auth.frontierstore.net manually from outside of the popup works normally, letting me login and view user.frontierstore.net

**Comment by Avera9eJoe** [comment]
Resolved. Authentication was bugging out due to me relocating the save location from `Program Files (x86)` to a custom folder with the rest of my E:D mods. Reinstalling to Program Files seems to have fixed this.

**Comment by Athanasius** [comment]
> Resolved. Authentication seems to have been bugging out due to me relocating the save location from `C:Program Files (x86)\EDMarketConnector` to `%user%\AppData\Local\Frontier Developments\Elite Dangerous Mods` with the rest of my E:D mods. Reinstalling to Program Files seems to have fixed this issue, and Authentication is now successful.

This would have been because the authentication, by default, uses a custom edmc:// protocol which is set up via a Registry entry pointing at the executable.  So, you no longer had EDMarketConnector.exe in the correct place that failed.

See https://github.com/EDCD/EDMarketConnector/wiki/Installation-&-Setup#windows-in-custom-location-ie-a-different-drive for how to do an installation to a non-default path (you'd have to uninstall first).
