### ISSUE TITLE
ED Market Connector Brokent

### ISSUE THREAD

**Issue by kwidmayer** [EDCD/EDMarketConnector#1542]
I started my computer after using it the day before and now the ED Market connector tells me I nened re-authenticate with Frontier.  So I put in my verifiyed Frontier userid and password, and after proving I'm a human the Frontier website askes me to click an accept link and then their website gives me a 500 server error.   So I am not able to connect the ED Market Connector to Frontier
[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/8617924/EDMarketConnector-debug.log)
.

**Comment by Athanasius** [comment]
As this is the Frontier site giving you a 500 server error the problem is at their end.  Contact Frontier user support.
