### ISSUE TITLE
linux: Journal file is `None` 

### ISSUE THREAD

**Issue by mdartmann** [EDCD/EDMarketConnector#1564]
**Please complete the following information:**
 - Version: both 5.3.4 and `693463d3a0dbe58a1f72b83fc09a44a4398af3fd`
 - Game Version: Oddysey
 - OS: Linux (self-compiled, Arch-like)
 - OS Locale: `en-US.UTF-8`
- [EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/8793509/EDMarketConnector-debug.log)

**Describe the bug**

When running EDMarketConnector.py or EDMC.py, the journal directory is always `None` no matter what is configured in the app.

**To Reproduce**
1. Follow the "From Source" build instructions.
2. Start EDMC and set the journal directory to either `~.var/app/com.valvesoftware.Steam/.steam/steam/steamapps/compatdata/359320/pfx/drive_c/users/steamuser/Saved Games/Frontier Developments/Elite Dangerous` or `~/dev/elite` (a symlink to the same directory)

**Expected behavior**
The journal directory applies properly.

**Additional context**
Config file (`$XDG_CONFIG_HOME/EDMarketConnector/EDMarketConnector.ini`):
```ini
[config]
outdir = /home/mae/dev/elite
ui_scale = 100
dark_text = #ff8000
dark_highlight = white
prefsversion = 4
output = 2065
journaldir = 
shipyard_provider = EDSY
system_provider = EDSM
station_provider = eddb
loglevel = INFO
language = 
hide_private_group = 0
hide_multicrew_captain = 0
ui_transparency = 100
always_ontop = 0
minimize_system_tray = 0
theme = 0
coriolis_normal_url = https://coriolis.io/import?data=
coriolis_beta_url = https://beta.coriolis.io/import?data=
coriolis_overide_url_selection = auto
edsm_out = 0
inara_out = 0
geometry = +2438+1430
```

**Comment by klightspeed** [comment]
You haven't set the `E:D Journal file location` in File -> Settings -> Configuration.
You need to point it at either the directory within the Proton prefix (if running the game under Steam on the Linux PC), or a CIFS mounted directory from the computer you are running the game on.

**Comment by mdartmann** [comment]
> Is `~` resolving properly?
Yep, as seen in the ini file, it resolves to the right folder.

**Comment by klightspeed** [comment]
Click the Configuration tab - the journal location setting is in there.

**Comment by mdartmann** [comment]
oh, my bad.

**Comment by Trezamere** [comment]
I also was confused by this and didn't figure it out until I saw this issue... perhaps having the configuration tab and not the output tab as the first tab that opens up would make more sense? It's a bit counterintuitive that the application settings aren't the default.
