### ISSUE TITLE
PermissionError on debug log file with multiple users on Linux

### ISSUE THREAD

**Issue by DrGFreeman** [EDCD/EDMarketConnector#1576]
**Please complete the following information:**
 - Version: `commit 693463d3a0dbe58a1f72b83fc09a44a4398af3fd (HEAD -> refs/heads/stable, tag: refs/tags/Release/5.3.4, refs/remotes/origin/stable, refs/remotes/origin/release-5.3.4, refs/remotes/origin/main, refs/remotes/origin/HEAD)`
 - Game Version: Horizons
 - OS: `Pop!_OS 20.04 LTS x86_64`
 - OS Locale: `fr_CA.UTF-8`
 - If applicable: Browser N/A

**Describe the bug**
On Linux, the log file `/tmp/EDMarketConnector/EDMarketConnector-debug.log` is owned by the first user launching the application. Attempting to launch `EDMarketConnector.py` from another user results in a `PermissionError` exception. See log below (from second user):

```
$ python EDMarketConnector.py 
Traceback (most recent call last):
  File "/home/jul/git/EDMarketConnector/EDMarketConnector.py", line 55, in <module>
    import killswitch
  File "/home/jul/git/EDMarketConnector/killswitch.py", line 16, in <module>
    import EDMCLogging
  File "/home/jul/git/EDMarketConnector/EDMCLogging.py", line 553, in <module>
    edmclogger = Logger(base_logger_name, loglevel=loglevel)
  File "/home/jul/git/EDMarketConnector/EDMCLogging.py", line 190, in __init__
    self.logger_channel_rotating = logging.handlers.RotatingFileHandler(
  File "/usr/lib/python3.9/logging/handlers.py", line 153, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,
  File "/usr/lib/python3.9/logging/handlers.py", line 58, in __init__
    logging.FileHandler.__init__(self, filename, mode=mode,
  File "/usr/lib/python3.9/logging/__init__.py", line 1146, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.9/logging/__init__.py", line 1175, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding,
PermissionError: [Errno 13] Permission denied: '/tmp/EDMarketConnector/EDMarketConnector-debug.log'
```

**To Reproduce**

1. Open a session with user "A" and launch EDMC.
2. Shutdown EDMC and close the user session.
3. Open a session with user "B" and launch EDMC.

**Expected behavior**

The application can be launched by the second user.

**Screenshots**
N/A

**Additional context**
1. The issue resolves itself after a reboot or whenever the OS cleans the files in `/tmp/`.
1. It is my understanding that on Windows, Python's `tempfile.gettempdir()` returns a path that is unique to the user (in `%APPDATA%`) so this issue should be specific to Linux (though I don't have a Windows machine to test this).

**Comment by DrGFreeman** [comment]
I fixed the issue in a local branch by appending the username to the folder name in the `logfile_rotating` path in `EDMCLogging.py:

```python
logfile_rotating = pathlib.Path(tempfile.gettempdir())
username = ''
if sys.platform != 'win32':
    username = f'-{getpass.getuser()}'
logfile_rotating = logfile_rotating / f'{appname}{username}'
```

I'd be happy to submit a PR if the maintainer(s) agree with this direction or propose an alternate solution.

**Comment by Athanasius** [comment]
Or you could just set TMPDIR in your environment to point to a per-user directory.  I always have this point at `$HOME/tmp` myself, with shell startup to both set it and ensure it's created.

`tempfile.gettempdir()` will then pick that up.

**If** we were to attempt to fix this then it gets a little complicated with ensuring it does exist, but making sure it doesn't already exist, possibly owned by another user.  It's just easier and cleaner if users have an actual private TMPDIR set.  I'm more inclined to just document this.

**Comment by DrGFreeman** [comment]
> It's just easier and cleaner if users have an actual private TMPDIR set. I'm more inclined to just document this.

Sounds good to me as well.

**Comment by Athanasius** [comment]
See https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting#logfile-permission-error and https://github.com/EDCD/EDMarketConnector/wiki/Running-from-source#ensure-log-files-can-be-written that it links to.
