### ISSUE TITLE
SUGGESTION: Add Private Comment to EDSM

### ISSUE THREAD

**Issue by MarkJelic** [EDCD/EDMarketConnector#164]
As you may know, EDSM has the ability to have Private Comments about a system save to your profile.

Could we add a small text box that is cleared each time you enter a new system. Allow user to enter a comment and when they hit enter or click on Update button, this comment is saved to EDSM as a private comment for that system in their Flight Log.

Enhancement: Not sure if it is possible to read data OUT of EDSM, but if the system you just jumped into already has a Private Comment saved in EDSM, retrieve it and display it in the comment box. Allow user the edit the contents and if they hit enter or Update button, data gets re-saved to EDSM.

Suggestion for how it might look is attached.

![edmc - add private comment](https://cloud.githubusercontent.com/assets/13119623/20644764/de6dfed2-b495-11e6-9c5a-f8631a0c7f93.png)

**Comment by Marginal** [comment]
I like the idea. The [EDSM API](https://www.edsm.net/api-logs-v1) allows one to retrieve comments, so it would be possible to populate the box with any existing comment.

My only concern is that it takes up quite a lot of screen space for users not interested in the feature, so I would want to make it an option.

**Comment by Red13x3** [comment]
Yeah, fair call about it being an option of showing comments or not.

What do you think about the way to use it? Enter key to write to EDSM?
Would it be possible to set the focus to the text box (if there isn't a comment in it already) when the app gets the Windows focus? As in, if the user Alt-Tabs to EDMC, and there is no current comment, then the insertion cursor is blinking away in the box, ready for you to type something, you hit Enter, and it is written to EDSM and the comment box becomes "display" based?

Alternatively, could we have a Hot-key that sets the Windows focus to the app and puts the insertion cursor in that field. If there is any previous comment, then that gets fully selected so the text can be replaced as soon as you start typing. But only by hitting enter or clicking on the Update button does anything actually get written to EDSM.

What do you think?

**Comment by Red13x3** [comment]
* Bump

**Comment by NoFoolLikeOne** [comment]
I think this would make more sense as a plugin

I don't think it would be particularly challenging to implement as a plugin. 

I was considering writing a plugin to generate some text based on certain events like discovering ELWs and life and like the idea of being able to edit before sending. I hadn't considered that. I'd probably keep the minimalist UI and open a fresh window for the edit/send function

**Comment by NoFoolLikeOne** [comment]
When you click on the system name it takes you to EDSM and on that page the comment form is open. 

is there a reason why you would not want to switch to the browser to enter the comment?

**Comment by NoFoolLikeOne** [comment]
@Marginal  Related to this.  I have written some hyperdiction tracking code and would like to be able to write a journal entry in EDSM. Is there a way for a plugin to get the API key?

**Comment by Marginal** [comment]
Yes, see https://github.com/Marginal/EDMarketConnector/blob/master/plugins/edsm.py#L162
