### ISSUE TITLE
typo in wiki - setup into custom location

### ISSUE THREAD

**Issue by VAKazakov** [EDCD/EDMarketConnector#1642]
That is not a bar report about EDMC itself, but rather about wiki pages

https://github.com/EDCD/EDMarketConnector/wiki/Installation-&-Setup#windows-in-custom-location-ie-a-different-drive

install command example is not finished (path not closed by ")
now:  `msiexec /i "X:\path\to\EDMarketConnector_win_NNN.msi" INSTALLDIR="Y:\destination\EDMarketConnector`  
should be:   `msiexec /i "X:\path\to\EDMarketConnector_win_NNN.msi" INSTALLDIR="Y:\destination\EDMarketConnector"`

**Comment by Athanasius** [comment]
It also has extraneous backticks around it, un-necesssary for the 'code' formatting, because indentation is achieving that.

**Comment by Athanasius** [comment]
Fixed.
