### ISSUE TITLE
Update not installing where the last version was installed

### ISSUE THREAD

**Issue by DawnTreader** [EDCD/EDMarketConnector#1679]
I do a custom installation to a particular folder on a particular drive. The 5.5 version installed itself in the typical C:\Program Files\EDMC folder.

This is not ideal.

**Comment by Athanasius** [comment]
Did you install it to the other location using the method outlined at https://github.com/EDCD/EDMarketConnector/wiki/Installation-&-Setup#windows-in-custom-location-ie-a-different-drive ?

**Comment by Athanasius** [comment]
Closing due to lack of additional feedback.
