### ISSUE TITLE
Always on top only working on Windowed-Mode?

### ISSUE THREAD

**Issue by FormBurden** [EDCD/EDMarketConnector#1696]
1. I am running EDMC on Arch Linux
2. I am not using Wine (which EDMC's Windows version does work fine on Wine)
3. I'm running it from source ./EDMarketConnector.py
4. Version: 5.5.0
5. Color Appearance is Dark (if it matters)

Is there a way to use Borderless Windowed-Mode and have the EDMC Overlay be ontop of the game? Default, it only seems to work in Windowed-Mode.

Maybe there is a command line I could run with EDMC to cause it to force on-top of Borderless?

**Comment by A-UNDERSCORE-D** [comment]
What DE are you using? I assume kde?

**Comment by FormBurden** [comment]
> What DE are you using? I assume kde?

Ah right, sorry about that.

Yes KDE, and on Wayland.
Arch Linux

**Comment by A-UNDERSCORE-D** [comment]
KDE does not allow apps requesting always on top to draw above fullscreen windows

**Comment by FormBurden** [comment]
> 

Oh... I'm guessing that involves fullscreen-windowed as well? 

Do other Display Environments have this at all? Never really used any others than KDE.

**Comment by A-UNDERSCORE-D** [comment]
Gnome works with it; you can also try force the window type to be OSD or so in kwin rules, which may force it to behave correctly but my experience with that was flaky at best

**Comment by FormBurden** [comment]
Ah I see. No worries. Thanks for the info!

**Comment by A-UNDERSCORE-D** [comment]
Also see https://bugs.kde.org/show_bug.cgi?id=439573 (source: https://www.reddit.com/r/kde/comments/qq5ojw/always_on_top_windows_ignored_if_an_app_is/ ) -- KDE calls this Working as Intended, but added the OSD option as a workaround
