### ISSUE TITLE
GitHub: Replace current 'Create Draft Release' code with GitHub CLI

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDMarketConnector#1704]
Our windows-build.yaml is configured to utilise https://github.com/softprops/action-gh-release to create a draft release after the build completes.

Unfortunately that action hasn't, yet, been updated to change from `set-output` to Environment Files:
```
 Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
There's an [open issue](https://github.com/softprops/action-gh-release/issues/265), but no response from the developer.

There *is* a comment about just using the GitHub CLI instead: https://github.com/softprops/action-gh-release/issues/265#issuecomment-1312584610

So, investigate that, or other alternatives.  Keep in mind we want a **DRAFT** release from this action.

**Comment by A-UNDERSCORE-D** [comment]
`gh release create $tag --draft --discussion-category Release/$tag`

---

https://cli.github.com/manual/gh_release_create

**Comment by Athanasius** [comment]
It *appears* that softprops has updated now, possibly just by updating its own dependencies.

Either way I didn't get the warnings when building 5.6.1 just now -> https://github.com/EDCD/EDMarketConnector/actions/runs/3601587722/jobs/6067613851
