### ISSUE TITLE
Updates not going through since 5.6.0 update

### ISSUE THREAD

**Issue by PhilHibbs** [EDCD/EDMarketConnector#1724]
**Please check the [Known Issues](https://github.com/EDCD/EDMarketConnector/issues/618) in case this has already been reported.**
Done.

**Please also check if the issue is covered in our [Troubleshooting Guide](https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting).**
Done.

**Please complete the following information:**
 - Version: 5.6.0+a9ccb7d
 - Game Version: Odyssey
 - OS: Windows 10
 - OS Locale: English
 - Please attach **BOTH** log files, by dragging and dropping them into this input:
     1.  [EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/10111760/EDMarketConnector.log)
     2.  [EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/10111763/EDMarketConnector-debug.log)

**Describe the bug**
After updating the EDMC application as prompted, it appears that data is no longer getting through to Inara (I checked EDDB as well and the stationsI visited aren't updated there).
I visited these three stations, plus a few others:
Wyndham Dock, MCC 549
Pippin Dock, MCC 549
Biggle Dock, MCC 549
This was around 2022-11-28 20:00:00 UTC.

**To Reproduce**
Dock at station, click Update in EDMC, check Inara.

**Expected behavior**
Data should be updated.

**Screenshots**
n/a

**Additional context**
n/a

**Comment by Athanasius** [comment]
I'll look into this more when the servers are back up.  If I find things definitely working for me then I'll need a relevant Journal file (matching the log files you've already provided, or fresh ones of them) to cross-check.

FYI Re: "Dock at station, click Update in EDMC, check Inara." - Pressing Update has absolutely nothing to do with updating anything on Inara.  Inara only takes Journal-sourced information.  The Update button triggers a pull of **CAPI** data, none of which is sent to Inara.  It used to be that Inara credits total would be updated that way, but that hasn't been true for a while now.

**Comment by VAKazakov** [comment]
as per ross eddb, there was updates, but @ 00:58 29-11-2022 https://ross.eddb.io/eddn/log?station_id=27235
so 5.6.0 itself works.

**Comment by Athanasius** [comment]
> FYI Re: "Dock at station, click Update in EDMC, check Inara." - Pressing Update has absolutely nothing to do with updating anything on Inara. Inara only takes Journal-sourced information. The Update button triggers a pull of **CAPI** data, none of which is sent to Inara. It used to be that Inara credits total would be updated that way, but that hasn't been true for a while now.

Although it now occurs to me that what you're failing to see is *station* information on Inara updating.  That would indeed be via EDDN, and for market, shipyard and outfitting that *is* either an automatic CAPI pull ("Automatically update on docking" in Output settings) *or* a manual press of the Update button, combined with "Send station data to the Elite Dangerous Data Network" in the EDDN settings, *or* a Journal-based update if you manually open the relevant station screens.

There are some other caveats, e.g. the EDDN Relay will drop any duplicate message, such that if *someone else* updates a station within 15 minutes of you attempting it, and the data hasn't changed, there'll be no new EDDN message to Listeners.

**Comment by Athanasius** [comment]
This being an EDDN thing you can get some more detail about what the (new) code is doing by running the program as:
```
EDMarketConnector.exe --trace-on plugin.eddn.send
```
You'll need to look in the debug log file, not the plain one, for TRACE level logging.

**Comment by PhilHibbs** [comment]
> Pressing Update has absolutely nothing to do with updating anything on Inara...
> ...that _is_ either an automatic CAPI pull ("Automatically update on docking" in Output settings) _or_ a manual press of the Update button,

Okay... I do have automatic update on docking turned on but I didn't know that. I didn't see anything in the instructions on whether you do or do not need to click the Update button, so I kinda assumed that clicking "Update" was necessary! Maybe the "Update" button should go into the 60 second timer if it's just updated on docking?

**Comment by PhilHibbs** [comment]
Just went to Matheson Ring in Njorovices to update the 89-day-old market data, and it won't update. I docked at 20:08:41 and checked the log, then clicked the Update button at 20:10.

[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/10116940/EDMarketConnector-debug.log)
[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/10116942/EDMarketConnector.log)

**Comment by PhilHibbs** [comment]
It now appears to be working. Earllier today I launched it with the command mentioned above:

`EDMarketConnector.exe --trace-on plugin.eddn.send`

I closed it, and launched it normally. I am now seeing updates on Inara, I just visited **Bamford City** in **L 190-21** and it updated automatically.

**Comment by Athanasius** [comment]
> Just went to Matheson Ring in Njorovices to update the 89-day-old market data, and it won't update. I docked at 20:08:41 and checked the log, then clicked the Update button at 20:10.
> 
> [EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/10116940/EDMarketConnector-debug.log) [EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/10116942/EDMarketConnector.log)

This particular example is not an EDMC or EDDN problem.  EDDB picked it up fine, as did my own EDDN Listener:

https://ross.eddb.io/eddn/log?station_id=32226
https://ross.eddb.io/eddn/log/1126401091
https://ross.eddb.io/eddn/log/1126401092

Ergo, at this time, any problem was with Inara (which I assume is where you were checking given you mentioned it in OP).  It's entirely possible that Inara.cz had its EDDN Listener shutdown to assess the update and hadn't yet re-activated it.

On my own listener the commodity/3 message without the actual (large) commodity data is:

```json
{"header": {"gamebuild": "", "uploaderID": "<elided>", "gameversion": "CAPI-market", "softwareName": "E:D Market Connector [Windows]", "softwareVersion": "5.6.0", "gatewayTimestamp": "2022-11-29T20:08:44.524754Z"}, "message": {"odyssey": true, "horizons": true, "marketId": 3228231936, "economies": [{"name": "Tourism", "proportion": 1}], "timestamp": "2022-11-29T20:08:43Z", "prohibited": ["BasicNarcotics", "BattleWeapons", "BootlegLiquor", "CombatStabilisers", "ImperialSlaves", "Landmines", "OnionHeadC", "PersonalWeapons", "Slaves", "Tobacco"], "systemName": "Njorovices", "stationName": "Matheson Ring"}, "$schemaRef": "https://eddn.edcd.io/schemas/commodity/3"}
```
The gatewaytimestamp matches up with this from your debug log:
```python
2022-11-29 20:08:44.676 UTC - TRACE - 17672:9784:9784 plugins.eddn.EDDNSender.add_message:291: Message for msg['$schemaRef']='https://eddn.edcd.io/schemas/commodity/3'
2022-11-29 20:08:44.682 UTC - TRACE - 17672:9784:9784 plugins.eddn.EDDNSender.add_message:330: Message for msg['$schemaRef']='https://eddn.edcd.io/schemas/commodity/3' recorded, id=18
2022-11-29 20:08:44.682 UTC - TRACE - 17672:9784:9784 plugins.eddn.EDDNSender.send_message_by_id:355: Sending message with id=18
2022-11-29 20:08:44.683 UTC - TRACE - 17672:9784:9784 plugins.eddn.EDDNSender.send_message:391: Sending message
2022-11-29 20:08:44.849 UTC - TRACE - 17672:9784:9784 plugins.eddn.EDDNSender.delete_message:339: Deleting message with row_id=18
```

**Comment by Athanasius** [comment]
Closing this as it's apparently not recurred, and was more likely due to Inara not listening to EDDN just after Update 14 dropped.
