### ISSUE TITLE
Enter cooldown when auto updating on docking

### ISSUE THREAD

**Issue by PhilHibbs** [EDCD/EDMarketConnector#1725]
**Describe the enhancement**

Enter cooldown when automatic update has been sent.

**Expected behavior**

If **Automatically update on docking** is enabled, and an update is sent, the Update button should enter the 60 second Cooldown state.

**Additional context**

This change would help new users to realise that their updates have been sent, and that they do not need to click the Update button. When I started using EDMC I did not realise that the **Automatically update on docking** setting existed. I just assumed that I needed to click that Update button. The documentation told me to click the Update button after first logging in, but nothing about whether further updates needed the button to be pressed.

**Workarounds considered**

Maybe just a small update to the instructions to indicate that clicking Update is not needed after the first log in, as long as the automatic setting remains selected.

**Comment by Athanasius** [comment]
I am sure that this already happens, especially given the number of times I've been rapidly re-testing and gotten the 'bad' sound because the automatic update ran into still being on cooldown from the last automatic update.

If you're testing *right now* I'd say that's invalid due to the game servers being down.

**Comment by PhilHibbs** [comment]
Just went to Matheson Ring in Njorovices to update the 89-day-old market data, and it won't update.

[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/10116940/EDMarketConnector-debug.log)
[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/10116942/EDMarketConnector.log)
