### ISSUE TITLE
CAPI query fails under heavy CAPI load

### ISSUE THREAD

**Issue by norohind** [EDCD/EDMarketConnector#1727]
**Please complete the following information:**
 - Version: 5.6.0+a9ccb7d
 - Game Version: Odyssey
 - OS: Windows 10
 - OS Locale: Russian
 - Please attach **BOTH** log files, by dragging and dropping them into this input:
[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/10117266/EDMarketConnector-debug.log)
[5.6.0_00.log](https://github.com/EDCD/EDMarketConnector/files/10117268/5.6.0_00.log)

**Describe the bug**
Query to CAPI failed right after I started EDMC.  
Next is only my thoughts: It happened not long after servers (for live) came online after deploying ED update 14.
CAPI had long response time, it could reach couple seconds according to my observation.
So in EDMC it might be some edge case when initial flow of getting access token isn't done yet because FDEV has high latency and some something inside EDMC tries to perform actual query to CAPI but I'm not sure what I'm talking about.

**To Reproduce**
It should be hard, I didn't managed to do that again.
1. Make FDEV api have high latency
2. Start EDMC
3. Wish you look to capture it

**Expected behavior**
No failed queries to CAPI.

**Screenshots**
N/A

**Additional context**
Last game I launched and players journals EDMC should had read of on startup is Odyssey (before update 14).

**Comment by Athanasius** [comment]
This had to be something cause the call to `Session.start_frontier_auth()` to be delayed/not happen, combined with then some other action trying to perform CAPI queries.

So, I've changed it so `Session.requests_session()` is simply set up/initialised in `Session.__init__()` so there's no way it could still be `None` by the time any other methods are invoked on the Session object.
