### ISSUE TITLE
Inara plugin: Incorrect format of opponentName parameter or it is completely missing.

### ISSUE THREAD

**Issue by chennin** [EDCD/EDMarketConnector#1732]
**Please check the [Known Issues](https://github.com/EDCD/EDMarketConnector/issues/618) in case this has already been reported.**

**Please also check if the issue is covered in our [Troubleshooting Guide](https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting).** It might be something with a known work around, or where a third party (such as EDSM) is causing logging that is harmless.

**Please complete the following information:**
 - Version: 5.6.0
 - Game Version: Live
 - OS: Windows 10
 - OS Locale: English
 - Please attach **BOTH** log files, by dragging and dropping them into this input:
[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/10126230/EDMarketConnector.log)
[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/10126234/EDMarketConnector-debug.log)

**Describe the bug**

Interdiction by a Thargoid throws a WARNING

```
2022-11-30 18:15:48.310 UTC - WARNING - 13876:27056:27056 plugins.inara.send_data:1638: Inara	200 Incorrect format of opponentName parameter or it is completely missing.
2022-11-30 18:15:48.310 UTC - DEBUG - 13876:27056:27056 plugins.inara.send_data:1639: JSON data:
{"eventName": "addCommanderCombatInterdicted", "eventTimestamp": "2022-11-30T18:15:26Z", "eventData": {"starsystemName": "Matshiru", "isPlayer": false, "isSubmit": true, "opponentName": ""}}
```

Corresponding journal entry:

```
{ "timestamp":"2022-11-30T18:15:26Z", "event":"Interdicted", "Submitted":true, "IsPlayer":false, "Faction":"" }
```

[Journal.2022-11-30T111811.01.log](https://github.com/EDCD/EDMarketConnector/files/10126257/Journal.2022-11-30T111811.01.log)

Ultimately sounds like a game journal bug to me, but you might want to handle that and silence the warning?

**Comment by Athanasius** [comment]
Technically I think we're in compliance with [the Inara API documentation for this](https://inara.cz/elite/inara-api-docs/#event-40).

So, over to @clonedArtie to comment as to if he wants to update the documentation to "only send non-empty strings", and just not send the event at all if we can't get a value for `opponentName`, or if he wants to start accepting that.

**Comment by Athanasius** [comment]
Artie has informed me that for required properties in Inara API messages `""` should be treated as "not set"/"not available" and probably mean just not sending the message.

So I'll adjust EDMC code, for the 5.6.1 bugfix release coming soon, to add a check for that.

**Comment by Athanasius** [comment]
@chennin I've not played to know.  Was that caused by an "in supercruise, not jumping" Thargoid interdiction?  If so, was it an inevitable interdiction, or do you know for sure these can be escaped (i.e. win the mini-game) ?

Specifically I'm wondering if there can be an `EscapeInterdiction` journal event without an `Interdiction` property, or where it is an empty string.

**Comment by Athanasius** [comment]
OK, thanks for the info.  I've implemented a paranoia check for that anyway.
