### ISSUE TITLE
[WIKI] L3-37

### ISSUE THREAD

**Issue by HalJordan** [EDCD/EDMarketConnector#1750]
It's looking like any dev on it may have been halted going by the Issues that haven't been responded to for quite some time, and it's not  working with the current release of EDMC. You may want to move it to the 'Deprecated plugins' list, at least temporarily.

**Comment by Athanasius** [comment]
Wiki page updated for this report.

Also, a note added that the 'Confirmed working' was specifically about the move to python3, and may not indicate a plugin *still* works.
