### ISSUE TITLE
System hangs when starting EDMC since last update.

### ISSUE THREAD

**Issue by jhaprins** [EDCD/EDMarketConnector#1770]
**Please check the [Known Issues](https://github.com/EDCD/EDMarketConnector/issues/618) in case this has already been reported.**

**Please also check if the issue is covered in our [Troubleshooting Guide](https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting).** It might be something with a known work around, or where a third party (such as EDSM) is causing logging that is harmless.

**Please complete the following information:**
 - Version: 5.7.0+defdc2b
 - Game Version: Live / Odyssey
 - OS: Windows 10
 - OS Locale: English
 - If applicable: Browser [e.g. chrome, safari]
 - Please attach **BOTH** log files, by dragging and dropping them into this input:
     1. `%TEMP%\EDMarketConnector.log` from *immediately* after the bug occurs (re-running the application overwrites this file).
     1. `%TEMP%\EDMarketConnector\EDMarketConnector-debug.log`.  See [Debug Log File](https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting#debug-log-files).  NB: If you don't have this log file then you're not running the latest version of the application and should update first to see if we already fixed the bug you're reporting.

**Describe the bug**
When I have EDMC running when trying to start ED, the launcher won't start and I can't start ED.
When I start EDMC when ED is running, I can't do anything anymore. I can move my mouse, but all other things are impossible. Can't switch tasks or anything. Have to turn the system off using the power button.
This all started after the last update.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Athanasius** [comment]
>     * Version: 5.7.0+defdc2b
>     * Game Version: Live / Odyssey
>     * OS: Windows 10
>     * OS Locale: English
>     * Please attach **BOTH** log files, by dragging and dropping them into this input:
>       
>       1. `%TEMP%\EDMarketConnector.log` from _immediately_ after the bug occurs (re-running the application overwrites this file).
>       2. `%TEMP%\EDMarketConnector\EDMarketConnector-debug.log`.  See [Debug Log File](https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting#debug-log-files).  NB: If you don't have this log file then you're not running the latest version of the application and should update first to see if we already fixed the bug you're reporting.

Despite the 'not start' nature of this bug report you should still have supplied the latest log files as they *might* offer some clues.

> **Describe the bug** When I have EDMC running when trying to start ED, the launcher won't start and I can't start ED. When I start EDMC when ED is running, I can't do anything anymore. I can move my mouse, but all other things are impossible. Can't switch tasks or anything. Have to turn the system off using the power button. This all started after the last update.

There's absolutely no way in which EDMarketConnector.exe running could cause the *game launcher* to not start.  EDMC only reads the Journal files that the game writes (in a manner that could never interfere with the game writing to the latest one), there's no other interaction.

I'd suggest performing a full scan for malware.  Provide the logs this bug report template asks for and maybe we can suggest something more.

**Comment by Athanasius** [comment]
Furthermore, as it's the ED *launcher* not starting when EDMarketConnector.exe is already running, that **really** has to be something specific to your system, as EDMC has **zero** interactions with the *launcher*.

Unless, of course, you have a third-party EDMC plugin that is causing the whole issues.  In which case, again, we need to see the logs from the latest run of EDMarketConnector.exe whilst the ED launcher is *not* running, and then again with the launcher already running.

**Comment by inorton** [comment]
I vote that we close this. About the only thing I can think of is a strange interaction with antivirus and OS-level locking of the journal and status files.  Either way, I don't think this is an EDMC bug.

**Comment by Athanasius** [comment]
Even that really shouldn't be causing some of the described symptoms.

Not even if some of the behaviour is due to using one of the AV that keeps on falsely flagging EDMC as malicious.  Then I'd expect, at worst, EDMC to be 100% quarantined, which would mean it couldn't affect the game or its launcher at all.

Due to lack of further feedback I'm closing this.
