### ISSUE TITLE
Running from source also needs FDevIDs files

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDMarketConnector#1801]
Ensure any documentation for running from source points out/instructs that if *not* using a git clone the user will need to ensure the FDevIDs files (commodity.csv and rare_commodity.csv) files are available.

This only affects some niche 'Output' functionality, but is still necessary.

Alternatively, see if we can get GitHub to include these in the generated archives.  It includes the directories of the sub-modules, but not anything they *contain*.

**Comment by Athanasius** [comment]
I've just updated the wiki:Running-from-source to both outline the necessary extra files if using a release archive **and** the necessary `git submodule` commands to actually sync them if using a git clone.

**Comment by Athanasius** [comment]
I'm now looking at tweaking the windows-build workflow to also create custom .zip and .tar.gz archives that include the FDevIDs files.

**Comment by Athanasius** [comment]
We should look into using one of the 'file-sync' actions to simply pull in the two specific files from FDevIDs into our repo, i.e. stop using it as a sub-module.  It'll be as functional as the 'check if sub-modules have updated' action we currently have.

**Comment by Rixxan** [comment]
I don't think I can find a way to sync without gaining access to more complex repo permissions such as secrets. However, I can add additional warnings of "if these files don't exist, don't die horribly, terminate/log cleanly". 

At least for now.

**Comment by Rixxan** [comment]
Pushing the second half of this issue to the next version to see how this new behavior acts.

**Comment by Rixxan** [comment]
Looking through this one... 

- [x] Releases have the files included in them
- [x] Documentation is up to date stating direct checkouts need submodules
- [x] Program is set to inform you if you don't have the submodules

Frankly speaking, I don't think we can really put too many more safeguards on the program with our available resources. I don't think it's worth the extra effort to add the files into the mainline distro on their own right now. 

Open to reconsidering this, but for now going to close this.
