### ISSUE TITLE
Source Tarball from Release Does Not Display Git Hash

### ISSUE THREAD

**Issue by dvdmuckle** [EDCD/EDMarketConnector#1827]
This is with at least Version 5.8.0, and also happens with 5.8.1, tested on Fedora 37.

The new tarball provided with the intention of running from source, and on Linux, will show the version as "5.8.0+UNKNOWN."
![image](https://user-images.githubusercontent.com/8870292/214176917-7c5645a7-3eb1-4396-8ce4-42a5824ffdb0.png)
While this isn't a bug per say, it doesn't really align with the feature for the Windows version, which will show the Git hash as it's running "frozen" and thus using the included `.gitversion` file. This also affects the new Flatpak version of EDMC, as 1. `git` is not included in the Flatpak runtime and 2. There's a PR for Flatpak to switch to this new tarball, which doesn't include the `.git` folder in it.

Pertinent log:
```
'fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).' doesn't look like a valid git short hash, forcing to None
2023-01-23 23:41:23.323 UTC - INFO - 34582:140044549572416:34582 EDMarketConnector.__main__:2110: Startup v5.8.1+UNKNOWN : Running on Python v3.11.1 (main, Jan  6 2023, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)]
```

One possible solution for this is to include the `.gitversion` file in the tarball, and always check if this file exists, instead of just when the app is running in a "frozen" state. If that sounds agreeable, I can submit a PR with the changes to make that work.

**Comment by Rixxan** [comment]
I'd welcome a PR for this! We should probably only rely on the .gitversion file if the exact hash can't be found (as in, check for git status and then fall back to hash) and might want to have some indication of relying on the githash, but it seems like a good idea.
