### ISSUE TITLE
carrier with crystal shards in hip 36601

### ISSUE THREAD

**Issue by jnorthrup** [EDCD/EDMarketConnector#1849]
checked out the latest master as of this post, in hopes of solving the issue. 

![image](https://user-images.githubusercontent.com/73514/218069568-67f5fd4e-d48c-47f3-8a4f-8d417724a0e0.png)

**Comment by NoFoolLikeOne** [comment]
This is an issue with the contents of the Canonn database.

It seems that EDD-Canonn on 6 occasions put the carrier callsign into the bodyname field.

Ive deleted all the offcending data

**Comment by NoFoolLikeOne** [comment]
This issue can be closed
