### ISSUE TITLE
CAPI: Refreshing access token... 

### ISSUE THREAD

**Issue by Frostbite-UK** [EDCD/EDMarketConnector#1931]
- Version: 5.8.1d81c93c
 - Game Version: Elite Dangerous Horizons - Open Play - v2023.01.26.291050 0.4.6779.0 FD
 - OS: [e.g. Windows 10
 - OS Locale: English, United Kingdom
 - If applicable: Browser - Firefox
 
 - Debug files attached  
[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/11299921/EDMarketConnector.log)
[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/11299923/EDMarketConnector-debug.log)

**Describe the bug**
When clicking on the UPDATE button, the status reads "CAPI: Refreshing access token..." and does not change or update market data for INARA.

**To Reproduce**
1. Start EDMC
2. Wait for cooldown to complete
3. Click on UPDATE button
4. Status does not change from "CAPI: Refreshing access token..." 

**Expected behavior**
Update market data for INARA website

**Screenshot**
![Screenshot](https://user-images.githubusercontent.com/131500169/233752671-5f5d4339-3779-47f8-a80f-d328f97eb1ee.jpg)

**Comment by klightspeed** [comment]
It looks like the token refresh is working, but any attempts to use that token fail with a 401 Unauthorized, which suggests that it is being affected by the CAPI issue that requires both `capi` and `auth` scopes where the token has been created with only the `capi` scope.

**Comment by Frostbite-UK** [comment]
Thanks for your reply. This has fixed the issue for me.

**Comment by Rixxan** [comment]
Glad it's working for you now! Closing this issue as "Resolved".
