### ISSUE TITLE
EDMC Help | About : make version information copyable

### ISSUE THREAD

**Issue by athulin** [EDCD/EDMarketConnector#1936]
**Describe the enhancement**

In the EMCC Help | About E:D Market Connector dialog, the version text cannot be copied. 

**Expected behavior**

I expected that the information would be possible to copy, to make bug reporting (where this information is requested) simpler.

A read-only text field would probably do the job.

**Considered workarounds**

None I can think of.  Re-keying by hand seems to be the alternative, but is apt to introduce error.

**Additional context**

Version: 5.8.1+d81c93c (latest)
OS: Windows 10
Browser: Firefox 112.0.1 

Attached screenshot shows the relevant information in a red rectangle
-
![Image1](https://user-images.githubusercontent.com/53051907/234522849-b27431cc-a9ce-49e9-9cd5-0358567f6d78.png)

**Comment by norohind** [comment]
Re: Considered workarounds. EDMarketConnector writes version to logs each time version window opens, it usually how I get it for bug report.

**Comment by Rixxan** [comment]
I think I've gotten this working on my local system, will include in 5.9.2 after testing.
