### ISSUE TITLE
The station link is dead.

### ISSUE THREAD

**Issue by athulin** [EDCD/EDMarketConnector#1937]
- Version: 5.8.1+d81c93c
 - Game Version: Odyssey
 - OS: Windows 10
 - OS Locale: ( ... no idea: probably english as base, but some setting makes Windows try Swedish dates and currency so ...)
 - 
[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/11330985/EDMarketConnector.log)
[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/11330999/EDMarketConnector-debug.log)

**Describe the bug**
When I am at a station, and click on the Station link, the link produces an error message ("Unable to connect" in my case)

**To Reproduce**
1. Visit a station / outpost / fleet carrier / ... with EDMC active
2. Click on link shown in E:D Market Connect window, next to "Station:" label.
3. See browser show an error message indicating a failure to reach or connect to the site

The link I received this error about is:
https://eddb.io/station/market-id/3701871104

and relates to a fleet carrier (V0Z-84L)

**Expected behavior**

I expected EDMC to connect to a working site.  As EDDB is no more, I consider this something that has to
be fixed in the EDMC end.

**Screenshots**
-  (Don't think any are needed, but if I am wrong please let me know)

**Additional context**
-

**Comment by VAKazakov** [comment]
THere is possibility, in "Configuration" tab of settings, to change sites for those links. Hope that helps.

**Comment by Athanasius** [comment]
> THere is possibility, in "Configuration" tab of settings, to change sites for those links. Hope that helps.

This.  Also, someone could get around to implementing https://github.com/EDCD/EDMarketConnector/issues/1490 .

**Comment by athulin** [comment]
Workaround noted with thanks.  Still, EDDB should be dropped as station info provider (or at least not be the default selection).

**Comment by Rixxan** [comment]
Closing as EDDB is no longer in operation.
