### ISSUE TITLE
Invisible ring survey

### ISSUE THREAD

**Issue by jmunoz2141** [EDCD/EDMarketConnector#1979]
**Please check the [Known Issues](https://github.com/EDCD/EDMarketConnector/issues/618) in case this has already been reported.**

**Please also check if the issue is covered in our [Troubleshooting Guide](https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting).** It might be something with a known work around, or where a third party (such as EDSM) is causing logging that is harmless.

**Please complete the following information:**
 - Version:5.8.1
 - Game Version: Live
 - OS: Windows 11
 - OS Locale:English
 - If applicable: Browser chrome
 - Please attach **BOTH** log files, by dragging and dropping them into this input:
    N/A

**Describe the bug**
When I click on the invisible ring survey link in the app, It launches the browser page which says I need permission from the owner.

**To Reproduce**
1. click on the invisible ring survey link.

**Expected behavior**
expected to be take to a browser page to fill in the survey

**Screenshots**
![image](https://github.com/EDCD/EDMarketConnector/assets/84143412/71b8daac-1489-4774-ab0e-7200fa395c1a)

**Additional context**
N/A

**Comment by Athanasius** [comment]
"Invisible ring survey"?  Sounds like a plugin, not core EDMC code.  Report it to the plugin developer.

**Comment by klightspeed** [comment]
My guess is that it is the currently under heavy development Canonn [EDMC Ring Survey](https://github.com/canonn-science/EDMC-RingSurvey) version Alpha One.

**Comment by Rixxan** [comment]
Hey there Klightspeed. It does look like this was a bug with a particular plugin, not EDMC core. Did you manage to get it working with them, or is this still an issue?

**Comment by jmunoz2141** [comment]
It's likely it was as klightspeed stated although I could not verify.  The issue seems to have gone away on its own.  I will close the ticket.
