### ISSUE TITLE
Errors in 'EDMarketConnector.exe' under Win 11 Pro 22H2

### ISSUE THREAD

**Issue by Marcurling** [EDCD/EDMarketConnector#2004]
**Please check the [Known Issues](https://github.com/EDCD/EDMarketConnector/issues/618) in case this has already been reported.**
- DONE
**Please also check if the issue is covered in our [Troubleshooting Guide](https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting).** It might be something with a known work around, or where a third party (such as EDSM) is causing logging that is harmless.
- DONE

 - Version: 5.8.1+d81c93c (last version on 26th of July 2023)
 - Game Version: 'Odyssey'
 - OS: Windows 11 Pro 22H2
 - OS Locale: French
 - If applicable: Browser Google Chrome / MS Edge
[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/11867293/EDMarketConnector.log)

 - Please attach **BOTH** log files, by dragging and dropping them into this input:
 - > These files do NOT exist [yet] in %TEMP% but in 
     1. `%TEMP%\EDMarketConnector.log` from *immediately* after the bug occurs (re-running the application overwrites this file).
     1. `%TEMP%\EDMarketConnector\EDMarketConnector-debug.log`.  See [Debug Log File]

**Describe the bug**
Starts with window "Errors in 'EDMarketconnector.exe' showing
See the logfile
'C:\Users\user\AppData\Roaming\EDMarketConnector.log' for details
-> included in attached files ;) which says
Traceback (most recent call last):
  File "EDMarketConnector.py", line 49, in <module>
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\MARCUR~1\\AppData\\Local\\Temp\\EDMarketConnector.log'

**To Reproduce**
Just launch EDMC in normal or admin mode.

**Additional context**
1.Can't find file 'EDMarketConnector.py'
2.Fresh Win 11 install : Python may NOT be installed...

Thanks in advance for your help, Marc.

**Comment by Athanasius** [comment]
What *are* the permissions on `%LOCALAPPDATA%\Temp` for the user you're trying to run this as ?  The program needs to be able to create files in that location.

Normally the user in question would automatically have these permissions.  So, either something has changed them at the NTFS level ... or you have some form of anti-virus/firewall blocking the file creation.
