### ISSUE TITLE
5.9.1 Installer not setting link handling for Frontier Auth

### ISSUE THREAD

**Issue by Harry3528** [EDCD/EDMarketConnector#2046]
**Please check the [Known Issues](https://github.com/EDCD/EDMarketConnector/issues/618) in case this has already been reported.**

**Please also check if the issue is covered in our [Troubleshooting Guide](https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting).** It might be something with a known work around, or where a third party (such as EDSM) is causing logging that is harmless.

**Please complete the following information:**
 - Version: [e.g. 4.0.6 - See 'Help > About E:D Market Connector'.  If running from source using git then please paste the output of `git log --decorate=full | head -1`]
 - Game Version: [e.g. 'Live' or 'Odyssey']
 - OS: [e.g. Windows 10, Linux Debian 10.6, etc.]
 - OS Locale: [e.g. English, French, Serbian...]
 - If applicable: Browser [e.g. chrome, safari]
 - Please attach **BOTH** log files, by dragging and dropping them into this input:
     1. `%TEMP%\EDMarketConnector.log` from *immediately* after the bug occurs (re-running the application overwrites this file).
     1. `%TEMP%\EDMarketConnector\EDMarketConnector-debug.log`.  See [Debug Log File](https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting#debug-log-files).  NB: If you don't have this log file then you're not running the latest version of the application and should update first to see if we already fixed the bug you're reporting.

**Describe the bug**
The installer does not set handling of the frontier auth link to connect to the program. In chrome, i get the console error message "Failed to launch 'edmc://auth?code=[REMOVED FOR PRIVACY]&state=[REMOVED FOR PRIVACY]' because the scheme does not have a registered handler." after clicking log in on the frontier web page.

Installing 5.9.0 fixes it, and I can log in and authorize.

**To Reproduce**
Fresh install 5.9.1

**Expected behavior**
Send auth data to the program after I log in and authenticate.

Additional info: This was my first time installing the program, so people just updating will probably not encounter this issue.

**Comment by Razwerkz** [comment]
I'm still having an issue similar to this post-update.  When attempting to login, the "login" button does not seem to do anything.

**Comment by Rixxan** [comment]
Hmm, unfortunately, that part of the tool seem to need a little more TLC (even from before the 5.9.0 update) 

Take a look at these steps and see if one of those solves it? If not let me know and we can go from there. 

https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting#problems-with-frontier-authentication

@Razwerkz

**Comment by Razwerkz** [comment]
I was able to use the localserver-auth.bat file and authenticate.  Thanks!
