### ISSUE TITLE
Make a way to choose the browser that the authentication page opens in

### ISSUE THREAD

**Issue by DawnTreader** [EDCD/EDMarketConnector#2054]
**Describe the enhancement**

I use Edge as my default browser and I have a chrome profile that I use to play elite with. 

**Expected behavior**

It would be nice if instead of auto opening the browser with the authentication page that there was a way to chose the browser EDMC uses to do the authentication thing.

**Considered workarounds**

Changing the default browser back and forth is not an option. 

**Additional context**

Edge is better for security, haven't gotten around to moving my elite profile to an edge profile yet.

**Comment by Rixxan** [comment]
I believe that the system currently calls whatever browser is set as the default for the OS. I'll need to look more at what options we have available to us to make this change or if it is feasible.

**Comment by DawnTreader** [comment]
I changed my mind. I just created a new profile with the same email account in Edge and imported everything. As Edge is more secure, might as well use it. Sorry for the unnecessary post.
