### ISSUE TITLE
Vcruntime140.dll is missing

### ISSUE THREAD

**Issue by techno314** [EDCD/EDMarketConnector#2055]
- OS: Windows 8.1 PRO
 - OS Locale: English
 
**Describe the bug**
If you try to install EDMC to windows 8.1 PRO you get the error "This program can't start because VCRUNTIME140.dll is missing"

**To Reproduce**
1. Install EDMC on Windows 8.1 PRO without vcredist x86 installed
2. Open EDMC

**Expected behavior**
EDMC should open normally

**Screenshots**
![image](https://github.com/EDCD/EDMarketConnector/assets/47404203/1f5e7f24-b8cc-4745-a016-36ff548ee73b)
![image](https://github.com/EDCD/EDMarketConnector/assets/47404203/b1ce7782-9e6a-4c1d-a532-8ee4bb06f4e6)

**Additional context**
The fix is to install vcredist x86

**Comment by Athanasius** [comment]
https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting#missing-vcruntime140-dll

**Comment by Rixxan** [comment]
I asked tech to make an issue for this one, gonna see if the new installer can smart check for this missing dependency and compensate.

**Comment by Rixxan** [comment]
Interestingly, even when VCRUNTIME140.dll is present, EDMC fails to load. Signs of a deeper problem?
![image](https://github.com/EDCD/EDMarketConnector/assets/26337384/5511b878-0934-43f7-bcf2-daa33b1c52b3)

**Comment by Rixxan** [comment]
Steam will stop working on Windows 7, 8, and 8.1 in ~150 days. Should we instead consider just no longer supporting those versions? That would seem to avoid the issue.

**Comment by techno314** [comment]
> Steam will stop working on Windows 7, 8, and 8.1 in ~150 days. Should we instead consider just no longer supporting those versions? That would seem to avoid the issue.

Agreed, this would be a better course of action in my opinion since playing Elite Dangerous will not longer be possible on Win 8.1 soon anyways.

**Comment by Rixxan** [comment]
This is not within remit at this time. Closing.
