### ISSUE TITLE
Latest EDMC causing constant blue wheel beside mouse pointer

### ISSUE THREAD

**Issue by Tommytoff** [EDCD/EDMarketConnector#2058]
EDMC V 5.9.3 exe
 - Version: EDMC V 5.9.3 exe
 - Game Version:  'Odyssey'
 - OS: Windows 10
 - OS Locale: English

 - Please attach **BOTH** log files, by dragging and dropping them into this input:
 [EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/12271324/EDMarketConnector-debug.log)
[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/12271343/EDMarketConnector-debug.log)

**Describe the bug**
When I run EDMC, as it starts up, it opens a browser page(EDGE, still does the same thing when trying to log through Firefox) requesting a log in to Frontier. When I click on the log in, my mouse cursor then has a permanent blue spinning wheel beside it until I close EDMC(which took days to work out where the cause was coming from). I thought at first this was from the ED launcher. I have attached some pics of the screen. This problem, whilst having the 'Blue thinking wheel' causes my CPU to run at an extra 15-20% of its process

**To Reproduce**

**Expected behavior**
For my PC to run normally
To report this problem and for you guys to fix it

**Screenshots**

![IMG20230806140219](https://github.com/EDCD/EDMarketConnector/assets/141596494/9ef7fe67-7c8e-43f0-acbc-1312a12521a1)
![IMG20230806140407](https://github.com/EDCD/EDMarketConnector/assets/141596494/d664843c-5a23-432d-93c9-5afc7c6434f0)

**Additional context**

**Comment by Tommytoff** [comment]
I see one of the photo's I provided doesn't show the blue wheel. It does occasionally blink off

**Comment by Rixxan** [comment]
Looks like the same symptoms (and probably the same cause) as #2057, should be fixed by #2060

**Comment by GreybeardSeawolf** [comment]
I have the same issue with Chrome I open EDMC and it says Update, Logging in. When I click Update it opens Frontier Auth in Chrome, Clicking Frontier log in opens a popup asking if I want to open EDMC (it's already open). If I click open EDMC I get a rapidly flashing blue circle that continues until I shut EDMC down

Version: EDMC V 5.9.3 exe

Game Version: 'Odyssey'

OS: Windows 11 64 bit

OS Locale: English

**Comment by Rixxan** [comment]
Fixed in 5.9.4. Leaving #2060 open as a master ticket for this issue if there are any follow-up issues.

**Comment by Tommytoff** [comment]
Hi Rixxan, 
Thanks for taking time to read about the EDMC issue I was having and yourself and the team fixing it.
EDMC has been updated on my pc and is working well, same as before, normal. 
Cheers,
Tommytoff
