### ISSUE TITLE
ED Market Connector is no longer searchable in start menu by 'market connector' phrase

### ISSUE THREAD

**Issue by norohind** [EDCD/EDMarketConnector#2062]
**Please complete the following information:**
 - Version: v5.9.3+16ffdff
 - Game Version: Odyssey
 - OS: Windows 10
 - OS Locale: English
 - If applicable: Firefox
 - Please attach **BOTH** log files, by dragging and dropping them into this input:
Logs are irrelevant for this issue

**Describe the bug**
I can not find ED Market Connector in windows start menu search by phrase `market connector` or just `market` but early it was
possible. (I blame migration to new installer).

**To Reproduce**
1. Go to windows start menu
2. Type `market connector`
3. Observe lack of search results (view screenshot 1)

**Expected behavior**
ED Market Connector should be found in windows start menu using phrase `market connector`.

**Screenshots**
Screenshot 1
![изображение](https://github.com/EDCD/EDMarketConnector/assets/60548839/46188bd4-d48e-41ca-88d4-a7a440f59349)

Screenshot 2
![изображение](https://github.com/EDCD/EDMarketConnector/assets/60548839/1dc7cde5-719f-42a3-90a8-84655253cf72)

**Additional context**
It appears to be searchable using pharse `edmarketconnector` (see screenshot 2) and this phrase appears to be name of the application in windows(?).

**Comment by Rixxan** [comment]
Updated in [77fd48c](https://github.com/EDCD/EDMarketConnector/pull/2060/commits/77fd48c0334a1bce31cfbf7f8cd65d0f7d983847), will be included in the next patch (coming in like...  less than two hours)
