### ISSUE TITLE
Program won't start

### ISSUE THREAD

**Issue by Dallas25** [EDCD/EDMarketConnector#2064]
- Version: 5.9.4+6e8f881
 - Game Version: 'Odyssey'
 - OS: Windows 10
 - OS Locale: Russian
 - If applicable: Browser Chrome
 
1. [EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/12385705/EDMarketConnector.log)
2. [EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/12385704/EDMarketConnector-debug.log)

**Describe the bug**
Program won't start

**Additional context**
The program does not start, but if you turn off the Internet in the network adapter settings windows, then the program starts.
Everything worked fine for the first few days, but when I reboot my computer this problem started.
Reinstalling the app didn't help.
EDMarketConnector - reset-ui.bat didn't help.
Removing configuration is stored in the registry under HKEY_CURRENT_USER\Software\Marginal\EDMarketConnector didn't help.
Removing the log file %TEMP%\EDMarketConnector.log didn't help.
Ticking the box "Beta: Use Unicode UTF-8 for worldwide language support" didn't help.
In the antivirus settings, I do not see blocked network connections and I repeat that for the first few days everything worked well.

**Comment by Rixxan** [comment]
That's very strange. Thanks for reporting!

Looking through the logs, it looks like your computer was unable to resolve the domains `auth.frontierstore.net` OR `edsm.net`. Usually I would chalk that up to an issue with FDEV's API, but that doesn't appear to be the case. It looks like something on your network has blocked the app's access to the internet, at least in part. 

I would double-check that your firewall has been set to allow EDMC, as this appears to be something on your computer blocking the app not the app itself.

**Comment by Dallas25** [comment]
I don't see any blocked connections in firewall or antivirus. I also put the program in all exclusions but it didn't help
I think I have figured out what the problem is.
The problem is with the auth.frontierstore.net domain. 
I did some network troubleshooting and this is what I got
Finding host auth.frontierstore.net by DNS server (1 of 2).
Pinging auth.frontierstore.net [54.77.152.86] with 64 bytes of data:
Request timed out (seq=0).
Request timed out (seq=1).
Request timed out (seq=2).
Request timed out (seq=3).
Ping statistics for 54.77.152.86:
Packets: Sent = 4, Received = 0, Lost = 4 (100% loss).
Maybe my internet provider is partially blocking the auth.frontierstore.net domain.

There are no problems with the edsm.net domain
Finding host edsm.net by DNS server (1 of 2).
Pinging edsm.net [95.217.192.241] with 64 bytes of data:
Reply from 95.217.192.241: bytes=64 time=50ms TTL=52 (seq=0).
Reply from 95.217.192.241: bytes=64 time=50ms TTL=52 (seq=1).
Reply from 95.217.192.241: bytes=64 time=50ms TTL=52 (seq=2).
Reply from 95.217.192.241: bytes=64 time=50ms TTL=52 (seq=3).
Ping statistics for 95.217.192.241:
Packets: Sent = 4, Received = 4, Lost = 0 (0% loss).
Approximate round trip times in milli-seconds:
Minimum = 50ms, Maximum = 50ms, Average = 50ms
Thanks for the feedback, but I guess you can't help me in this problem.
