### ISSUE TITLE
Fail Export Journal Data to EDSM

### ISSUE THREAD

**Issue by SamuelKeel** [EDCD/EDMarketConnector#2067]
Hi,
using E:D Market Connector' version 5.9.5+6f2ba8d.
-ED Odyssey Live
-Windows 11
-German

Since a couple of days the import of journal date from ED Odyssey Live doesn't work. Updated API, no effect.
Do you see the problem and could you solve it?

Thanks a lot

[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/12428237/EDMarketConnector.log)
[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/12428252/EDMarketConnector-debug.log)

**Please check the [Known Issues](https://github.com/EDCD/EDMarketConnector/issues/618) in case this has already been reported.**

**Please also check if the issue is covered in our [Troubleshooting Guide](https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting).** It might be something with a known work around, or where a third party (such as EDSM) is causing logging that is harmless.

**Please complete the following information:**
 - Version: [e.g. 4.0.6 - See 'Help > About E:D Market Connector'.  If running from source using git then please paste the output of `git log --decorate=full | head -1`]
 - Game Version: [e.g. 'Live' or 'Odyssey']
 - OS: [e.g. Windows 10, Linux Debian 10.6, etc.]
 - OS Locale: [e.g. English, French, Serbian...]
 - If applicable: Browser [e.g. chrome, safari]
 - Please attach **BOTH** log files, by dragging and dropping them into this input:
     1. `%TEMP%\EDMarketConnector.log` from *immediately* after the bug occurs (re-running the application overwrites this file).
     1. `%TEMP%\EDMarketConnector\EDMarketConnector-debug.log`.  See [Debug Log File](https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting#debug-log-files).  NB: If you don't have this log file then you're not running the latest version of the application and should update first to see if we already fixed the bug you're reporting.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Rixxan** [comment]
Hey there! 

Thanks for reporting. If I look at the logs, there are two plugins that are not very happy, EDMC-RingSurvey-2.0.1 and GPL. 

It looks like the GPL problem is simply a warning of using a deprecated method, though I would strongly encourage reaching out to the plugin developer for those ones. (For now, they are non-issues). 

It looks like Inara and EDDN are still ingesting data, so I'm not seeing any issues with the journal read. 

Can you provide more context to what seems to be out of place for you? Do the issues persist if you (temporarily) remove the RingSurvey or GPL Plugins? 

We'll see if we can isolate this and figure out what's going on :)

**Comment by SamuelKeel** [comment]
Hi, 

after renewing the EDSM API again, the transfer of the journal entries is working again....I can't understand what caused the error, but as long as it works, I don't really care.

 

Thank you for your quick feedback and best regards!

 

Von: David Sangrey ***@***.***> 
Gesendet: Donnerstag, 24. August 2023 15:42
An: EDCD/EDMarketConnector ***@***.***>
Cc: SamuelKeel ***@***.***>; Author ***@***.***>
Betreff: Re: [EDCD/EDMarketConnector] Fail Export Journal Data to EDSM (Issue #2067)

 

Hey there!

Thanks for reporting. If I look at the logs, there are two plugins that are not very happy, EDMC-RingSurvey-2.0.1 and GPL.

It looks like the GPL problem is simply a warning of using a deprecated method, though I would strongly encourage reaching out to the plugin developer for those ones. (For now, they are non-issues).

It looks like Inara and EDDN are still ingesting data, so I'm not seeing any issues with the journal read.

Can you provide more context to what seems to be out of place for you? Do the issues persist if you (temporarily) remove the RingSurvey or GPL Plugins?

We'll see if we can isolate this and figure out what's going on :)
