### ISSUE TITLE
Documentation bug: page https://raw.githubusercontent.com/wiki/EDCD/EDMarketConnector/Troubleshooting.md unreadable

### ISSUE THREAD

**Issue by athulin** [EDCD/EDMarketConnector#2069]
**Please complete the following information:**
Not relevant

**Describe the bug**
I visit the main page https://github.com/EDCD/EDMarketConnector/wiki.

The entry  "If you encounter problems" says "Please see Troubleshooting", where the word Troubleshooting is a link to

https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting.md

That page is unreadable, and looks more like something that hasn't been converted from markup to web format.  See

![image](https://github.com/EDCD/EDMarketConnector/assets/53051907/ce1f8747-0325-43a9-9b83-55e79e5569fa)

In the "Known Issues" posting (#618), another link to the same page (Also check over things covered in the [Wiki Troubleshooting page](https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting).)  seems to work as expected.  

**To Reproduce**
See above

**Expected behavior**
The first link identified above should have produced a readable web page, not a markup page

**Screenshots**
(included in description above)

**Comment by Rixxan** [comment]
That's uh... strange. 

I think I found the busted link and fixed it. Is it working now?

**Comment by athulin** [comment]
Yes, that did the trick. Thanks.
