### ISSUE TITLE
Station name not shown in UI before change in station provider

### ISSUE THREAD

**Issue by der-eismann** [EDCD/EDMarketConnector#2077]
**Please check the [Known Issues](https://github.com/EDCD/EDMarketConnector/issues/618) in case this has already been reported.**

**Please also check if the issue is covered in our [Troubleshooting Guide](https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting).** It might be something with a known work around, or where a third party (such as EDSM) is causing logging that is harmless.

**Please complete the following information:**
 - Version: 5.9.5
 - Game Version: 'Odyssey'
 - OS: Fedora 38
 - OS Locale: German
 - Please attach **BOTH** log files, by dragging and dropping them into this input: Actually I can't find any of the log files, need to work on that as well.
 - 
[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/12653181/EDMarketConnector-debug.log)

**Describe the bug**
~I tried to finally update the Flatpak version of EDMC from 5.8.1 to 5.9.5, but when testing it, it seems to not be able to read the currently docked station from the journal anymore.
This is while being docked at a station. Leaving and re-docking also doesn't help. When I go back to 5.8.1 it works fine again.~

I updated the Flatpak version from 5.8.1 to 5.9.5, but when testing it, it seems to not be able to read the currently docked station from the journal anymore. While debugging, I found that in my config I still had the line
```
station_provider = eddb
```

Interestingly removing the line also didn't fix the issue. Only when I enter the configuration menu and select Inara as the station provider and confirm the change, the station is shown in the UI again. Changing it back to EDSM afterwards also works fine. But it seems that the selection of the default provider is failing somehow.

**To Reproduce**
1. Remove line with `station_provider` from `EDMarketConnector.ini`
2. Start EDMC
3. See no Station name in UI
4. Enter configuration menu, set station provider to Inara
5. Station name is now visible

**Expected behavior**
Station name shown in UI

**Screenshots**
![Bildschirmfoto vom 2023-09-18 22-08-30](https://github.com/EDCD/EDMarketConnector/assets/10406217/f10de100-4cfd-4195-b9ba-56961d205a9b)

**Comment by der-eismann** [comment]
This seems to be a configuration issue. I noticed that I still had EDDB set as the `station_provider`. But removing the line from the config doesn't help. Only when I change the station provider at least once in the settings, the station name is shown.

**Comment by Rixxan** [comment]
I am now able to recreate the issue, and I have designed a fix that would automatically reset the provider to default on opening the preferences... but I can't seem to find how it is loaded in the first place. Ideally, if station_provider is not in the list of valid station providers, it should reset or at least throw an error.
