### ISSUE TITLE
[Docs] Translations - Call out the "find all translations" script

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDMarketConnector#2087]
https://github.com/EDCD/EDMarketConnector/blob/main/docs/Translations.md#edit-l10nentemplate-to-add-the-phrase was never updated to call out that there's a helper script to forgo the tedious (and error prone, if only in forgetting to do it) editing of `L10n/en.template`.

The script is https://github.com/EDCD/EDMarketConnector/blob/main/scripts/find_localised_strings.py - it scans all the code for instances of the `_(...)` calls, and uses the `# LANG ...` comments that should be associated with them to automatically build a new `en.template` file.

**Comment by Rixxan** [comment]
Added a reminder to the in-text docs in the indicated area, will ensure it is even more clear on our upcoming docs review.
