### ISSUE TITLE
Privacy Panel Indentation

### ISSUE THREAD

**Issue by GLWine** [EDCD/EDMarketConnector#2088]
## Basic information
 - Version: EDMC 5.9.5+6f2ba8d
 - Game Version: Live 4.0.17
 - OS: Windows 10
 - OS Locale: Italian
 - Log file: [EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/13216942/EDMarketConnector.log) and [EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/13216951/EDMarketConnector-debug.log)
## Description of the BUG
The BUG is visible every time a language is loaded that modifies the text strings in the Privacy section. Specifically, if the strings (`Hide private group name in UI` and `Hide multi-crew captain name`) are translated, they are indented strangely. it may happen that the first or second gear moves forward compared to the normal position for no apparent reason.

I checked that there was nothing in the translation files that might lead to this irregularity (e.g. `\t`), but there is nothing that justifies these events.
## To Reproduce
1. Go to 'File->Settings->Appearance'
2. Click on 'language and choose one of these: German, Polish, Portuguese (Brazil), Portuguese (Portugal), Serbian (Latinica), Serbian (Latinica, Bosnia and Herzegovina), Russian, Japanese, Chinese (Simplified) and Korean'
2.1 It also happens with the new Italian translation file.
3. Go to 'Privacy section'
4. You will see the error
## Expected behavior
I expect the text to be indented correctly as in English.
## Screenshots
**English**
![00 Inglese](https://github.com/EDCD/EDMarketConnector/assets/54741923/9a320e94-650e-42eb-bc47-cb9e18b82389)
**German**
![01 Tedesco](https://github.com/EDCD/EDMarketConnector/assets/54741923/156b0d4a-6da3-48ab-bd80-560b73d7ea1b)
**Polish**
![02 Polacco](https://github.com/EDCD/EDMarketConnector/assets/54741923/d1ff757b-daac-4dbd-ab8d-c51cc649ad7d)
**Portuguese** (Brazil)
![03 Portoghese (Brasile)](https://github.com/EDCD/EDMarketConnector/assets/54741923/cadd01d4-bfb1-4fe1-985b-1601dfc6de97)
**Portuguese** (Portugal)
![04 Portoghese (Portogallo)](https://github.com/EDCD/EDMarketConnector/assets/54741923/a29f8e0b-0f82-4081-9a08-4a583cd584d1)
**Serbian** (Latinica)
![05 Serbo (Latinica)](https://github.com/EDCD/EDMarketConnector/assets/54741923/23baf53f-b085-4f51-8f20-a21006453686)
**Serbian** (Latinica, Bosnia and Herzegovina)
![06 Serbo (Latinica, Bosnia Erzegovina)](https://github.com/EDCD/EDMarketConnector/assets/54741923/c525aa60-0158-438b-b8c9-e7a0a744ac0e)
**Russian**
![07 Russo](https://github.com/EDCD/EDMarketConnector/assets/54741923/35731931-41ac-4f94-afef-b189a6008e82)
**Japanese**
![08 Giapponese](https://github.com/EDCD/EDMarketConnector/assets/54741923/aa80ee64-1195-44c6-8222-55a20b4e6d31)
**Chinese** (Simplified)
![09 Cinese (semplificato)](https://github.com/EDCD/EDMarketConnector/assets/54741923/a248cdca-0452-410c-89c2-a96d4751ea06)
**Korean**
![10 Coreano](https://github.com/EDCD/EDMarketConnector/assets/54741923/668f957a-64ab-4a40-ae14-0a7dbaa25941)
**Italian**
![11 Italiano](https://github.com/EDCD/EDMarketConnector/assets/54741923/81a85bc7-bd99-4ede-b653-857413b73821)
## Additional context
The problem only exists on translations that actually translated those specific sentences.

**Comment by klightspeed** [comment]
Probably need `sticky=tk.W` in the `.grid` calls for those checkbuttons.

**Comment by C1701D** [comment]
Fixed in #2096
