### ISSUE TITLE
Plugin address box displayed incorrectly

### ISSUE THREAD

**Issue by GLWine** [EDCD/EDMarketConnector#2089]
## Basic information
 - Version: EDMC 5.9.5+6f2ba8d
 - Game Version: Live 4.0.17
 - OS: Windows 10
 - OS Locale: Italian
 - Log file: [EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/13216942/EDMarketConnector.log) and [EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/13216951/EDMarketConnector-debug.log)
## Description of the BUG
The BUG is visible in the Plugins section regardless of the language selected. The text box containing the address where the plugins are saved is partially cut off. This makes the position unclear and in general the panel aesthetically incorrect.
## To Reproduce
1. Go to 'File->Settings->Plugin'
2. You will see the error
## Expected behavior
I expect the address box to behave like the one in Output.
## Screenshots
**English**
![01 inglese](https://github.com/EDCD/EDMarketConnector/assets/54741923/1554f844-8f38-44cc-8737-970c65eeac3c)
**Francese**
![02 Francese](https://github.com/EDCD/EDMarketConnector/assets/54741923/c2e8903a-8691-4f5e-af85-d70eefadc2d6)
**Italian**
![03 Italiano](https://github.com/EDCD/EDMarketConnector/assets/54741923/1d5b93fd-be54-4aa7-9189-1c942806627e)
**Outpot**
![00 Output](https://github.com/EDCD/EDMarketConnector/assets/54741923/73140a33-69e9-4ae6-8d28-0b93d7fea56f)
## Additional context
If I had to speculate I think that the writing overlaps the address box where the plugin is located

**Comment by C1701D** [comment]
Fixed in #2096
