### ISSUE TITLE
Missing module when opening ship build in coriolis.io

### ISSUE THREAD

**Issue by PoL0** [EDCD/EDMarketConnector#2093]
**Please complete the following information:**
 - Version: 5.9.5+6f2ba8d
 - Game Version: 'Odyssey'
 - OS: Windows 10
 - OS Locale: English
 - If applicable: Browser Chrome 119.0.6045.124
 - Please attach **BOTH** log files, by dragging and dropping them into this input:
     1. `%TEMP%\EDMarketConnector.log` from *immediately* after the bug occurs (re-running the application overwrites this file).
     1. `%TEMP%\EDMarketConnector\EDMarketConnector-debug.log`.  See [Debug Log File](https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting#debug-log-files).  NB: If you don't have this log file then you're not running the latest version of the application and should update first to see if we already fixed the bug you're reporting.

**Describe the bug**
Refinery module not exported to coriolis.io build when clicking on ship name

This is my Type-7 build: https://s.orbis.zone/n92b (disregard disabled Abrasion Laser, I did that)
This is that same ship when opened from EDCM: https://s.orbis.zone/n92d

**To Reproduce**
1. Open EDCM
2. Ensure coriolis.io is configured as shipyard website
3. Click on your ship (it happens to me with a Type-7 miner build with refinery). Haven't tested with other ship types.
4. Notice Refinery module doesn't appear in coriolis.io.

**Expected behavior**
An exact copy of the current ship loadout is shown in coriolis.io (btw it works correctly in edsy)
[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/13369110/EDMarketConnector.log)
[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/13369111/EDMarketConnector-debug.log)

**Comment by C1701D** [comment]
Could you maybe also provide us the EDSY link you get? The longer one with ``https://edsy.org/#/I=`` that you get before clicking anything on their website, not the shorter ``https://edsy.org/#/L=`` one you get after selecting okay.
The data portion of both the coriolis and EDSY links should be the same so that we we can narrow down where the fault sits.

**Comment by PoL0** [comment]
It doesn't seem to be the refinery, but the size 2 Optional Internal slot which is never "exported" to coriolis

**Comment by PoL0** [comment]
Also, as requested, I'm sending both coriolis and EDSY links (as I'm using a different setup that also is missing one module (2E Cargo Rack) in coriolis:

Coriolis:
https://coriolis.io/import?data=H4sIANMAWGUC_7WWUU_bMBDHv8rk51I5SVOgb0DHqFQGo4iHTVNkkmtjkdiW7RR1iO--s0NpKKWhUulLbcf_n-9yd748kUuZVQUYMvjzREYWSjIgubKJyTkU2b2UxoJODP8HNEkLZkxIOuRKkIHVFXTIteZSc7sgg6BDJoW0KL_lYnHBdKYkFzYgz50vAYdfBY48-KQs5UicFVz5jfX0QioFmgzCTvPgHJg1XDwUrBJpjmfbSmuwiUXqB0eHm4_uNX2yCwWHSSrTB8VtqwuTnKuzl70NSOmiy3TK9Ezes0UmpW416cxtvmA2zd-bw3QpK53MNMsgaDXqxO9uUtDJRMlH0KpgOHRRij8bpWunu3a6dSKIGRewG-2ScfHd64zH1WPQXMzI4ImcFhUonNjREFXhUf8w6h_Tzmr9JysBMeeTYTKWYnbDxAzw0CXGPYKCp3jqt3OmjVtaPXXQiNKAInEMcyi8ZViKfMpB18U4ZvduHQ01hrhtxozMDykzv_dKc0Sx4o6hQRg92kXUchJ2qXNpSRgJCzPv_1sMfYcJ3nCCoN_tUfyFTZoPw1Czx1ajaLf_ysJxcNTE4Iu7UpaXrNjg4AbLaPzGtJAeduPnvx3yq2JFHVrndDMrcsxYnWk-f5MZ8QeZQV8z41xjaLGepnboxOvJVvApmEopqev87W3PuBV3jMJJLdxYEhk3VvP7ykrdBLcbXEdkpV6nGxBGauOh0XZrV7fADcvYO9K0gsIy8dB8oVFrqZ2j6hZV6zR_K2mW1rh-jWu_VdwfDZKJ0-wTGe4fGXlkvB0Z74Ts7R8Ze2Rvn8j-Z5DRTshDjwzfJbdv-zMQoNmycqLtlbMGPvoAXOH1keqKG0AWVldryXjasacF2z0Pd_L8eLOBroWCZUppydLcVNxCwrI5Eylk7c20FuvFyYt-4vTNI-aSp6CcxXN4aR7bkXd4gUNx52TE3czuk2T54UDqqet79GWYgXCq05sD2r_F59gG_cJYskxW7m1jdwBjWekoIQ2jgyA4CI5uKR3Q40Ec_ybP_wEFDwfJvwoAAA%3D%3D

EDSY: 
https://edsy.org/#/I=H4sIAJsBWGUC_7WW227iMBCGX2Xla4qchFO5a8uyRaLbbql6satVZJIBrAbbsh0qtuq779gpJRxKikS5wXb8f57JzHjyQm5kmmdgSPfPCxlYmJMumSkbmxmHLB1LaSzo2PB_QOMkY8aEpEZuBelanUON3GkuNbdL0g1qZJRJi_IHLpbXTKdKcmED8lr7EnD4VeDIgy_mczkQVxlXfmMxvZZKgSbdsFY-eAbMGi6eMpaLZIZn21xrsLFF6gdHh_uPbpR9sksF7TiRyZPittKF0Yyrq7e9JcjcRZfphOmpHLNlKqWuNOnKbb5mNpntmsP0XOY6nmqWQlBp1IXfXaagk7GSz6BVxnDootT8bJTunO7O6baJIKZcwHG0G8bFd68zHleMQXMxJd0XcpnloHBiBz1UhZ1WO2qd09p6_SebA2L6o148lGJ6z8QU8NAVxj2CjCd46rc-08YtrZ86aERpQJE4hAVk3jIsRT7hoItiHLKxW0dDjSFumzED80PK1O-91RxRLHtkaBBGj9YRtZqEdepcWhEGwsLU-7-JoTuYYIMTBK16g-IvLNN8GHqaPVcaReutdxaOg04Zgy_uVlk-Z9keB_dYRpsbpoW0XW--_q2RXznLitA6p8tZMcOM1anmi43MaH6QGfQ9M_oaQ4v1NLE9J95OtoxPwORKSV3kb-Nwxq25QxSOCuHekki5sZqPcyt1GVxtcBGRtXqbbkAYqY2HRoetXd8C9yxlO6RJDpll4qn8QqPKUuuj6gFV2zR_K2mWFLhWgau-VdwfDeKR05wSGZ4eGXlk8zCyeRSycXpk0yMbp0S2PoOMjkK2PTLcSW7f9qcgQLNV5USHK2cL3PkAnOP1keicG0AWVldlyXjauacFhz0Pj_L8fL-BroWCZUppyZKZybmFmKULJhJIq5tpIdbLizf9yOnLRywkT0A5ixfw1jwOIx_xAofs0cmIu5ndJ8nqw4EUU9f36NswBeFUl_dntPWAz7EN-oWhZKnM3dvG7gDGsrmjhDSMzoLgLOg8UNoNom7Q_E1e_wMV9l1UvwoAAA%3D%3D

**Comment by Rixxan** [comment]
Hey there PoL0! Thanks for reporting this to us. 

Looking at the code, this appears to be a bug with how Coriolis itself is handling the Type 7 with modules in the size 2 optional cargo slot. We've informed their team of the issue with the details you've provided. 

You might want to add your additional information to the Coriolis issue on this topic: https://github.com/EDCD/coriolis/issues/691

Sorry we can't be more help.

**Comment by PoL0** [comment]
No need to sorry, thanks a lot for your work!
