### ISSUE TITLE
pip install results in "error: externally-managed-environment" on Arch Linux

### ISSUE THREAD

**Issue by ThornedRose** [EDCD/EDMarketConnector#2112]
- Version: updating from 5.8.1 -> 5.9.5
 - Game Version: Odyssey
 - OS: Arch Linux kernel 6.6.7-arch1-1  / KDE Plasma 5.27.10
 - OS Locale: English en_nz

I was updating from 5.8.1 to 5.9.5. Previously I was able to just overwrite files, however this time, I received an error about watchdog, same as this issue here: https://github.com/EDCD/EDMarketConnector/issues/2071. The solution to which is to use pip to install dependencies. I followed that to do so, however received the following error:
```console
$ pip install -r requirements.txt
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try 'pacman -S
    python-xyz', where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Arch-packaged Python package,
    create a virtual environment using 'python -m venv path/to/venv'.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip.
    
    If you wish to install a non-Arch packaged Python application,
    it may be easiest to use 'pipx install xyz', which will manage a
    virtual environment for you. Make sure you have python-pipx
    installed via pacman.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```
I got around the issue by manually installing the python-watchdog package instead `sudo pacman -S python-watchdog`

The most up to date EDMC now run with no errors. Perhaps there needs to be a separate section in "Running from source" for Arch Linux? Or an addition to the "[Ensure you have dependencies installed](https://github.com/EDCD/EDMarketConnector/wiki/Running-from-source#ensure-you-have-dependencies-installed)" section, "On Arch you need" and adding `sudo pacman -S python-watchdog`?

I don't know anything about the error's suggested use of pipx so it's possible that would be a better solution instead for Arch users. (The package name is `python-pipx` in Arch repos.)

**To Reproduce**
1. Follow the Wiki [Running from source](https://github.com/EDCD/EDMarketConnector/wiki/Running-from-source) instructions
2. At the "Use pip to install application requirements" step run `pip install -r requirements.txt`
3. See above error

**Expected behavior**
Necessary python dependencies would install

**Comment by klightspeed** [comment]
One thing to possibly refer to is <https://packaging.python.org/en/latest/specifications/externally-managed-environments/> and <https://docs.python.org/3/library/venv.html>

**Comment by Athanasius** [comment]
Point 7 of <https://github.com/EDCD/EDMarketConnector/wiki/Running-from-source#using-a-non-distribution-python-on-eg-debian> basically needs to be called out as mandatory on Debian with bookworm (12.x) or later, or any other affected OS.

This is because of https://peps.python.org/pep-0668/ .

@Rixxan @C1701D basically you need to update the running from source documentation to reflect this.

**Comment by Rixxan** [comment]
Updated documentation page in the wiki, referencing both the packaging link and the pep. 

Closing as not an EDMC issue.
