### ISSUE TITLE
EDMC 5.1.10 not working with TCE

### ISSUE THREAD

**Issue by achimste** [EDCD/EDMarketConnector#2135]
Hi!

I accidently opened an issue in discussion (sorry for that).

Game Version: Odyssey
OS: Win 10
Locale: German (but I play the game in English)
Browser: Firefox

Description:
When starting TCE, under Settings the EDMC.exe is no more recognized. Also manually pointing to EDMC.exe does not work.
Older version of EDMC.exe does work flawlessly.

Steps to reproduce.
1. Start TCE wait for the first screen to appear.
2. Click on Extensions.
3. On the top you can see the EDMC status. It shows "Server down". Manually pointing to the EDMC.exe does not work.

LOGS:
No log file available (empty) for EDMC.exe because it was never (could not be) startet from TCE! (see above)

EDMarketConnector-debug.log

[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/13822861/EDMarketConnector-debug.log)

**Comment by klightspeed** [comment]
I think your discussion was converted to issue #2124

**Comment by Rixxan** [comment]
Hey there! Thanks for the report. We've managed to identify the issue and have developed a patch. It will be included in 5.10.1.

**Comment by achimste** [comment]
Thank you so much! Eager to wait for the patch :)
