### ISSUE TITLE
Change the link for edmcoverlay2 in wiki

### ISSUE THREAD

**Issue by pan-mroku** [EDCD/EDMarketConnector#2145]
I wasn't sure how to label this.

As discussed in [this thread](https://github.com/sersorrel/edmcoverlay2/pull/10) please change the URL of edmcoverlay2 in https://github.com/EDCD/EDMarketConnector/wiki/Plugins to [my fork](https://github.com/pan-mroku/edmcoverlay2)

**Comment by Rixxan** [comment]
Done!
