### ISSUE TITLE
Erroneous space in steam path in wiki installation instructions

### ISSUE THREAD

**Issue by fleetingffox** [EDCD/EDMarketConnector#2162]
The [Linux section](https://github.com/EDCD/EDMarketConnector/wiki/Installation-&-Setup#linux) for the installation instructions on the wiki appears to have an erroneous space in the path name in the `mkdir` command line, resulting in two directories being created (since the second directory requires root permission, it will simply not be created and an error will be issued):
```
mkdir -p ~/.steam/steam/steamapps/compatdata/359320/pfx/drive_c/users /steamuser/Saved\ Games/Frontier\ Developments/Elite\ Dangerous
                                                                     ^
```

If I understand the reasoning behind this `mkdir` command correctly, may I also make a suggestion to add a line such as, for example:

> This will ensure the directory exists, as it will create the directory if it doesn't yet exist, and does nothing if the directory already exists.

So that use of the`` `mkdir` here is better understood.

**Comment by Rixxan** [comment]
Updated and applied :)
