### ISSUE TITLE
Python 3.9 error: TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by chennin** [EDCD/EDMarketConnector#2171]
[Running from source wiki](https://github.com/EDCD/EDMarketConnector/wiki/Running-from-source) currently states (Dec 18, 2023 revision) that EDMC "will no longer work under Python 3.8 or earlier". However, EDMC does not run on 3.9 either.

```python
Traceback (most recent call last):
  File "/data/./EDMarketConnector.py", line 61, in <module>
    import killswitch
  File "/data/killswitch.py", line 20, in <module>
    import config
  File "/data/config/__init__.py", line 486, in <module>
    config = get_config()
  File "/data/config/__init__.py", line 480, in get_config
    from .linux import LinuxConfig
  File "/data/config/linux.py", line 17, in <module>
    class LinuxConfig(AbstractConfig):
  File "/data/config/linux.py", line 25, in LinuxConfig
    def __init__(self, filename: str | None = None) -> None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

Repro'd by checking out the code and `git checkout stable` (tag: Release/5.10.1), then `podman run -it --rm -v  $PWD:/data python:3.9 bash`, then in the container: `cd /data; pip install -r requirements.txt; python ./EDMarketConnector.py`.

Also reported on [ED Community Discord](https://discord.com/channels/89778537522802688/89782152853479424/1214828688219049994).

`str | None` syntax was apparently added in 3.10, though I don't have a source other than StackOverflow.

**Comment by Athanasius** [comment]
Yeah, that's just a wiki update being necessary.  The thing to note really is the 'targeted against'.  That means no actual testing of prior versions, so there should be no real expectation of it working.

**Comment by bgol** [comment]
Yes, added with 3.10: [Allow writing union types as X | Y](https://peps.python.org/pep-0604/)

**Comment by Rixxan** [comment]
@chennin please try the following: 

Change the imports and files in config/linux.py to include:

```python
"""
linux.py - Linux config implementation.

Copyright (c) EDCD, All Rights Reserved
Licensed under the GNU General Public License.
See LICENSE file.
"""
from __future__ import annotations

import os
import pathlib
import sys
from configparser import ConfigParser
from config import AbstractConfig, appname, logger

assert sys.platform == 'linux'
``` 

I think we just forgot to add a future annotation there.

**Comment by chennin** [comment]
Yes, that certainly moves past the unsupported operand error
