### ISSUE TITLE
[Translations] Update language - Italian

### ISSUE THREAD

**Issue by GLWine** [EDCD/EDMarketConnector#2184]
I have made the missing translations to the interface of EDMC 5.10.3 in the Italian language.

However, I was wondering if you ever migrate to Crowdin, I must admit that OneSky is veramnte inconvenient to translate.
It does not help at all to understand whether there is `\n` or `\r`, in general the interface is far too simplistic and what little there is is really poorly organized. 

I sincerely hope you will consider migrating to Crowdin.

Best regards

**Comment by Rixxan** [comment]
Thanks for the update! We generally apply updated translations just before every release. I'll be sure to pull it in. 

As to the translation system we can look into seeing what options exist, though I can't promise anything as I would need to look at the alternatives to determine if it's worth the added hassle of moving.

**Comment by Rixxan** [comment]
Closing as translations have been pushed to live, however, investigations into if we should move systems should continue.
