### ISSUE TITLE
Remove MacOS Support

### ISSUE THREAD

**Issue by Rixxan** [EDCD/EDMarketConnector#2186]
**Describe the enhancement**

Development of Elite Dangerous on MACos ended over half a decade ago. Recent changes to the MacOS NSSound API may have resulted in EDMC no longer functioning. There is no functional manner to play on MacOS natively, and known MaCoS users have reported using Wine and the distributed EXEs to utilize EDMC and Elite. 

macOS support should be formally removed. As this does not actually change the available API endpoints (See EDMC channel discussion in EDCD Discord) this does not particularly necessitate a major point version change. 

**Additional context**

This will also substantially reduce code complexity by removing specific caveats for Darwin code that no longer need to exist. Deprecation regarding public API available endpoints should be reviewed.

**Comment by Athanasius** [comment]
1. To be a pedanty it's "macOS", not "MacOS" ;)
2. Yup, it's time for this to just die.  Unless someone with actual macOS hardware wants to step up to help develop patches/PRs as needed.  I've not seen anyone volunteer for that.  Whilst it's possible to get a macOS image to boot under, e.g. VirtualBox, there's no legal way to do that without also owning an applicable piece of Apple hardware (for access to the OS install images).
3. Any user being perverse by wanting to run the game and EDMC on Apple hardware can do so using the windows installer via WINE or other such emulation/virtualisation.  They just need to be sure the Windows version they use for that is supported.

**Comment by Rixxan** [comment]
> 1. To be a pedant it's "macOS", not "MacOS" ;)

Updated to be much, much worse <3

**Comment by Rixxan** [comment]
OK. #2186 broke the new feature in #2183. Reverting and trying again from there.
