### ISSUE TITLE
[Translations] New language - Turkish

### ISSUE THREAD

**Issue by Kumdanadam** [EDCD/EDMarketConnector#2195]
Language: the new translation you'd like to help add.

**You should only open an issue if you're able to contribute to the new translation yourself.**

See https://github.com/EDCD/EDMarketConnector/wiki/Translations for guidelines.

**Comment by Kumdanadam** [comment]
I've translated bgs-tally(aussi) but we were not able to use related translation due to edmc has no Turkish translatation yet. 
I would like to translate EDMC to Turkish also. Thanks for opportunity.

**Comment by Rixxan** [comment]
Welcome to the team! Sent you the information.
