### ISSUE TITLE
The program just stopped opening, the reasons are unknown to me

### ISSUE THREAD

**Issue by Zapelmon** [EDCD/EDMarketConnector#2199]
[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/14961660/EDMarketConnector.log)
[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/14961661/EDMarketConnector-debug.log)

 I decided to update the BioScan plugin, I updated, everything was fine, I later shut down my computer, and behold when I tried to start the program again, it wouldn't open.... reinstalling, cleaning everything did not help. (including uninstalling all plugins, etc.)

**To Reproduce**
1. Idk, it just happened
**Expected behavior**
The program will open...

**Additional context**
The program as far as I know was not run as administrator, and it is in Windows Defender exception.

**Comment by Athanasius** [comment]
This looks like a simple case of "more exception cases, possibly a catch-all one, need adding to the code".

However that's only the necessary patch to get past the issue of "couldn't reach the github servers to retrieve killswitches".  So, @Zapelmon you might want to double-check local firewall configuration for EDMarketConnect.exe and/or raw.github.com (or other github.com hosts).

**Comment by Zapelmon** [comment]
You'll laugh, but, it fixed itself XD. Thanks for the reply of course, and it's good that it was resolved so easily. But I still haven't figured out the cause, it had no problems with the firewall.
