### ISSUE TITLE
Bug: The drop-down menus in the settings are shown completely white when the dark theme is set

### ISSUE THREAD

**Issue by GLWine** [EDCD/EDMarketConnector#2206]
**Basic nformation:**
 - Version:  from 5.10.0+b0b9113 to 5.10.4+3b2f37f (maybe even earlier)
 - Game Version: Live
 - OS: Windows 10 Pro 22H2
 - OS Locale: Italian
 - If applicable: Browser Chrome
 - Please attach **BOTH** log files, by dragging and dropping them into this input:
     1. `%TEMP%\EDMarketConnector.log`
        - [EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/14986458/EDMarketConnector.log)
     3. `%TEMP%\EDMarketConnector\EDMarketConnector-debug.log`.
        - [EDMarketConnector-debug.zip](https://github.com/EDCD/EDMarketConnector/files/14986453/EDMarketConnector-debug.zip)

**Describe the bug**
When the EDMC theme is set to dark, there are problems with the visibility of some items.
In the settings in the drop-down menus that concern EDMC (excluding plug-ins) these are loaded completely in white and are visible only when the cursor passes over the elements.

**To Reproduce**
1. Go to `settings`, to the `appearance` tab
2. Set the dark theme
3. Click on the `OK` button
4. Reopen settings
5. Go to the `Coriolis` tab
   1. Open the drop-down menu *(beta/nomal)*
   2. The texts will be white on a white background
   3. When you hover the cursor, the background turns black on the selected item.
6. Go to the `Configuration` tab
   1. Open the *any* drop-down menu
   2. The texts will be white on a white background
   3. When you hover the cursor, the background turns black on the item
7. Go to the `Appearance` tab
   1. Open the *Language* drop-down menu
   2. The texts will be white on a white background
   3. When you hover the cursor, the background turns black on the item

**Expected behavior**
When the theme is set to dark, since the settings do not change they themselves become dark, the drop-down menus must not be affected. They will then have to show the objects in gold so that there is black text on a white background..

**Screenshots**
![image](https://github.com/EDCD/EDMarketConnector/assets/54741923/f76d6152-e282-4997-b7d7-aaca3c6ada2f)
![image](https://github.com/EDCD/EDMarketConnector/assets/54741923/9cf605ce-311c-442a-954d-7f0a82fbafcc)
![image](https://github.com/EDCD/EDMarketConnector/assets/54741923/4497d709-769f-4047-ae52-e66ca64b4966)
![image](https://github.com/EDCD/EDMarketConnector/assets/54741923/00a3b622-0496-4115-b3bf-741e353f86ed)
![image](https://github.com/EDCD/EDMarketConnector/assets/54741923/38b5f513-9b8d-41ae-87ff-fee29f047481)
![image](https://github.com/EDCD/EDMarketConnector/assets/54741923/7085b577-95f4-4d05-8bd5-c961a5dcec36)

**Comment by Rixxan** [comment]
Unable to validate with EDMC 5.10.4+3b2f37f
![image](https://github.com/EDCD/EDMarketConnector/assets/26337384/e3c1f469-ceb0-4800-bee7-172b044f1a81)
![image](https://github.com/EDCD/EDMarketConnector/assets/26337384/bfda4b9c-17dc-4f7e-af04-1df3317654df)
![image](https://github.com/EDCD/EDMarketConnector/assets/26337384/ae705c4c-b243-4ff7-82b7-850cfa80d78a)

**Comment by Rixxan** [comment]
Can you test if this problem persists without plugins? Trying to determine where the issue might be.

**Comment by GLWine** [comment]
I have to test two specific plugins.
The two plugins are [EDRecon](<https://github.com/lekeno/edr>) and [BGS-Tally](<https://github.com/aussig/BGS-Tally>)

However I have 3 others installed (EDMC Hits](<https://github.com/inorton/EDMCHits>), [EDMC-ATEL](<https://github.com/Intergalactic-Astronomical-Union/ATEL-EDMC>) and [HourlyIncome](<https://github.com/Exynom/EDMC-HourlyIncome>)

**Comment by Rixxan** [comment]
Interesting, thanks for the follow-up!

@lekeno you may be interested in taking a look at this one (though I would encourage you to open a bug report with EDR, @glwine)

Will be closing this as a bug with EDR, not EDMC. If further information comes to light that it's something with EDMC itself, please feel free to reopen :)

**Comment by lekeno** [comment]
The issue should be fixed in the next release.
