### ISSUE TITLE
Incomplete Shipoutfit file export of EDMC.exe

### ISSUE THREAD

**Issue by Eventure-TCE** [EDCD/EDMarketConnector#2228]
Hello Rixxan,

I received a report from a user of TCE that references the outfitting export file for the ship in use where jump drive data is missing. I think this has to do with the new drives, which are not yet fully mapped by EDMC.exe.

Here is the incomplete export text:
[Vulture]
L: 3C/Gimballed Beam Laser
L: 3C/Gimballed Beam Laser
U: 0D Frame Shift Wake Scanner
U: 0I Point Defence
U: 0I Chaff Launcher
U: 0F Electronic Countermeasure

BH: 1I Lightweight Alloy
RB: 4A Power Plant
TM: 5C Thrusters
FH: 3C Frame Shift Drive
EC: 3C Life Support
PC: 5A Power Distributor
SS: 4C Sensors
FS: 3C Fuel Tank (Capacity: 8)

MC: 5D Module Reinforcement Package

5: 5E Cargo Rack (Capacity: 32)
4: 4C Shield Generator
2: 1B Collector Limpet Controller
1: 1A Fuel Scoop
1: 1C Frame Shift Drive Interdictor
1: 1E Supercruise Assist
1: 1E Advanced Docking Computer
---
Cargo : 32 T
Fuel  : 8 T
Mass  : 339.70 T empty
        379.70 T full

The range information (unladen/laden) is missing under the mass information.

**Comment by Rixxan** [comment]
Which EDMC cmdline flag does TCE use for that? I remember last time you mentioned you could replicate with `EDMC.exe --loglevel DEBUG -o %TEMP%\test.csv`. Will that also replicate here?

**Comment by Eventure-TCE** [comment]
Yes, it's the -e flag. 

Maybe you add a zero for unladen and laden, like

Range : 0 LY unladen
             0 LY laden
             
as long as no data is available, if you don't have another solution up your sleeve.
Hope that they can fill the gap at some point.
Thanks for your help, again!

**Comment by Rixxan** [comment]
So this isn't going to be an instant fix. To provide the output of the ship's range and loadout (EDSM.exe's -e flag), the program needs to know all the available details. We generally source this data from Coriolis's files and read the journal files. 

Unfortunately, there are two bits of data not present in the game data we have access to that seem to preclude us from just adding them ourselves - `fuelmul` and `fuelpower`. Historically, the community has reverse-engineered these values to be constants based on the size and rating of the drive. However, when I use the historical numbers for these formulas, they do not match what I observe in the game. Therefore, it is likely that either my math sucks (possible) or FDEV has altered these numbers for the new SCO drives. 

Without these updated numbers, we won't be able to determine the exact numbers of your laden, unladen, and other jump drive details. As such, we'll be filling these values with temporary placeholders of 0.0 if we can't figure out the range from the existing data. 

Of course, as these numbers are known we'll add the exact info. (Currently, I think there are 43 modules whose details are unknown to Coriolis and need these numbers to get added, and of course, anything added in this update may not be initially supported such as any Python Mk II specific modules like armor) There may be bugs when encountering Python Mk II specific modules or the new FSDs, among other details. 

I will continue to add things as I find them. Look for a 5.10.5 update to come out sometime in the next few hours to at least suppress these issues and add some of the data we know.  Further updates will come as more information becomes available.

**Comment by Rixxan** [comment]
@Eventure-TCE Is the language of "X.X LY Laden" exactly expected, or simply to have *some* content there? Because the "Laden" and "Unladen" output by EDMC seem to be misnomers - they assume maximum fuel and only differ based on if cargo is present. I want to correct that but not if it'll break TCE Or other readers.

**Comment by Eventure-TCE** [comment]
As long as only the values change, but not the name, you can adjust it. Otherwise, I would just have to know the new name in advance and I would then adapt TCE accordingly, if that is what you have in mind.

**Comment by Rixxan** [comment]
Potential minor change:
https://github.com/HullSeals/EDMarketConnector/blob/690523c9169a88c90fd5b7073c898e216cd8551d/edshipyard.py#L181-L182 

but it seemed to be okay, the program seemed to adapt cleanly. If that does break something let me know and I'll revert it in the next release.

**Comment by Rixxan** [comment]
https://github.com/EDCD/coriolis-data/pull/98 contains the information we need. Once that's merged in we can pull the data to EDMC and release an update with SCO module support.

**Comment by Eventure-TCE** [comment]
Thank you for the tip and nice to hear that you have now received the missing data. I have a TCE update in the pipeline with a new, configurable interface for EDMC. I'll wait for your release for a final check as I've rewritten the file's reader which should work with both versions so nothing breaks on my end.

**Comment by Rixxan** [comment]
Released in 5.10.6
