### ISSUE TITLE
5.11.0 Installer Issues

### ISSUE THREAD

**Issue by Onkelwilliam** [EDCD/EDMarketConnector#2250]
**Please complete the following information:**

[//]: # (You can gather most of this information with the EDMC System Profiler)
 
 - Version: [e.g. 5.10.4+39af6c34`]
 - Game Version: [e.g. 'Live' or 'Odyssey']
 - OS: [e.g. Windows 10, Linux Debian 10.6, etc.]
 - OS Locale: [e.g. English, French, Serbian...]
 - If applicable: Browser [e.g. chrome, safari]

**Describe the bug**

[//]: # (A clear and concise description of what the bug is.)

**To Reproduce**

**Expected behavior**

[//]: # (A clear and concise description of what you expected to happen.)

**Screenshots**

[//]: # (If applicable, add screenshots to help explain your problem.)

**Additional context**

**Please Confirm the Following...**

[//]: # (Add any other context about the problem here.)
- [ ] I have checked the [Known Issues](https://github.com/EDCD/EDMarketConnector/issues/618) list to ensure this is not a duplicate
- [ ] I have checked the [Troubleshooting Guide](https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting) to check for known workarounds

**Logs**
Please attach both the EDMarketConnector.log and EDMarketConnector-debug.log if available.

You can find these logs at `%TEMP%\EDMarketConnector.log` and `%TEMP%\EDMarketConnector\EDMarketConnector-debug.log`

See [Debug Log File](https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting#debug-log-files) for information on the Debug Log files

**Comment by Rixxan** [comment]
Hey there! If this has to do with 5.11, we just spotted a potential issue with the release and have rolled it back. We are investigating what caused this.

**Comment by Rixxan** [comment]
@Onkelwilliam Please reinstall from the latest installers. 

A fixed release is here: https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F5.11.0

**Comment by Onkelwilliam** [comment]
Thank you very much for your quick response David. I will reinstall the new version in the evening. have a nice dayo7 Cmdr WeedooAm 05.06.2024 um 23:36 schrieb David Sangrey ***@***.***>:﻿
@Onkelwilliam Please reinstall from the latest installers.
A fixed release is here: https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F5.11.0
