### ISSUE TITLE
Export ship to SLEF option

### ISSUE THREAD

**Issue by leonardofelin** [EDCD/EDMarketConnector#2262]
**Describe the enhancement**
Add export/generate SLEF to the right-click context menu of ships.

**Expected behavior**
When right-clicking the ship name, a new option to export to SLEF, together with the Coriolis and EDSY options.

**Considered workarounds**
This will be a shortcut to exporting to SLEF. Today, we need to open in EDSY and then generate the SLEF.

**Additional context**
This will be very useful in tools like Spansh's Galaxy Plotter, which need the exact ship outfitting to work.

**Comment by Rixxan** [comment]
Docs: https://inara.cz/elite/inara-impexp-slef/
