### ISSUE TITLE
Constantly needing to re-authenticate - but not working.

### ISSUE THREAD

**Issue by StarGoid** [EDCD/EDMarketConnector#2264]
- Version: 5.11.2
 - Game Version: Odyssey
 - OS: Windows 10
 - OS Locale: English
 - If applicable: N/A

**Describe the bug**

When the EDMC app starts up - it throws my browser to the FDEV Authentication page.
I put in my details - and click the button - but that's it.  Nothing happens.  No errors.
Then if I hit the "update" button on EDMC - it throws me to the authenticated/switch profile page which doesn't seem to be functional at all.  This has only happened since the last couple of days.  Updated to 5.11.2 today - but same issue.   I'm at a complete loss - EDMC status just says: Awaiting Full CMDR Login.

**Comment by Rixxan** [comment]
Hey there! Thanks for reporting. "Awaiting full CMDR Login" usually indicates EDMC is waiting on you to log into the game fully - not just to the menu but into your ship. 

Can you confirm if logging into the game fully then authenticating still doesn't fix the issue?

**Comment by StarGoid** [comment]
Yes, it happened while fully logged in and playing the game. It was still displaying the correct system and ship info while displaying “waiting” message at the same time. I’m not entirely sure it was an error at EDMCs end or at the FDev API end…. I was going to delete it and reinstall etc, but figured I’d report it first just in case it was either an easy fix or a new bug.I’d happily provide logs and trouble shoot it if needed.  But it was spawning the FDev login every few minutes which was annoying as heck while I was streaming on twitch.I ended up just closing the app - but then that bothered me because I’ve used EDMC religiously since the day I got it. Sent from my fully operational Death Star!On Jun 18, 2024, at 14:08, David Sangrey ***@***.***> wrote:﻿
Hey there! Thanks for reporting. "Awaiting full CMDR Login" usually indicates EDMC is waiting on you to log into the game fully - not just to the menu but into your ship.
Can you confirm if logging into the game fully then authenticating still doesn't fix the issue?

**Comment by StarGoid** [comment]
**UPDATE**
I removed one plugin at a time and restarted... until all the plugins were gone.  That didn't change anything - it still did the same strange thing.

So - I deleted the app completely and re-installed it.   Now (without any plugins yet) seems to be working perfectly fine.
Have not logged in with more than my one main account yet - will try that next, later tonight probably.

**Comment by Rixxan** [comment]
Odd. Let us know if there's anything else we can do to assist or the issue re-occurs.
