### ISSUE TITLE
Odd message: "unhashable type: list"

### ISSUE THREAD

**Issue by athulin** [EDCD/EDMarketConnector#2278]
EDMC Version: 
 - 5.11.1+5d43388

OS Details:
- Operating System: Windows 10
- Version: 10.0.19045
- Machine: AMD64
- Python Version: 3.11.9

Environment Details
- Detected Locale: Swedish_Sweden
- Detected Encoding: utf8
- Journal Directory: C:\Users\Anders Thulin\Saved Games\Frontier Developments\Elite Dangerous
- Game Version: 4.0.0.1807
- Game Build: r303387/r0 
- Using Odyssey: True
- Journal Dir Lockable: True

**Describe the bug**

Discovered the message "unhashable type: list" in the lower message field (added: the Status Text line) of EDMC.  Looks like an error message
or warning. Nothing in the user interface seemed to be wrong or inoperable.

No known way to reproduce it, as I don't know if it was my arrival at LHS 2687 that caused it, or if it remained from an earlier jump. I'll be jumping around my current system a bit later, and will keep my eyes peeled for this message. However, I also discovered that I had a new release waiting for install, which I have installed.

As I have not noted any negative effects, this is more info to you than a normal bug report.

**Expected behavior**

I don't expect odd messages.

**Screenshots**

Sorry.

**Additional context**

**Please Confirm the Following...**

[//]: # (Add any other context about the problem here.)
- [yes ] I have checked the [Known Issues](https://github.com/EDCD/EDMarketConnector/issues/618) list to ensure this is not a duplicate
- [yes] I have checked the [Troubleshooting Guide](https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting) to check for known workarounds

**Logs**
Please attach both the EDMarketConnector.log and EDMarketConnector-debug.log if available.

[EDMarketConnector-debug.log](https://github.com/user-attachments/files/16381443/EDMarketConnector-debug.log)

[EDMarketConnector.log](https://github.com/user-attachments/files/16381462/EDMarketConnector.log)

**Comment by Rixxan** [comment]
Thank you @athulin and @klightspeed for the report! I'll get a beta fix pushed out tonight and get a main release done in a few days if this is confirmed to fix it.
