### ISSUE TITLE
EDMC Will not launch the commander login page. (First-time setup on a new PC)

### ISSUE THREAD

**Issue by OhlsenO** [EDCD/EDMarketConnector#2293]
[//]: # (You can gather most of this information with the EDMC System Profiler)
 
EDMC Version: 
 - 5.11.3+9cc4630

OS Details:
- Operating System: Windows 10
- Version: 10.0.19045
- Machine: AMD64
- Python Version: 3.11.9

Environment Details
- Detected Locale: English_United States
- Detected Encoding: utf8
- Journal Directory: C:/Users/Olaf/Saved Games/Frontier Developments/Elite Dangerous
- Game Version: 4.0.0.1808
- Game Build: r304197/r0 
- Using Odyssey: False
- Journal Dir Lockable: True

 - OS Locale: English
 - Opera GX

As it currently stands, I am unable to get EDMC to launch the frontier login page so I can connect accounts. This will be my third install of this tool to this account, and I have made sure to remove authorization of this app from frontier so I can try and establish a new connection.

1. Install EDMC
2. Launch it after install
3. Sit and stare at "Awaiting full CMDR login"

Fully expecting it to let me login.

- [X] I have checked the [Known Issues](https://github.com/EDCD/EDMarketConnector/issues/618) list to ensure this is not a duplicate
- [X] I have checked the [Troubleshooting Guide](https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting) to check for known workarounds

**Logs**

[EDMarketConnector-debug.log](https://github.com/user-attachments/files/16839030/EDMarketConnector-debug.log)

**Comment by chennin** [comment]
"Awaiting full CMDR login" means fully log in to the game, that means having control of your ship/character in open, solo, or private group. Try that.

**Comment by OhlsenO** [comment]
![image](https://github.com/user-attachments/assets/0eb2b7fc-115f-47d3-9378-bb9d2250b0cc)

**Comment by Rixxan** [comment]
I'll take that as issue solved. Glad it's working now :)
