### ISSUE TITLE
Display = "AWAITING FULL CMDR LOGIN"

### ISSUE THREAD

**Issue by RoscoeDark** [EDCD/EDMarketConnector#2295]
**Please complete the following information:**

[//]: # (You can gather most of this information with the EDMC System Profiler)
 
 - Version: [e.g. 5.10.4+39af6c34`]
 - Game Version: [e.g. 'Live' or 'Odyssey']
 - OS: [e.g. Windows 10, Linux Debian 10.6, etc.]
 - OS Locale: [e.g. English, French, Serbian...]
 - If applicable: Browser [e.g. chrome, safari]

**Describe the bug**

[//]: # (A clear and concise description of what the bug is.)

**To Reproduce**

**Expected behavior**

[//]: # (A clear and concise description of what you expected to happen.)

**Screenshots**

[//]: # (If applicable, add screenshots to help explain your problem.)

**Additional context**

**Please Confirm the Following...**

[//]: # (Add any other context about the problem here.)
- [ ] I have checked the [Known Issues](https://github.com/EDCD/EDMarketConnector/issues/618) list to ensure this is not a duplicate
- [ ] I have checked the [Troubleshooting Guide](https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting) to check for known workarounds

**Logs**
Please attach both the EDMarketConnector.log and EDMarketConnector-debug.log if available.

You can find these logs at `%TEMP%\EDMarketConnector.log` and `%TEMP%\EDMarketConnector\EDMarketConnector-debug.log`

See [Debug Log File](https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting#debug-log-files) for information on the Debug Log files

**Comment by RoscoeDark** [comment]
[EDMarketConnector.log](https://github.com/user-attachments/files/17134483/EDMarketConnector.log)
[EDMarketConnector-debug.log](https://github.com/user-attachments/files/17134487/EDMarketConnector-debug.log)

**Comment by chennin** [comment]
0. Reboot. You have multiple EDMCs running.
1. Open one EDMC and leave it running
2. Log in to SOLO, OPEN, or PRIVATE GROUP

**Comment by RoscoeDark** [comment]
reboot means retart PC ?

**Comment by chennin** [comment]
Yes

`2024-09-25 15:49:22.816 UTC - INFO - 3764:8132:8132 journal_lock.JournalLock._obtain_lock:109: Exception: Couldn't lock journal directory "C:\Users\Huet\Saved Games\Frontier Developments\Elite Dangerous", assuming another process running: PermissionError(13, 'Permission denied')`

Your Windows profile may also be messed up (OneDrive?)

**Comment by RoscoeDark** [comment]
Ok I did so and = EDMC is running but still got the same message under the inlay. Applets open as frontier authentification twice. but the account is already linked to Steam. So what can I do now ? Uninstall EDMC ?

**Comment by RoscoeDark** [comment]
I use it till the update to day and did nothing else. Was running without issue till now

**Comment by RoscoeDark** [comment]
I have onedrive but nothing saved on it

**Comment by RoscoeDark** [comment]
Logs and debug are int his directory = C:\Users\MYNAME\AppData\Local\EDMarketConnector\logs

**Comment by flaneur93** [comment]
same here ..

2024-09-25 16:54:08.930 UTC - INFO - 8180:8084:8084 journal_lock.JournalLock._obtain_lock:109: Exception: Couldn't lock journal directory "C:\Users\Atilla Berke\Saved Games\Frontier Developments\Elite Dangerous", assuming another process running: PermissionError(13, 'Permission denied')
2024-09-25 16:54:08.938 UTC - INFO - 8180:8084:8084 EDMarketConnector.__main__:344: An EDMarketConnector.exe process was already running, exiting.

**Comment by RoscoeDark** [comment]
I have totally Uninstalled EDMC With revoUninstaller and then downloaded the last version from Github, then intall again.
I've got this message when installing :
One or more of your URL providers were invalid, and have been reset.
Station was set to None, and has been reset to EDSM
Shipyard was set to None, and have been reset to EDSY
System was set to None, and have been reset do EDSM

So I launched again EDMC and update API fields dor INARA and EDSM
The result remain the same.

**Comment by flaneur93** [comment]
ok i found the solution;

Go to installed files,
Start EDMarketConnector - localserver-auth.bat
click update and login 

its worked for me

**Comment by flaneur93** [comment]
where is the EDMC installed on your computer ?

**Comment by RoscoeDark** [comment]
ok I finally found it in the "programmes(x86)>EDMarket Connector. The applet leads to a loging frontier and error 500 occurs

**Comment by flaneur93** [comment]
send me a screenshot

**Comment by RoscoeDark** [comment]
![image](https://github.com/user-attachments/assets/d64cc7aa-c745-403a-aa29-f974f60b0ddf)

**Comment by flaneur93** [comment]
ok return to previous page and try diffrent login method

**Comment by RoscoeDark** [comment]
![image](https://github.com/user-attachments/assets/8427d1af-ced0-44d3-9f99-e2b9d75411c0)
This is previous page

**Comment by flaneur93** [comment]
ok click on change account and try with steam

**Comment by RoscoeDark** [comment]
Don. Must i close EDMS and Elite ?

**Comment by RoscoeDark** [comment]
Nothing have changed by the way eccept the error message which was not

**Comment by RoscoeDark** [comment]
MAN it works !! I did again the auth.bat and after applet authentification, it was successfull ! Si everything works fine now ! Thank you so much for your quick and efficient help ! 👍

**Comment by RoscoeDark** [comment]
The authentification by Steam finally solve the issue.
