### ISSUE TITLE
cant read journal file

### ISSUE THREAD

**Issue by flaneur93** [EDCD/EDMarketConnector#2297]
![Screenshot_3](https://github.com/user-attachments/assets/a1d3738a-e2b6-4804-8d0b-a05ac85ee810)

**Comment by Rixxan** [comment]
Hello, 

Please add any log files you have to assist in diagnosing this issue. 

Please also try this: 

Hello! Thank you for reporting an error. 

Please try the following steps (from ticket #2303)

>     * Launch EDMC by navigating "C:\Program Files (x86)\EDMarketConnector" and running "EDMarketConnector - localserver-auth.bat" (EDMC must be closed)
> 
>     * If you get an error 500 when attempting to authenticate, select change account and login with Steam

Let me know if that works for you!

**Comment by Rixxan** [comment]
I was able to confirm this one. Hotfix incoming today or tomorrow.

**Comment by Rixxan** [comment]
I believe this issue to be resolved.

Testing a fix in the Beta track right now. Please feel free to test and let me know if the issue persists!

https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F5.12.1-rc2

**Comment by Rixxan** [comment]
Fixed in latest release.
