### ISSUE TITLE
Tray Exit not working as of 5.12.0 Stable

### ISSUE THREAD

**Issue by taiiat0** [EDCD/EDMarketConnector#2299]
- Version: 5.12.0 Stable
 - Game Version: Odyssey
 - OS: win10 22H2
 - OS Locale: English

**Describe the bug**
as of the last Stable, now when i hit Exit on the Tray, EDMC doesn't actually shutdown. the UI says shutting down, but nothing happens.
Clicking the X on the UI does close it, however.
Clicking the X first also works fine, it's just the Tray option that seems to not be doing anything now.

(was working before this build)

**Expected behavior**
hit Exit on Tray, EDMC shuts down/exits

**Logs**
[EDMarketConnector.log](https://github.com/user-attachments/files/17156985/EDMarketConnector.log)
[EDMarketConnector-debug.log](https://github.com/user-attachments/files/17156986/EDMarketConnector-debug.log)

**Comment by Rixxan** [comment]
Hello! Thank you for reporting an error. 

Please try the following steps (from ticket #2303)

> I just solved this issue so I'll paste my solution here as well
> 
> Solved with following steps:
> 
>     * Use [release 5.11.3](https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F5.11.3) although I'm not sure if this is required or not
> 
>     * Launching the game **AND** entering solo play (loading the game is never stated anywhere even in troubleshooting)
> 
>     * Launch EDMC by navigating "C:\Program Files (x86)\EDMarketConnector" and running "EDMarketConnector - localserver-auth.bat" (EDMC must be closed)
> 
>     * If you get an error 500 when attempting to authenticate, select change account and login with Steam

Let me know if that works for you!

**Comment by Rixxan** [comment]
Looking through your logs, I see a number of errors regarding the "ATEL" plugin. Does this issue still persist if you remove that plugin? It's possible that plugin is causing EDMC to hang.

**Comment by Rixxan** [comment]
I'm just glad it's fixed! Thanks for the update. 

Given that, we'll say 5.12.1 fixed it and I'll close this out. If it comes back please feel free to reopen.
