### ISSUE TITLE
Exceptions logged on startup and shutdown

### ISSUE THREAD

**Issue by aussig** [EDCD/EDMarketConnector#2301]
**Please complete the following information:**

[//]: # (You can gather most of this information with the EDMC System Profiler)
 
EDMC Version: 
 - 5.12.0+cc6e200

OS Details:
- Operating System: Windows 10
- Version: 10.0.22631
- Machine: AMD64
- Python Version: 3.11.9

Environment Details
- Detected Locale: English_United Kingdom
- Detected Encoding: utf8
- Journal Directory: .
- Game Version: ValueError
- Game Build: ValueError
- Using Odyssey: ValueError
- Journal Dir Lockable: True

**Describe the bug**

On starting up EDMC, am getting the following exception thrown in the EDMC log file:

```python
Exception in thread DDE worker:
Traceback (most recent call last):
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "threading.pyc", line 982, in run
  File "protocol.pyc", line 206, in worker
TypeError: Objects of type 'int' can not be converted to Unicode.
```

On shutting down EDMC, am getting two different exceptions thrown, both from built-in plugins, in both the main EDMC log and the debug log:
```python
2024-09-28 07:30:41.406 UTC - ERROR - 61296:42352:42352 plug.notify_stop:273: Plugin "EDDN" failed
Traceback (most recent call last):
  File "plug.pyc", line 270, in notify_stop
  File "C:\Program Files (x86)\EDMarketConnector\plugins\eddn.py", line 2240, in plugin_stop
    this.eddn.close()
  File "C:\Program Files (x86)\EDMarketConnector\plugins\eddn.py", line 607, in close
    self.sender.close()
  File "C:\Program Files (x86)\EDMarketConnector\plugins\eddn.py", line 245, in close
    self.db.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 54412 and this is thread id 42352.
```

and

```python 
2024-09-28 07:30:41.408 UTC - ERROR - 61296:42352:42352 plug.notify_stop:273: Plugin "EDSM" failed
Traceback (most recent call last):
  File "plug.pyc", line 270, in notify_stop
  File "C:\Program Files (x86)\EDMarketConnector\plugins\edsm.py", line 264, in plugin_stop
    this.thread.join()  # type: ignore
    ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'join'
```

**To Reproduce**
1. Launch EDMC
2. Quit EDMC
3. Examine log files

**Expected behavior**

No errors on startup or shutdown

**Logs**

[EDMarketConnector-debug.log](https://github.com/user-attachments/files/17173598/EDMarketConnector-debug.log)
[EDMarketConnector.log](https://github.com/user-attachments/files/17173599/EDMarketConnector.log)

**Comment by aussig** [comment]
Interesting information in the system profiler:

* Operating System: Windows 10
* Version: 10.0.22631

My actual O/S, from Windows System Profiler is:

* OS Name: Microsoft Windows 11 Pro
* Version: 10.0.22631 Build 22631

Also, not too sure what's going on here:

* Game Version: ValueError
* Game Build: ValueError
* Using Odyssey: ValueError

Would you like me to raise a separate issue for that?

**Comment by Syzuna** [comment]
Win 11 being reported as Win 10 is nothing new. 
That is on Microsoft though.

**Comment by Rixxan** [comment]
Issue with system profiler has been fixed in the latest beta release. This is on deck for attention right after.

**Comment by aussig** [comment]
I haven't seen any of these exceptions being logged in v5.12.1 since using it over the last day. I can't be certain they are fixed after such a short testing time of course, but suspect that something in the latest release (Pathlib related?) solved the problems.

**Comment by Rixxan** [comment]
Closing due to lack of reoccurrence. If this happens again, please reopen with updated log files.
