### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by Johnny654** [EDCD/EDMarketConnector#2305]
**Please complete the following information:**

[//]: # (You can gather most of this information with the EDMC System Profiler)
 
 - Version: [e.g. 5.10.4+39af6c34`]
 - Game Version: [e.g. 'Live' or 'Odyssey']
 - OS: [e.g. Windows 10, Linux Debian 10.6, etc.]
 - OS Locale: [e.g. English, French, Serbian...]
 - If applicable: Browser [e.g. chrome, safari]

**Describe the bug**

[//]: # (A clear and concise description of what the bug is.)

**To Reproduce**

**Expected behavior**

[//]: # (A clear and concise description of what you expected to happen.)

**Screenshots**

[//]: # (If applicable, add screenshots to help explain your problem.)

**Additional context**

**Please Confirm the Following...**

[//]: # (Add any other context about the problem here.)
- [ ] I have checked the [Known Issues](https://github.com/EDCD/EDMarketConnector/issues/618) list to ensure this is not a duplicate
- [ ] I have checked the [Troubleshooting Guide](https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting) to check for known workarounds

**Logs**
Please attach both the EDMarketConnector.log and EDMarketConnector-debug.log if available.

You can find these logs at `%TEMP%\EDMarketConnector.log` and `%TEMP%\EDMarketConnector\EDMarketConnector-debug.log`

See [Debug Log File](https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting#debug-log-files) for information on the Debug Log files

**Comment by Rixxan** [comment]
Please resubmit with a completed bug report, including log files.

**Comment by Johnny654** [comment]
2024-09-30 12:19:05.517 UTC - INFO - 23196:17548:17548 journal_lock.JournalLock._obtain_lock:109: Exception: Couldn't lock journal directory "C:\Users\Name\Saved Games\Frontier Developments\Elite Dangerous", assuming another process running: PermissionError(13, 'Permission denied')
2024-09-30 12:19:05.523 UTC - INFO - 23196:17548:17548 EDMarketConnector.__main__:344: An EDMarketConnector.exe process was already running, exiting.
