### ISSUE TITLE
can't authorize through steam anymore. might be steam problems

### ISSUE THREAD

**Issue by vanishare** [EDCD/EDMarketConnector#2308]
**Please complete the following information:**

[//]: # (You can gather most of this information with the EDMC System Profiler)
 
 - Version: [e.g. 5.10.4+39af6c34`]
 - Game Version: [e.g. 'Live' or 'Odyssey']
 - OS: [e.g. Windows 10, Linux Debian 10.6, etc.]
 - OS Locale: [e.g. English, French, Serbian...]
 - If applicable: Browser [e.g. chrome, safari]

**Describe the bug**

[//]: # (A clear and concise description of what the bug is.)

**To Reproduce**

**Expected behavior**

[//]: # (A clear and concise description of what you expected to happen.)

**Screenshots**

[//]: # (If applicable, add screenshots to help explain your problem.)

**Additional context**

**Please Confirm the Following...**

[//]: # (Add any other context about the problem here.)
- [ ] I have checked the [Known Issues](https://github.com/EDCD/EDMarketConnector/issues/618) list to ensure this is not a duplicate
- [ ] I have checked the [Troubleshooting Guide](https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting) to check for known workarounds

**Logs**
Please attach both the EDMarketConnector.log and EDMarketConnector-debug.log if available.

You can find these logs at `%TEMP%\EDMarketConnector.log` and `%TEMP%\EDMarketConnector\EDMarketConnector-debug.log`

See [Debug Log File](https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting#debug-log-files) for information on the Debug Log files

**Comment by Rixxan** [comment]
Testing a fix in the Beta track right now. I think this is related to issue
#2303.

Please feel free to test and let me know if the issue persists!

https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F5.12.1-rc2

**Comment by Rixxan** [comment]
Fixed in 5.12.1
https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F5.12.1
