### ISSUE TITLE
Can't Get the Authorization to work

### ISSUE THREAD

**Issue by Whitewolf061486** [EDCD/EDMarketConnector#2313]
**Please complete the following information:**

[//]: # (You can gather most of this information with the EDMC System Profiler)
 
 - Version: 5.12.0+cc6e200
 - Game Version: Odyssey
 - OS: Windows 10
 - OS Locale: English
 - If applicable: Browser Chrome

**Describe the bug**

[//]: # When I start the program it launches a web page to do the authorization, but nothing happens when I click the button to sign in. I have tried going through the Frontier Authorization link in the troubleshooting. It will authorize the program, but when i start the program I still get sent to an auth web page.

**To Reproduce**
1. Start program
2. Click on sign in.
3. Nothing happens

**Expected behavior**

[//]: # Open program, get the auth web page, sign in, approve, use the program as advertised.
EDMC Version: 
 - 5.12.0+cc6e200

OS Details:
- Operating System: Windows 10
- Version: 10.0.22631
- Machine: AMD64
- Python Version: 3.11.9

Environment Details
- Detected Locale: English_United States
- Detected Encoding: utf8
- Journal Directory: .
- Game Version: ValueError
- Game Build: ValueError
- Using Odyssey: ValueError
- Journal Dir Lockable: True

**Please Confirm the Following...**

[//]: # (Add any other context about the problem here.)
- [X] I have checked the [Known Issues](https://github.com/EDCD/EDMarketConnector/issues/618) list to ensure this is not a duplicate
- [X] I have checked the [Troubleshooting Guide](https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting) to check for known workarounds

**Logs**
Please attach both the EDMarketConnector.log and EDMarketConnector-debug.log if available.

You can find these logs at `%TEMP%\EDMarketConnector.log` and `%TEMP%\EDMarketConnector\EDMarketConnector-debug.log`

See [Debug Log File](https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting#debug-log-files) for information on the Debug Log files
[EDMarketConnector.log](https://github.com/user-attachments/files/17229091/EDMarketConnector.log)
[EDMarketConnector-debug.log](https://github.com/user-attachments/files/17229095/EDMarketConnector-debug.log)

**Comment by Whitewolf061486** [comment]
IDK if it matters, but I migrated my account from Xbox to pc. I'm now using steam to play.

**Comment by Rixxan** [comment]
This appears to be the same issue as being tracked in #2303.

A fix for this bug is being tested in the Beta track right now.

Please see if that updated version works for you:
https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F5.12.1-rc4

**Comment by Whitewolf061486** [comment]
I think this worked. I'm going to try to update this version, and see if it
continues to work.




[image: image.png]
Respectfully,

Jeff Norton

**Comment by Rixxan** [comment]
Fixed in 5.12.1
https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F5.12.1
