### ISSUE TITLE
Suggestion: Tracking HazRES data

### ISSUE THREAD

**Issue by blarzgh** [EDCD/EDMarketConnector#341]
a feature that could note the locations of Resource Extraction Sites and send it back to like eddb and all that would be an awesome feature for bounty hunters

**Comment by Marginal** [comment]
I don't think Res sites appear in the Journal, so i don't think it's possible to automate this.
Some kind of manual system could work.

**Comment by inorton** [comment]
Sadly, http://hosting.zaonce.net/community/journal/v16/Journal_Manual_v16.pdf has no mention of resource sites.

I would expect it to be related to SupercruiseExit.  Some thing similar to USSDrop would be useful for this, but it looks like there is no data that can support this feature

**Comment by inorton** [comment]
Actually,  SupercruiseExit like so, 
```
{ "timestamp":"2018-12-12T00:04:48Z", "event":"SupercruiseExit", "StarSystem":"HIP 36509", "SystemAddress":44853905755, "Body":"HIP 36509 1 A Ring", "BodyID":2, "BodyType":"PlanetaryRing" }
```
Will tell us we are in a ring.

If we are deluged with "give me your cargo" messages in a short space of time (while clean) we can be fairly sure we are in some kind of RES.

If we see chat messages from system security we can be sure it isn't a HAZ.

**Comment by Athanasius** [comment]
If anyone is still interested in this then please implement it in a plugin.  If such a plugin is possible and works well enough then I *might* look into merging it into the core code.

**Comment by Athanasius** [comment]
I believe this is covered by the EDDN `fsssignaldiscovered` schema now.  Indeed that was part of the impetus for adding it.
