### ISSUE TITLE
Henry O'Hare's Hangar vs. Henry O'Hare's Hanger

### ISSUE THREAD

**Issue by CMDR-Cometborne** [EDCD/EDMarketConnector#352]
The station Henry O'Hare's Hang**a**r in the Summerland used to be named Henry O'Hare's Hang**e**r in the past.  Unfortunately, this rename looks to have been somewhat incorrectly in-game, leading to a number of problems.

In the system map, the station has the "...gar" name, this variant is also used in the journal, and also shows in the EDMC window:
![image](https://user-images.githubusercontent.com/25147462/46580606-63670a80-ca28-11e8-803d-cb4f9958c373.png)
```{
  "timestamp": "2018-10-07T09:30:02Z",
  "event": "Docked",
  "StationName": "Henry O'Hare's Hangar",
  "StationType": "Coriolis",
  "StarSystem": "Summerland",
  "SystemAddress": 972566792555,
  "MarketID": 128043008,
  "StationFaction": "Summerland Patron's Party",
```
![image](https://user-images.githubusercontent.com/25147462/46580639-fd2eb780-ca28-11e8-9152-c025b9d53946.png)

However, once you dock, the old name is displayed:
![image](https://user-images.githubusercontent.com/25147462/46580627-af19b400-ca28-11e8-89b4-0da6bab8eee0.png)
![image](https://user-images.githubusercontent.com/25147462/46580630-bccf3980-ca28-11e8-8344-1f3a7a9d969f.png)

Saving the raw JSON also shows the "...ger" name, both in the file name and in the file:
[Summerland.Henry O'Hare's Hanger.2018-10-07T11.34.01.json.txt](https://github.com/Marginal/EDMarketConnector/files/2453794/Summerland.Henry.O.Hare.s.Hanger.2018-10-07T11.34.01.json.txt)

```    "name": "Henry O'Hare's Hanger",
    "outpostType": "starport",
    "prohibited": {
      "128049212": "BasicNarcotics",
      "128049233": "PersonalWeapons",
      "128049234": "BattleWeapons",
      "128049243": "Slaves",
      "128049670": "CombatStabilisers",
      "128672312": "Landmines"
    },
```

Because of this conflict, updating the market data fails with an "Frontier Server is lagging" error after a long delay, while market updates work just fine everywhere else.

Additionally, clicking on the Station name in the EDMC will result in an error 404 from EDDB because the "...ger" variant was deleted there.

I took a look at the source code, and found both names in stations.p.  I don't speak that much Python, but this looks to be some kind of translation table, and it is either not applied correctly or does the translation in the wrong direction.

Since the journal uses the "Hangar" variant and the FD servers do not seem react correctly to the old "Hanger" name, can you turn this translation around?

Credit were it is due: This issue was originally reported by Bolkonski on EDSM's clean-up channel.

**Comment by Nazrex** [comment]
Since the correct spelling is "Hangar" then that is the one that should be used.

A "hanger" is what you use to hang your coat in your closet; so you can't really park a ship "on" a hanger unless you somehow find a way to "hang" your ships in a coat closet.

A "Hangar" however is a covered building used to park airplanes, and in space games it is often considered a garage of sorts where you can park your space ships.

**Comment by Athanasius** [comment]
I'll take a look sometime to see if this still causes the "Frontier Server is lagging" error.  I might be able to switch that to comparing MarketID instead, as that's provided both by the journal and the CAPI `/profile` data.  I'd rather not put in place a specific hack for this.

**Comment by Athanasius** [comment]
Note that the EDDB 404 is now moot, as I've switched the EDDB plugin to use a by-marketid URL form that themroc kindly set up.

We should double-check the other options for the station 'provider' though.

**Comment by Athanasius** [comment]
This is a Frontier bug.  Open an issue with them and get enough reproductions for them to ensure all their output (game client, game Journal **and** CAPI on all endpoints) is returning one consistent name.
