### ISSUE TITLE
No response from program even after reinstall

### ISSUE THREAD

**Issue by switchblade06** [EDCD/EDMarketConnector#368]
Installed EDMC after the first time startup the program was working fine, any time after that it wont display any information. It wont login (yes I started the game and was not in the main menu). I then tried to reinstall EDMC so that i could get the first time setup, however the tool still remembered all the old setting and still would not display any info or let me relogin. I figured the data was maybe in the ED files so I wiped ED completely along with EDMC. after fresh installs of both programs it still will not let me login, and is still remembering old setting.

**Comment by Sven-Dog** [comment]
I've been having the same problem since the Elite Dangerous 3.3 update. EDMC will not accept my Frontier credentials and the fields for EDSM and Inara API's are greyed out.
