### ISSUE TITLE
EDMC displays literal text 'MyReputation' on entering a system

### ISSUE THREAD

**Issue by wegotourselvesareader** [EDCD/EDMarketConnector#375]
The application displays the literal text 'MyReputation' (including the two surrounding apostrophes) at the bottom of the window, below the "Update" button, whenever the player enters a system.

Is this intentional behaviour? Should something else be shown there? Should nothing be shown there?

**Comment by Marginal** [comment]
That's not supposed to happen.
Please compress and post your latest Journal file here.

**Comment by morrisalex** [comment]
[Journal.190101122540.01.log.zip](https://github.com/Marginal/EDMarketConnector/files/2719512/Journal.190101122540.01.log.zip)

Here goes.

**Comment by morrisalex** [comment]
I forgot to mention - the original report above is from version 3.31. I was just now prompted to install 3.32; I'll see if the behaviour still occurs and report back here.

**Comment by morrisalex** [comment]
Tested - still occurs with v3.32.

**Comment by Marginal** [comment]
Thanks. I don't see the problem.
Do you have any plugins installed?
Please compress and attach the file `%TMP%\EDMarketConnector.log`.

**Comment by morrisalex** [comment]
I added no plugins to EDMC (never even occurred to me to try), and the plugins folder is empty:
```
 Directory of C:\Users\Alex\AppData\Local\EDMarketConnector\plugins

28/01/2017  13:47    <DIR>          .
28/01/2017  13:47    <DIR>          ..
               0 File(s)              0 bytes
```
Log file zipped and attached.
[EDMarketConnector.zip](https://github.com/Marginal/EDMarketConnector/files/2721679/EDMarketConnector.zip)

**Comment by morrisalex** [comment]
Fair enough. It's a curious one, alright.

What should EDMC display - if anything - at the bottom of the window on entry to a new system?

Can you suggest any investigation or troubleshooting I could carry out at my end to try to obtain further information?

**Comment by Marginal** [comment]
> What is EDMC supposed to display - if anything - at the bottom of the window on entry to a new system?

"Sending data to EDDN..." (unless you've turned off the relevant option under EDDN settings, in which case nothing).

> Can you suggest any investigation or troubleshooting I could carry out at my end to try to obtain further information?

[Run from source](https://github.com/Marginal/EDMarketConnector/wiki/Running-from-source) if that's not too challenging and see if there's any more detail printed out on the console.

**Comment by morrisalex** [comment]
Python's not my strong suit, but I probably ought to learn a bit more about it.

I'll give it a go and report back here.

**Comment by vanderaj** [comment]
I get this too. The sound is of failure is connect, so is EDMC failing to update an API?

**Comment by vanderaj** [comment]
Looking at the code, this MyReputation is in the Inara.py and EDDN.py, and both are trying to manipulate a dictionary. For EDDN, it is trying to send interesting information including MyReputation when not in a crew (I am not in a crew). Lines 397-430. 

For Inara.py, MC makes the sound and puts up the message when changing the location, which is exactly where the code in lines 368-375 might be called. It adds an event for setCommanderReputationMinorFaction using MyReputation as data. Again, I'm not in a faction, wing, or squadron. I'm often exploring, so I dock once in a blue moon. 

Maybe the data structure f doesn't have a member "MyReputation" when you're not in a faction but the faction data exists?

**Comment by vanderaj** [comment]
![reputation](https://user-images.githubusercontent.com/5029993/50739344-d56bfe80-1193-11e9-8346-c7f407e49207.jpg)

**Comment by vanderaj** [comment]
Let me trigger it again and I'll compress the latest journal. I'm heading out to a Guardian site atm, and it doesn't happen all the time.

**Comment by vanderaj** [comment]
[Journal.190106100522.01.zip](https://github.com/Marginal/EDMarketConnector/files/2730742/Journal.190106100522.01.zip)
[EDMarketConnector.zip](https://github.com/Marginal/EDMarketConnector/files/2730743/EDMarketConnector.zip)

**Comment by vanderaj** [comment]
FWIW, my system has Python installed, but as you compiled it, I don't think that matters. It's also a bit of beast, and I do leave it running. I was able to both not trigger and trigger the exception. I re-logged into an empty system - no message. I jumped into a smallish system - message. I thought, okay, maybe if we went to a big system, it might not trigger, so I jumped to a 20 billion pop system. Triggered.

**Comment by vanderaj** [comment]
I've just updated to 3.3.3.0, I'll see if it's still a bug.

**Comment by vanderaj** [comment]
It's still a problem with 3.3.3.0. Here's the log and my journal. 

E:D Market Connector 3.3.3.0 2019-01-06T10:43:38
loading plugin coriolis from "C:\Program Files (x86)\EDMarketConnector\plugins\coriolis.py"
loading plugin eddb from "C:\Program Files (x86)\EDMarketConnector\plugins\eddb.py"
loading plugin eddn from "C:\Program Files (x86)\EDMarketConnector\plugins\eddn.py"
loading plugin edsm from "C:\Program Files (x86)\EDMarketConnector\plugins\edsm.py"
loading plugin edsy from "C:\Program Files (x86)\EDMarketConnector\plugins\edsy.py"
loading plugin inara from "C:\Program Files (x86)\EDMarketConnector\plugins\inara.py"
loading plugin HabZone from "C:\Users\vande\AppData\Local\EDMarketConnector\plugins\HabZone\load.py"
Auth	Refreshed token for Purrfect
[Journal.190106100522.01.zip](https://github.com/Marginal/EDMarketConnector/files/2730759/Journal.190106100522.01.zip)

**Comment by vanderaj** [comment]
Repro. I took off from SIKSIKAS. I travelled to a no pop empty system. It didn't trigger when I jumped to the empty system. I travelled to Caverda, a 4.5 billion pop system. It definitely triggers just as you jump into a big system, and not when you dock at a station with a full complement of 7 factions.

**Comment by vanderaj** [comment]
p.s. Thanks for all your work on ED Market Connector!
