### ISSUE TITLE
EDMarketConnector hangs at Fetching Data

### ISSUE THREAD

**Issue by CommandoCat** [EDCD/EDMarketConnector#386]
Whenever E:D Market Connector goes into "Fetching data..." status, it hangs and becomes unresponsive in Task Manager. Uninstalling and reinstalling does not solve the problem. Running in compatibility does not solve the problem. Running as administrator does not solve the problem.

**Comment by Amarok73** [comment]
+1

**Comment by Marginal** [comment]
https://github.com/Marginal/EDMarketConnector/wiki/Troubleshooting#reporting-a-problem

**Comment by Amarok73** [comment]
Problem seems to be solved now.

**Comment by Marginal** [comment]
@CommandoCat Please try [Release 3.33](
https://github.com/Marginal/EDMarketConnector/releases/latest).

**Comment by CommandoCat** [comment]
Is mine not 3.33?! 😱😱😱 I thought i downloaded it from here as well when i tried reinstalling it. I will download again and uninstall and reinstall and re-test

**Comment by CommandoCat** [comment]
Hmmmmmmmm. Now it gives me "Error: User not found". But I suspect that the issue is with Frontier side, because when I click update, it opens up the login/authentication page to authorize ed market connector app, i login and press authorize, but nothing happens.

**Comment by Marginal** [comment]
Do any of these apply to you? https://github.com/Marginal/EDMarketConnector/wiki/Troubleshooting#app-repeatedly-opens-the-frontiers-authentication-website

**Comment by CommandoCat** [comment]
Ahhhh. That did it. Thanks @Marginal. Buggy frontier.
