### ISSUE TITLE
Hab Zone Plugin Text Distance

### ISSUE THREAD

**Issue by Pipedream420** [EDCD/EDMarketConnector#388]
I used the Hab Zone plugin for EDMC and not long ago the distances used to be right next to each other, but now, since an unknown update, the text for distances gets separated when I try to resize the window. The only way to bring the distances text close to each other anymore is to make the window very thin but then once I jump to a system with a long name, it automatically resizes the window to be wider which then makes the hab zone text far apart again.
Any fix for this would be greatly appreciated.

**Comment by Athanasius** [comment]
Did you ever report this to the developers of the HabZone plugin?

**Comment by Athanasius** [comment]
Note that whilst 'HabZone' was made by Marginal, the original developer of EDMC itself, he's not currently involved, nor has anyone else taken over maintenance of the 'HabZone' plugin.

Looking at the HabZone code there was no change even vaguely around the time of your report.  Previous commit `Nov 16, 2017` and the next was the Python 3 work `Oct 2, 2019` so presumably it's some change in EDMC around your report date.

**Comment by Athanasius** [comment]
HabZone was written by Marginal, he's gone from the game.  The plugin is now moot because you'd need to have scanned planets to know their distance from arrival in order for it to work.  No-one has reported similar with other plugins.  Closing.
