### ISSUE TITLE
Frontier Authentication successful the first time, then fails afterwards

### ISSUE THREAD

**Issue by Azzurite** [EDCD/EDMarketConnector#408]
[EDMarketConnector.log](https://github.com/Marginal/EDMarketConnector/files/2923228/EDMarketConnector.log)

So when I start EDMC, it opens the Frontier Auth. It successfully logs me in and EDMC says "Authentication Successful".

However, when I press on the "Update" button afterwards (or after some time when I'm in game) it tells me "Error: Invalid Credentials" and then redirects me to the Frontier Auth site again. If I log in again, EDMC tells me "Authentication Successful" again.

Rinse repeat. 

I tried reinstalling the app and deauthorizing EDMC in the Frontier Auth settings, both without success.

**Comment by cmdr-j0linar** [comment]
Exactly the same problem. Feels like I've tried everything to fix this.
Anyone got an idea?

**Comment by Marginal** [comment]
Please attach the log file `%TMP%\EDMarketConnector.log` after experiencing this problem.

**Comment by cmdr-j0linar** [comment]
[EDMarketConnector.log](https://github.com/Marginal/EDMarketConnector/files/3139054/EDMarketConnector.log)
Here ya go mate, thanks for the quick response

**Comment by nairraf** [comment]
[EDMarketConnector.log](https://github.com/Marginal/EDMarketConnector/files/3160447/EDMarketConnector.log)

I have the same issue as well. tried edge and chrome as default browsers just to see if it was a browser issue, but I have the same results in each browser.

**Comment by almandinemerlot** [comment]
Exact same issue. Tried all 3 updated browsers and it still asks for manual auth everytime I dock, change ships etc
[EDMarketConnector.log](https://github.com/Marginal/EDMarketConnector/files/3288061/EDMarketConnector.log)

**Comment by Athanasius** [comment]
Is this still happening with release 3.44 or later ?

**Comment by Azzurite** [comment]
@Athanasius if I run E:D again, I'll try it, but could be some time. Is it supposed to be fixed?

**Comment by Athanasius** [comment]
There were some code changes since the initial report, and it's now over a year since any report or confirmation.

So, I'm going to close this.  Anyone seeing it anew please open a new ticket.
