### ISSUE TITLE
Credentials don't seem to be saved

### ISSUE THREAD

**Issue by arancaytar** [EDCD/EDMarketConnector#432]
After starting the client and authenticating in the browser, the client shows "Authentication successful". However, anything that requires an API call ("Status", "Save Data", and "Update") will cause the client to show "Invalid Credentials" and open a new login page in the browser.

This happens regardless whether the game is currently running.

**Comment by arancaytar** [comment]
The relevant log section is quoted below:

```
Auth	Invalidated token for aran ilyaris
Auth	Can't refresh token for aran ilyaris
Auth	https://auth.frontierstore.net/token 500 Internal Server Error {"message":"An error occured.","logref":"5aa571cf69fa9f6efb02f9a6c684590a"}
Auth	New authorization request
Auth	New token for aran ilyaris
Traceback (most recent call last):
  File "companion.pyo", line 373, in query
  File "requests\models.pyo", line 935, in raise_for_status
HTTPError: 404 Client Error: Not Found for url: https://companion.orerve.net/
cAPI	https://companion.orerve.net/ 404 Not Found <!DOCTYPE html>
<html>
<head>
        <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="noindex, nofollow">
    
        
        <link rel="icon" href="https://companion.orerve.net:443/favicon.ico" type="image/x-icon">
    </head>
<body class="">
            <h1>404</h1>
<p>Page not found.</p>
    
    
        </body>

</html>

Traceback (most recent call last):
  File "companion.pyo", line 373, in query
  File "requests\models.pyo", line 935, in raise_for_status
HTTPError: 404 Client Error: Not Found for url: https://companion.orerve.net/
cAPI	https://companion.orerve.net/ 404 Not Found <!DOCTYPE html>
<html>
<head>
        <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="noindex, nofollow">
    
        
        <link rel="icon" href="https://companion.orerve.net:443/favicon.ico" type="image/x-icon">
    </head>
<body class="">
            <h1>404</h1>
<p>Page not found.</p>
    
    
        </body>

</html>

Auth	Invalidated token for aran ilyaris
Auth	Can't refresh token for aran ilyaris
Auth	https://auth.frontierstore.net/token 500 Internal Server Error {"message":"An error occured.","logref":"8eaae9af66e15104da91a64f8d42eb3b"}
Auth	New authorization request
Auth	New token for aran ilyaris
```

I'm not sure if the failed call to companion.orerve.net is related or just coincidental though.

**Comment by ilift13** [comment]
I had the same issue

**Comment by JTwinleaf** [comment]
Same issue here

**Comment by Psilovybin** [comment]
Same here, i'm running in linux, ED is running on Steam in linux with proton:

`Auth    New token for Psilovybin
Traceback (most recent call last):
  File "/home/doc/ed/EDMarketConnector/companion.py", line 371, in query
    r.raise_for_status()        # Typically 403 "Forbidden" on token expiry
  File "/usr/lib64/python2.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found for url: https://companion.orerve.net/
cAPI    https://companion.orerve.net/ 404 Not Found <!DOCTYPE html>
<html>
<head>
        <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="noindex, nofollow">
    
        
        <link rel="icon" href="https://companion.orerve.net:443/favicon.ico" type="image/x-icon">
    </head>
<body class="">
            <h1>404</h1>
<p>Page not found.</p>
    
    
        </body>

</html>

Traceback (most recent call last):
  File "/home/doc/ed/EDMarketConnector/companion.py", line 371, in query
    r.raise_for_status()        # Typically 403 "Forbidden" on token expiry
  File "/usr/lib64/python2.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found for url: https://companion.orerve.net/
cAPI    https://companion.orerve.net/ 404 Not Found <!DOCTYPE html>
<html>
<head>
        <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="noindex, nofollow">
    
        
        <link rel="icon" href="https://companion.orerve.net:443/favicon.ico" type="image/x-icon">
    </head>
<body class="">
            <h1>404</h1>
<p>Page not found.</p>
    
    
        </body>

</html>

Auth    Invalidated token for Psilovybin
Auth    No token for Psilovybin
Auth    New authorization request
Traceback (most recent call last):
  File "/home/doc/ed/EDMarketConnector/stats.py", line 192, in showstats
    data = companion.session.profile()
  File "/home/doc/ed/EDMarketConnector/companion.py", line 395, in profile
    return self.query(URL_QUERY)
  File "/home/doc/ed/EDMarketConnector/companion.py", line 384, in query
    return self.query(endpoint)
  File "/home/doc/ed/EDMarketConnector/companion.py", line 381, in query
    raise CredentialsError()
CredentialsError: Error: Invalid Credentials
Traceback (most recent call last):
  File "EDMarketConnector.py", line 678, in save_raw
    data = companion.session.station()
  File "/home/doc/ed/EDMarketConnector/companion.py", line 398, in station
    data = self.query(URL_QUERY)
  File "/home/doc/ed/EDMarketConnector/companion.py", line 350, in query
    raise CredentialsError()
CredentialsError: Error: Invalid Credentials`

**Comment by aserowy** [comment]
Im having the same issue on Windows (with a steam version of the game, but using the frontier credentials :)).

**Comment by Saxtus** [comment]
Same as @aserowy here. Except that I tried with Steam login too, but the result was the same: Authentication successful until the next update.

**Comment by babbycp** [comment]
I also use Steam and if I click the update button i have to login via website then it work but if I click the button it says Error: Invalid Credentials again.

**Comment by ItBeNiro** [comment]
I am having the same issue, on the Steam version of the game. Running as administrator does not help. I've authenticated in Firefox And Chrome, neither helped. Application says "Authentication Successful" until the next update of any sort.

Attached is the entirety of the EDMC log file.

[EDMarketConnector.log](https://github.com/Marginal/EDMarketConnector/files/3688620/EDMarketConnector.log)

**Comment by Athanasius** [comment]
Whilst there does seem to be an EDMC bug there with how it's (not) reporting the issue, this is fundamentally Frontier's Authorization Server saying "no":

`https://github.com/Marginal/EDMarketConnector/issues/432#issuecomment-538192011`

I'd advise searching the Frontier Issues for any other reports, and then either adding your confirmation to it, or if not found open a new issue: https://issues.frontierstore.net/

**Comment by GiacomoLaw** [comment]
Having this issue, it is on every game launch - on the launcher, and when I launch the main game.

Thanks!

**Comment by Athanasius** [comment]
Is this still happening with 3.44 ?

**Comment by arancaytar** [comment]
I recently had to set it up on a new machine and it didn't happen, so I
guess not.
