### ISSUE TITLE
Monitoring of Modulesinfo.json

### ISSUE THREAD

**Issue by lekeno** [EDCD/EDMarketConnector#433]
Would it be possible to emit an event for when the modulesinfo.json file is updated?
See section 11.28 of the player journal v23 documentation.

Thanks!

**Comment by Athanasius** [comment]
Is the `ModuleInfo` Journal event not coming through to plugins ?   That would signal that a plugin could then open the `ModulesInfo.json` file itself to read and use the contents.

**Comment by lekeno** [comment]
I ended up doing it myself, in response to a modulesinfo event in the journal.
I was thinking that EDMC might want to provide a callback for it so that plugins don't have to all open the file, etc.

**Comment by Athanasius** [comment]
I'm finally getting around to this with https://github.com/EDCD/EDMarketConnector/pull/898 which will get completed and merged once https://github.com/EDCD/EDMarketConnector/pull/897 is merged.

**Comment by Athanasius** [comment]
#897 was merged, code in 5.0.0-beta5
