### ISSUE TITLE
Have to remove authorization every month.

### ISSUE THREAD

**Issue by Noodles4Pasta** [EDCD/EDMarketConnector#436]
Every month I am having to go into the Frontier auth system and remove permission for EDMC so it can re-authenticate. I have to do this for ALL of my accounts. This may be related to issues [#419](https://github.com/Marginal/EDMarketConnector/issues/419) [#427](https://github.com/Marginal/EDMarketConnector/issues/427) and/or [#432](https://github.com/Marginal/EDMarketConnector/issues/432)

This has been going on since i started playing in december of last year, and one of the updates seemed to have fixed it for a while... not sure which one. But for the last 3 or 4 months I've had to re-auth the app.

now for the mandatory _"this is broke... gib fix nao..."_ LOL.
Seriously tho, thanks for your work on this!

**Comment by Noodles4Pasta** [comment]
Last couple weeks i have ahd to reauth, and to day it got worse, i tried to reauth but it wont log in.

**Comment by Athanasius** [comment]
Is this still happening ?

**Comment by Athanasius** [comment]
To be clear, is it still happening with release 3.44 or later ?

**Comment by Athanasius** [comment]
- [ ] Document that if you don't use EDMC/CAPI often enough then you'll need to re-authorize.
