### ISSUE TITLE
Always have to authenticate when starting EDMC via Script

### ISSUE THREAD

**Issue by NeoNavras** [EDCD/EDMarketConnector#442]
I use a Script (found [here](https://forums.frontier.co.uk/threads/ed-runner-a-help-program-for-vr-headsets-with-joysticks-hotas-part-2.440760/)) to automatically start EDMC when Elite is launched. But when EDMC is launched via this script/program the frontier authentication page always opens and I have to login, once I'm sitting in the ship at the latest. Starting EDMC manually via a Shortcut in my Windows start menu, this issue doesn't happen. It immediately says "authentication successful" in the lower info bar of EDMC. Why is there a difference? Could I fix it with launch parameters or does this need a EDMC fix?

**Comment by Athanasius** [comment]
EDMC looks in the Registry for its settings, including the saved Frontier authentication token.  The only way I can think of for it to not find that is if the script is running EDMC as a different user.

I might have a play with that script if I find the time.

**Comment by YanSeyffert** [comment]
The behaviour I descripted last August doesn't seem to happen to me anymore. From time to time I might need to re-authenticate, but mostly everything is working seemless now. Also when jumping between main and secondary CMDR accounts.

**Comment by NeoNavras** [comment]
The behaviour I descripted last August doesn't seem to happen to me anymore. From time to time I might need to re-authenticate, but mostly everything is working seemless now. Also when jumping between main and secondary CMDR accounts. Not sure when it changed for me, since I took a long-ish break from the game.

**Comment by Athanasius** [comment]
Regarding the Cmdr switching, I've opened #564 to investigate.  If it's "meant" to be happening I'll change that to an Enhancement, else I'll look into fixing the bug.

**Comment by NeoNavras** [comment]
I'm not sure what you mean. I meant, I have authenticated my main and secondary CMDR account each for EDMC. And this seems to have been remembered so far (the last couple weeks, since I started be more active again). So when I start either my main or secondary account I am not asked to re-authenticte, but EDMC says authentication successfull, as I would expect.

**Comment by Athanasius** [comment]
Ah I read it as "From time to time I might need to re-authenticate ... Also when jumping between main and secondary CMDR accounts".  Rather than "mostly everything is working seemless now. Also when jumping between main and secondary CMDR accounts".

Good to know, and I'll close the other ticket.

**Comment by NeoNavras** [comment]
Ah I see, sorry for ambiguity.
