### ISSUE TITLE
Suggestion: Add an option to send the data when undocking

### ISSUE THREAD

**Issue by Belshazu** [EDCD/EDMarketConnector#462]
Typical scenario: you dock, EDMC updates the data, you buy some stuff and leave. The problem is that EDDB now has already outdated data. Poor kids will fly over 70 ly on their clumsy Type-7 Transporter to pick up some juicy Synthetic Reagents just to find out that there is none left. Could be fixed by adding an option to send the data when undocking.

**Comment by Athanasius** [comment]
(I suggested they post this as an issue.)

This would entail using the CAPI to get the data (as EDMC does on dock).  And given the cool-down on that would mean needing to *not* get the data when docking in case the Cmdr is very quick in buying and un-docking again.  Although the 60s cool-down is self-imposed by EDMC it's there for a reason.

I assume the Market.json, written when opening the Commodites screen in-game, has a latch on it, or could we trigger off the Cmdr buying, closing, re-opening Commodites, and doing a diff to see if the data is now different before sending over EDDN ?

**Comment by Athanasius** [comment]
Will address in #493 (if it's even possible).
