### ISSUE TITLE
Main window disapear

### ISSUE THREAD

**Issue by Arkhchance** [EDCD/EDMarketConnector#463]
Hi, 
In version 3.5 beta  If I interact with the main window, it disappear 
works well with current stable 
(I'm on Archlinux)

**Comment by Athanasius** [comment]
Are you running from source, or via WINE or the like ?  Any traceback ?  If you're running from source are you doing so directly in a terminal window so you can see the traceback ?

**Comment by Arkhchance** [comment]
I'm runing from source, in a terminal window. No traceback as EDMC doesn't crash, the main window just disapear ( like  mainWindow.hide() ) but EDMC still runs fine

**Comment by Athanasius** [comment]
Does this always happen, i.e. the moment you interact with the main window?  If not can you narrow it down to a set of actions that causes it ?

What theme are you using?

A cursory check on Debian 10/buster with Python 3.7.3 shows no issues.  Once I'd pointed it at my journals on the Windows partition it's let me hit 'Update' without issues.  I'm using the Dark theme.

**Comment by Athanasius** [comment]
Also appears to work 100% with the default theme.  I can only think this is some different in the Tcl/Tk library versions and/or python version.

**Comment by Athanasius** [comment]
Also, do you have any additional plugins loading ?  They'd be in ~/.local/share/EDMarketConnector/plugins/ - and not with a .disabled extension - if you did.

**Comment by Athanasius** [comment]
The sum total of loaded dynamic libraries, from `lsof -nPp <pid> | egrep '\.so' | awk '{print $9;}' | sort`

/lib/x86_64-linux-gnu/ld-2.28.so
/lib/x86_64-linux-gnu/libblkid.so.1.1.0
/lib/x86_64-linux-gnu/libbz2.so.1.0.4
/lib/x86_64-linux-gnu/libc-2.28.so
/lib/x86_64-linux-gnu/libcrypt-2.28.so
/lib/x86_64-linux-gnu/libdbus-1.so.3.19.11
/lib/x86_64-linux-gnu/libdl-2.28.so
/lib/x86_64-linux-gnu/libexpat.so.1.6.8
/lib/x86_64-linux-gnu/libgcc_s.so.1
/lib/x86_64-linux-gnu/libgcrypt.so.20.2.4
/lib/x86_64-linux-gnu/libgpg-error.so.0.26.1
/lib/x86_64-linux-gnu/liblzma.so.5.2.4
/lib/x86_64-linux-gnu/libm-2.28.so
/lib/x86_64-linux-gnu/libmount.so.1.1.0
/lib/x86_64-linux-gnu/libnsl-2.28.so
/lib/x86_64-linux-gnu/libnss_compat-2.28.so
/lib/x86_64-linux-gnu/libnss_dns-2.28.so
/lib/x86_64-linux-gnu/libnss_files-2.28.so
/lib/x86_64-linux-gnu/libnss_mdns4_minimal.so.2
/lib/x86_64-linux-gnu/libnss_nis-2.28.so
/lib/x86_64-linux-gnu/libpcre.so.3.13.3
/lib/x86_64-linux-gnu/libpthread-2.28.so
/lib/x86_64-linux-gnu/libresolv-2.28.so
/lib/x86_64-linux-gnu/librt-2.28.so
/lib/x86_64-linux-gnu/libselinux.so.1
/lib/x86_64-linux-gnu/libsystemd.so.0.25.0
/lib/x86_64-linux-gnu/libutil-2.28.so
/lib/x86_64-linux-gnu/libuuid.so.1.3.0
/lib/x86_64-linux-gnu/libz.so.1.2.11
/usr/lib/libBLT.2.5.so.8.6
/usr/lib/python3.7/lib-dynload/_bz2.cpython-37m-x86_64-linux-gnu.so
/usr/lib/python3.7/lib-dynload/_csv.cpython-37m-x86_64-linux-gnu.so
/usr/lib/python3.7/lib-dynload/_ctypes.cpython-37m-x86_64-linux-gnu.so
/usr/lib/python3.7/lib-dynload/_hashlib.cpython-37m-x86_64-linux-gnu.so
/usr/lib/python3.7/lib-dynload/_json.cpython-37m-x86_64-linux-gnu.so
/usr/lib/python3.7/lib-dynload/_lzma.cpython-37m-x86_64-linux-gnu.so
/usr/lib/python3.7/lib-dynload/_opcode.cpython-37m-x86_64-linux-gnu.so
/usr/lib/python3.7/lib-dynload/_queue.cpython-37m-x86_64-linux-gnu.so
/usr/lib/python3.7/lib-dynload/_ssl.cpython-37m-x86_64-linux-gnu.so
/usr/lib/python3.7/lib-dynload/_tkinter.cpython-37m-x86_64-linux-gnu.so
/usr/lib/python3.7/lib-dynload/_uuid.cpython-37m-x86_64-linux-gnu.so
/usr/lib/python3.7/lib-dynload/termios.cpython-37m-x86_64-linux-gnu.so
/usr/lib/python3/dist-packages/Crypto/Cipher/_AES.cpython-37m-x86_64-linux-gnu.so
/usr/lib/python3/dist-packages/Crypto/PublicKey/_fastmath.cpython-37m-x86_64-linux-gnu.so
/usr/lib/python3/dist-packages/Crypto/Util/_counter.cpython-37m-x86_64-linux-gnu.so
/usr/lib/python3/dist-packages/Crypto/Util/strxor.cpython-37m-x86_64-linux-gnu.so
/usr/lib/python3/dist-packages/_dbus_bindings.cpython-37m-x86_64-linux-gnu.so
/usr/lib/python3/dist-packages/_dbus_glib_bindings.cpython-37m-x86_64-linux-gnu.so
/usr/lib/python3/dist-packages/cairo/_cairo.cpython-37m-x86_64-linux-gnu.so
/usr/lib/python3/dist-packages/gi/_gi.cpython-37m-x86_64-linux-gnu.so
/usr/lib/python3/dist-packages/gi/_gi_cairo.cpython-37m-x86_64-linux-gnu.so
/usr/lib/x86_64-linux-gnu/libX11.so.6.3.0
/usr/lib/x86_64-linux-gnu/libXau.so.6.0.0
/usr/lib/x86_64-linux-gnu/libXcursor.so.1.0.2
/usr/lib/x86_64-linux-gnu/libXdmcp.so.6.0.0
/usr/lib/x86_64-linux-gnu/libXext.so.6.4.0
/usr/lib/x86_64-linux-gnu/libXfixes.so.3.1.0
/usr/lib/x86_64-linux-gnu/libXft.so.2.3.2
/usr/lib/x86_64-linux-gnu/libXrender.so.1.3.0
/usr/lib/x86_64-linux-gnu/libXss.so.1.0.0
/usr/lib/x86_64-linux-gnu/libbsd.so.0.9.1
/usr/lib/x86_64-linux-gnu/libcairo-gobject.so.2.11600.0
/usr/lib/x86_64-linux-gnu/libcairo.so.2.11600.0
/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
/usr/lib/x86_64-linux-gnu/libffi.so.6.0.4
/usr/lib/x86_64-linux-gnu/libfontconfig.so.1.12.0
/usr/lib/x86_64-linux-gnu/libfreetype.so.6.16.1
/usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.5800.3
/usr/lib/x86_64-linux-gnu/libgirepository-1.0.so.1.0.0
/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.5800.3
/usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0.5800.3
/usr/lib/x86_64-linux-gnu/libgmp.so.10.3.2
/usr/lib/x86_64-linux-gnu/libgnome-keyring.so.0.2.0
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.5800.3
/usr/lib/x86_64-linux-gnu/liblz4.so.1.8.3
/usr/lib/x86_64-linux-gnu/libpixman-1.so.0.36.0
/usr/lib/x86_64-linux-gnu/libpng16.so.16.36.0
/usr/lib/x86_64-linux-gnu/libssl.so.1.1
/usr/lib/x86_64-linux-gnu/libtcl8.6.so
/usr/lib/x86_64-linux-gnu/libtk8.6.so
/usr/lib/x86_64-linux-gnu/libxcb-render.so.0.0.0
/usr/lib/x86_64-linux-gnu/libxcb-shm.so.0.0.0
/usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0

**Comment by Arkhchance** [comment]
Yes it happen 100% of the time. I just found that it is dark theme specific. if I switch to the light theme, it works perfectly fine

**Comment by Marginal** [comment]
The master branch has a [fix](https://github.com/Marginal/EDMarketConnector/commit/8c2775f6d8ea2966aa829e08d8bbe65cda712c5b) for dark theme on Linux that hasn't yet been merged into the 3.5 beta. Does latest master work for you?

**Comment by Arkhchance** [comment]
Sorry about this extremely late answer, 
Yes master branch works perfectly fine (both theme)

**Comment by Athanasius** [comment]
Fixed by 8c2775f6d8ea2966aa829e08d8bbe65cda712c5b then.
