### ISSUE TITLE
Attempting to override EDMC window with External Manifest Fails

### ISSUE THREAD

**Issue by Elite-IGAU** [EDCD/EDMarketConnector#465]
EDMC draws a very small box, which causes readability issues on high resolution displays. 

Attempting to override this causes the app to not start. 

Steps to reproduce:

Open the Windows registry and navigate to the following location;
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\SideBySide
Create a new DWORD value and name it ‘PreferExternalManifest’. Double click it and set its value to 1.

Navigate to EDMC install location. 

Paste this code into a file called EDMarketConnector.exe.manifest:

[manifest.txt](https://github.com/Marginal/EDMarketConnector/files/3812255/manifest.txt)

Suggested fix: Add the following: EDMC -> Settings -> [Appearance]
Application Window size: (1x) (2x) ( I don't think 4x is necessary )

**Comment by Athanasius** [comment]
Will address for #515
