### ISSUE TITLE
cAPI 401 Errors

### ISSUE THREAD

**Issue by Elite-IGAU** [EDCD/EDMarketConnector#466]
Noticed a few cAPI 401 error lines in the edmc log file:

HTTPError: 401 Client Error: Unauthorized for url: https://companion.orerve.net/profile
cAPI    https://companion.orerve.net/profile 401 Unauthorized {"status":401,"message":"JWT has incorrect\/unexpected fields"}

**Comment by Athanasius** [comment]
That's just a Frontier error.  It might indicate the current Access Token has simply expired (in which case EDMC will utilise the Refresh Token to get a new one), or that the Frontier CAPI servers had a brainfart.

**Comment by Athanasius** [comment]
Closing.  Open new ticket if it occurs again with 3.44 or later version.
