### ISSUE TITLE
Update Documentation to clarify "update" button on bottom of UI?

### ISSUE THREAD

**Issue by Elite-IGAU** [EDCD/EDMarketConnector#468]
Hey there, 

Would it be possible to update the documentation on the main page to clarify the purpose of the "update" button on the bottom of the UI?

Our squadron has several members new to EDMC, and it seems quite a few people think that button must be clicked often.

**Comment by Athanasius** [comment]
How's it look now? https://github.com/EDCD/EDMarketConnector/wiki
