### ISSUE TITLE
Add plugin to list on wiki

### ISSUE THREAD

**Issue by Elite-IGAU** [EDCD/EDMarketConnector#469]
Hello!

Could you please add this plugin to your list at: https://github.com/Marginal/EDMarketConnector/wiki/Plugins

https://github.com/Elite-IGAU/ATEL-EDMC/releases

Description for the wiki entry:
"EDMC plugin which automatically collects "Codex" discovery data, and (optionally) posts public Astronomical Discovery "Telegram" style notices"

Thanks!

**Comment by Athanasius** [comment]
Done
