### ISSUE TITLE
EDMC 3.5.0.0 b1 breaks EDMC-HourlyIncome and HabZone plugins

### ISSUE THREAD

**Issue by kyanha** [EDCD/EDMarketConnector#474]
As it says in the subject, the update to EDMC 3.5b1 breaks some of the plugins linked in the wiki. 

Any idea what changes caused the breakage?

(I found this when trying to work through SayakMukhopadhyay/EDMC-Discord-Presence#14, which also mentions that the 'Tkinter' import got renamed to 'tkinter' in EDMC 3.5.0.0.)

**Comment by Athanasius** [comment]
Presumably those plugins have not been updated to work with python 3.x, which is the whole point of the EMDC 3.5 release.  Contact the authors of those plugins to have them update for the change.  It should be possible for them to adjust their code such that they work in both Python 2.7 and 3.x.

**Comment by Poneyy** [comment]
I have updated EDMC Rich Discord presence (released) and HourlyIncome(Pull requested).
habZone too, but I don't have time to test all the features of this plugin, it loads without error. I can request a pull request for it, and you can confirm if it works or not :).

**Comment by Athanasius** [comment]
Closed as this is about third-party plugins.  Point their developers towards https://github.com/EDCD/EDMarketConnector/blob/master/PLUGINS.md#migration-to-python-37 if they've still not updated their code.

The clock is very much ticking on them migrating their code.
