### ISSUE TITLE
Transparent theme for linux

### ISSUE THREAD

**Issue by Widowan** [EDCD/EDMarketConnector#476]
Any plans for adding it? AFAIK in Tk it's windows-only feature, but I'm pretty sure it's possible to imitate it on other platforms.

**Comment by A-UNDERSCORE-D** [comment]
https://github.com/EDCD/EDMarketConnector/pull/770 Implements this.

**Comment by A-UNDERSCORE-D** [comment]
#770 has been implemented in develop. Would you like to try it and report back, @Widowan ?

**Comment by Widowan** [comment]
![image](https://user-images.githubusercontent.com/34800021/104117753-c3019e00-5334-11eb-9583-ec4a1ffa8697.png)
I'm not sure that's how it's supposed to work...
I tried multiple DEs and WMs, didn't help

**Comment by A-UNDERSCORE-D** [comment]
Thats... Weird. This on Wayland?

**Comment by A-UNDERSCORE-D** [comment]
![Screenshot from 2021-01-10 23-10-32](https://user-images.githubusercontent.com/21071450/104135423-10aff200-5399-11eb-9b37-6bed738119c7.png)

For reference this is what it should look like.

**Comment by Widowan** [comment]
Aww, sad. Well, in that case I guess it is working as expected. Thank you!

**Comment by A-UNDERSCORE-D** [comment]
Yeah sorry it was the best I could come up with. The mechanism windows uses straight up isn't supported, and after a few days of looking for workarounds and other solutions, I gave up and did what we have. It's.... Alright when used to overlay the game
