### ISSUE TITLE
Enhancement Request: Calculate raw market values for bulk-rated products

### ISSUE THREAD

**Issue by Charixfox** [EDCD/EDMarketConnector#482]
The recent game update applies demand-based bulk discounts to the sales of certain things, especially minerals. This causes the prices reported to (and by) the market connector to be based on the amount of cargo in the ship's hold as opposed to accurate market pricing.

I would like to see the market connector make use of Cargo.json in the journal directory, combined with the Demand number from the station, to calculate the base price of demand-based commodities.

Assumed logic for this (subject to validation and further verification, and I'm willing to do legwork):
Discount amount is ship cargo divided by demand, with a deadzone (drop to 0%) at < 4.5% and a ceiling of 50%.
Demand viewed by a given ship is only accurate when pulling up the market for the first time after docking. 
The discount amount is removed from the base sell price to create the offered sell price that ship sees.

This means that, for example, a commodity with a base price of 1000 and a demand of 1000 will show a price of 936 to a ship with 64 in the hold, but a price of 500 to a ship with 512 in the hold. If a player with 512 of that item gets data at the station with EDMC running, it deflates the reported price of the item.

**Comment by Athanasius** [comment]
This should be coded up as a third-party plugin.

I'll leave this open for now in case extra EDMC plugin functionality is necessary to allow for that.
