### ISSUE TITLE
NO BUG | plugin writing, get Entry Value

### ISSUE THREAD

**Issue by Asrothear** [EDCD/EDMarketConnector#483]
I´m trying to write a small plugin and wanted a text input on the config tab where the user can change an url but i dont get it how to make this work
i tried some variation i know from other languaged but nothing worked so far with :
!!!  ................/ used as code placeholder !!!

```
def plugin_prefs(parent, cmdr, is_beta):
.........../
this.new_url = nb.Entry(frame).grid()
........../

def prefs_changed(cmdr, is_beta):
........./
   print(this.new_url)
```
i got the output : NoneType

So what i´m mssing and what am I doing wrong ?
Again the target is a Text-Input field in the plugin setting tab

**Comment by bgol** [comment]
> this.new_url = nb.Entry(frame).grid()

This will set `this.new_url` to the value of the grid() return not the entry object. You need to make this in two steps:
```python

this.new_url = nb.Entry(frame)
this.new_url.grid()
```

>    print(this.new_url)

After the changes outlined above you'll need to use the get() function to retrieve the value:
```python

    print(this.new_url.get())
```

**Comment by Athanasius** [comment]
Issues aren't meant to be coding tutorials.
