### ISSUE TITLE
Jump Data seems to be different.

### ISSUE THREAD

**Issue by z-vap** [EDCD/EDMarketConnector#484]
In game when I go to Outfitting, the lower bottom section of the screen shows my Jump CUR as 18.12, but when I click my on my ship in ED MarketConnector, EDSY shows NAV JMP CUR as 19.37.

Is this a bug or due to an in game update?

**Comment by Athanasius** [comment]
This is the wrong place to ask about EDSY issues.  Try the #edsy channel on the EDCD Discord: https://discord.gg/0uwCh6R62aQ0eeAX

**Comment by z-vap** [comment]
Thanks, but honestly there's no way for me to know if the problem is with your connector, Frontier, or with edsy.   I will ping them in their discord server,

**Comment by Athanasius** [comment]
Closing due to being an EDSY issue.
