### ISSUE TITLE
Some tiny UI enhancements ? 

### ISSUE THREAD

**Issue by SweetyVolty** [EDCD/EDMarketConnector#485]
I know it's minimal enough but wouldn't be wonderful if we have option to these tiny but sweet features added to EDMC;

- Run on startup
- Hide when minimized
- Minimize on start

Anyway we have a keybind for popping it out any time ^^

**Comment by Athanasius** [comment]
Note that "Minimize to system tray option " is already requested in #126

**Comment by Athanasius** [comment]
"Minimize to systray" has been available for a while now, which includes "Hide when minimized".

For "Run on startup", just make a shortcut and place it in your Windows Start-up folder.
