### ISSUE TITLE
Can't connect to inara

### ISSUE THREAD

**Issue by UselessGH** [EDCD/EDMarketConnector#487]
Been getting this error since installing EDMC, it has no trouble authenticating and is working with EDDN, API key is correct and so far I've been unable to find any way to fix this connection issue.

**Comment by DuncanIdahoCT** [comment]
I'm having this issue too but I wonder if it's due to some recent maintenance on Inara.

**Comment by DuncanIdahoCT** [comment]
I was able to clear up this issue for myself by pulling the latest inara.py file and overwriting the local Program Files plugin folder version.

**Comment by Athanasius** [comment]
Yeah, we really need a new release of EDMC with https://github.com/Marginal/EDMarketConnector/pull/479 incorporated.

@Marginal - you able to get this done for both 3.4 and 3.5 ?

**Comment by Athanasius** [comment]
Will be fixed when 3.44 is releases, see #479
