### ISSUE TITLE
Friends EDMC has my username in it

### ISSUE THREAD

**Issue by UselessGH** [EDCD/EDMarketConnector#488]
Where it shows the commander name it shows [His Username/[My Username]
Is this normal and is it something to be concerned about

**Comment by pwerken** [comment]
I'm guessing you two were playing in your private group?
EDMC displays the private group you're in behind the cmdr name.
I also just recently found this out while participating in Drew Wagar's lore tour. :)

**Comment by QuakeMcGoon** [comment]
Wow.  So glad I signed up for this place.  This has been driving me nuts for years.  
Sorted.  Thank-you VERY much.

**Comment by Athanasius** [comment]
Confusing, but not a bug.
