### ISSUE TITLE
Alt account getting sent to INARA

### ISSUE THREAD

**Issue by BeckyYork** [EDCD/EDMarketConnector#489]
I recently also logged in to my inara account to find my ranks messed up and a whole bunch of ships added to my ship yard... I didn't know what was going on at first but I realised that it's sent my "Space Elf" alt account details to overwrite my primary inara account.

{ "timestamp":"2020-04-24T16:58:50Z", "event":"Commander", "FID":"xxxxx", "Name":"Space Elf" }
{ "timestamp":"2020-04-24T17:14:55Z", "event":"Commander", "FID":"xxxxx", "Name":"Inyahin" }

The commander name is in the top of the journal.
Please only send the correct journal details to Inara.

**Comment by BeckyYork** [comment]
![image](https://user-images.githubusercontent.com/25744286/80239867-d959b380-8658-11ea-96af-3d08f688ad98.png)

**Comment by bgol** [comment]
This should not happen. EDMC uses different settings for different commanders.
Check your Settings->Inara while you're logged into the game for each commander separately.

**Comment by Athanasius** [comment]
Indeed EDMC stores things like the Inara APIKey per-Commander.  It won't even let you set an Inara (or EDSM) API Key until it has determined, from Journal events on logging in to the game, which Commander it is for.

If you're sure you have the correct Inara API Key show in the EDMC settings as you're just logged in (all the way, not just at the Main Menu) to each, then I'll need to see your Registry settings for EDMC to diagnose any further.  Do **NOT** just post them here as that will contain your API keys, not to mention Frontier account oAuth2 token as well.
