### ISSUE TITLE
Application appears locked down

### ISSUE THREAD

**Issue by Therapho** [EDCD/EDMarketConnector#490]
I installed this yesterday and it was functioning well.  Today, the status screen has no data, and the settings for Inara, etc are blank and the fields are locked.  I have tried reinstalling, same issue.

**Comment by n1ghtsn1p3r** [comment]
Same issue on Windows and Linux (steam play). both the 3.43 and 3.50 beta. Fresh OS installs on both.

Reauthenticating to the Frontier servers fixed it for me.

**Comment by Athanasius** [comment]
Were you running the game client when you checked?  EDMC needs some information from the 'login' events to be sure of the correct commander, and thus the correct account details for other sites.

**Comment by Athanasius** [comment]
And note that moving/deleting your Journal files will cause EDMC to be unable to determine your game Commander name, and thus it can't allow editing any settings for EDSM or Inara as those are per-Commander.

At some point I'll be checking and documenting the "New User Experience" which might shed some light on why you were experiencing this.  Or I might also have made code changes to make it all more obvious.
