### ISSUE TITLE
Crash when choosing log folder

### ISSUE THREAD

**Issue by Ivoz** [EDCD/EDMarketConnector#492]
After actually reading the readme (I just started using it after a friend recommended it for use with squadron and engineering) I just found that by default it spams your Documents folder with a whole lot of files.

It's very nice of the readme to at least tell you this. I think it would be much better for a future version of the tool to actually just migrate all these files... into a dedicated folder (maybe some sort of opt in on a first run to migrate, so you don't piss off people who... actually _like_ their Documents folder with a whole lot of files specific to one game...) `Documents/EDMC/`, for instance. By default. Rather than chucking them all in the bare documents folder by default. So that's sort of a enhancement request.

I was about to do this myself, and configure EDMC to use some specific folder and move all the files there... however after opening the *Browse...* button I got this error:

![](https://up.s-ul.eu/FIqw6sTM.png)

I think this was as soon as I did one click in the folder chooser dialogue, or maybe started happening as soon as it was brought up. I got it to crash in the same way after doing the same, after opening it up again when restarting the app. Not easy to make 100% reproducible. Worked perfectly fine a couple times after.

**Comment by Athanasius** [comment]
Are you using the latest Python-2.7 based release 3.43, or the Python-3.7 based 3.50 beta0 ?

**Comment by Athanasius** [comment]
I just tested this with the 3.50 beta0 version and had no problems setting this back to `Documents` or again to the `Documents\My Games\Elite Dangerous` I'd previously changed it to.

Please also check the file `%TEMP%\EDMarketConnector.log` *immediately* after you cause this crash and past the contents here.

**Comment by Ivoz** [comment]
I am only using the installer

**Comment by Athanasius** [comment]
Can you reproduce this using the latest stable release, 3.46 ?

**Comment by Athanasius** [comment]
Closing due to lack of response.
