### ISSUE TITLE
EDDN error reporting needs to be more verbose

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDMarketConnector#503]
Currently if the EDDN plugin can't connect/send to the EDDN Gateway for any reason all you'll see is "Error: Can't connect to EDDN" on the bottom line of the EDMC UI.  Unless you've set debug output active you won't even get extra output in the log file.

This needs to be changed so, for instance, the user can see if the EDDN Gateway is returning a specific error because their version of the client has been banned.

**Comment by Athanasius** [comment]
Ah, my bad, I forgot I was running from source there, so the log file stuff just went to the console.  Still, not many know to check the log file and a slightly more verbose status line error would be useful in some cases.

**Comment by A-UNDERSCORE-D** [comment]
Likely this can be closed now?
