### ISSUE TITLE
Port to Python 3.8

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDMarketConnector#505]
This is, currently, a long-term TODO item.

python.org/downloads/ says that Python 3.7.x will be supported until 2023-06-27 so there's no rush on this, but we will want to update **before** that point.

Key, currently untested, possible tripping point is py2exe.  This was never updated by the original authors for any Python 3.x, and there's just a single developer who's worked on the fork that has Python 3.x support.  There *is* a py38 branch available there, but when I checked earlier today there'd been no new commits to that entire repo since late 2019.  We might have to look into finding an alternative method for the .exe generation.  Keep in mind that includes packaging all of the correct module files as well, which is most of what py2exe ends up doing.

**Comment by inorton** [comment]
Would it be the end of the world to ship a whole working python?

**Comment by Athanasius** [comment]
> Would it be the end of the world to ship a whole working python?
Hmmm, that is indeed only "Size on disk: 109 MB" for my Python 3.7.7 32-bit install (and I know I have some site-packages modules that EDMC doesn't need), so it's not like we'd be bloating the install to GBs.  Current 3.43 of EDMC is 24.1 MB, so we're looking at 5x the installed size.

There might be niggles if we're actually running python.exe instead of EDMarketConnector.exe though.

**Comment by wereii** [comment]
Why not PyInstaller ?

**Comment by Athanasius** [comment]
I briefly looked at at least one other option when I was working on the packaging part of the python3 branch, but couldn't get anything working.  I'd need to look back over notes to see if I tried PyInstaller.

This is on the backurner until we're released in a stable manner for Python 3.7 and have addressed any bugs and non-trivial enhancements.

**Comment by inorton** [comment]
I've done a thing where you statically link an exe against libpython.lib and have a small stub that loads a script.   But actually, it might be comparatively easy to just ship a python.  It might make it easier on plugin developers too

**Comment by Athanasius** [comment]
Getting the .exe made is indeed the simple part.  Most of what py2exe does is ensure that it also packages all the right module files (including things like the cacerts.pem file for `certifi`) in the distribution (they go in the library.zip file in this case).

I am indeed leaning towards investigating just packaging the requisite Python, it'll just mean working out a way to automate an extra Python install in a custom location so I can ensure it literally only includes the necessary modules (rather than anything extra I've installed for other reasons).  And, of course, double-checking what licenses say about redistribution.

To be honest, my first step on this was going to check what the official Python documentation says about "Packaging an application for release/distribution".

**Comment by Athanasius** [comment]
py2exe released an update that works with Python 3.8.  It initially still had an issue with certifi and cacert.pem, but the developer has now fixed that with https://bintray.com/alby128/py2exe/py2exe/0.10.0.1#files .

Our branch https://github.com/EDCD/EDMarketConnector/tree/enhancement/python-3.8 appears to now be working.
