### ISSUE TITLE
[python3] - Rename modules away from python2.7 names

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDMarketConnector#514]
To keep the python3 port simpler/smaller I chose to use `from X import Y as Z`  syntax so that the code could continue to use the python 2.7 'Z' name for a module.  This works, but might be found confusing in the future ("Why are you still using the python 2.7 names for modules/classes ?").

So, at some point, actually rename all of those references to make the code more purely python3.

**Comment by Athanasius** [comment]
NB: Definitely don't do this until after the python3 code is the release code.  What I did has made it simpler to merge later changes to the old python 2.7 code into the python3 branch.

**Comment by Rixxan** [comment]
This appears to be complete, as there aren't any weird-looking `from x import y as z` that don't look normal in context. Closing as non-issue (at least, not anymore!)
