### ISSUE TITLE
Python3 branch link broken in PLUGINS.md

### ISSUE THREAD

**Issue by DlljsCodes** [EDCD/EDMarketConnector#516]
It leads to a 404. Should change from `https://github.com/EDCD/EDMarketConnector/blob/master/EDCD/EDMarketConnector/tree/python3` to `https://github.com/EDCD/EDMarketConnector/tree/python3`.

**Comment by Athanasius** [comment]
Ah, the joys of previewing locally (using `grip PLUGINS.md --export PLUGINS.html`) and then github making the link relative to repo rather than whole site.  I'll commit a fix for this shortly, thanks!

**Comment by Athanasius** [comment]
Fixed in a8631e5bb87740a64bb9d0853831e732af222f25
