### ISSUE TITLE
Pre-Release / Beta channel

### ISSUE THREAD

**Issue by bgol** [EDCD/EDMarketConnector#519]
Make an pre-release / beta channel with its own release cycle and let the user decide (over the settings) if he wants to get notified about it / to participate in it.

**Comment by Athanasius** [comment]
I'll need to have a think about how to do this with respect to WinSparkle/appcast, but in theory it should be as simple as switching between update_feed settings.

**Comment by Athanasius** [comment]
The lack of people testing betas and rcs really emphasises the need for this.

We need to keep in mind easy rolling forwards and backwards between live and beta channels.  On Windows that's going to mean explicitly removing a beta version before going back to a live version, else Windows Installer will just refuse to do it (unless there's a flag to `msiexec` to achieve this).
