### ISSUE TITLE
Tooling required for single changelog

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDMarketConnector#525]
Currently the main changelog users see is in edmarketconnect.xml (the appcast file).  But that same text also needs to be in:

- [ ] Release feed file
- [ ] The github release
- [ ] Forum post
- [ ] Reddit post

Ideally we'd have a CHANGELOG.md as the main source and scripting/tooling to then get that into the appcast file (need to render to HTML), plus something to spit out BBCode etc as needed rather than hand editing for other places.

**Comment by Athanasius** [comment]
As part of this it would be nice to have templates for Forum, Reddit etc posts as well.  Sure, I could do this privately but any other/future maintainer might appreciate it as well :) 

I think it's probably best to designate the forum post as the go-to place to check for both new versions *and* other announcements, so the Reddit template should state that.

**Comment by A-UNDERSCORE-D** [comment]
markdown and some sed would probably be the easiest for conversion to other formats

**Comment by Athanasius** [comment]
Yup, I've already moved to the (new) ChangeLog.md as the primary location of the changes.  Where you need HTML `pip install grip` and then `grip ChangeLog.md --export ChangeLog.html` and process further from there.

**Comment by Rixxan** [comment]
GH Releases uses the markdown from changelog, so we really need 4: 

1. GH MD (manually made in ChangeLog.md)
2. HTML, for use in the appcast
3. Forum BBCode, for use on the forums. 
4. Reddit for Major and Minor (non-patch) releases

Of those, BBCode is going to be the hardest one to figure out.
