### ISSUE TITLE
Update all documentation to be correct for Python 3.7

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDMarketConnector#526]
Ensure all documentation is updated before first Python 3.7 based release.

- [x] https://github.com/EDCD/EDMarketConnector/blob/python3/README.md - Updated for no more MacOS releases, and anything else related to moving to Python 3.7.
- [x] https://github.com/EDCD/EDMarketConnector/blob/python3/PLUGINS.md - e.g. we're going to use 4.0.0.0/4.00 as the first release.
- [x] https://github.com/EDCD/EDMarketConnector/wiki/Plugins will need an update to ensure we only point users to plugins known to work under Python 3.7.
- [x] Either firm up the description of the plugin API in PLUGINS.md, or open a separate ticket to do that later.

**Comment by Athanasius** [comment]
Contributing: See https://github.com/EDCD/EDDI/blob/develop/docs/Contributing.md#git-branch-structure-and-tag-conventions

**Comment by robbyxp1** [comment]
As we discussed, If we have the energy to, plugins.md should firm up the interface:

Which imports EDMC provides (Config.config, l10n) and their methods/data fields (as much as possible)

Journal_Entry state dictionary also should be defined - which fields are in it.

**Comment by Athanasius** [comment]
See #545 for updating Plugins.md documentation.  Not blocking on it for 4.0.0.0
