### ISSUE TITLE
Solidly define and document all of the Plugin interfaces.

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDMarketConnector#545]
Plugins.md already does a reasonable job of this, but is missing:

- [x] What can plugins expect to find in the `journal_entry()` `state` variable?
- [x] Check if the  `cmdr_data()` `data` variable *is* simply the `/profile` data from the CAPI.  If it is then we're not documenting, or promising anything about, it here.
- [x] Which imports EDMC provides (Config.config, l10n) and their methods/data fields (as much as possible)

**Comment by Athanasius** [comment]
Re: `data` passed to `cmdr_data()`

It's *almost* pure CAPI return (modulo having gone through json.loads() courtesy of requests.Session.json()), but has one field added by companion.py -> Session.query():

        if 'timestamp' not in data:
            data['timestamp'] = time.strftime('%Y-%m-%dT%H:%M:%SZ', parsedate(r.headers['Date']))

Then the basic data is just what CAPI returns from the `/profile` endpoint, but it has `/market` endpoint data added in the 'marketdata' key and `shipyard` endpoint data added in the `shipdata` key.

**Comment by Athanasius** [comment]
- [ ] I know inorton at least just asked about detecting ED game is running and found `monitor.gamerunning()`

**Comment by Athanasius** [comment]
I think this is now mostly covered in the updated https://github.com/EDCD/EDMarketConnector/blob/develop/PLUGINS.md - particularly https://github.com/EDCD/EDMarketConnector/blob/develop/PLUGINS.md#available-imports .

Please comment here if I missed anything.

**Comment by sersorrel** [comment]
PLUGINS.md says that `plugin_prefs` returns `Optional[tk.Frame]`, but the code disagrees – if it returns `None`, or if it's not specifically an `nb.Frame`, an exception is raised:

https://github.com/EDCD/EDMarketConnector/blob/87324661d963e1dd415b13138c92478bc746a31f/plug.py#L160-L162

**Comment by Athanasius** [comment]
I think you're misunderstanding what `Optional` means in this context.  It's part of the type-hinting.  All it *means* is that the function may return a `tk.Frame`, but may also return `None`.  It doesn't mean that, in normal function, a plugin may return `None` from its plugin_prefs() and expect it to work.

The intention is that a correctly run `plugin_prefs()` method will always return a `tk.Frame`, but if it errors out in some manner it may either explicitly return `None`, or do so due to a bare `return`.  The point of returning a `tk.Frame` is that it's a reference to the frame the plugin corrected that can then be used to display that on the Settings window.

```python

plug.py:
	def get_prefs(self, parent, cmdr, is_beta):
...
                frame = plugin_prefs(parent, cmdr, is_beta)
                if not isinstance(frame, nb.Frame):
                    raise AssertionError
                return frame
...                

prefs.py:
    def __setup_plugin_tabs(self, notebook: Notebook) -> None:
        for plugin in plug.PLUGINS:
            plugin_frame = plugin.get_prefs(notebook, monitor.cmdr, monitor.is_beta)
            if plugin_frame:
                notebook.add(plugin_frame, text=plugin.name)```

**Comment by sersorrel** [comment]
I mean, any function can return whatever it likes – Python's not a statically-typed language. If a correctly-implemented `plugin_prefs` should always return a `tk.Frame`, then that's what the type hints should say. imo, the type hints in the documentation should be about what the function _should_ do, not what it might do if it's buggy.

**Comment by Athanasius** [comment]
No, because it's defined that if the plugin_prefs has any issues it can return `None` to signal that, and the calling code won't then add a broken tk.Frame to the Settings dialogue.

The type hints in the documentation match that in the code, which has to be that, else `mypy` will rightly complain (as there's explicit code testing it it's (not) `None`.

**Comment by Athanasius** [comment]
However I will look at explictly stating this in the documentation.  The `Optional[tk.Frame]` is only there because of citing the code.
