### ISSUE TITLE
[3.99.0.0] Serbian (Latinica, BiH) missing in available languages

### ISSUE THREAD

**Issue by mIRCon** [EDCD/EDMarketConnector#547]
EDMC 3.99.0.0 doesn't have Serbian (Latinica, BiH). It's just missing in available languages, although it has fully updated Serbian (Latinica) which missing phrases I added before 3.99.0.0 release at the same time I added full Serbian (Latinica, BiH).
Note: Serbian (Latinica, BiH) would be displayed as such in the app while it's full Microsoft style name is Serbian (Latin, Bosnia and Herzegovina).

**Comment by Athanasius** [comment]
This will be a case of my having neglected to add the new languages to the .wxs installer-build file.

- [ ] Add new languages (see #530 ) to the .wxs file
- [ ] Test they work from an installation, not just from dist.win32 folder.
- [ ] Update docs/Translations.md to reflect the extra step(s)

**Comment by Athanasius** [comment]
Actually, it's probably the `EDMarketConnector.manifest` file that needs updating.  Will update the checklist when I've confirmed that.

**Comment by Athanasius** [comment]
Nope, right the first time, just a different section of the .wxs file.  I only changed the bit for the *installer* language support, not also to have any additional L10n/* files included.
