### ISSUE TITLE
[Translations] - Add 'all' languages to the installer.

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDMarketConnector#551]
The list of numerical IDs for languages in EDMarketConnector.wxs are for the *installer* languages.  The strings for those are nothing to do with EDMC itself, coming from the MicroSoft SDK and tools.  So, why not just support all the languages rather than an explicit list ?

If needs be this will mean some sort of (PowerShell?) iteration over the available ones.

**Comment by Rixxan** [comment]
This appears to be completed. If it is not, please let us know.
