### ISSUE TITLE
[Installer] Create 'defaults' Registry keys at install time

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDMarketConnector#555]
Check if there's a way to have the MSI installer create certain Registry keys, with default values, if and only if they don't already exist.

Then we don't need to be trying to set things like WinSparkle options in the EDMC code (search config.py for WinSparkle).

**Comment by Rixxan** [comment]
@Athanasius I think we've got this one sorted. Is the change as shown in #2109 about what you had in mind?

**Comment by Rixxan** [comment]
Closing as completed, however if there are further questions/comments/concerns should be reopened.
