### ISSUE TITLE
EDR by Lekeno not working

### ISSUE THREAD

**Issue by feiercrack** [EDCD/EDMarketConnector#560]
EDR 1.07 is not showing up in the Plugins tab, nor it is working

https://github.com/lekeno/edr/releases/tag/v1.0.7https://github.com/lekeno/edr/releases/tag/v1.0.7

**Comment by Athanasius** [comment]
They have a python 3.7 branch: https://github.com/lekeno/edr/tree/py-3.7

And in general, if it's a plugin, please open an issue with *them* about updating to work under Python 3.7.
