### ISSUE TITLE
[Enhancement] Add proper logging 

### ISSUE THREAD

**Issue by A-UNDERSCORE-D** [EDCD/EDMarketConnector#563]
Currently all logging is done via print statements, which works fine for simple information but lacks time (and optionally file/line) information. Python3 provides a [very powerful logging engine](https://docs.python.org/3.7/library/logging.html) that would even allow plugins to hook in and augment their logging to fit our structure.

- [x] Replace most `__debug__` stuff with appropriate `logging` level statements.
- [ ] A_D : maybe add "THIS IS A BUG, PLEASE REPORT ON EDMC GITHUB", so if users ever see it, we can see it
- [ ] Consider some level of log file rotation, rather than losing all previous logging on a fresh run.

TODO:

- [x] - Check that 'found' third-party plugins *can* use this without issue.  There shouldn't be any problem, I just want to be paranoid about them loading from a different path not blowing anything up.
- [x] - Update non-wiki Plugins.md for how to use logging.
- [x] - Add both EDMC.py commandline and EDMarketConnector.py UI for changing logging level.  Really just toggling between INFO and DEBUG.
- [x] - Check method for detecting (in plugins) if logging is available:
    `l = logging.getLogger(); if l.hasHandlers: <something to make all logging functions just be print, or set up basic logger?>`
    This would then need to go in non-wiki Plugins.md in main/stable for plugin developers to see/check.

**Comment by Athanasius** [comment]
You read my mind, I'd been musing on this change already :) .

**Comment by A-UNDERSCORE-D** [comment]
Ill add it to the list :D

**Comment by Athanasius** [comment]
You're possibly more familiar with the module than me.

I'm assuming it will, of course, just end up using print() anyway, and that must normally be going through some sort of mutex else threads would all print over and in the middle of each other, right ?

Basically, is it OK for each file/module to just `import logging` and get on with it, or should we make a global `logger` instance available, including through to plugins, and document that as the way to do it?  It would mean easy enforcement of the format/other logging options.

Our own edmclogging.py that is imported everywhere ?

**Comment by A-UNDERSCORE-D** [comment]
Yeah its safe for multiple threads (at the very least by way of the GIL), there are two ways we can do that, either as you say, a global logger instance, or you can ask the logging lib for the instance by name: `logging.getlogger("name")`

for the actual logger setup, we'll probably want to do that in an __init__.py somewhere, or in the main. For plugins Im unsure, passing them a logger we control for some more consistent formatting between plugins may be a good idea? pretty much all I'd want to do on any plugin logger is add `[plugin_name]` to their lines, for clarity.

**Comment by Athanasius** [comment]
So long as whoever adds the `logger` argument to `plugin_start3()` remembers to do it on the end of the argument list, to avoid actually breaking the API, I'd say do it that way.  It's the paradigm I've done in a few bits of my own code so as to only have to set it up once in the 'main', not in every module I import and use.

**Comment by Athanasius** [comment]
Per IRC discussion:

- [ ] Replace most __debug__ stuff with appropriate `logging` level statements.
- [ ] A_D : maybe add "THIS IS A BUG, PLEASE REPORT ON EDMC GITHUB", so if users ever see it, we can see it
- [ ] Consider some level of log file rotation, rather than losing all previous logging on a fresh run.

**Comment by Athanasius** [comment]
>     *  A_D : maybe add "THIS IS A BUG, PLEASE REPORT ON EDMC GITHUB", so if users ever see it, we can see it
The problem with this is we either add it in every appropriate message... or if we're adding it on `.error()` and `.critical()` then that means overriding them, but then you end up with `%(funcName)s` being your overriding function instead of the actual caller.

`logger.Formatter` uses the frame record to get at this stuff in its `findCaller()` function and only goes back far enough to find the first caller not in its own file, I think ?  Copying that or overriding it is going to be fragile, I'd rather not.

**Comment by Athanasius** [comment]
Work for this has been started in the https://github.com/EDCD/EDMarketConnector/tree/enhancement/563-proper-logging branch.

1. A logging.Logger instance defined in EDMarketConnector.py
    1. This also has a filter to add support for `%(qualname)s` and `%(class)s` via stack tracing.
    1. It's defined at module level, so is available for import to elsewhere, BUT...
1. Other modules should NOT `from EDMarketConnector import logger` as this could cause a circular import.  Use this instead:

        import logging
        from config import appname
        logger = logging.getLogger(appname)

1. Intention is to get all GUI and CLI files converted ASAP.  I'm leaving the 'helper scripts' for now, especially as they likely don't even cause EDMarketConnector to be parsed, at least in some cases.  Yes, maybe there should be EDMCLogging.py for this.
    1. EDMarketConnector.py is converted.
    1. plug.py is converted (messages about plugin loading always happen, was good for testing).
    1. plugins/*.py are done (tested that we get sane output here).
    1. Right now I'm up to, and have completed 'companion.py'

**Comment by Athanasius** [comment]
TODO:

- [ ] - Check that 'found' third-party plugins *can* use this without issue.  There shouldn't be any problem, I just want to be paranoid about them loading from a different path not blowing anything up.

**Comment by Athanasius** [comment]
Of course *now* we have a way to fiddle with LogRecords on the fly with our filter.

**Comment by Athanasius** [comment]
https://github.com/EDCD/EDMarketConnector/pull/630 now merged.

We can start adding logging to all other files now outside of that PR.

**Comment by Athanasius** [comment]
From some testing with code to give plugin developers a way to add logging now...

Using my 'miggytest' plugin in my `%LOCALAPPDATA\EDMarketConnector\plugins` folder under `develop` branch:

```
2020-07-30 11:45:40.853 - EDMarketConnector - INFO - plug.Plugin.__init__:95: Plugin: loading plugin "miggytest" from "C:\Users\Athan\AppData\Local\EDMarketConnector\plugins\miggytest\load.py"
2020-07-30 11:46:04.492 - EDMarketConnector - INFO - load.plugin_start3:63: <none>: Folder is C:\Users\Athan\AppData\Local\EDMarketConnector\plugins\miggytest
2020-07-30 11:47:12.887 - EDMarketConnector - DEBUG - load.miggytest.__init__:35: miggytest: directory = "C:\Users\Athan\AppData\Local\EDMarketConnector\plugins\miggytest
```
There's no indication in the core logging as to which plugin that's from (load.miggytest is citing a class name).

**Comment by Athanasius** [comment]
The suggested code for third-party devs will be:

```python
import logging

from config import appname

plugin_name = "miggytest"  # Can be also returned from plugin_start3()

logger = logging.getLogger(appname)
if not logger.hasHandlers():
    level = logging.INFO  # So logger.info(...) is equivalent to print()

    logger.setLevel(level)
    logger_channel = logging.StreamHandler()
    logger_channel.setLevel(level)
    # Including plugin_name in the output.
    logger_formatter = logging.Formatter(f'%(asctime)s - %(name)s - %(levelname)s - {plugin_name}:%(module)s:%(lineno)d:%(funcName)s: %(message)s')
    logger_formatter.default_time_format = '%Y-%m-%d %H:%M:%S'
    logger_formatter.default_msec_format = '%s.%03d'
    logger_channel.setFormatter(logger_formatter)
    logger.addHandler(logger_channel)
```
which does give the plugin name in the logging output.

**Comment by Athanasius** [comment]
`main` now has Plugins.md documentation about using proper logging.

**Comment by Athanasius** [comment]
I think we can consider this 'done', so long as plugin authors pay attention to the docs, which now point out that the `plugin_name` in `logger = logging.getLogger(f'{appname}.{plugin_name}')` *must* be the plugin's folder name (as that's what plug.py uses to properly set up the logger).
