### ISSUE TITLE
EDMC.py complains when $DISPLAY not set

### ISSUE THREAD

**Issue by pwerken** [EDCD/EDMarketConnector#568]
**Describe the bug**
When no $DISPLAY is set EDMC.py raises an exception (see below).
It still also outputs the correct info about the current system & docked location.

**To Reproduce**
1. On linux, go to source directory
2. Run EDMC.py

**Expected behavior**
It's a CLI tool, it should not complain about $DISPLAY not being set.

**Screenshots**
```
$ ./EDMC.py 
Traceback (most recent call last):
  File "/usr/local/src/EDMarketConnector/theme.py", line 89, in <module>
    raise Exception("Can't find your display, can't continue")
Exception: Can't find your display, can't continue
LHS 2088,K4X-33F
```

**Desktop (please complete the following information):**
 - OS: Linux, debian bullseye/sid
 - Version 3.99.3.0 ( from source, develop 3476956d854afaf49ea7addd79310ab3b2897ab3 )

**Additional context**
Did a bit of digging in throught the imports, the problematic chain:
`EDMC.py` > `stats.py` > `prefs.py` > `theme.py`

`prefs.py` builds the GUI preference dialog, so it looks like `stats.py` should not be importing it.
Since EDMarketConnector.py imports the `prefs.py` directly it seems safe to remove its import from `stats.py` ( ? ).

**Comment by Athanasius** [comment]
And again it's demonstrated that we really need some tests so that I don't keep forgetting about EDMC.py.

At least you have the workaround of just setting DISPLAY to *something*.  I'll review the code (which is aimed at not getting a "Segmentation Fault" from the main program when running without DISPLAY set) to see if the check can be moved elsewhere.

**Comment by Athanasius** [comment]
I note that if I take out the check that we added that causes the exception splat:

```16:34:40 1$ ./EDMC.py -v
Segmentation fault```

So the current situation is at least better than it was before that fix!

**Comment by Athanasius** [comment]
So, as the 3.99.3.0 behaviour is at least better than before I won't push out another pre-release just for this fix.  It'll be in 4.0.0.0.
