### ISSUE TITLE
[Minor] Tweak "Error: Frontier server is down" message

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDMarketConnector#585]
Consider changing this to something like:

`Error: Frontier CAPI didn't respond`

As it is some users might think that EDMC is monitoring the actual game servers and this pertains to them.

We could possibly turn this issue into reviewing *all* such error messages for clarity and ambiguity.

**Comment by A-UNDERSCORE-D** [comment]
I think making sure that all error messages are clarified is a good idea, though note that any translations will need to be re-verified

**Comment by Athanasius** [comment]
Changed in 1bc1a4f1b9c72b5c125bd2bac9cb3e8e3e843d23 - awaiting new translations on OneSky.
