### ISSUE TITLE
Systems link to eddb is bugged - Release 3.99.4.0

### ISSUE THREAD

**Issue by MartindForlon** [EDCD/EDMarketConnector#586]
In my EDMC settings I chosed opening Systems in eddb. However when I clik system (Afli), it opens next link: `https://eddb.io/system/ed-address/61062` which results in error "Not Found (#404)". Correct link is: `https://eddb.io/system/520`

_Note: Stations are opened correctly in eddb._

**Comment by Athanasius** [comment]
The correct SystemAddress would be `3107576550106`, which is nothing at all like `61062`.

I don't suppose you could find the relevant FSDJump event from the Journal file to see what it said ?

**Comment by MartindForlon** [comment]
moment

**Comment by MartindForlon** [comment]
`{ "timestamp":"2020-07-11T16:27:32Z", "event":"FSDJump", "StarSystem":"Afli", "SystemAddress":3107576550106, "StarPos":[35.31250,-78.03125,38.62500], "SystemAllegiance":"Independent", "SystemEconomy":"$economy_HighTech;", "SystemEconomy_Localised":"High Tech", "SystemSecondEconomy":"$economy_Refinery;", "SystemSecondEconomy_Localised":"Refinery", "SystemGovernment":"$government_Dictatorship;", "SystemGovernment_Localised":"Dictatorship", "SystemSecurity":"$SYSTEM_SECURITY_medium;", "SystemSecurity_Localised":"Medium Security", "Population":90349309, "Body":"Afli A", "BodyID":2, "BodyType":"Star", "JumpDist":15.801, "FuelUsed":1.038458, "FuelLevel":27.059908, "Factions":[ { "Name":"HR 8829 Purple State Industries", "FactionState":"War", "Government":"Corporate", "Influence":0.102307, "Allegiance":"Empire", "Happiness":"$Faction_HappinessBand2;", "Happiness_Localised":"Happy", "MyReputation":100.000000, "ActiveStates":[ { "State":"War" } ] }, { "Name":"Afli Imperial Society", "FactionState":"War", "Government":"Patronage", "Influence":0.102307, "Allegiance":"Empire", "Happiness":"$Faction_HappinessBand2;", "Happiness_Localised":"Happy", "MyReputation":100.000000, "ActiveStates":[ { "State":"Boom" }, { "State":"War" } ] }, { "Name":"Afli Power Co", "FactionState":"None", "Government":"Corporate", "Influence":0.052156, "Allegiance":"Independent", "Happiness":"$Faction_HappinessBand2;", "Happiness_Localised":"Happy", "MyReputation":-19.408400 }, { "Name":"Afli Patron's Principles", "FactionState":"None", "Government":"Patronage", "Influence":0.092277, "Allegiance":"Empire", "Happiness":"$Faction_HappinessBand2;", "Happiness_Localised":"Happy", "MyReputation":100.000000 }, { "Name":"Afli Blue Partnership", "FactionState":"None", "Government":"Anarchy", "Influence":0.047141, "Allegiance":"Independent", "Happiness":"$Faction_HappinessBand2;", "Happiness_Localised":"Happy", "MyReputation":-75.000000 }, { "Name":"The Sovereign Justice Collective", "FactionState":"Boom", "Government":"Dictatorship", "Influence":0.538616, "Allegiance":"Independent", "Happiness":"", "SquadronFaction":true, "MyReputation":100.000000, "ActiveStates":[ { "State":"Boom" }, { "State":"CivilLiberty" } ] }, { "Name":"Afli Silver Universal Exchange", "FactionState":"None", "Government":"Corporate", "Influence":0.065196, "Allegiance":"Independent", "Happiness":"$Faction_HappinessBand2;", "Happiness_Localised":"Happy", "MyReputation":-6.468400 } ], "SystemFaction":{ "Name":"The Sovereign Justice Collective", "FactionState":"Boom" }, "Conflicts":[ { "WarType":"war", "Status":"active", "Faction1":{ "Name":"HR 8829 Purple State Industries", "Stake":"Wheeler Enterprise", "WonDays":2 }, "Faction2":{ "Name":"Afli Imperial Society", "Stake":"Royal Concourse", "WonDays":3 } } ] }`

**Comment by Athanasius** [comment]
OK, so something prevented EDMC from picking up the SystemAddress correctly.  Thanks for the report, I'll have a closer look at this later this evening.

**Comment by MartindForlon** [comment]
Interesting, after next jump to Oluf system it uses correct system adress. Will add further comments if found something.

**Comment by MartindForlon** [comment]
ok, after I arrived into LTT 8750 system is opened correct adress, but when I docked on station it used bugged adress. Back to supercruise (left station) and adress of system is correct.

**Comment by Athanasius** [comment]
Could you please use "File" > "Save Raw Data" when you see the incorrect URL ?  This will save the return from the Frontier CAPI, which is the only other source of the SystemAddress besides Journal files.

I have a 'fix' which will only use the CAPI value if EDMC doesn't have one yet, thus relying on Journal for it once you start playing (but allowing for it to work before you get in-game if you hit 'Update'), but I'm curious how you're getting the bad value in the first place.

**Comment by Athanasius** [comment]
Oh, look, I just saw the bug.  Yeah, something is not setting this right from CAPI data.

**Comment by Athanasius** [comment]
Yup, this is some sort of Frontier bug.  I've confirmed it with my own separate code for fetching the `/profile` endpoint.  I got `data['lastSystem']['id'] == 56368` for LTT 8750, when it should be `1733187015394`.

I think it only isn't showing up more because Journal events also change the value used in the plugin.  I'll apply my fix outlined above and put out a 3.99.5.0 shortly.

**Comment by Athanasius** [comment]
Please try out https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F3.99.5.0 - it should have fixed this issue.
