### ISSUE TITLE
Sort plugins name for loading

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDMarketConnector#589]
Some people have plugins that depend on one another.  Currently they're at the mercy of the order returned by `os.listdir()` in plug.py -> load_plugins():

        for name in os.listdir(config.internal_plugin_dir):
There's no reason we can't wrap that in a `sort()` so they can, for now, enforce order with name prefixes.

**Comment by A-UNDERSCORE-D** [comment]
Depending on how we do plugins themselves we could also offer a pluginLoaded and a loadingFinished event, which would allow for soft depends as well. Docs should also make it clear that plugin files should do nothing active on import other than defining themselves. That way if we want we can later control how Interop works if we provide our own get_handle method for getting other plugins. Which leads it's way nicely to hot reloads

**Comment by Athanasius** [comment]
It turns out that 'found' (not internal/core) plugins already have a `sorted(...)` wrapper anyway.

But I'm going to add one to the internal/core loading for consistency, and lack of surprise if anyone ever accidentally makes one of them dependent on another.
