### ISSUE TITLE
EDMC crash on system entry

### ISSUE THREAD

**Issue by CMDR-Cometborne** [EDCD/EDMarketConnector#592]
Just after completing a jump to Byeia Thoea LD-K c8-0, EDMC crashed with an alert box about the runtime requesting an unusual termination. The log file has the following lines at the end:

Exception in Tkinter callback
Traceback (most recent call last):
  File "Tkinter.pyo", line 1547, in __call__
TypeError: callit() takes no arguments (5 given)

Jumping out and back in worked just fine.

**Desktop (please complete the following information):**
 - OS: Windows 10
  - Version 3.46

**Comment by A-UNDERSCORE-D** [comment]
Please provide a full stacktrace.

**Comment by CMDR-Cometborne** [comment]
The messages above were all that I got.  However, based on public feedback, I am closing this.
