### ISSUE TITLE
Improve display of system link when system is not known to preferred website

### ISSUE THREAD

**Issue by Thurion** [EDCD/EDMarketConnector#597]
**Description**
Currently the system name is shown as a link even when the preferred website (EDDB, EDSM, Inara) doesn't know about it. When the user wants to click it, it looks like it can't be clicked for some reason.

**To Reproduce**
1. Optional but makes it easier to test: Turn off EDDN, EDSM, and Inara sync
2. Jump to a new, previously unknown system
3. Try to click on system name

**Expected behavior**
Better feedback to make it clearer to the user that the preferred website has no data about that system.
I can think of a few ways how this could be improved:
* Change appearance to a normal label
* Add a tool tip that explains what's going on

**Screenshots**
Trying to open a system that is not known to the selected website:
![](https://cdn.discordapp.com/attachments/251742967927144449/732147963253751818/unknown.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 3.99.5.0

**Comment by Athanasius** [comment]
From Discord conversation it appears in this case you have Inara as the system provider, and are not sending to EDDN (either at all, or 'delay until docked' ?

Probably working as expected if that's the case, *but* we really should document this.  In fact we need to actually document everything that can happen on that line:

- [ ] The EDSM 'green circle' -> EDSM knows this system's co-ordinates.
- [ ] The EDSM 'Yellow Star' -> You were first to upload data about this system to EDSM.

@Thurion - Can we have permission to use the image you included in the docs ?

**Comment by Thurion** [comment]
Yes you can use the image.
The behavior is working as expected and it's only an idea for an enhancement. Maybe you should create a template for that?

I think the main issue here is that even if people read the documentation, they will forget about it eventually. And when they come across some unexpected behavior like this, it seems strange and appears like a bug unless it is made clear in the UI what's going on.

**Comment by Athanasius** [comment]
I've updated the [wiki documentation](https://github.com/EDCD/EDMarketConnector/wiki) to better reflect functionality and the various states you can find bits of the UI in.
