### ISSUE TITLE
Plugins desctivados

### ISSUE THREAD

**Issue by Sebaxstyian01** [EDCD/EDMarketConnector#601]
hola, hoy de me actualizó el DE Market Connector y se daçactivaro todos los Plugins. eta en la carpeta correpondiente.

**Comment by Athanasius** [comment]
As the changelog for 4.0.0.0 said you probably need to update your plugins to versions that work with Python 3.7.  Ask the plugin authors if it seems they haven't yet updated their code.

**Comment by Sebaxstyian01** [comment]
Gracias
