### ISSUE TITLE
EDMC.py version check needs better exception handling

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDMarketConnector#604]
One report on forums of 'EDMC.exe -v' not showing 4.0.0.0 -> 4.0.1.0 as an update.

Check the code, might need some adjustment for no longer using the old A.BC form.

**Comment by Athanasius** [comment]
It turns out that the update check in EDMC.py (it's not using WinSparkle) doesn't handle Unicode in Python 2.7.  There's an:

```
except:
    pass
```

in there that was swallowing the:
`Exception 'ascii' codec can't encode character u'\xd7' in position 10999: ordinal not in range(128)`

That's the 'x' character in description of changes to EDDB Station URL handling.  For now I've commited a change only in `releases` to allow 3.46 users to see there's a new version.

We should check that code in 4.x and be sure to at least change the exception handling to something sane.  Heck, s/pass/raise/ would be an improvement.

**Comment by A-UNDERSCORE-D** [comment]
Rather than reraising,  a log would probably be better. Assuming the handler can't be narrowed down exception wise

**Comment by Athanasius** [comment]
If it wasn't for wanting the 'finally' of saying the current version I'd say just take the code out of the try block.  As it is, at least logging the exception is the way to go, yes.  It's how I found what the error was at all.

Then we can think about catching specific exceptions individually (like network issues from requests, and badly formed XML, and whatever else).

Right now I'd just like to not have the mystery of "hey, this version isn't saying there's an update, why ?".

**Comment by Athanasius** [comment]
'eventure' on the Frontier forums has replied that it was 4.0.0.0 not showing the 4.0.1.0 update as available.  So, yes, need to review this code in general to at least give decent feedback about *why* it's not announcing an update is available.

I'm tempted to move the statement of the current version above the try/except, and then just move the "is there an update too?" code outside a try/except entirely to let it splat whatever exceptions happen.

**Comment by Athanasius** [comment]
Aha!  I broke this in 3ff77c3c54dea4bf36d957cd2dbd5b1b02dcb094 - it no longer prints about an update at all.  I'll 'revert' that and it should be OK for now.

**Comment by A-UNDERSCORE-D** [comment]
There is a missing += in the current, I believe, but Im not entirely sure thats the only issue, investigating

**Comment by Athanasius** [comment]
I'm working on it, save your time!
