### ISSUE TITLE
Remove `keyring` as no longer required.

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDMarketConnector#611]
`keyring` was originally added as a dependency for #89 but then when Frontier moved to oAuth2 it became moot with #418 . 

The remaining code was never removed.  See `get_password()` and `set_password()` in  config.py, and any references to them.

**Comment by A-UNDERSCORE-D** [comment]
Resolved by #644 (aside from the get/set code, but those have been marked deprecated)
