### ISSUE TITLE
Indentation error in source code.

### ISSUE THREAD

**Issue by MarkAusten** [EDCD/EDMarketConnector#620]
4.0.3-rc2
Windows 10 defender complained, no problem told it to run the installer anyway.
I have Elite open, ran EDMC, no system or station despite being docked.
Changed station provider to Inara, still no system or station.
Pressed the update button and now have both system and station showing.

Error reported in log:

```
E:D Market Connector 4.0.3-rc1 2020-07-21T17:57:59
loading plugin coriolis from "C:\Program Files (x86)\EDMarketConnector\plugins\coriolis.py"
loading plugin eddb from "C:\Program Files (x86)\EDMarketConnector\plugins\eddb.py"
loading plugin eddn from "C:\Program Files (x86)\EDMarketConnector\plugins\eddn.py"
loading plugin edsm from "C:\Program Files (x86)\EDMarketConnector\plugins\edsm.py"
Traceback (most recent call last):
  File "plug.pyc", line 97, in __init__
  File "<frozen importlib._bootstrap_external>", line 407, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 907, in load_module
  File "<frozen importlib._bootstrap_external>", line 732, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Program Files (x86)\EDMarketConnector\plugins\edsm.py", line 219
    this.station = entry.get('StationName') or this.station
       ^
IndentationError: expected an indented block
loading plugin edsy from "C:\Program Files (x86)\EDMarketConnector\plugins\edsy.py"
loading plugin inara from "C:\Program Files (x86)\EDMarketConnector\plugins\inara.py"
```

**Comment by A-UNDERSCORE-D** [comment]
Related code is: https://github.com/EDCD/EDMarketConnector/blob/Release/4.0.3-rc2/plugins/edsm.py#L217 -- Unable to confirm indention error. Please can you upload the file `C:\Program Files (x86)\EDMarketConnector\plugins\edsm.py` from your system?

**Comment by MarkAusten** [comment]
I've compressed edsm.py and edsm.pyo and attached the compressed file. Added the compile file just in case the error is in that rather than the source.

[edsm-files.zip](https://github.com/EDCD/EDMarketConnector/files/4958428/edsm-files.zip)

**Comment by A-UNDERSCORE-D** [comment]
Ah Yeah, its missing there, I would suggest reinstalling or just swapping out the file with the one I linked above. The rest of the files should be fine.

**Comment by MarkAusten** [comment]
Since that was a reinstall in the first place, I'll try just downloading that one file and over-writing the existing file.

However, how did it get to be wrong when the source is correct? Odd.

**Comment by Athanasius** [comment]
It's possible that the `msiexec` side of things is being a pain given that 4.0.3-rc1 and 4.0.3-rc2 would both present as 4.0.3.0 to it.

I'm going to have to advise that anyone trying beta/rc version actually Uninstall the prior version before installing a newer one.

And, no, I can't just attempt to put a serial number in the last part of 4.0.3.0 because it's explicitly *not* counted as part of the version string for comparison purposes.

**Comment by MarkAusten** [comment]
Is it possible to uninstall EDMC but to leave the configuration such that the next install picks up the config again?

**Comment by Athanasius** [comment]
> Is it possible to uninstall EDMC but to leave the configuration such that the next install picks up the config again?

Yes, this is the default.  In fact there's no option to remove all the settings, still stored in the Registry, on uninstall.
