### ISSUE TITLE
unable to get endpoint /profil

### ISSUE THREAD

**Issue by Tirelas** [EDCD/EDMarketConnector#626]
**Describe the bug**
unable to get endpoint /profil

**Screenshots**

![image](https://user-images.githubusercontent.com/10535329/88223206-5d770380-cc67-11ea-8c50-9dc0f42bd483.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Version 4.0.2.0

**Comment by Athanasius** [comment]
This relates to the Frontier CAPI service.  At times it came respond slowly, or not at all.

It just responded for me, but slowly.  Are you *still* seeing this problem, even if you hit the 'Update' (Aktualisieren) button as often as it will allow you to try ?
