### ISSUE TITLE
[Enhancement] - Investigate *secure* way to flake8 fork PRs

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDMarketConnector#638]
flake8-your-pr workflow is working for in-repo PRs, but doesn't for other-fork PRs.

It's a security/authentication issue, and tricky to solve without opening up a security hole.

- [ ] Investigate if the API allows to gather sufficient information about outstanding failed-checks PRs.
- [ ] Cron schedule workflow to check for such, and do something like cloning the branch into this REPO to then make a new PR and run the checks (or just run the checks on the branch).

**Comment by A-UNDERSCORE-D** [comment]
Just to have it here per the discussion we have had -- we can still have flake8 run as a "status" check, and still show up red etc on PRs, we just cant have it annotate line by line like it does for internal PRs.

**Comment by Athanasius** [comment]
Ah, so just change the current push-checks.yml to push-and-pr-checks.yml (yes, keep the name indicative of what it runs on) and add prs into what it triggers on.

**Comment by A-UNDERSCORE-D** [comment]
Yeah, that should work perfectly

**Comment by Athanasius** [comment]
See https://github.com/EDCD/EDMarketConnector/pull/647

**Comment by Athanasius** [comment]
The current work ... works.  But really it needs to use a small bit of code that tests if it CAN annotate, always exit with `0` and set an env var as to what it found.  That way the annotations will always happen if the pushing user has the permissions, else not.

**Comment by Athanasius** [comment]
> The current work ... works. But really it needs to use a small bit of code that tests if it CAN annotate, always exit with `0` and set an env var as to what it found. That way the annotations will always happen if the pushing user has the permissions, else not.

Yup, this fails for me if the PR source is in my repo, not EDCD. so really need to do the proper check (and consider opening an issue with flake8-your-pr to get them to build the check in).

**Comment by Athanasius** [comment]
We'll just live with annotations only working for in-repo branches/PRs, so closing this.
