### ISSUE TITLE
EDMC 4.0.3 crashes during loading (TypeError: expected str, bytes or os.PathLike object, not NoneType)

### ISSUE THREAD

**Issue by MGM175** [EDCD/EDMarketConnector#639]
When attempting to launch EDMC from source (Linux Manjaro 20 + Python 3.8.3 (default, May 17 2020, 18:15:42)), I'm getting this error:

```
PS /home/[1000]/edmc> ./EDMarketConnector.py
loading plugin coriolis from "/home/chr0me/edmc/plugins/coriolis.py"
loading plugin eddb from "/home/chr0me/edmc/plugins/eddb.py"
loading plugin eddn from "/home/chr0me/edmc/plugins/eddn.py"
loading plugin edsm from "/home/chr0me/edmc/plugins/edsm.py"
loading plugin edsy from "/home/chr0me/edmc/plugins/edsy.py"
loading plugin inara from "/home/chr0me/edmc/plugins/inara.py"
Traceback (most recent call last):
  File "/home/[1000]edmc/EDMarketConnector.py", line 947, in <module>
    app = AppWindow(root)
  File "/home/[1000]/edmc/EDMarketConnector.py", line 322, in __init__
    self.postprefs(False)       # Companion login happens in callback from monitor
  File "/home/[1000]/edmc/EDMarketConnector.py", line 339, in postprefs
    if not monitor.start(self.w):
  File "/home/[1000]/edmc/monitor.py", line 121, in start
    logdir = expanduser(config.get('journaldir') or config.default_journal_dir)  # type: ignore # config is weird
  File "/usr/lib/python3.8/posixpath.py", line 231, in expanduser
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

Of course, I had to install "tk" and "python-semantic-version" to attempt the run.

**Comment by Athanasius** [comment]
I *think* this is a bad default_journal_dir.  Try editing `~/.config/EDMarketConnector/EDMarketConnector.ini` to set a 'journaldir' in it.

```
[config]
...
journaldir = <where you have the journal files>
```

Once something is set you should be able to change it on 'File' > 'Settings' > 'Configuration' > 'E:D journal file locations' if needs be.

**Comment by Athanasius** [comment]
Also it's best to run this command before trying to run from source:

```
pip3 install -r requirements.txt
```

**Comment by Athanasius** [comment]
In general how to run from source is documented at https://github.com/EDCD/EDMarketConnector/wiki/Running-from-source

Once we've confirmed a fix for it we'll put it in that `main` branch so you can download a fresh archive (or `git pull` if you're using that).

**Comment by Athanasius** [comment]
If you grab fresh source (please check the wiki page linked above, I've changed it to recommend using the stable branch) this should be fixed.

Please let us know if it doesn't work for you.

**Comment by MGM175** [comment]
I've managed to git-clone the fresh code; and error seems to be fixed now.

Thanks.

PS: I've ran the "pip install", but the only difference back then was asking me for the keyring. Error wasn't changed.

![obraz](https://user-images.githubusercontent.com/20325180/88581489-86bfd700-d04d-11ea-9dd3-fe34d947d985.png)

**Comment by Athanasius** [comment]
Good to know.

The `pip install` is just the easiest way to get the necessary python modules without guessing at things like Debian packages.

And we have an issue open to remove keyring as it's not actually used any more (used to be for storing the actual account name and password before Frontier gave us the oAuth2 authentication instead which makes it moot).
