### ISSUE TITLE
Switch to POST for edsy.org builds

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDMarketConnector#642]
edsy.org can take builds via POST, which will be less prone to browser issues:

> [21:53] taleden (EDSY): @Athanasius (EDMC/ed.miggy.org) haven't been keeping up so apologies if you already know this, but I saw the edsy mentions and wanted to clarify that since v3 there is indeed a (very minimal) server side component that you can POST imports to
> [21:54]Athanasius (EDMC/ed.miggy.org):ooooh, docs somewhere ?
> [21:55]taleden (EDSY):ah, heh, no formal docs, no :) but you just POST to edsy.org/import and put your capi/journal loadout data in a field called 'import'
> [21:55]taleden (EDSY):it can be plain text or gzip+b64

**Comment by A-UNDERSCORE-D** [comment]
After poking at this for a while, there isnt a way to do this from `webbrowser`, therefore it'd have to be a redirect like we already do for the "this link is too long for IE" approach

**Comment by Athanasius** [comment]
> After poking at this for a while, there isnt a way to do this from `webbrowser`, therefore it'd have to be a redirect like we already do for the "this link is too long for IE" approach

Or performing the query directly and then invoking `webbrowser` with the resultant link.  The edsy URLs are *not* just the compressed loadout... but I'm still not sure it's worth the effort, when we have the "go via a local file" workaround anyway.
