### ISSUE TITLE
Update certifi dep

### ISSUE THREAD

**Issue by A-UNDERSCORE-D** [EDCD/EDMarketConnector#643]
We currently have version 2019.9.11, and while I dont believe that it will cause an issue currently, its still prudent
to keep the cert store as new as possible, just in case there are any revocations that we dont know etc.

**Comment by Athanasius** [comment]
As I said on Discord, it's that version because of py2exe.  It errors out trying to find the cacerts.pem file with whatever was current when I was checking mid-June 2020.

See https://github.com/EDCD/EDMarketConnector/projects/6 (Python 3.8)

**Comment by Athanasius** [comment]
Is now done on `develop`.
