### ISSUE TITLE
Inara 400 Too much requests

### ISSUE THREAD

**Issue by FJRMaverick** [EDCD/EDMarketConnector#657]
EDMC prints error message: "Inara	400 Too much requests, slow down, cowboy. ;) If you are using multiple applications capable to access Inara API, please ensure that just ONE of them is updating your profile and so on. Also double-check that the same app is not running in multiple instances at once. The access to API was temporarily revoked (1 hour)."

This is also written to the log file.

I am not quite sure what triggers this error for the first time. But it seems to related with engineering (applying blueprints to modules).  After that it reappears every time I relog or dock at a station.

This happened more than once over the last two weeks.

EDIT: this is with EDMC version 4.0.3

**Comment by Athanasius** [comment]
We're aware of this, and have a fix.  I'll put together a 4.0.4 release this evening latest to address this.

**Comment by Athanasius** [comment]
https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F4.0.4 has just been published with the fix for this.

**Comment by FJRMaverick** [comment]
Nice thank you. Until now I had no problem.
