### ISSUE TITLE
INARA does not show the system from URL

### ISSUE THREAD

**Issue by radek3911** [EDCD/EDMarketConnector#667]
Hi, if you configure your EDMC to open Inara for systems it will open a blank page, I beleive the error is in this line of code:

https://github.com/EDCD/EDMarketConnector/blob/5083db991833c37ac6c6bd7c9a2cd5a422d2d553/plugins/inara.py#L69

where it's trying to pass a system number instead of system name. I have tested in with system name which works but does not work with system id.

Example: ERAVATE
https://inara.cz/galaxy-starsystem/?search=Eravate

vs
https://inara.cz/galaxy-starsystem/?search=4615

**Comment by radek3911** [comment]
Also note that on other line where it's referencing a station it's using a system_name
https://github.com/EDCD/EDMarketConnector/blob/5083db991833c37ac6c6bd7c9a2cd5a422d2d553/plugins/inara.py#L79

**Comment by Athanasius** [comment]
> Also note that on other line where it's referencing a station it's using a system_name
> 
> https://github.com/EDCD/EDMarketConnector/blob/5083db991833c37ac6c6bd7c9a2cd5a422d2d553/plugins/inara.py#L79

I believe *this* is correct, as the way EDMC looks up the station is to search for it within the system.  Certainly https://inara.cz/galaxy-station/?search=Rutena%20[Weitz%20City] works as expected.

**Comment by Athanasius** [comment]
And the system opening also works for me.  I'm in V2578 Ophiuchii and get the URL https://inara.cz/galaxy-starsystem/?search=V2578%20Ophiuchii which succeeds in displaying the system.

As for the id number version of that, the URL is *also* correct, but what you're seeing is a bug where the CAPI sometimes returns some *other* ID for a system, not the SystemAddress.  But, release 4.0.4 doesn't even *use* the CAPI's idea of SystemAddress.  So for you to see this with 4.0.4 you must be hitting a Journal bug and we need to see that Journal file to check.

Or, of course, you're not actually running 4.0.4 ?

**Comment by radek3911** [comment]
I am on 4.0.4 but I am not inside the bubble. Perhaps this is only reproducable on deep space systems?

**Comment by radek3911** [comment]
Oops this is not an issue with ED:MC because Inara does not have that system in DB.

**Comment by Athanasius** [comment]
Aha!  Presumably you have "Delay sending until docked" active on EDDN options, or it set to not send system and scan data ?

**Comment by radek3911** [comment]
> 
> 
> Aha! Presumably you have "Delay sending until docked" active on EDDN options, or it set to not send system and scan data ?

Nope I guess I was discovering the systems for first time and Inara haven't processed them yet. They usually show up on EDDB through. Thanks anyway :D
