### ISSUE TITLE
Implement kill switches

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDMarketConnector#668]
Not quite as scary as it sounds.

The idea is from EDDI.

Occasionally bugs crop up in how programs such as EDMC send to EDDN or use another API.  When we learn about such we obviously get a fix together ASAP and publish a new version, but that doesn't help where users, for whatever reason, stay on an older version.

So, implement kill switches.

1. The program will check at startup for the current list of kill switches (remote JSON/whatever file).
1. For any feature where there's a kill switch for the current version (SemVer comparisons!) disable that feature *and alert the user*.

Obviously this needs both core code and putting tentacles out into things like the internal plugins.

We could probably also use this to enforce using some minimum version of third-party plugins, but we don't yet have a way to get a version of a plugin cleanly.

**Comment by Athanasius** [comment]
NB: This should **not** be abused as a general "oh come on, upgrade!" mechanism outside of actual known issues with code.

**Comment by A-UNDERSCORE-D** [comment]
Should additionally have a method of overriding killswitches, for testing etc.

**Comment by A-UNDERSCORE-D** [comment]
This is implemented in develop as of #758
