### ISSUE TITLE
Doccument different weirdness the various APIs have 

### ISSUE THREAD

**Issue by A-UNDERSCORE-D** [EDCD/EDMarketConnector#669]
for example EDSM doesnt support every single journal event.

In the case of EDSM we should continue to send them as they're stored and reprocessed later. But the others may or may not. eg inara doesnt like near zero faction relations. So we may want to note that response only in debug logs

**Comment by Athanasius** [comment]
Cough #594

**Comment by A-UNDERSCORE-D** [comment]
Lol Im blind
