### ISSUE TITLE
Wiki: Add Linux TK requirement

### ISSUE THREAD

**Issue by grantek** [EDCD/EDMarketConnector#673]
I followed the install instructions for Linux on Debian Sid, but after installing requirements from pip, the main script failed to locate the tkinter module.

In Debian, this is packaged as python3-tk - installing that allowed the EDMC GUI to run.

This could be added as a note to the Linux install instructions, or to the instructions for running from source.

**Comment by A-UNDERSCORE-D** [comment]
Whoops, didnt close this, I have updated the wiki
