### ISSUE TITLE
Error message when docking at damaged station

### ISSUE THREAD

**Issue by pwerken** [EDCD/EDMarketConnector#698]
**Please complete the following information:**
 - Version: 4.1.0-beta4 (running form source, develop branch, 44353b6)
 - OS: Debian Linux (bullseye/sid)
 - OS Locale: English
 - [EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/5213814/EDMarketConnector.log)

**Describe the bug**
When I dock at the damaged station Tsiolkovsky Terminal in Gabjaujis, the EDMC status line reads:  `'list' object has no attribute 'values'`. This doesn't happen when docking at the nearby rescue ship.

**To Reproduce**
1. Go to the Gabjaujis system
2. Dock at Tsiolkovsky Terminal

**Expected behavior**
EDMC displays no error message.

**Additional context**
The [Journal.200913091022.01.log](https://github.com/EDCD/EDMarketConnector/files/5213815/Journal.200913091022.01.log) of the session.

**Comment by Athanasius** [comment]
So it doesn't only happen with Fleet Carriers -> #671 

Closing this in favour of that issue, please follow that one if interested.
