### ISSUE TITLE
4.1.0-beta5 can't start

### ISSUE THREAD

**Issue by arymkus** [EDCD/EDMarketConnector#711]
Checked Known Issues and Troubleshooting.

**Please complete the following information:**
 - Version 4.1.0-beta5
 - OS: Windows 10 1903
 - antivirus - Kaspersky EP, was turned on and later off to ensure it's not involved.
 - OS Locale: Russian
 - Browser: Firefox
 - Log file.
[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/5252518/EDMarketConnector.log)

**Describe the bug**
EDMC can't start after upgrade from 4.1.0-b4 to 4.1.0-b5.
Ship's loadout is generated properly

**To Reproduce**
1. While being docked to a Fleet Carrier saw the error about value isn't in list and decided to upgrade.
2. Closed EDMC app
3. Without exiting downloaded new msi
4. Installed new version and tired to start it

**Expected behavior**
App should start.

**Screenshots**
Can't make a screenshot of an app without any visible parts.

**Comment by Athanasius** [comment]
Presumably that's the EDMarketConnector.log from `%TEMP%` ?  If so, could you look in `%TEMP%\EDMarketConnector\` (note, this is a folder) and attach the relevant `EDMarketConnector.log` file from in there please.  It's the newer log file we're adding in 4.1.0 which always contains all the DEBUG logging.

**Comment by arymkus** [comment]
[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/5252533/EDMarketConnector.log)

**Comment by arymkus** [comment]
I also noted a difference in ship's loadout between what was created by 4.1.0-b4 and one by 4.1.0-b5:
![изображение](https://user-images.githubusercontent.com/19597706/93721444-13dc6380-fb99-11ea-931a-b3266686216e.png)

**Comment by Athanasius** [comment]
Well, then, it seems it's falling over on `locale.setlocale(locale.LC_ALL, (locale_startup[0], 'utf8'))` on your system, but in such a manner as to not log *anything* in either file about why it's falling over.

As a last ditch, could you open a command prompt, `cmd.exe`, navigate to where you have EDMC installed, and run `EDMarketConnector.exe` manually from there?  All the output should be redirected into the traditional log file, but let's see if anything useful shows up.

**Comment by arymkus** [comment]
Started as you requested, no difference.
Both log files are attached:
[%TMP%\EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/5252547/EDMarketConnector.log)
[%TMP%\EDMarketConnector\EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/5252548/EDMarketConnector.log)

**Comment by Athanasius** [comment]
So, no extra output in the cmd.exe window when you ran it that way ?

**Comment by arymkus** [comment]
Nothing:
![изображение](https://user-images.githubusercontent.com/19597706/93721750-ad584500-fb9a-11ea-9faa-d561d53ae264.png)

**Comment by Athanasius** [comment]
Hmmm, this is *ancient*, but might at least hint as to why no output... if the locale is set bad then all the output stuff also fails? <https://bugs.python.org/issue2173>

**Comment by Athanasius** [comment]
And annoyingly this works on my system (where I've never used Russian):
```py
>>> import locale
>>> locale.setlocale(locale.LC_ALL, ('Russian_Russia', 'utf8'))
'Russian_Russia.utf8'```

**Comment by arymkus** [comment]
Just to confirm the issue is with my locale - what's the way to force EDMC to run in default language?

**Comment by Athanasius** [comment]
> Just to confirm the issue is with my locale - what's the way to force EDMC to run in default language?

Set the 'language' registry key (in the EDMC keys of course) to an empty string.  *But* this should have nothing to do with it, because that functionality of EDMC isn't even set up at this stage, and has nothing to do with this, it just controls where the internal string translation looks for the translations.

**Comment by arymkus** [comment]
It's already empty.
I just updated the python3 (system wide install on my system) version to 3.7.9, nothing changed.

**Comment by Athanasius** [comment]
So it doesn't get lost, @A-UNDERSCORE-D found this, which *might* be relevant:

https://stackoverflow.com/questions/61935980/process-finished-with-exit-code-1073740940-0xc0000374

**Comment by A-UNDERSCORE-D** [comment]
Just as a note, this did work and fixed the issue

**Comment by arymkus** [comment]
Confirmed.

**Comment by Athanasius** [comment]
So, we'll need to document this in Troubleshooting on Wiki. I'll do that shortly.

**Comment by Athanasius** [comment]
I've looked into this further and it's possible I've found a method for us to tell Windows we're a Unicode-aware application.  Thus could you please:

1. **Undo** that configuration change (untick the box, reboot).
1. Try this new executable (replace the real one with it) and report back: [EDMarketConnector-utf8-codepage.zip](https://github.com/EDCD/EDMarketConnector/files/5255452/EDMarketConnector-utf8-codepage.zip)

NB: This claims to be 4.1.0-beta6 but isn't actually -beta6, I just wanted it to be easy for you to be sure which file you're running.

Thanks!

**Comment by arymkus** [comment]
Disabled beta windows setting and rebooted my PC.
Old exe isn't starting, as it is expected to.
Downloaded, unpacked and executed not-beta-6 ;)
It has started correctly!
![изображение](https://user-images.githubusercontent.com/19597706/93803824-177df200-fc4e-11ea-9d1b-d008b1c60788.png)

**Comment by Athanasius** [comment]
NB: Version shows as 4.1.0-beta5 because @arymkus still has the beta5 library.zip and its version of config.py.  It's not baked into the binary.

**Comment by AndrewdAzotus** [comment]
I seem to have this problem on Win 8.1Pro, there is not a beta tick box in the region settings work around for Win-10

**Comment by A-UNDERSCORE-D** [comment]
@AndrewdAzotus We're tracking this in #736
