### ISSUE TITLE
Clipboard on Linux/Wine

### ISSUE THREAD

**Issue by alexzk1** [EDCD/EDMarketConnector#724]
OS: Linux, Elite running latest wine-staging.

Problem is right-click link in window and selecting copy.
It works once for Elite/wine. Next don't. However, native guis DO PASTE PROPER 2nd copy, if I paste in native GUI and then copy from native gui it "restores" python copy for 1 more copy. So chain python copy, gui copy, python copy works to paste into Elite.
That can be because Linux has 3 different clipboards. Native GUIs could just join info from them as 2 are for consoles. However Elite/wine have no idea about that and paste something prior copied.
Copy - paste from any native gui to elite works ok. For your python code only each 1st. Pasting into native gui works always too.

**Comment by Athanasius** [comment]
Are you running *EDMC* under Wine?  If so, why?  It runs natively from source on Linux, and that's a supported way to run it.  Running it under Wine isn't supported at this time.

**Comment by alexzk1** [comment]
No, I run EDMC native, Elite is in wine. So copy is from native edmc to elite wine works once. Then elite keeps pasting 1st copy. However native gui will paste latest proper at the same moment.

**Comment by A-UNDERSCORE-D** [comment]
Which clipboard are you trying to get data into? your secondary (IIRC) clipboard is what elite will be able to understand. And the clipboards are _not_ joined by default on most installs. Primary goes to middle mouse button, secondary is what people think of when they want ^C ^V.

**Comment by alexzk1** [comment]
Have no idea which, i right click link into EDCM window. And select copy. It seems it uses wrong method.

**Comment by A-UNDERSCORE-D** [comment]
Okay. Tell me what you _expect_ to happen, in detail, step by step. Just actions you take, dont tell me what clipboard you think is used or what have you.

**Comment by alexzk1** [comment]
Doing

xsel -b -c

which clears clipboard makes next link copy/paste to work.

What I do:
![image](https://user-images.githubusercontent.com/4589845/94682514-ba5cfd00-032d-11eb-810a-c30166ad8f29.png)

Select copy, then paste on map in elite. That works once.
If prior clicking copy I clear cb using
xsel -b -c
then copy works again once.

**Comment by A-UNDERSCORE-D** [comment]
Does it work as expected with the system location below your ship name?

**Comment by alexzk1** [comment]
No, upper link broken too.

**Comment by A-UNDERSCORE-D** [comment]
Okay. To be clear, what do you mean by "it breaks"? Does pasting break, copying? does it not update your clipboard? As I said. I need a step by step of what you _want to see_ not what happens. I still dont understand what you're trying to report, because you skipped our bug report format. Please tell me: What you wanted to happen, in order, step by step. Then what _actually_ happened. Don't assume I can read your mind and understand exactly what you mean by "It doesnt work"

**Comment by A-UNDERSCORE-D** [comment]
From my side, if I rclick and hit copy, data updates into my clipboard and I can paste it wherever, I can copy other data and still get the correct update if I ^C again.

**Comment by alexzk1** [comment]
Lets say I copied 1 system, it pastes OK in elite and everywhere.
Then I copy 2nd system. Elite keeps pasting 1st system. Anything else, like chrome browser or console window pastes 2nd system at the same moment.

**Comment by A-UNDERSCORE-D** [comment]
That sounds more like a wine issue than an EDMC issue. But give me a moment And I'll test this

**Comment by A-UNDERSCORE-D** [comment]
Okay, that I can confirm. And by native gui you mean anything other than EDMC, yes?

**Comment by alexzk1** [comment]
Yes, not-python programs.
Because I suppose, there is small chance that python itself do something wrong.

**Comment by A-UNDERSCORE-D** [comment]
I dont believe its python, its possibly wine (you can see this yourself, do the copy, use `xclip -sel c -o` to dump your clipboard, then copy the next one, its updated correctly). Im investigating possible fixes.

**Comment by A-UNDERSCORE-D** [comment]
Im inclined to say this is an ED issue, because its _only_ ED that has this problem. If I run notepad++ in wine for example it works fine. The clipboard is being updated correctly by tkinter, as shown by the above commands.

**Comment by alexzk1** [comment]
Well, xsel -b -c prior copy fixes that. Maybe you can just add 'clean clipboard" prior "copy to" call?

**Comment by A-UNDERSCORE-D** [comment]
We already clear the clipboard before writing to it

**Comment by alexzk1** [comment]
Weird. Then maybe problem is in clear method. Somehow elite don't get notified.

**Comment by A-UNDERSCORE-D** [comment]
Not our code. And regardless, its elite not correctly requesting the data, or something in wine (but unlikely as it works fine in N++ as mentioned). EDMC is setting the data correctly.

**Comment by alexzk1** [comment]
I would agree, but not. Any other program copies to Elite ok, so that is something EDMC/python or both differently do then Qt5 for example.

**Comment by A-UNDERSCORE-D** [comment]
Regardless. Not us. Not in any way we can detect or fix. We are doing everything correctly as we can. the clipboard data is being set correctly as far as X is concerned. Thats all the control we have over this.

**Comment by alexzk1** [comment]
Can you link please line, where copy happens? 
I'm not so good with python to find meself

**Comment by A-UNDERSCORE-D** [comment]
https://github.com/EDCD/EDMarketConnector/blob/main/ttkHyperlinkLabel.py#L109

**Comment by alexzk1** [comment]
Ok, found. Problem is into ttinter or whatever it is
https://stackoverflow.com/questions/579687/how-do-i-copy-a-string-to-the-clipboard-on-windows-using-python/4203897#4203897

```
def copy(self):
        # self.clipboard_clear()
        # self.clipboard_append(self['text'])
        clipboard.copy(self['text'])
```

**Comment by alexzk1** [comment]
need to use "clipboard" module

pip install clipboard

**Comment by alexzk1** [comment]
Just a thought: 

I see, that gui library do access to clipboard as self. this means each widget may have own copy >: And this means...bad.
While clipboard. do access to single global object.

**Comment by A-UNDERSCORE-D** [comment]
Okay. Tkinter is our UI library. It is a Python stdlib library.

We are not going to switch to a different lib for an issue that _isnt even our doing_. Especially not a lib which only calls into another lib (pyperclip), which can do a bunch of different methods for clipboards, including _using GTK and Qt_ **or just executing arbitrary binaries and hoping they do what it wants**

**Comment by alexzk1** [comment]
As I said I'm not expert in python.
Just pointing that tkinter is broken OR wrong used.
You could try to make simple test with 1 widget - nothing more, which copies something to CB and if it can be pasted to Elite. If it works then... problem is in instancing somehow. Too many of them OR not enough persistent. In Linux copier owns CB, i.e. if copier closed then CB is cleared. On Windows system owns it, so CB is persistent.

**Comment by A-UNDERSCORE-D** [comment]
This is an ED issue. EDMC and Tkinter are setting the clipboard fine.
