### ISSUE TITLE
TypeError: category LC_ALL is not supported

### ISSUE THREAD

**Issue by pwerken** [EDCD/EDMarketConnector#725]
**Please complete the following information:**
 - Version: v4.1.0-rc1 (running from source 25ee03a)
 - OS: Linux Debian testing/bullseye
 - OS Locale: English
 - Please attach log files:
     1. There does not seems to be a `%TEMP%\EDMarketConnector.log`.
     1. `%TEMP%\EDMarketConnector\`[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/5306906/EDMarketConnector-debug.log) was present
   
**Describe the bug**
EDMarketconnector.py wil not start when LC_* environment variable(s) are set.
Last error message is `TypeError: category LC_ALL is not supported`.

**To Reproduce**
1. cd to the source directory
2. Start EDMarketConnector.py from the commandline
3. See error below "Screenshots"

**Expected behavior**
EDMarketConnector starts normally.

**Screenshots**
```
$ ./EDMarketConnector.py
2020-09-30 18:29:59.777 - INFO - EDMarketConnector.__main__:1096: Startup v4.1.0-rc1 : Running on Python v3.8.6 (default, Sep 25 2020, 09:36:53)
[GCC 10.2.0]
2020-09-30 18:29:59.783 - DEBUG - EDMarketConnector.__main__:1097: Platform: linux
argv[0]: ./EDMarketConnector.py
exec_prefix: /usr
executable: /usr/bin/python3
sys.path: ['/usr/local/src/EDMarketConnector', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/home/pwerken/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/dist-packages', '/usr/lib/python3/dist-packages']
2020-09-30 18:29:59.784 - DEBUG - EDMarketConnector.log_locale:1061: Locale: Initial Locale
Locale LC_COLLATE: (None, None)
Locale LC_CTYPE: ('en_US', 'UTF-8')
Locale LC_MONETARY: ('en_US', 'UTF-8')
Locale LC_NUMERIC: ('en_US', 'UTF-8')
Locale LC_TIME: ('en_US', 'UTF-8')
2020-09-30 18:29:59.784 - DEBUG - EDMarketConnector.log_locale:1061: Locale: After LC_ALL defaults set
Locale LC_COLLATE: (None, None)
Locale LC_CTYPE: ('en_US', 'UTF-8')
Locale LC_MONETARY: ('en_US', 'UTF-8')
Locale LC_NUMERIC: ('en_US', 'UTF-8')
Locale LC_TIME: ('en_US', 'UTF-8')
Traceback (most recent call last):
  File "./EDMarketConnector.py", line 1111, in <module>
    locale_startup = locale.getlocale(locale.LC_ALL)
  File "/usr/lib/python3.8/locale.py", line 590, in getlocale
    raise TypeError('category LC_ALL is not supported')
TypeError: category LC_ALL is not supported
```

**Additional context**
```
$ env | grep '\(LC\|LANG\)'
GDM_LANG=en_US.utf8
LANG=en_US.UTF-8
LC_COLLATE=C
```
Oddly, despite the `LC_COLLATE` environment variable being set, EDMarketConnector reports it as None.
If I unset `LC_COLLATE` EDMarketConnector does start.

**Comment by Athanasius** [comment]
Checking documentation some more, it does look like we should probably be using LC_CTYPE there.  It certainly works for me on Windows with Python 3.7.9, and you have LC_CTYPE including language there.

The purpose of the code is to find your language so we can then re-set it, but with definitely UTF-8 encoding.

-rc2 will be out this evening or tomorrow with this tweaked.

As for the LC_COLLATE... it's possible something in the python/locale code treats 'C' as 'None', because it *is* the default.

However, I feel I need to caution you that running under other than Python 3.7 is untested in general at this time, and using Debian testing (but at least you're not using unstable) might be asking for trouble.

**Comment by arwkin** [comment]
I am using a similar environment as pwerken, but am using Manjaro Linux.  LC_COLLATE is not defined, so his work around to unset it does not work for me. I've looked into downgrading to Python 3.7, but it will cause issues with other programs.

$ env | grep '\(LC\|LANG\)'
LC_ADDRESS=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_MONETARY=en_US.UTF-8
GDM_LANG=en_US.utf8
LC_PAPER=en_US.UTF-8
LANG=en_US.utf8
LC_IDENTIFICATION=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_NUMERIC=en_US.UTF-8


$ ./EDMarketConnector.py
2020-09-30 16:50:23.749 - INFO - EDMarketConnector.__main__:1096: Startup v4.1.0-rc1 : Running on Python v3.8.5 (default, Sep  5 2020, 10:50:12) 
[GCC 10.2.0]
2020-09-30 16:50:23.762 - DEBUG - EDMarketConnector.__main__:1097: Platform: linux
argv[0]: ./EDMarketConnector.py
exec_prefix: /usr
executable: /usr/bin/python3
sys.path: ['/data/Games/EDMarketConnector', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/home/arwkin/.local/lib/python3.8/site-packages', '/usr/lib/python3.8/site-packages']
2020-09-30 16:50:23.762 - DEBUG - EDMarketConnector.log_locale:1061: Locale: Initial Locale
Locale LC_COLLATE: ('en_US', 'UTF-8')
Locale LC_CTYPE: ('en_US', 'UTF-8')
Locale LC_MONETARY: ('en_US', 'UTF-8')
Locale LC_NUMERIC: ('en_US', 'UTF-8')
Locale LC_TIME: ('en_US', 'UTF-8')
2020-09-30 16:50:23.762 - DEBUG - EDMarketConnector.log_locale:1061: Locale: After LC_ALL defaults set
Locale LC_COLLATE: ('en_US', 'UTF-8')
Locale LC_CTYPE: ('en_US', 'UTF-8')
Locale LC_MONETARY: ('en_US', 'UTF-8')
Locale LC_NUMERIC: ('en_US', 'UTF-8')
Locale LC_TIME: ('en_US', 'UTF-8')
Traceback (most recent call last):
  File "./EDMarketConnector.py", line 1111, in <module>
    locale_startup = locale.getlocale(locale.LC_ALL)
  File "/usr/lib/python3.8/locale.py", line 590, in getlocale
    raise TypeError('category LC_ALL is not supported')
TypeError: category LC_ALL is not supported

**Comment by Athanasius** [comment]
No need to downgrade for *this*, it was more of a general warning.

I have a fix that involves using LC_CTYPE instead of LC_ALL in that line of code.

**Comment by Athanasius** [comment]
@pwerken As you're running from source (and cited a git short hash), could you please try the fix in https://github.com/EDCD/EDMarketConnector/tree/fix/725-locale-LC_ALL-invalid ?

**Comment by pwerken** [comment]
@Athanasius EDMarketConnector.py starts nicely on the fix-branch.

For completeness the stdout:
```
/usr/local/src/EDMarketConnector
$ git l -2
* 3063b23 2020-10-01 (HEAD -> fix/725-locale-LC_ALL-invalid, origin/fix/725-locale-LC_ALL-invalid) Locale: Use LC_CTYPE as source of language for setting UTF-8 encoding
* 25ee03a 2020-09-29 (tag: Release/4.1.0-rc1, origin/release-4.1.0-rc1, origin/main, origin/develop, origin/beta, origin/HEAD, develop) Another minor format edit to Changelog
/usr/local/src/EDMarketConnector
$ ./EDMarketConnector.py
2020-10-01 12:10:18.566 - INFO - EDMarketConnector.__main__:1096: Startup v4.1.0-rc1 : Running on Python v3.8.6 (default, Sep 25 2020, 09:36:53)
[GCC 10.2.0]
2020-10-01 12:10:18.573 - DEBUG - EDMarketConnector.__main__:1097: Platform: linux
argv[0]: ./EDMarketConnector.py
exec_prefix: /usr
executable: /usr/bin/python3
sys.path: ['/usr/local/src/EDMarketConnector', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/home/pwerken/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/dist-packages', '/usr/lib/python3/dist-packages']
2020-10-01 12:10:18.573 - DEBUG - EDMarketConnector.log_locale:1061: Locale: Initial Locale
Locale LC_COLLATE: (None, None)
Locale LC_CTYPE: ('en_US', 'UTF-8')
Locale LC_MONETARY: ('en_US', 'UTF-8')
Locale LC_NUMERIC: ('en_US', 'UTF-8')
Locale LC_TIME: ('en_US', 'UTF-8')
2020-10-01 12:10:18.573 - DEBUG - EDMarketConnector.log_locale:1061: Locale: After LC_ALL defaults set
Locale LC_COLLATE: (None, None)
Locale LC_CTYPE: ('en_US', 'UTF-8')
Locale LC_MONETARY: ('en_US', 'UTF-8')
Locale LC_NUMERIC: ('en_US', 'UTF-8')
Locale LC_TIME: ('en_US', 'UTF-8')
2020-10-01 12:10:18.573 - DEBUG - EDMarketConnector.__main__:1112: Locale LC_CTYPE: ('en_US', 'UTF-8')
2020-10-01 12:10:18.573 - DEBUG - EDMarketConnector.log_locale:1061: Locale: After switching to UTF-8 encoding (same language)
Locale LC_COLLATE: ('en_US', 'UTF-8')
Locale LC_CTYPE: ('en_US', 'UTF-8')
Locale LC_MONETARY: ('en_US', 'UTF-8')
Locale LC_NUMERIC: ('en_US', 'UTF-8')
Locale LC_TIME: ('en_US', 'UTF-8')
E:D Market Connector 4.1.0-rc1
```
