### ISSUE TITLE
4.1.0 fails to start on Windows 7,8,8.1

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDMarketConnector#736]
**Please complete the following information:**
 - Version 4.1.0
 - OS: Windows 7, 8, 8.1
 - OS Locale: Russian_Russia
[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/5332836/EDMarketConnector-debug.log)

**Describe the bug**
Application fails to start.

This is almost certainly pre-10 Windows not supporting the Unicode codepage manifest element, so not starting with UTF-8 encoding, and then falling over when we try to set it explicitly.

**Comment by mas1701** [comment]
Problem exists also on Windows 10 Pro v1709 (system is locked to this build)

Region / Display format: English (Germany)
System locale for non-unicode programs: English, United States

The  checkbox "Beta: Use Unicode UTF-8 for worldwide language support" as desribed in Wiki/Trouleshooting is NOT present, can neither check nor uncheck.

Application appears in Task Manager only for  tiny fraction of a second, then vanishes again, no Window opening.

**Comment by sgb** [comment]
Getting the same thing on Win7 for English (Australia).  EDMC isn't giving me a log though, or I'd attach it.  Reverting to 4.0.6 works fine.

**Comment by Athanasius** [comment]
> Problem exists also on Windows 10 Pro v1709 (system is locked to this build)

I note that https://support.microsoft.com/en-gb/help/13853/windows-lifecycle-fact-sheet says you'll be out of any sort of support in a week's time.

> Region / Display format: English (Germany)
> System locale for non-unicode programs: English, United States
> 
> The checkbox "Beta: Use Unicode UTF-8 for worldwide language support" as desribed in Wiki/Trouleshooting is NOT present, can neither check nor uncheck.

The little documentation I can find for that option suggests it was added much later than version 1709.

**Comment by A-UNDERSCORE-D** [comment]
As an update to the above, it was added (I believe) in 1903.

**Comment by TowersTony** [comment]
Version 4.1.0
OS: Win7 HP SP1 64 bit
OS Locale: en-gb;English (United Kingdom)
[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/5333982/EDMarketConnector.log)

**Comment by sgb** [comment]
Confirming what I said in discord, 4.1.1 works for me - thanks!

**Comment by mas1701** [comment]
> I note that https://support.microsoft.com/en-gb/help/13853/windows-lifecycle-fact-sheet says you'll be out of any sort of support in a week's time.

Yes, that may be, but I don't care! I don't follow Microsoft's policy of enforcing "Feature Updates" unless I'm convinced the horrible Windows upgrade installation process is actually worth the trouble. By that I mean the balance of solving problems and improving Windows vs. introduction of new bugs and the need to re-activate (DRM) several software products manually after each "Feature Update" (Windows Upgrade) installation. So thank you, no thanks. ;-)

A remark to all who didn't get it: Microsoft claims Windows 10 to be a "final version", so "10" could possibly stay forever. In reality, ever "Feature Update" installs a completely new OS as an upgrade. If you have the lastest upgrade from May 2020 installed, you're in fact using Windows 10.9 by old versioning conventions. Would you have manually installed so many OS upgrades when you were still running Windows 7 or 8, with even normal updates still being voluntary?

Not to mention that Windows 7 support has already ended quite some time ago. But I don't see any remarks on that here ...

> Can all of you for whom 4.1.0 wouldn't run please try https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F4.1.1

I can confirm that 4.1.1 and 4.1.2 do start successfully. Thanks for all the efforts.

May I suggest to not unconditionally rely on new OS features in the future?
