### ISSUE TITLE
4.1.0 msi installs - but doesn't run in wine lutris-5.7-8x86_64

### ISSUE THREAD

**Issue by dudib3tccc** [EDCD/EDMarketConnector#737]
...as above - I had to revert to previous version 4.06

**Comment by Athanasius** [comment]
If you're running on Linux then why not just run natively from source ?

**Comment by dudib3tccc** [comment]
It's for convenance sake and i simply don't know how to do it ;) I'd like to run ED and EDMC with a windows batch file simultaneously as this has been working with the previous version.

**Comment by A-UNDERSCORE-D** [comment]
Its far easier to run from source on linux.

setup, need only be done once:
```
git clone https://github.com/EDCD/EDMarketConnector/
python3 -m venv venv
source ./venv/bin/activate
pip install -r requirements.txt
```
To execute every time,  `./EDMarketConnector.py` is all you need

That all said, if you truly want to use us in wine. Please provide logs so we can figure out what broke.

**Comment by A-UNDERSCORE-D** [comment]
Will need the EDMC logs from within the wine prefix lutris is using, looks like that is `/home/dudib3tccc/Games/EliteDangerous/drive_c`, within there should be a users folder, followed by AppData/local/Temp. In there should be an EDMarketConnector.log, and within a directory called EDMarketConnector should be another log file. Please give us both of them. Also, for the native python version of EDMC, you will want to find the journal directory within the above prefix to get EDMC to work correctly,

**Comment by dudib3tccc** [comment]
[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/5334472/EDMarketConnector.log)
got this from ~/Games/EliteDangerous/drive_c/users/dudib3tccc/Temp/
the EDMarketConnector-debug.log file in the EDMarketConnector Folder within Temp is an empty file

**Comment by A-UNDERSCORE-D** [comment]
Ah okay, that we know how to fix. But that will work fine if you run EDMC locally.

**Comment by dudib3tccc** [comment]
Being able to help is always a pleasure - Keep up the good work ;)

**Comment by A-UNDERSCORE-D** [comment]
> Being able to help is always a pleasure - Keep up the good work ;)

No problem! Also feel free to hop into discord, I'd be happy to help you get it running without wine. We can probably even get a shell script to launch the lutris version of the game as well as edmc like your batch file does.

**Comment by Athanasius** [comment]
Please test https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F4.1.3 to confirm it fixes this for you.

**Comment by dudib3tccc** [comment]
I'm on a vacation trip right now sorry-- no machina! will test this as soon as i'm home again - this will be approx monday evening \o/

**Comment by A-UNDERSCORE-D** [comment]
@dudib3tccc This good to close or does this remain an issue?

**Comment by dudib3tccc** [comment]
This is good to close, all problems solved.
