### ISSUE TITLE
Fonts look ugly in transparent mode

### ISSUE THREAD

**Issue by FJRMaverick** [EDCD/EDMarketConnector#739]
Since the new scaling is implemented the font looks quite ugly in transparent mode.
This maybe is related to Issue #734.

![image](https://user-images.githubusercontent.com/57774924/95243886-8c862580-0811-11eb-9f91-5f2c12f99d41.png)

if not in transparent mode it looks fine:
![image](https://user-images.githubusercontent.com/57774924/95243979-a889c700-0811-11eb-888a-27c1627a995b.png)

**Comment by FJRMaverick** [comment]
I seems to be a problem of the used font. I deleted EUROCAPS.TTF and the problem is gone:

![image](https://user-images.githubusercontent.com/57774924/95246409-bb51cb00-0814-11eb-91ef-8745918ad2a7.png)

**Comment by FJRMaverick** [comment]
The problem also disappears, when setting the internal UI-scaling to any other value than 100%.
Following screenshot taken  with internal UI-scaling set to 110%

![image](https://user-images.githubusercontent.com/57774924/95250967-23a3ab00-081b-11eb-96ad-3360aa89575b.png)

**Comment by FJRMaverick** [comment]
The problem also disappears, when setting the internal UI-scaling to any other value than 100%.
Following screenshot taken  with internal UI-scaling set to 110%

![image](https://user-images.githubusercontent.com/57774924/95250967-23a3ab00-081b-11eb-96ad-3360aa89575b.png)

**Comment by FJRMaverick** [comment]
btw: setting the internal scaling to any other value than 100% also removes the blurry mentioned in Issue #734

**Comment by Athanasius** [comment]
We'll be reverting the use of gidScaling in the next release, no ETA just yet.
