### ISSUE TITLE
Automated download and install, installs again when you use keyboard to click the install button

### ISSUE THREAD

**Issue by alski** [EDCD/EDMarketConnector#741]
- Version 4.1.2
 - OS: Windows 10
 - OS Locale: English
 - If applicable: Browser [e.g. chrome, safari]
 - Please attach log files:
Nothing in the log files
> 2020-10-07 12:47:30.591 - INFO - monitor.EDLogs.worker:343: We're not meant to be running, exiting...
> 2020-10-07 12:47:31.282 - INFO - EDMarketConnector.__main__:1204: Exiting
> <=== Upgrade here ???
> 2020-10-07 12:47:45.116 - INFO - EDMarketConnector.__main__:1096: Startup v4.1.2 : Running on Python v3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:01:55) [MSC v.1900 32 bit (Intel)]
  
**Describe the bug**
When you have downloaded the next version, you are presented with UI to install the download. If you hit the spacebar you should be clicking the Install button, but the focus hasn't moved from the now hidden Download button, so you download again. 
Note, haven't tried tabbing to move focus. Instead I used the mouse to install which worked as expected.

**To Reproduce**
1. Wait to be prompted about a new update
2. Click on Download 
3. When downloaded, press space

**Expected behavior**
Focus should have moved to the Install button

**Screenshots**
Will update at the next release

**Additional context**
...

**Comment by Athanasius** [comment]
The behaviour I see is slightly different.  If I manually trigger an update check (from the Help menu) then, despite it looking like focus is on the 'Install' button, tapping the space bar closes the update window.

I note, however, that hitting the Return or Enter key instead does trigger the Install process.

This is true either of the initial popup with the changelog details *and* the subsequent window once download has completed.

What leads you to believe that Space Bar should activate a highlighted button?  The documentation I find only mentions it selecting or clearing a checkbox if one is focused: https://support.microsoft.com/en-us/help/12445/windows-keyboard-shortcuts

In any case, the whole update checking and installation process isn't our code.  We use the WinSparkle library and if there is a bug it will be in their code.

**Comment by alski** [comment]
If it's not your code, then there isn't much you can do. :-)

For further reading, and apologies in advance for the link to a massive page... You'll need to read down about 4 pages before you get to the Space Bar 
[https://docs.microsoft.com/en-us/windows/uwp/design/input/keyboard-interactions#custom-experiences-and-efficient-keyboarding](https://docs.microsoft.com/en-us/windows/uwp/design/input/keyboard-interactions#custom-experiences-and-efficient-keyboarding).

Also, you are correct that Space triggers checkboxes, but it should also "interact" with whatever control has focus. CheckBoxes get checked, Buttons get pushed. This is slightly different to the Return/Enter as this should interact with the button that is marked as the default operation of the form/window/dialog, usually the "Ok" button, and the escape key which should interact with the cancel operation usually "Cancel".

Of course all of this is just a windows standard, no one has to implement it, and lots of libraries and apps don't, but it also helps for people who can't use a mouse etc.

Thanks for investigating anyway
