### ISSUE TITLE
UI Scale again

### ISSUE THREAD

**Issue by alexzk1** [EDCD/EDMarketConnector#750]
Version is "git pull", just did 5 mins ago.
Not sure what you mean by "UI scale 200%" but what I see on Linux:
![image](https://user-images.githubusercontent.com/4589845/95559956-38ea2680-0a21-11eb-9c7d-33e665643fda.png)

That is normal scale:
![image](https://user-images.githubusercontent.com/4589845/95560033-54553180-0a21-11eb-98fa-d236a1af00fd.png)

What I expected, window will be twice bigger of everything with 200%.

**Comment by Athanasius** [comment]
1. If you're using git then tell us the 'HEAD' you're on, so we can be sure of which branch you're using.  `git rev-parse HEAD`
1. You've decided not to use the [Bug Report Template](https://github.com/EDCD/EDMarketConnector/issues/new?assignees=&labels=bug%2C+unconfirmed&template=bug_report.md&title=) so we're missing lots of potentially useful information.

**Comment by alexzk1** [comment]
git rev-parse HEAD
5f6f81cdf2e19ee0f965114ec3aa5aad4109c403

**Comment by alexzk1** [comment]
I was doing changes like copy-paste implementation and cursor. So it's different then yours
![image](https://user-images.githubusercontent.com/4589845/95563082-a1d39d80-0a25-11eb-9182-bd64780fd322.png)

**Comment by alexzk1** [comment]
git status
On branch stable
Your branch is ahead of 'origin/stable' by 4 commits.
  (use "git push" to publish your local commits)

**Comment by Athanasius** [comment]
In that case please reproduce this with a pure checkout of our `main`.

If you're doing any local changes they should be in a branch of your own so you can easily switch.

**Comment by alexzk1** [comment]
Made fresh clone, same picture:

git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

**Comment by alexzk1** [comment]
git checkout stable
Branch 'stable' set up to track remote branch 'stable' from 'origin'.
Switched to a new branch 'stable'

Same picture

**Comment by Athanasius** [comment]
What exact OS, and version of it, are you using?  There's a reason the Bug Report template asks for all the information that it does.

You didn't provide the exact steps you're using to see this bug, i.e. you *are* remembering that an EDMC restart is required for changes to the selected UI scale to take effect ?  I'm asking this in particular because your screenshots appear to show the scaling being inverted, which would happen if you're on 100% scale, select 200%, and don't restart, and then restart and select 100%, but are still on 200%.

**Comment by alexzk1** [comment]
uname -a
Linux moy-super 5.7.9-arch1-1 #1 SMP PREEMPT Thu, 16 Jul 2020 19:34:49 +0000 x86_64 GNU/Linux
ython --version
Python 3.8.3
pip --version
pip 20.1.1 from /usr/lib/python3.8/site-packages/pip (python 3.8)


Yes, i select 200 from 100 and do restart. Nothing changes without restart at all

**Comment by Athanasius** [comment]
And, once more I ask for more information **that would have been provided if you'd used the Bug Report template in the first place**:

1. `${TMP}/EDMarketConnector.log`
1. `${TMP}/EDMarketConnector/EDMarketConnector-debug.log`

**Comment by alexzk1** [comment]
[Uploading EDMarketConnector-debug.log…]()

**Comment by alexzk1** [comment]
Scroll down it, it has from yesterday my attempts to fix another guy plugin.

**Comment by alexzk1** [comment]
[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/5353790/EDMarketConnector-debug.log)
Not sure if it uploaded in post above, seems not

**Comment by Athanasius** [comment]
Please:

1. git fetch
1. git checkout fix/750-linux-ui-scaling
1. Run with 200% scaling already set.
1. Attach a new -debug log file from that run.

**Comment by alexzk1** [comment]
[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/5354435/EDMarketConnector-debug.log)
Same small screen

**Comment by alexzk1** [comment]
git status
On branch fix/750-linux-ui-scaling
Your branch is up to date with 'origin/fix/750-linux-ui-scaling'.

**Comment by Athanasius** [comment]
```py
2020-10-09 13:54:03.860 - DEBUG - EDMarketConnector.__main__:1171: Scaling:
default_ui_scale: 1.4023464458247066
scale_factor: 2.0
new_scale to set: 2.804692891649413
2020-10-09 13:54:03.860 - DEBUG - EDMarketConnector.__main__:1177: Scaling: tk-scaling after changing: 2.798898071625344
```
So we're definitely setting tk-scaling to approx 2x what it was at program start.  This can only be a Tk bug with whatever version you're using.

We literally only do:

```py
root.tk.call('tk', 'scaling', new_scale)
```
after making the root window and before adding anything to it.  I'll see about making a small program to reproduce this.

**Comment by Athanasius** [comment]
Please clone https://github.com/Athanasius/tk-scaling and then run the start-50-100-200.sh script and show us the resultant windows.

**Comment by alexzk1** [comment]
![image](https://user-images.githubusercontent.com/4589845/95577562-0a794500-0a3b-11eb-914e-9a5afc500b65.png)

**Comment by Athanasius** [comment]
Yup, TK scaling is going backwards on your system for some reason.  This is not something we can fix.  Report it upstream (initially to Arch devs by the looks of it?).

**Comment by Athanasius** [comment]
Well, here's the weird thing about the tk-scaling and Linux ... it works perfectly on my system.

So it's not just it being totally screwy with Xorg.

That's with Debian Buster (10.6, current stable), which has Xorg 1:7.7, and I'm using fvwm 1:2.6.8 as my window manager.  Two 2560x1440 displays (108x107 dpi) as separate X screens, nvidia binary drivers (418.152.00).  I have no special settings in my xorg.conf.  Attaching for reference.
[xorg.conf.txt](https://github.com/EDCD/EDMarketConnector/files/5358832/xorg.conf.txt)

To be clear, that's both EDMarketConnector.py scaling as it should *and* the tk-scaling test program also scaling properly.

**Comment by alexzk1** [comment]
Ok then, not a big deal. I use lxqt as desktop. It has separated emulation for gtk and custom themes over qt which emulates for gtk too.
That how Linux works. Maybe somewhere in chain tcl emulation is broken. I'm not really sure what is it though. I tend to use qt-based solutions as I understand how that gui works.
