### ISSUE TITLE
Can't install the newest version of EDMC

### ISSUE THREAD

**Issue by D4VID-B** [EDCD/EDMarketConnector#751]
- Version: Release 4.1.3 
 - OS: Windows 10
 - OS Locale: English
 - If applicable: Browser Chrome
 - Please attach log files:
     1. EDMarketConnector-debug.log/EDMarketConnector.log - Doesn't exist in %TEMP%

   
  Also, I'm sorry, but this -> `_`, `|` and `^` doesn't make sense to me. Is it that supposed to be the "Reference an Issue or PR" button?

**Describe the bug**
I had an older version of EDMC. I downloaded the .msi for the latest version and ran it. It started to do stuff (including overriding the old version I think) and then told me that it didn't have access to ProgramFiles(x86)\EDMarketConnector and couldn't install. Turns out I don't have access to the folder either ("Access Denied" message pops up) and its properties say it's empty.

**To Reproduce**
1. Download latest version (4.1.3 atm)
2. Run .msi
3. See error

**Expected behavior**
New version is installed and the program runs

**Screenshots**
The error message when installing: ![EDMC_1](https://user-images.githubusercontent.com/48723686/95690766-0a6a7800-0be8-11eb-973d-90ed646539dd.PNG)
The Error message when trying to open the folder: ![EDMC_2](https://user-images.githubusercontent.com/48723686/95690769-0e969580-0be8-11eb-9dc2-7e158d61367b.PNG)
What inspecting the Properties shows: ![EDMC_3](https://user-images.githubusercontent.com/48723686/95690770-0fc7c280-0be8-11eb-859c-4e008fda670b.PNG)

**Additional context**
I think the easiest solution for this might be an option to choose were to install EDMC, but idk

**Comment by A-UNDERSCORE-D** [comment]
Appears you have permissions issues on your system unrelated to EDMC. Try setting the folder not to read only.

**Comment by Athanasius** [comment]
The folder Read-Only is almost certainly a red herring.  It's a weirdness of Windows/NTFS.

But, still, yes, this appears to be a permissions problem unrelated to our installer.

1. Is our installer actually causing a UAC prompt for the necessary permissions ? 
1. IIRC the folder *should* end up owned by SYSTEM due to the UAC elevation.

**Comment by Athanasius** [comment]
Reference for the Read-Only Folder thing.  Basically for folders it isn't actually a Read-Only flag, it's a "use (or not) the desktop.ini file for that folder to customise the view" flag.

> When a folder has the Read-Only attribute set it causes Explorer to request the Desktop.ini of that folder to see if any special folder settings need to be set. 

https://support.microsoft.com/en-us/help/326549/you-cannot-view-or-change-the-read-only-or-the-system-attributes-of-fo

**Comment by D4VID-B** [comment]
How do I check for the UAC pro-
Nevermind! I ran the .msi again to make sure I understood what UAC meant and everything just ... worked. 
I didn't even restart my computer, just put it to sleep, but everything seems to be good now.
Thank you both for the help! Should I close the issue or is it best done on your end?

**Comment by Athanasius** [comment]
I'd wonder if you either missed/accidentally dismissed the UAC prompt first time, or some Anti-Virus got in the way.

Glad to hear it's now worked, closing.
