### ISSUE TITLE
Can’t open my Imperial Cutter build in Coriolis EDCD Edition

### ISSUE THREAD

**Issue by Kiyos** [EDCD/EDMarketConnector#767]
- Version: 4.1.4
 - OS: Windows 7 SP1
 - OS Locale: Russian
 - Browser: Google Chrome 86.0.4240.111, Mozilla Firefox 71.0, Opera 71.0.3770.284
 - [EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/5432983/EDMarketConnector.log)
 - [EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/5432985/EDMarketConnector-debug.log)

**Describe the bug**
Opening my current Imperial Cutter ship build in Coriolis EDCD Edition (https://coriolis.io/) by clicking on the ship’s name in the main program window results in a “Failed to import ship” error in browser.
The URL is as follows:

`https://coriolis.io/import?data=H4sIAC4zlF8C_81YbW_bNhD-K4Y-u4JIvftbGjdNNmf1Yq8FNgwCI9E2F5nUKCqpF-S_7yi5jmS5lewaaPMhsRnewyOfe-6OfDZuRVKkNDdGfz0bF-u1uOGXKcuMERpuv16LLKPSGOGh8Y4vGadUMr40Rs_G27SgGXxRN2OYjwPfRo7vDF_HfyNraoyMW5bH0YQtV-oT1b-NVyT47x1ZD-ZkVRvUcLZlIWQNjQl9pKkxAlRwlC0YlZWrE3Kvx41bkueGnpbnN_l7IZLS8w-SARRJPxJwBUZMe2hsP1um7bih_TJ8xbjhii4lU5s9IKsF5LimtUPCvmnpH_zy99D4vSCpRgD8wA5fhsaNomvAXmUqWlGicsYfUlLweEVlpAopqYoU43rJD9wYKVnQoTGVTMgKZWjMUqEAYA6TrolMMgEHigztd4MmvM8T0j714ir4GbmyTLfGFbJt5zSqbKtGFQpMq8USbrKUpSRfk_KYE7qgPKan84RLnrbgcaEUkB6L-CFj6itAaAc0W7Hscju3hrLWOiUyJnIp7skmEUJ-BQrvoC715Gui4tUBf4hci0JGS0kSijq9uihn12Fgm9GygB0zwjPxRCUcIAzl7D9qd8JNtcFUG5SQHcHq-bbnhe1grcyiecFp0gzUqRQLCA8hB1NgnLcDFmOtkc-gGLamXJH03WJBY-1antGYkTSiFXiqVfC000LLIpqIGJbIwQPgTkkGKkwGY_HEjZ0i3O9ShOfUItn1TTeEn-A0VSDckIUFOtDpopEOS27Gkjx1ehaYaIcVmnbo1WGqA_-QKbYm6YGNtp3DbsM7jD0t20OQUyoXQq4JiLR7y1Zjy_gg5jWk6Dui6JGlxG3mfqSh6_rYxpDWRBDFkGBy3JlIbgnjlVN5X22EBxL51WwMocmXd4QvaVMcVzRlMaw6uCIy10PtdG51qWORJ7quPW66RaG5H9wSTpblUmfRRNAMY6fJ6RF6aIhLBwd2Agt5p-nBMsNXLNOy3ToMEHKUGPxG3Dq2i0FhYWh1hNxqA2Qkkj1WYedXYed2ht2VhLiB2rNQY23cJ_R0DxHax_YQb1maDuaF5IcCz6r1EfZ3RYiN68QiE-s8h06MEt0_7MAC_CUFf5OIlEEFKrJMSFVnojsBTMBwVhn2TAC-faA4VmHLcihJ94USMroGLq4k_beA3mbT5GS-ooPxE03Tg8kg6EoGZflPakv9-KKJvDr9jtnoIj9R6PN4fkkyEvfqJev024DcqsBbxDsar6Dn6i5Kdi1TuKaHtJbaVam_h7i-XeyYnvYwPIDY20NsOq9bNh3X9xobnm1yCPVzOrhF_C4H91r80PObmmwFqham11eY-4rqlSMdCwTaVueMcuhOz5Al3fNlSc90XS84OUla9csxVKtG9av2O9fMqllM-AVfpvS4SxzWkE2GgWC7yXBerpMfl3HvSEJad5tFQVNF-EM9RrovNldgNQerfbTy3iZJ_FBvBruvXfqPhaKZtjknJO4D6R0FaZeQ3jkhnRpkdxUM8IEqCB0NTZP3FHREtODLFqwsPA25TSgbXK5oAeDt-td5VczLRX62quebDtaPHKeI2atXPBc12-v-DTHk6KDWEbvYR0GjEu_oOaY1dp16WnAt3_R0c-cdBIZzhluYWnWihs0rBYabsS5SexnH0_43Ek650HIXYEdVlDLK3T7CcY8SjldCuueE9PtAOkdBBiWk0_Oq4R6S9w9_rqzrBGqpHZz4XOn79cue9-W6slfuXNwMvkQKTmPBlRRpFAvo32PFBK8e4SounH5BGJZc2N-mFx1DL7JKSFSHTCgkwEjpJ8eIwq5oJ9JYWxzAoJ-zVEgqj4HBbZhYrO-J0mhUqn4ojTPKCJzSP-I-2j6qLoo0XVNVIpfP8Z0PoRrgF3G_f_D6MRVwskwKEq_yos8mp5WN3FxszWalWQ35UbCYZprOR7oNy29DfoSgpelHbWboYNSP07snZKP6XkrU3X5OoN7BhF9v3iB0uZ2w1eofPKESLGEUlFdOmwiSiHIEsj_NFVlrdGxh6w2y3mBnjuy`

Importing the same ship from an [auto-exported JSON file](https://github.com/EDCD/EDMarketConnector/files/5432993/Undercut.2020-10-24T00.00.31.txt) works fine, although generates a different Coriolis URL.

**To Reproduce**
1. Paste the URL I provided into any browser
2. Observer the error

**Expected behavior**
Seeing my build without any errors.

**Screenshots**
Coriolis screenshot: ![coriols_cutter_error](https://user-images.githubusercontent.com/5103155/97084007-9931b880-161c-11eb-887a-ecc61d51efb9.png)
(Some lines won’t fit no matter how wide the window is.)

**Other information**
Coriolis itself is working fine for me, and I can successfully open my other ships in it using the same function.

**Comment by A-UNDERSCORE-D** [comment]
This is a known bug with super-long URLs (Like the ones we use to export to coriolis and EDSY), we have a workaround in the settings. Go to settings, configuration, and check the "Use alternate URL method" button.

**Comment by Kiyos** [comment]
The workaround is functional, thank you.
