### ISSUE TITLE
RSA Fingerprint

### ISSUE THREAD

**Issue by dinotheextinct** [EDCD/EDMarketConnector#771]
**Please complete the following information:**

Linux

Cloning into 'EDMarketConnector'...
The authenticity of host 'github.com (140.82.121.4)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com,140.82.121.4' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

**Describe the bug**
Cant install from source, RSA fingerprint problem.

**To Reproduce**

**Expected behavior**
Installing from github

**Screenshots**

**Additional context**

**Comment by Athanasius** [comment]
This isn't an EDMC problem.  I would guess you've not told GitHub any public key to match a private key of yours.

But, it's also irrelevant to cloning our repo.  Just use the HTTPS option instead: https://github.com/EDCD/EDMarketConnector.git
