### ISSUE TITLE
Update our Actions for more-secure GH defaults

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDMarketConnector#784]
Ref: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

Currently one of the actions fails for dependabot PRs.

**Comment by Athanasius** [comment]
I don't *think* we're directly affected by this, and would be seeing warnings if any of the stuff we use in workflows was a problem ?

**Comment by A-UNDERSCORE-D** [comment]
IIRC this was prompted by dependabots own stuff using those features, I took a quick glance and dont see us using those at all
