### ISSUE TITLE
i cant login

### ISSUE THREAD

**Issue by ByGarNi17** [EDCD/EDMarketConnector#788]
i just installed it and it doesn't show me anything to login with my account i have been searching and i didnt found a single thing, if you can help me it would be great

**Comment by Athanasius** [comment]
You're attempting to make a Bug Report.

You have failed to find, or specifically bypassed, the Bug Report Template.

You might find that one of the scenarios, and possible fixed, are outlined in our Troubleshooting doc: https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting

If that is not the case then please open a new issue using https://github.com/EDCD/EDMarketConnector/issues/new?assignees=&labels=bug%2C+unconfirmed&template=bug_report.md&title= and fill out all the required information.
