### ISSUE TITLE
change other browser not default

### ISSUE THREAD

**Issue by unknown-program** [EDCD/EDMarketConnector#797]
Make it possible to select the browser through which it works.
Not touch my default browser.
For windows platform.

**Comment by Athanasius** [comment]
You're going to have to explain your suggestion a bit better than that.

**Comment by Athanasius** [comment]
We're not going to attempt to implement anything that necessitates us trying to enumerate the available browsers and offer the user a choice as to which EDMC uses.  It will simply always use the 'system default' as decided by the python `webbrowser` module.
