### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by JamesMoth** [EDCD/EDMarketConnector#801]
- Version: 4.1.4
 - OS: Windows 10
 - OS Locale: Poland
 - Browser: Mozilla Firefox
 

The program seems to crash as soon as it is opened

[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/5675262/EDMarketConnector.log)
[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/5675263/EDMarketConnector-debug.log)

**Comment by Athanasius** [comment]
If you mean "the window for the app never opens", then please check you don't have a lingering EDMarketConnector.exe process, as there's a known bug we're trying to track down where sometimes the process doesn't shutdown properly.
