### ISSUE TITLE
Document how to bundle additional python modules with a plugin.

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDMarketConnector#818]
Ref:

>  KAZAK0V [CEC R&D]:If you already have your's plugin dir, with load.py inside, you just need to create subdir, with any name you want (i suggest add to name yours plugins's name, to evade conflicts with others plugins), and drop to that dir all modules you need, plus add file __init__.py, to mark subdir as dir with modules
After that, you can do in code something like

```python
from plugin_folder import foo
Import plugin_modules.foo [as foo]
#in case of sub sub dirs, let's say you droped to your plugins_modules dir full package with PIL (image processing library)
from plugin_folder.PIL import bar
```

> and so on
> Please, keep in mind, i took that code from my memories, not my github, and that code samples may or may not be broken

**Comment by A-UNDERSCORE-D** [comment]
Should use relative imports (`from . import xxx`), and yes the dir will probably need an `__init__.py` to mark it as a module

**Comment by inorton** [comment]
The folder that a plugin's `load.py` is inside is added to sys.path, so you can put modules and packages in the same folder easily, eg:
```
my-plugin/load.py
my-plugin/some_module.py
my-plugin/a_package/__init__.py
```

**Comment by inorton** [comment]
> Should use relative imports (`from . import xxx`), and yes the dir will probably need an `__init__.py` to mark it as a module

the `__init__.py` file makes it a package, a "module" is a single file that is either in the current directory, in a folder in sys.path, in a folder inside $PYTHONPATH or inside a package

**Comment by A-UNDERSCORE-D** [comment]
>the __init__.py file makes it a package, a "module" is a single file that is either in the current directory, in a folder in sys.path, in a folder inside $PYTHONPATH or inside a package

Correct. I misspoke. However my point stands, especially if at any point we want to stop plugins from relying on that (such as in a more strict plugin system https://github.com/EDCD/EDMarketConnector/projects/9 )

**Comment by Athanasius** [comment]
> The folder that a plugin's `load.py` is inside is added to sys.path, so you can put modules and packages in the same folder easily, eg:

Yes, but then you might be at the mercy of an earlier-loaded plugin (it's sys.path.append) having a different version of the same python module, which might not work with your code.  Hence, I think, @VAKazakov 's suggestion to:

1. Have the module be in a sub-directory with a name unique to your plugin.
2. Import it in a manner that should guarantee loading *that* copy, not another.

**Comment by VAKazakov** [comment]
> The folder that a plugin's `load.py` is inside is added to sys.path, so you can put modules and packages in the same folder easily, eg:
> 
> ```
> my-plugin/load.py
> my-plugin/some_module.py
> my-plugin/a_package/__init__.py
> ```

thought, if you have many modules, root dir will became mess



> Should use relative imports (`from . import xxx`)
that should do a trick, but i never used that method)
> and yes the dir will probably need an `__init__.py` to mark it as a module

i mentioned that in original message :)

**Comment by Athanasius** [comment]
It turns out that the way we load 'found' (third-party) plugins is incompatible with `from . import some_module`, even with an empty `__init__.py` file which should otherwise be enough to make it work.

But it works with the `from EDMC_my_plugin import some_module` form.

The following is what I'll add in some form to PLUGINS.md.  If there are any comments it'll be easier for me to open a PR and discuss such there.

---

# Introduction
EDMarketConnector's Windows installs only package a minimal set of modules. All of the 'stdlib' of Python is provided, plus any modules the core application code uses and a small number of additional modules for the use of plugins.  See [Plugins:Available imports](https://github.com/EDCD/EDMarketConnector/blob/main/PLUGINS.md#available-imports) for a list.

As such if your plugin requires additional modules you will need to package them with your plugin.  There is no general Python interpreter in which to rely on [pip](https://pypi.org/project/pip/) to install them.

## Environment

It will be easier of you are using a Python [virtual environment](https://docs.python.org/3/library/venv.html) for actually testing the plugin.  This is so that you can be sure it is working *because* you have copied all the correct Python modules inside your plugin, and not because they are installed within the Python site-packages in some applicable location (system level or user level).

So, setup a virtual environment to use when running EDMarketConnector code to test your plugin, and use the 'system' non-virtual Python to install modules in order to have somewhere to copy them from.

NB: If you use PyCharm it's possible to have it do the work of [creating a virtual environment](https://www.jetbrains.com/help/pycharm/creating-virtual-environment.html) for your project.

## Install the modules for the system Python 
Technically you could also do this within an additional virtual environment. If they were in your plugin testing virtual environment then you can't be sure you have all the necessary files copied into your plugin so it will work within a vanilla Windows EDMarketConnector install.

We'll use `xml_dataclasses` for this example.

    pip install xml_dataclasses

## Copy the module files into your plugin directory

1. Assuming it's a 'simple' module with no caveats, now we copy:
  1. `pip show xml_dataclasses` - `Location` is where it was installed.
  1. If you have a POSIX-compliant command-line environment:

         cp -pr <Location> <plugin_dir>

  or just use Windows File Explorer, or other GUI means, to copy.

## Your plugin directory name **must** be importable
You're going to have to refer to your plugin directory in order to import anything within it.  This means it should be compatible with such.

1. Do **not** use hyphens (`-`) as word separators, or full-stops (`.`).
1. You can use underscore (`_`) as a word separator.

So:

 - `EDMC-My-Plugin` **BAD**.
 - `EDMC.My.Plugin` **BAD**.
 - `EDMC_My_Plugin` **GOOD**.

NB: No, you can't use `from . import xml_dataclasses` because the way EDMarketConnector:plug.py loads 'found' plugins prevents this from working.

## Test the module import

Add an import of this module to your plugin code:

    from EDMC_My_Plugin import xml_dataclasses

If you're lucky you won't have the "surprise!" of learning your chosen extra module itself requires other modules.  If you are gifted such a surprise then you will need to repeat the [Copy](#copy-the-module-files-into-your-plugin-directory) step for the extra module(s) until it works.

**Comment by Athanasius** [comment]
See https://github.com/EDCD/EDMarketConnector/pull/1072

**Comment by Athanasius** [comment]
PR merged.
