### ISSUE TITLE
Linux - Running for Source - ImportError: cannot import name 'OrderedDict'

### ISSUE THREAD

**Issue by cpeosphoros** [EDCD/EDMarketConnector#822]
**Please complete the following information:**
 - Version commit 4883c1606bc867d1a4e5984b2d5fa2530daddbcc (HEAD -> refs/heads/stable, refs/remotes/origin/stable)
 - OS: Linux Mint 19.3 Tricia base: Ubuntu 18.04 bionic
 - OS Locale: English
 - Browser: Not applicable
 - Please attach **BOTH** log files as follows: Not applicable

**Describe the bug**
`$ ./EDMarketConnector.py`
```Traceback (most recent call last):
  File "./EDMarketConnector.py", line 178, in <module>
    import prefs
  File "/home/chronos/elitedangerous/EDMarketConnector/prefs.py", line 21, in <module>
    from monitor import monitor
  File "/home/chronos/elitedangerous/EDMarketConnector/monitor.py", line 10, in <module>
    from typing import Any, Optional, OrderedDict as OrderedDictT, Tuple, TYPE_CHECKING, Union
ImportError: cannot import name 'OrderedDict'
```
`$ ./EDMC.py`
```Traceback (most recent call last):
  File "./EDMC.py", line 38, in <module>
    import stats
  File "/home/chronos/elitedangerous/EDMarketConnector/stats.py", line 16, in <module>
    from monitor import monitor
  File "/home/chronos/elitedangerous/EDMarketConnector/monitor.py", line 10, in <module>
    from typing import Any, Optional, OrderedDict as OrderedDictT, Tuple, TYPE_CHECKING, Union
ImportError: cannot import name 'OrderedDict'
```

**To Reproduce**
Followed all instructions from "Running from source".
Package python3-tk is installed.
`pip3 install -r requirements.txt` Successfully installed certifi-2019.9.11 chardet-4.0.0 idna-2.10 requests-2.25.1 semantic-version-2.8.5 urllib3-1.26.2 watchdog-1.0.2

**Expected behavior**
Should run without the Import Error?

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Athanasius** [comment]
Please tell us the output of `/usr/bin/env python3 --version`

**Comment by cpeosphoros** [comment]
Python 3.6.9

**Comment by cpeosphoros** [comment]
Should be 3.7, right? Sorry for not checking that beforehand. I'm in the process of upgrading my python version.

**Comment by Athanasius** [comment]
We've never supported Python 3.6.x.  Support went from the old Python 2.7-based version straight to Python 3.7.x.

I'd suggest checking if you can get a later version of Python on that version of Mint, else upgrading to the latest Mint.  A quick check shows that Mint 19.3 being based on Ubuntu 18.04 indeed means it only has Python 3.6.x.
