### ISSUE TITLE
Cannot Connect to EDDN

### ISSUE THREAD

**Issue by snarkyone** [EDCD/EDMarketConnector#832]
Version 4.1.5
Unable to connect to EDDN

Opened TCP Port 4430 in Firewall

Both Log files attached.
[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/5782917/EDMarketConnector.log)
[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/5782918/EDMarketConnector-debug.log)

**Comment by Athanasius** [comment]
EDDN looks to be running OK.  Despite saying you've opened port 4430 in your firewall I'd advise you to double-check that (look in the firewall's logs).  This is very clearly just a failure to connect to eddn.edcd.io on port 4430.

**Comment by snarkyone** [comment]
![image](https://user-images.githubusercontent.com/7718132/103927180-eedc1400-50e7-11eb-90dd-2085773deda6.png)

That's not it.

**Comment by snarkyone** [comment]
Not sure if this is pertinent, but I had a VERY old version up till a few months ago.  And instead of uninstalling, I just updated it.
Could that have left some conflicting issue in a registry key that doesn't get removed on uninstall?

**Comment by Athanasius** [comment]
The only registry setting related to sending to EDDN is the one that would stop the code from even trying to.

The logs you have provided are literally saying:

`urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='eddn.edcd.io', port=4430): Read timed out. (read timeout=10)`

i.e. your connection to EDDN isn't returning any response inside of 10 seconds.  For reference `eddn.edcd.io` should resolve to `151.80.235.144`.

**Comment by snarkyone** [comment]
![image](https://user-images.githubusercontent.com/7718132/103928835-627f2080-50ea-11eb-957e-65e4da20aa69.png)

I mean I hear what you're saying but if I'm hitting the right IP and I'm showing that the outgoing port is working.. then it's clearly something else.

**Comment by A-UNDERSCORE-D** [comment]
An IP can respond to a ping and still not return data when asked for HTTP info.

**Comment by snarkyone** [comment]
The point was to demonstrate that I am resolving to the right IP.   I demonstrated in the previous post that outgoing port 4430 is open.

**Comment by Athanasius** [comment]
What happens if you literally try to go to `https://eddn.edcd.io:4430/` in your web browser on the same machine ?  It should result in something like:

```
Error: 404 Not Found

Sorry, the requested URL 'https://eddn.edcd.io:4430/' caused an error:

Not found: '/
```

**Comment by snarkyone** [comment]
I get an "ERR_CONNECTION_RESET" in Chrome instead of an action 404 page.   Which in my mind means they must be filtering something or somehow it's restricting partial traffic.   I have another router coming today to replace the pos one from the service provider, I spent an hour with them yesterday trying to get router logs and they clearly know less than a 12 year old with a fortnite addiction.    I'll update once it's in place and at least we know it won't be a router issue.

**Comment by snarkyone** [comment]
Update:  New Router, ports open. 

Still cannot connect to EDDN

One change, when I go to https://eddn.edcd.io:4430/ I am getting the 404 error like you show, as opposed to the ERR_CONNECTION_RESET like I was getting.   

Not sure if this is helpful.

**Comment by snarkyone** [comment]
Out of Curiosity I tried running my internet through my phone direct to the computer and it still could not connect to EDDN. 
I can only assume something is wrong with the installation, or somehow something is stopping it from working, maybe a conflicting app?  

Any suggestions welcomed at this point not sure what else to check.

**Comment by A-UNDERSCORE-D** [comment]
Anti-Virus, Firewall, Anything running locally could be stopping your connection to eddn. Hell the EDDN guys may have an IP ban on you or similar.

**Comment by Athanasius** [comment]
My only two thoughts are:

1. Again, firewall/anti-virus.  Even if you think you're not using one, check.  Although I note the Windows Firewall doesn't actually seem to have an entry on my setup, and it works.
2. Yes, remove "Elite Dangerous Market Connector" from Apps on Windows, then re-install again using the 4.1.5 msi and see if it magically starts working.

The EDMC code is obviously trying to make the connection.  It's not getting a 'connection refused' back, but is timing out on receiving any response.  Something is stopping either its packets from going out or the reply coming back.

**Comment by Athanasius** [comment]
> Anti-Virus, Firewall, Anything running locally could be stopping your connection to eddn. Hell the EDDN guys may have an IP ban on you or similar.

Except @snarkyone reported the in-browser test working, so it can't be an IP ban.

**Comment by snarkyone** [comment]
No Anti-Virus, No other Firewalls.

**Comment by snarkyone** [comment]
I have attempted several reinstalls even tried the 4.1.6 rc2

**Comment by snarkyone** [comment]
Welp, I got frustrated so I thumbed around in the registry till I found all the configuration data, wiped it out, deleted everything in appdata as well and uninstalled, also clearly temp folders.

That seems to have done it.

**Comment by A-UNDERSCORE-D** [comment]
Thats... Even stranger -_-

**Comment by snarkyone** [comment]
For reference I deleted HKEY_CURRENT_USER\Software\Marginal
If I wasn't as frustrated I probably would have done one of those at a time so not sure what was the ultimate solution.  
Could have been the registry entry, could have been something in the temp folder, though I doubt it.

**Comment by snarkyone** [comment]
Welp, issue has returned.  Not sure if it working yesterday helps figure out what's wrong, but at least we know for 100% certainty it's not a network issue.

**Comment by A-UNDERSCORE-D** [comment]
As far as we can tell, it isnt us either. Something else must be going on.

**Comment by snarkyone** [comment]
I think something about the application, it's installation, or registry or something on my specific machine is the issue, but short of wiping it completely from registry and disk, I'm not sure how else to resolve it.
I don't suppose you have a removal tool or something to remove every registry entry?

**Comment by A-UNDERSCORE-D** [comment]
Nope but you pretty much got them all -- We keep most things under `Software\Marginal` and `Software\EDCD\`, there's also a URL handler and some stuff for our update engine

**Comment by Athanasius** [comment]
The EDMC code is clearly initiating the connection.  The specific code that's doing that is within the core Python code, not ours.  1,000s of other EDMC users don't have this issue.

The only other thing I can suggest is seeing if https://github.com/EDCD/EDMarketConnector/wiki/Running-from-source helps, but I'd be very surprised if it (**consistently**) does.  It will be the exact same python `libssl-1_1.dll` code that ends up getting called to make the connection.

**Comment by snarkyone** [comment]
Are there any dependencies I could check?   I'd rather not try to mess with running for source especially if it's the same thing. 
I tried removing again, but noticed that I can't seem to shutdown EDMC on it's own anymore.   
Not sure if this is helpful to the overall problem I'm having, and I know it's specific to me, no worries there. 

`
The program EDMarketConnector.exe version 4.1.6.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 Process ID: 41cc
 Start Time: 01d6e82ba13722ba
 Termination Time: 14
 Application Path: C:\Program Files (x86)\EDMarketConnector\EDMarketConnector.exe
 Report Id: aad0575a-19cc-474b-b2d5-2ca66ec1b599
 Faulting package full name: 
 Faulting package-relative application ID: 
 Hang type: Unknown`

**Comment by snarkyone** [comment]
I also noticed this error... prior to today's changes 
`svchost (9052,R,98) TILEREPOSITORYS-1-5-18: Error -1023 (0xfffffc01) occurred while opening logfile C:\WINDOWS\system32\config\systemprofile\AppData\Local\TileDataLayer\Database\EDB.log.`

**Comment by A-UNDERSCORE-D** [comment]
Thats a bug we're working on right now. But its unrelated to your issue.

**Comment by snarkyone** [comment]
This didn't start until today, before now it always closed just fine.   Not sure if there's a loose connection or why this would happen all the sudden.

**Comment by Athanasius** [comment]
> This didn't start until today, before now it always closed just fine. Not sure if there's a loose connection or why this would happen all the sudden.

That's what @A-UNDERSCORE-D was referring to.  It's because the whole of EDSM is down.  I'm working right now on the fix/workaround.  So we don't need to know anything else, for now, about the application hanging during shutdown.

**Comment by snarkyone** [comment]
Ohh okay sorry.
