### ISSUE TITLE
A script for easy integration with SteamPlay

### ISSUE THREAD

**Issue by pan-mroku** [EDCD/EDMarketConnector#833]
**Describe the enhancement**

I think it would be nice to have a script that we could easily introduce into steam launch options that will run the connector.

**Considered workarounds**

I'm attaching [my quick hack](https://github.com/EDCD/EDMarketConnector/files/5783848/venvandlog.txt) for that.
In order to use it save the file as `venvandlog.sh` in your EDMarketConnector directory, enable execution permission and put `<EDMarketConnector_dir>/venvandlog.sh; %command%` into steam launch options of the game.

**Additional context**

I assume that since the connector has external requirements some users might want to use virtualenv.

**Comment by A-UNDERSCORE-D** [comment]
virtual env definitely. Not entirely sure we want to include this and support it. Personally I am no bash wizard even though I daily drive linux :D. That said, interesting idea

**Comment by Athanasius** [comment]
On the whole I'm not inclined to include such a script with the application as it just adds support load to us whilst probably not being of that much interest to most users.

It's something that you could post over in https://github.com/EDCD/EDMarketConnector/discussions/categories/show-and-tell
