### ISSUE TITLE
Cleanup monitor shutdown code

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDMarketConnector#834]
As per https://github.com/EDCD/EDMarketConnector/issues/678#issuecomment-756463931 we at least have some code running when it shouldn't during shutdown.

1. Move the
```
            # Check whether we're still supposed to be running
            if threading.current_thread() != self.thread:
                logger.info("We're not meant to be running, exiting...")
                return  # Terminate
```
to the top of the `while True` it's in.  Although it being directly after the sleep() **should** mean this is moot.  We might also want to be more paranoid in the main logfile reading loop.  That *should* exit when it hits end of file, then cause the sleep and checks and going around the loop again.  But what if we trigger shutdown whilst it's in the middle of reading a new set of lines ?

2. As monitor.stop() does things like `self.currentdir = None` we should check for that kind of state in any other monitor related code that could be triggered outside of the monitor.worker() thread.  In theory we should be able to trigger off of `self.thread is None`.  Candidates are `EDMarketConnector.AppWindow.journal_event()` and `monitor.get_entry()`.
3. Check for any old style debug printing and convert to logging. e.g. in monitor.stop()
```
        if __debug__:
            print('Stopping monitoring Journal')
```

**Comment by A-UNDERSCORE-D** [comment]
Possibly do 1 in both places? rather than hope we catch both sides?

**Comment by Athanasius** [comment]
4. We might want to re-consider the order of shutdown calls in EDMarketConnector.py.  Mostly, do we perhaps want to shutdown plugins *first* ?  Doing them first risks something in their shutdown code hanging, but it's not like the core EDMC code will be needing to save any persistent state.  Doing them later risks them depending on something we've already shutdown.

**Comment by A-UNDERSCORE-D** [comment]
plugin teardown being first makes sense logically, obviously we can have the hang as you mentioned. But it leaves us an opening to do other teardown that depends on plugins not existing (Not that we have anything as of yet, but it means we can make assumptions about messing with `monitor`, for example).

Honestly what we could also do, to be "sure" is to start up a shutdown thread that forces us to die (in some way, I havent really thought about how :D perhaps asking the OS to kill us?) if we're still hanging around after x seconds

**Comment by Athanasius** [comment]
> Honestly what we could also do, to be "sure" is to start up a shutdown thread that forces us to die (in some way, I havent really thought about how :D perhaps asking the OS to kill us?) if we're still hanging around after x seconds

Whilst that would indeed clear the issue for users it would also hide the underlying problem so that we'll have even fewer reports and logs to check for ideas in finally tracking down the root cause.  So that's a no for the time being.

**Comment by Athanasius** [comment]
Done and released in https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F4.1.6-rc2
