### ISSUE TITLE
Suppress message when double running EDMC

### ISSUE THREAD

**Issue by norohind** [EDCD/EDMarketConnector#848]
**Describe the enhancement**

Add an option for suppress window that showing when you try to start EDMC when EDMC was already started

**Expected behavior**

I want to have an option (something like checkbox in settings, CL flag) that will let suppress window which showing when you double start EDMC. Instead of showing this window new EDMC should silently close. Already started EDMC should continue work like nothing happened.

**Considered workarounds**

Don't start new EDMC when already have one. It is a good choice but not in any case (see Additional context).

**Additional context**

*What for?*
I run elite dangerous and EDMC from bat file. Elite dangerous launcher starting with parameters that let me fully skip interactive with it and launcher just do it own work - launch game, after exit from game launcher automatically closing but EDMC don't do it.
This is beautiful to click one file and after a bit of time get the main menu of the game. But if I forgot to close EDMC from a previous game session it gives me a window that I can't start second EDMC. If EDMC already running let new one silently close.

**Comment by alterNERDtive** [comment]
As a different solution for your specific issue, there are various ways that you can make tools start with the game when you start it, without explicitly running them through e.g. a batch file.

I’m using [this AHK script of mine](https://github.com/alterNERDtive/ahk-joystick-focus) which technically has a different main purpose, but you can probably get the gist anyway.

There is probably also a way to check if an EDMC process is already active before trying to run it in your batch file and not run it if it already is.

**Comment by Athanasius** [comment]
@norohind please try out https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F4.1.7-rc1 (see the changelog there for the CL argument you need to use).
