### ISSUE TITLE
Populate state['CargoJSON'] with StartUp

### ISSUE THREAD

**Issue by RemainNA** [EDCD/EDMarketConnector#855]
**Describe the enhancement**

When the StartUp event is sent `state['Cargo']` is populated and available to use, but `state['CargoJSON']` is not.  Change this so it is included in the state dictionary immediately at start up.

**Expected behavior**

`state['CargoJSON']` can be accessed by plugins during the StartUp event

**Considered workarounds**

Read the file directly, or set a flag that EDMC was started after the game and try to get the info with each event until successful.

**Additional context**

Looking around monitor.py, `state['CargoJSON']` only appears to be updated for some Cargo events, not all.  This would seem to negate the second considered workaround above as once the plugin receives a Cargo event the full inventory is made available, but not before.

**Comment by Athanasius** [comment]
> **Considered workarounds**
> 
> Read the file directly, or set a flag that EDMC was started after the game and try to get the info with each event until successful.

This is down to how Frontier have designed it.  The first `Cargo` event in the journal, on logging in, is fully within the Journal file, and not written to the Cargo.json file.  We could probably just blindly load the file (assuming the user didn't remove it, and this isn't the first login for the Cmdr) as there shouldn't be any way for it to be 'behind' **EXCEPT** that's going to break in the multi-Cmdr case, as the contents will be for a previous Cmdr if you switch.  We could also try just faking it from that initial in-Journal full `Cargo` event.

This will take some careful thinking about, and the answer in the end might just be "CargoJSON is only populated *when* we naturally load the file from a Journal file event indicating we should, users should program accordingly".

**Comment by Athanasius** [comment]
Note that the 'faking it' case does really break the promise we make about CargoJSON, that it is precisely the raw data loaded from Cargo.json, not processed further by us in any manner.

**Comment by A-UNDERSCORE-D** [comment]
Yeah I'd really rather not fake it, it'd cause far more issues than its worth. I'd be all for reading it at start if we could be sure that it wouldnt break with multi-cmdr, but until it contains a name we can never be sure.

**Comment by Athanasius** [comment]
We will not be faking this.  But I'll leave the issue open as a reminder to *document* this wrinkle about that data.

**Comment by Athanasius** [comment]
Documented in 4658b267fb38817ae26938f0af071bc3ed03e876
