### ISSUE TITLE
EDMC.exe failed to create a shipyard file

### ISSUE THREAD

**Issue by Eventure-TCE** [EDCD/EDMarketConnector#868]
Hello Athan,
I have to report an issue with EDMC.exe when using the -s parameter:
![grafik](https://user-images.githubusercontent.com/78804889/107376173-e06b8880-6ae9-11eb-994e-2988cb70f896.png)

Here is the output as requested (with the -d parameter):
[test.txt](https://github.com/EDCD/EDMarketConnector/files/5951910/test.txt)

And here is the log:
[EDMC-debug.log](https://github.com/EDCD/EDMarketConnector/files/5951966/EDMC-debug.log)

**Comment by Athanasius** [comment]
Yup, that `lastStarport` has no `ships` key at all.  Are you sure it doesn't only have *modules*, no ships for sale ?

**Comment by Eventure-TCE** [comment]
Please check EDDB: [https://eddb.io/station/2364](url)

**Comment by Athanasius** [comment]
Yes, but that's not what your CAPI data is saying.  We can't give you data that the Frontier API is failing to pass back.

A relevant EDDB-stored EDDN message is https://ross.eddb.io/eddn/log/648294859 - which does indeed show ships for sale.  `EDMC.exe -s` is only using CAPI data, not the journal.  The whole of EDMC.exe is designed to only query the CAPI for such data (it does load the latest Journal it finds so as to set some state).  There's no way to get EDMC.exe to react to the Cmdr opening the shipyard screen which would cause journal data for it to be written.

**Comment by Eventure-TCE** [comment]
That's true, but we got the data as long as I think. 
So do you saying, the shipyard info is not longer available for all stations at the CAPI data, beside the file export of ED, when a player opens the shipyard screen in game?

**Comment by Athanasius** [comment]
This is, at least, a bug on Frontier's side.  If it's not a wholesale change by them.  It will need more investigation (i.e. check more stations, including ones that absolutely always have ships for sale like Jameson Memorial).

We could possibly provide a method to output the desired information from the Journal *if it's actually available* (the Cmdr needs to have opened the screen, and have done so for the latest docked station).

**Comment by Eventure-TCE** [comment]
The shipyard data isn't available at the journal by now, only at the created file called 'Shipyard.json', so I guess we have to wait and maybe report the issue to Frontier, if we have tested it with some more stations.

TCE automatically reads the file, if it was updated. So it is not required to provide support for TCE in that case.
 
Thanks for your help and work and please post an update here, if you got a new info about. Will do the same.

**Comment by Athanasius** [comment]
I've taken the trip out to Gilliland Ring myself and have reproduced the issue.  The **RAW** (from my own code, not EDMC) output from the CAPI for the `/shipyard` endpoint is attached.

[Athanasius-shipyard-2020211-00_LTT 1798_Gillland Ring.json.txt](https://github.com/EDCD/EDMarketConnector/files/5965171/Athanasius-shipyard-2020211-00_LTT.1798_Gillland.Ring.json.txt)

Literally `"shipyard":"ok"` in the services list, but no sign at all of the `ships` list.  In-game I'm looking at the absolutely available (so not closed due to some BGS state, station damage or the like) shipyard: 

![LTT 1798_Gillland Ring_Shipyard](https://user-images.githubusercontent.com/118007/107636960-56e0c580-6c65-11eb-8f49-6156bf20e1b3.png)

**Comment by Athanasius** [comment]
And it turns out we'd already found this issue some time back, see https://discord.com/channels/164411426939600896/251742967927144449/736960475090256013 (EDCD Discord, #edmc channel)

**Comment by Athanasius** [comment]
If you want to add reproductions to the issue I opened: https://issues.frontierstore.net/issue-detail/18441
