### ISSUE TITLE
Authentication not possible via Steam

### ISSUE THREAD

**Issue by wrtlbrmpft** [EDCD/EDMarketConnector#870]
- Version 4.1.6
 - OS: Windows 10
 - OS Locale: English
 - Browser: Chrome

There is no option to authenticate via Steam (see first screenshot).

1. Start E:D Market Connector
2. Start Elite Dangerous via Steam
3. Click 'Update' or dock ship in game
4. Browser shows Fontier - Authentication - Login Screen without any option to login via Steam.

I expect to be able to login via steam (see second screenshot).

![image](https://user-images.githubusercontent.com/15228271/107857940-ad026400-6e31-11eb-8fc2-b1ee9f0223a2.png)
![image](https://user-images.githubusercontent.com/15228271/107858152-facb9c00-6e32-11eb-9b50-77ecaa546df5.png)

**Comment by Athanasius** [comment]
Yes, this is a misfeature.  However, you would have *needed* to create a Frontier account to link the steam purchase to for it to work at all.  You can (I can do this on my Steam-bought account) auth with EDMC using those credentials.

We'll look at widening the scope to include the other possibilities, but it will need testing to be sure it does work with EDMC.

**Comment by Athanasius** [comment]
This is addressed in https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F4.2.0-beta1 - please test.  Of course you should also be aware it is a *beta*, although in this case not too much else has changed (see the changelog) so you should be safe to use this.

**Comment by wrtlbrmpft** [comment]
My test was not successful:
When I start the apllication via
`runas /user:OTHERUSER <path to>EDMarketConnector.exe --force-localserver-for-auth`
as described in [https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F4.2.0-beta1](https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F4.2.0-beta1),
it opens the Frontier authentication dialog in the browser **without** the option to login via Steam.

**Comment by Athanasius** [comment]
Oh bleh, looks like that commit somehow didn't make it into the branch.  Expect a -beta2 tomorrow.

**Comment by Athanasius** [comment]
I put https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F4.2.0-beta2 already.  Works for me.  Note what it says about the exact form of the runas command.

**Comment by wrtlbrmpft** [comment]
Can confirm, it works with the latest release 4.2.0-beta2. Thank you!
