### ISSUE TITLE
auto start EDMC

### ISSUE THREAD

**Issue by nyydynasty** [EDCD/EDMarketConnector#875]
**Describe the enhancement**

Not sure if this has already been requested or confirmed as an upcoming feature but it'd be awesome if the EDMC application automatically starts when Elite Dangerous launches.  I currently added it to my Win10 autostart folder but I dont want this application running when i'm not playing the game.

**Expected behavior**

Auto launch EDMC when E:D launches

**Considered workarounds**

Currently added to Win10 autorun folder

**Additional context**

nothing to add

**Comment by Athanasius** [comment]
Find a way that EDMC, before it runs, can tell when ED starts running and I'll add it.

I'm being facetious.  If EDMC isn't running it can't detect that.  So, yes, you need to just run it along with the game, preferably before.

An alternative it to use some sort of batch file or powershell script to launch both EDMC and ED at the same time.  We even added a command-line argument so EDMarketConnect.exe won't complain if it was already running.

See https://github.com/EDCD/EDMarketConnector/issues/848 and https://github.com/EDCD/EDMarketConnector/issues/833
