### ISSUE TITLE
error git@github.com: Permission denied (publickey). fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by ninjaijr** [EDCD/EDMarketConnector#881]
- OS:OS: Manjaro Linux x86_64
 - Kernel: 5.10.18-1-MANJARO
 - 
 - OS Locale: English

**Describe the bug**
unable to clone repo. i get the error git@github.com: Permission denied (publickey). fatal: Could not read from remote repository.

**To Reproduce**
1. Ran mkdir -p ~/.steam/steam/steamapps/compatdata/359320/pfx/drive_c/users/steamuser/Saved\ Games/Frontier\ Developments/Elite\ Dangerous (verified it was created)
2. Cd to that directory
3. ran git clone git@github.com:EDCD/EDMarketConnector.git
Cloning into 'EDMarketConnector'...
The authenticity of host 'github.com (140.82.114.4)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com,140.82.114.4' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

Also tried running as sudo but with the same error 

**Expected behavior**
i should be able to clone repo to run from source 

**Additional context**
my steam game folder is on a 2nd hard drive 

is there an issue with the repo at the moment?

**Comment by inorton** [comment]
This isn't a bug, clone EDMC over https unless you are using your own github ssh key to clone your own fork.

The public repo to clone is https://github.com/EDCD/EDMarketConnector.git

**Comment by ninjaijr** [comment]
thanks. got it up and running
just a FYI... i was following the steps from https://github.com/EDCD/EDMarketConnector/wiki/Running-from-source

b. git clone git@github.com:EDCD/EDMarketConnector.git

**Comment by Athanasius** [comment]
> just a FYI... i was following the steps from [EDCD/EDMarketConnector/wiki/Running-from-source](https://github.com/EDCD/EDMarketConnector/wiki/Running-from-source)
> 
> b. git clone [git@github.com](mailto:git@github.com):EDCD/EDMarketConnector.git

Fixed.  Thanks.
