### ISSUE TITLE
Authentication not possible (PC)

### ISSUE THREAD

**Issue by MartindForlon** [EDCD/EDMarketConnector#909]
Login with your Frontier account into EDMC (4.2.0) not working on my PC. First time I experience this issue. Frontier Authentication is normally opened, I add email/password (Sign in with Frontier) like usual and press Login ... but then nothing, EDMC still shows trying to log in.

Windows 10
Locale Czech
Browser Firefox 86.0
[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/6136834/EDMarketConnector-debug.log)
[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/6136835/EDMarketConnector.log)
![EDMC](https://user-images.githubusercontent.com/22664864/111072343-7d02bb00-84da-11eb-8c7f-4481fe183a67.jpg)

**Comment by Athanasius** [comment]
1. EDMC started around 08:35, at which time it succeeded in using Refresh Token to get a new Access Token.  It should also have stored the new Refresh Token at this time.
2. Then at 14:53 the game is started and EDMC springs into action...
3. The first attempt to get `/profile` from the CAPI fails with a 401.
4. The attempt then to auth from scratch yields:

```json
2021-03-14 14:53:51.963 - ERROR - companion.Session.dump:591: Frontier CAPI Auth: https://companion.orerve.net/profile 401 Unauthorized {"status":401,"message":"JWT has incorrect\/unexpected fields"}
2021-03-14 14:53:51.965 - DEBUG - companion.Auth.refresh:231: Trying for "Martind Forlon"
2021-03-14 14:53:51.967 - DEBUG - companion.Auth.refresh:235: Cmdrs: ['Martind Forlon', 'Karina Forlon']
2021-03-14 14:53:51.968 - DEBUG - companion.Auth.refresh:238: idx = 0
2021-03-14 14:53:51.969 - DEBUG - companion.Auth.refresh:243: We have a refresh token for that idx
2021-03-14 14:53:51.970 - DEBUG - companion.Auth.refresh:250: Attempting refresh with Frontier...
2021-03-14 14:53:52.418 - ERROR - companion.Auth.refresh:261: Frontier CAPI Auth: Can't refresh token for "Martind Forlon"
2021-03-14 14:53:52.420 - DEBUG - companion.Auth.dump:363: Frontier CAPI Auth: https://auth.frontierstore.net/token 401 Unauthorized {"message":"An error occured.","logref":"2531a26a6ead8695b4af32177402c731"}
2021-03-14 14:53:52.421 - INFO - companion.Auth.refresh:271: Frontier CAPI Auth: New authorization request
2021-03-14 14:53:52.423 - INFO - companion.Auth.refresh:277: Trying auth from scratch for Commander "Martind Forlon"
2021-03-14 14:53:52.598 - DEBUG - companion.Session.login:428: We do NOT have an access_token
2021-03-14 14:53:52.599 - ERROR - companion.Session.query:518: Frontier CAPI Auth: HTTP error or invalid JSON
```

5. This then repeats over and over, ending up without an access_token each time.

**Comment by Athanasius** [comment]
We're going to need some extra logging to see *precisely* what comes back from the Frontier Auth callback.  I'll look into adding some for 4.2.1.

**Comment by Johnat31** [comment]
I am also having this exact same problem.
[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/6137544/EDMarketConnector.log)


Windows 10
Firefox 86.0.1

**Comment by Athanasius** [comment]
Having worked on a branch to add some extra logging I'm wondering if this is only related to the edmc:// protocol handler.

Could anyone experiencing this try launching EDMarketConnector.exe with the `--force-localserver-for-auth` argument so that it uses a localhost:// listening local webserver instead ?

`"c:\Program Files (x86)\EDMarketConnector\EDMarketConnector.exe" --force-localserver-for-auth`

in a `Command Prompt` (`cmd.exe`) window will do this.

I'll still want to track down the actual cause, but this might get Auth working for you in the meantime.

**Comment by MartindForlon** [comment]
That link above is little wrong :)

copy this:
`c:\Program Files (x86)\EDMarketConnector\EDMarketConnector.exe --force-localserver-for-auth`

I tried it on my laptop (where I have the same issue now as was yesterday on my gaming PC) and it is working.

**Comment by Athanasius** [comment]
So, something is wrong, but only for some people, with the code for the `edmc://` protocol handler.

My first guess is firewall/anti-virus.  I know when I used to run Comodo Personal Firewall it blocked some DDE calls, which this relies on.  So, do any of you with this not working (without the `--force-localserver-for-auth ` argument) have an AV/firewall ?  If so, check the logs in it to see if decided to block this.

It would have been a DDE call from your web browser of type DDE_EXECUTE, with arguments something like:

    open("edmc://auth...")

**Comment by Johnat31** [comment]
have added the extra line and is now working I am using avast av with firewall along with windows firewall but can see no mention of dde calls

**Comment by MartindForlon** [comment]
I also have avast/windows defender combo ... I see nothing there, but I'm not sure which logs exactly I should check, there was not any report that edmc might cause problems. I also did not any changes to both (they uses practically default settings). Prior this last edmc version I had no issues with authentication.

**Comment by Athanasius** [comment]
https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F4.2.1 is now available with the extra logging for this issue.  If you can reproduce it then please attach your latest debug log file to this issue.

**Comment by MartindForlon** [comment]
With a 4.2.2 I logged now into frontier without issues on laptop. Will check this later today also on my gaming PC and will report back.

**Comment by MartindForlon** [comment]
Sorry folks ... on my gaming PC it doesnt work right now, but I cannot access some websites and also discord suddenly stopped working, so it can be just internet connection failure for here.

**Comment by Johnat31** [comment]
Seems to be working normally now thanks

**Comment by MartindForlon** [comment]
Seems local connection issue only. EDMC authentication is now working smoothly. Thanks!

**Comment by StevenNuke** [comment]
Hi, i have also same problem since v4.2.0. (excuse please my english)

[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/6162752/EDMarketConnector.log)

I trying turn off AV and FW and nothing change. To user section frontierstore i can login normaly, also trying deauthorise EDMC and new start. Authorization here is proceede normaly, but Connector still cant take token from Frontier. I really dont know, what can i do.

**Comment by Athanasius** [comment]
> Hi, i have also same problem since v4.2.0. (excuse please my english)
> 
> [EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/6162752/EDMarketConnector.log)
> 
> I trying turn off AV and FW and nothing change. To user section frontierstore i can login normaly, also trying deauthorise EDMC and new start. Authorization here is proceede normaly, but Connector still cant take token from Frontier. I really dont know, what can i do.

Two things:

1. It looks like something is preventing your web browser from invoking the DDE path for communicating the successful authentication back to EDMC.  This definitely works with Windows 10 Home and latest Firefox as the browser, that's how I test it.
2. But it does look like we lost a bit of code somehow, for handling the auth callback being invoked by running the program again.  I'll look into that and likely put out a 4.2.3 later today.  In the log (and this means we do need to be checking the 'raw' log file, not just the debug one):

    ```    
    usage: EDMarketConnector [-h] [--trace] [--suppress-dupe-process-popup]
                         [--force-localserver-for-auth]
    EDMarketConnector: error: unrecognized arguments: edmc://auth/?code=...
    ```

**Comment by StevenNuke** [comment]
So, i tried latest Firefox as main browser, as you say. Still off AV and FW. Still same result, unfortunately.

**Comment by Athanasius** [comment]
Yeah, we somehow lost that bit of code I mentioned in point 2.  I've just added it back and have been testing that it now works.

I'm still puzzled as to why anyone's system would be failing to invoke the DDE path for this in the first place though.

Could you please open `regedit.exe` and then paste in `Computer\HKEY_CLASSES_ROOT\edmc\shell\open` to the location bar and verify there's a `ddeexec` folder inside that, with a single `Default` key with value `Open("%1")` ?  It should look like this:

![EDMC-ddeexec-registry](https://user-images.githubusercontent.com/118007/111609641-6ad29680-87d2-11eb-80e1-d59a9d252266.png)

**Comment by StevenNuke** [comment]
Yes, is it there.
![aaa](https://user-images.githubusercontent.com/80885608/111610331-85f5d400-87db-11eb-8dcc-62e196113c0c.jpg)

**Comment by Athanasius** [comment]
> Yes, is it there.

Yet for some reason, even with Firefox, on your system the DDE method isn't invoked.  A quick web search doesn't turn up anything.  I can only suspect AV/security software blocking it.  NB: That could be:

1. Blocking Firefox from even seeing the registry entry
2. Blocking Firefox from sending the DDE message
3. Blocking EDMarketConnector.exe from listening to DDE messages
4. Blocking the specific DDE message from being delivered to EDMarketConnector.exe

Anyway, 4.2.3, which I'll put out in a few hours time at most, should fix this, assuming that EDMarketConnector.exe is still allowed to use ShellExecute() to send the DDE message (from the extra process your browser starts) back to the main EDMarketConnector.exe process.

If *that* doesn't work, then I advise to launch EDMarketConnector.exe with `--force-localserver-for-auth` argument to use the non-DDE method:

`"c:\Program Files (x86)\EDMarketConnector\EDMarketConnector.exe" --force-localserver-for-auth`

**Comment by StevenNuke** [comment]
Ah, this method working, im not tried this before. Now is authorisation successful.

**Comment by Athanasius** [comment]
@MartindForlon @Johnat31 @StevenNuke Please try https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F4.2.3 **without** the `--force-localserver-for-auth` argument.  Report back if it still doesn't work (and then use `--force-localserver-for-auth` in the meantime).

**Comment by StevenNuke** [comment]
Yes, this version is working for me. Launch via MS Edge and without `--force-localserver-for-auth`. Before try i manualy deauthorized EDMC via `user,frontierstore,net` and new authorization was successful. Thank you so much, I can't even imagine Elite without EDMC :)

**Comment by MartindForlon** [comment]
All works for me now, tested on my gaming PC. I'm running Firefox and edmc was newly authorised (I removed old authorisation first) without any argument. Thanks much!

**Comment by Leif-The-Head** [comment]
So I've been experiencing this again for the last month or so. EDMC is a few versions further now, tried every step listed here. Deauthorised on frontier site, which got me past the login prompt, but then clicking approve wouldn't do anything.
Now I started using `--force-localserver-for-auth` after another deauth, which turned out to be successful. After a restart it still would work, so I deauthed again and started again using no argument, and since then it apparently works as intended.

While that is technically resolved for me, I'd assume this isn't intended behaviour, also this might help others that come across this issue that is supposedly fixed since last major version.

Oddly enough, seems like the callback from auth tried to start another instance - at least I clicked the login twice here. This is before I fiddled with it:
```2022-02-26 10:35:30.029 UTC - DEBUG - 10100:18672:18672 companion.Session.login:678: changed account or retrying login during auth
2022-02-26 10:35:30.030 UTC - DEBUG - 10100:18672:18672 companion.Auth.refresh:323: Trying for "Leif"
2022-02-26 10:35:30.031 UTC - DEBUG - 10100:18672:18672 companion.Auth.refresh:327: Cmdrs: ['Leif']
2022-02-26 10:35:30.031 UTC - DEBUG - 10100:18672:18672 companion.Auth.refresh:330: idx = 0
2022-02-26 10:35:30.032 UTC - DEBUG - 10100:18672:18672 companion.Auth.refresh:335: We have a refresh token for that idx
2022-02-26 10:35:30.033 UTC - DEBUG - 10100:18672:18672 companion.Auth.refresh:342: Attempting refresh with Frontier...
2022-02-26 10:35:30.241 UTC - ERROR - 10100:18672:18672 companion.Auth.refresh:359: Frontier CAPI Auth: Can't refresh token for "Leif"
2022-02-26 10:35:30.241 UTC - DEBUG - 10100:18672:18672 companion.Auth.dump:532: Frontier CAPI Auth: failed with `r` False: <Response [401]>
2022-02-26 10:35:30.242 UTC - INFO - 10100:18672:18672 companion.Auth.refresh:371: Frontier CAPI Auth: New authorization request
2022-02-26 10:35:30.243 UTC - INFO - 10100:18672:18672 companion.Auth.refresh:377: Trying auth from scratch for Commander "Leif"
2022-02-26 10:35:30.260 UTC - DEBUG - 10100:18672:18672 companion.Session.login:694: We do NOT have an access_token
[...] Canonn Plugin logging
2022-02-26 10:35:41.379 UTC - INFO - 12704:2096:2096 journal_lock.JournalLock._obtain_lock:106: Exception: Couldn't lock journal directory "C:\Users\Leif\Saved Games\Frontier Developments\Elite Dangerous", assuming another process running: PermissionError(13, 'Permission denied')
2022-02-26 10:35:41.381 UTC - INFO - 12704:2096:2096 EDMarketConnector.__main__:353: An EDMarketConnector.exe process was already running, exiting.
2022-02-26 10:35:59.928 UTC - INFO - 19680:10264:10264 journal_lock.JournalLock._obtain_lock:106: Exception: Couldn't lock journal directory "C:\Users\Leif\Saved Games\Frontier Developments\Elite Dangerous", assuming another process running: PermissionError(13, 'Permission denied')
2022-02-26 10:35:59.930 UTC - INFO - 19680:10264:10264 EDMarketConnector.__main__:353: An EDMarketConnector.exe process was already running, exiting.
```

And now, after I did all that:
```2022-02-26 10:52:24.146 UTC - DEBUG - 14816:8288:8288 companion.Session.login:678: changed account or retrying login during auth
2022-02-26 10:52:24.147 UTC - DEBUG - 14816:8288:8288 companion.Auth.refresh:323: Trying for "Leif"
2022-02-26 10:52:24.148 UTC - DEBUG - 14816:8288:8288 companion.Auth.refresh:327: Cmdrs: ['Leif']
2022-02-26 10:52:24.149 UTC - DEBUG - 14816:8288:8288 companion.Auth.refresh:330: idx = 0
2022-02-26 10:52:24.149 UTC - DEBUG - 14816:8288:8288 companion.Auth.refresh:335: We have a refresh token for that idx
2022-02-26 10:52:24.150 UTC - DEBUG - 14816:8288:8288 companion.Auth.refresh:342: Attempting refresh with Frontier...
2022-02-26 10:52:24.393 UTC - DEBUG - 14816:8288:8288 companion.Session.login:688: We have an access_token
2022-02-26 10:52:24.394 UTC - DEBUG - 14816:8288:8288 companion.Session.start_frontier_auth:642: Starting session
[...] Canonn Plugin logging
```

**Comment by Athanasius** [comment]
> So I've been experiencing this again for the last month or so. EDMC is a few versions further now, tried every step listed here. Deauthorised on frontier site, which got me past the login prompt, but then clicking approve wouldn't do anything. Now I started using `--force-localserver-for-auth` after another deauth, which turned out to be successful. After a restart it still would work, so I deauthed again and started again using no argument, and since then it apparently works as intended.
> ```
> 2022-02-26 10:35:30.260 UTC - DEBUG - 10100:18672:18672 companion.Session.login:694: We do NOT have an access_token
> [...] Canonn Plugin logging
> 2022-02-26 10:35:41.379 UTC - INFO - 12704:2096:2096 journal_lock.JournalLock._obtain_lock:106: Exception: Couldn't lock journal directory "C:\Users\Leif\Saved Games\Frontier Developments\Elite Dangerous", assuming another process running: PermissionError(13, 'Permission denied')
> 2022-02-26 10:35:41.381 UTC - INFO - 12704:2096:2096 EDMarketConnector.__main__:353: An EDMarketConnector.exe process was already running, exiting.
> ```

This implies there's something going wrong with the "is another process running?  Yes, does this invocation have the edmc:// argument? Yes, forward the message" code in your use case.  Using `--force-localserver-for-auth` explicitly avoids that scenario.  There's a small possibility that an anti-virus/software firewall could interfere with the edmc:// process.

**Comment by Athanasius** [comment]
@ergose Try deauthorizing EDMC:

1. Go to <https://user.frontierstore.net/>
2. Login
3. Approve
4. Click 'Authorized Applications' from the menu on the left -> <https://user.frontierstore.net/linked>
5. Find "Elite Dangerous Market Connector (EDCD/Athanasius)"
6. Click the "DEAUTHORISE" button on that line.
7. Try EDMC login again (restart if needs be to trigger it).

**Comment by Athanasius** [comment]
Also, for *everyone* reporting issues with Frontier Auth and EDMC, please always state what kind of account you're trying it with: Frontier, Steam or Epic (Games Store).

**Comment by ergose** [comment]
Update to above. I just thought to try `edmc://auth` in a new tab to see what would happen (Edge). I get a pop-up: 'This site is trying to open EDMarketConnector.exe. A website wants to open this application.'. Clicking that 'Open' button then results in 'malformed payload'. May be nothing, but felt best to add it.

@Athanasius  - Trying that now. As for account type. I have a Frontier account with a different login, but it's linked to my Steam account. Steam is where I bought and installed Elite from.

**Comment by Athanasius** [comment]
> Update to above. I just thought to try `edmc://auth` in a new tab to see what would happen (Edge). I get a pop-up: 'This site is trying to open EDMarketConnector.exe. A website wants to open this application.'. Clicking that 'Open' button then results in 'malformed payload'. May be nothing, but felt best to add it.

Yes, going to only `edmc://` will result in an error, because it's meant to have the response code on the end of it.  If it wasn't doing that in the normal auth flow (i.e. your browser not showing that pop-up, or otherwise proceeding) then that points to the issue being at Frontier's end.  All we pass is the information in that URL you cited/elided, asking for the response to be sent to `edmc://`.
 
> @Athanasius - Trying that now. As for account type. I have a Frontier account with a different login, but it's linked to my Steam account. Steam is where I bought and installed Elite from.

That counts as a Steam account.  I'd try always doing this using the Steam option on the frontier website, not the Frontier account login.  You'd hope Frontier would realise it's a Steam account in this case and always do the right thing, but ....

**Comment by ergose** [comment]
@Athanasius - Well. Wasn't expecting that. This time it may be Frontier-side. Got to Step 2, logged in. Same behavior. Login page refreshes and doesn't go further. 

To clarify, If I login from the 'www' site and try to login via that form then, no issues. From user.frontierstore.net -> auth.frontierstore.net or via the EDMC tab open. Same behavior.

**Comment by Athanasius** [comment]
> @Athanasius - Well. Wasn't expecting that. This time it may be Frontier-side. Got to Step 2, logged in. Same behavior. Login page refreshes and doesn't go further.
> 
> To clarify, If I login from the 'www' site and try to login via that form then, no issues. From user.frontierstore.net -> auth.frontierstore.net or via the EDMC tab open. Same behavior.

If you can't even login to user.frontierstore.net then contact Frontier support as it's definitely an issue their end.

**Comment by ergose** [comment]
@Athanasius  - Bingo. Got it. Thanks. You're comment on using the Steam option nagged on me so I tried it with fresh open of EDMC. It redirected to Steam and I logged in that way. That worked on Frontier's site and sent me to the Approve page. Clicked Approve and then EDMC now says 'Authentication Successful'

Further suggesting Frontier change/issue after clicking the approve button...
```
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.
```

**Comment by Leif-The-Head** [comment]
> Also, for _everyone_ reporting issues with Frontier Auth and EDMC, please always state what kind of account you're trying it with: Frontier, Steam or Epic (Games Store).

> That counts as a Steam account. I'd try always doing this using the Steam option on the frontier website, not the Frontier account login. You'd hope Frontier would realise it's a Steam account in this case and always do the right thing, but ....

This is indeed a weird behaviour. Had to come back here since my authentication period ran out.
Trying today with Frontier Acc no dice, although it worked last time.
Using Steam Acc first try.
Now the jist: I'm running on an account that predates Elite being on Steam, I've only switched to a Steam installation to use VR more than a year ago, and every other login on account-related frontier pages worked *better* using the frontier login over the Steam login.
I should try this again with my second account which doesn't officially run on steam (also predating Elite on Steam) and never retrieved a code for it, but having it used through the same Steam installation in the past.

**Comment by mpetricone** [comment]
[EDMarketConnector-debug.log](https://github.com/user-attachments/files/17142042/EDMarketConnector-debug.log)
[EDMarketConnector.log](https://github.com/user-attachments/files/17142092/EDMarketConnector.log)
 
Version 5.12.0+cc6e200

I'm no longer to login after the latest update. With similar symptoms as above .  I recently install EDCopilot, I don't know if that might affect anything.
