### ISSUE TITLE
Not launching (Linux)

### ISSUE THREAD

**Issue by bjorkalx** [EDCD/EDMarketConnector#910]
I have tried running from source and installing the AUR package. Python 3.8 and 3.9 gives me basically the same error.

```
Traceback (most recent call last):
  File "/usr/lib/edmarketconnector/./EDMarketConnector.py", line 188, in <module>
    journal_lock = JournalLock()
  File "/usr/lib/edmarketconnector/journal_lock.py", line 26, in init
    self.journal_dir_path = pathlib.Path(self.journal_dir)
  File "/usr/lib/python3.9/pathlib.py", line 1071, in new
    self = cls._from_parts(args, init=False)
  File "/usr/lib/python3.9/pathlib.py", line 696, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python3.9/pathlib.py", line 680, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by SamathyTheManathy** [comment]
I have a similar error, this is what it looks like in Python 3.8

python3 EDMarketConnector.py

Traceback (most recent call last):
  File "EDMarketConnector.py", line 186, in <module>
    journal_lock = JournalLock()
  File "/home/samtheon/Downloads/EDMarketConnector-stable/journal_lock.py", line 36, in __init__
    self.journal_dir_path = pathlib.Path(self.journal_dir)
  File "/usr/lib/python3.8/pathlib.py", line 1038, in __new__
    self = cls._from_parts(args, init=False)
  File "/usr/lib/python3.8/pathlib.py", line 679, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python3.8/pathlib.py", line 663, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by A-UNDERSCORE-D** [comment]
@bjorkalx  @SamathyTheManathy these fresh installs?

**Comment by A-UNDERSCORE-D** [comment]
Also, what branch?

**Comment by SamathyTheManathy** [comment]
Freshly installed and stable.

**Comment by A-UNDERSCORE-D** [comment]
Ah yes I see the issue. Been poking about. Develop will work for you for now, if you're happy with using it (I do daily, it should be stable.) 

For me for later:
JournalLocks constructor asks for either the config defined journal location or the default one. On linux, that default is None, thus making pathlib explode. Fix that is in develop just stringifies None, so it'll probably still error down the line, but it should at least manage to start. We should _probably_ check if the dir exists, for the develop case, but I'll look at this more tomorrow when Im likely to be more awake / ath is around to poke at

**Comment by SamathyTheManathy** [comment]
Not a problem, thanks for the quick fix!

**Comment by A-UNDERSCORE-D** [comment]
Poke me in our discord if you still have an issue, it's a reasonably simple patch

**Comment by Athanasius** [comment]
Ah, and I was so close to fixing this when looking at macOS, except it has a default for journal_dir.

Yeah, can fix later today for 4.2.1 that we already have a few other fixes queued for.

**Comment by Athanasius** [comment]
https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F4.2.1 is now available, also in the `stable` branch that should fix this.

**Comment by Athanasius** [comment]
@bjorkalx @SamathyTheManathy Did you get chance to test 4.2.1 or later (4.2.3 is now out), or fresh pull of `stable` as the same code is in there now ?

**Comment by bjorkalx** [comment]
> @bjorkalx @SamathyTheManathy Did you get chance to test 4.2.1 or later (4.2.3 is now out), or fresh pull of `stable` as the same code is in there now ?

Tested 4.2.1 and 4.2.2, all good.

**Comment by SamathyTheManathy** [comment]
Sorry for the late reply, 4.2.2 works! Thanks a lot :)
