### ISSUE TITLE
edmc generates 67GB log file overnight!?

### ISSUE THREAD

**Issue by feiercrack** [EDCD/EDMarketConnector#918]
i let my pc run last night.
when i woke up, i saw that my C: drive is almost full.
after 1hr search i´ve found that edmc generated an 67 !!! GB large Log file in
C:\Users\*****\AppData\Local\EDMarketConnector\

What is that?

**Comment by Athanasius** [comment]
If it's that location then it's not core EDMC code.  This points to a plugin.

Core EDMC code logs into:

`%LOCALAPPDATA%\Temp\EDMarketConnector.log` - for the latest session only, size unrestricted.
`%LOCALAPPDATA%\Temp\EDMarketConnector\EDMarketConnector-debug.log` - This file is limited to 10MiB at most, and then rotated up to ten times to EDMarketConnector-debug.1.log etc.

**Comment by Athanasius** [comment]
If you erroneously missed out `Temp` in your report then it's possible it's the main log file growing to that size because you're frequenting Damaged Stations and/or Fleet Carriers without certain services.  I'm just about to gather more data in-game to help track this down and fix it.

**Comment by feiercrack** [comment]
what u mean with "missed out Temp in your report"? i dont understand -.-
i had following plugins installed: EDR 1.0.7 (old version), SpanshRouter 3.0.3 (also old), Cannon 5.25, DistanceCalc 1.24, RSE 1.3.1
i did not visited any station at all during last night. my NPC pilot was fighting against pirates, alone, until my ship got destroyed sometime last night. 
My SSD was 80GB left over size, when i came back, 10hrs later, it was only 13GB left

**Comment by Athanasius** [comment]
What I mean is that the location you've reported as containing the 'spam' is not where the core application logs to.

It's where the third-party plugins are installed, and thus it is one of your plugins that will be to blame, not the core code.

I suggest you look into *where* under `C:\Users*****\AppData\Local\EDMarketConnector\` is using up all the space to know which plugin it is, and report the bug to the developer of that plugin.

**Comment by feiercrack** [comment]
all right. got ya^^
i think it was the "edmcoverlay.log" file, which i´ve deleted... i updated all the edmc plugins, also the EDR, which contains the overlay. i will have an eye on that for now. maybe they fixed that already in the current, updated version^^
thanks
cheers

**Comment by A-UNDERSCORE-D** [comment]
This is an EDMC Overlay bug that was fixed in 2018, for anyone looking through EDMC issues: https://github.com/inorton/EDMCOverlay/issues/16

**Comment by feiercrack** [comment]
as the EDR Central guys in discord told me, i now installed the EDMCOverlay separately as Stand-Alone. Will check if that helps
quote:
It happens when you restart EDMC while the overlay and Elite are running https://github.com/inorton/EDMCOverlay/issues/16
Using the standalone EDMCOverlay can solve that, EDRecon doesn't ship with the latest version because of some issues but if you install your own it will use it.
https://github.com/inorton/EDMCOverlay/issues/16
Otherwise the workaround is to
 Exit Elite or terminate the EDMCOverlay process and delete the log if the file remains.
quote end:
