### ISSUE TITLE
Message: "Got an auth callback while not doing auth" not translated

### ISSUE THREAD

**Issue by mIRCon** [EDCD/EDMarketConnector#925]
Message: "Got an auth callback while not doing auth" seems to be hardcoded since it doesn't exist in onesky translations keywords.
![image](https://user-images.githubusercontent.com/40735411/111906369-80ed8a80-8a50-11eb-853e-4c5175dae5dc.png)

**Comment by Athanasius** [comment]
We should do a general review of all uses the status text (although it won't catch where some exception text ends up in there) and preferences.

**Comment by Athanasius** [comment]
To be honest this particular message is more of an internal thing rather than "for the user".  By that I mean that I don't think it's actually going to help the ordinary user to have this text in their own language.  "What's an auth callback?" is one likely response.
