### ISSUE TITLE
Put Suit/Loadout information on Status panel

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDMarketConnector#956]
This should go on its own new tab of the notebook.  Maybe just the suit info, but if loadout as well, maybe that should also get a tab.
[Athanasius-profile-20210329-00.json.txt](https://github.com/EDCD/EDMarketConnector/files/6223578/Athanasius-profile-20210329-00.json.txt)

**Comment by Rixxan** [comment]
@Athanasius not sure why this was reopened - was there something missing from the original?

**Comment by Athanasius** [comment]
> @Athanasius not sure why this was reopened - was there something missing from the original?

\_O_/  It's almost 3 years ago now.  I'd have to look at the state of it when running the game to be sure, and I don't even have it installed any more.

It's possible it was simply a case of "closed it before the release with this in was made".

**Comment by Rixxan** [comment]
Well, given that this *appears* to have been completed, going to re-close as complete.
