### ISSUE TITLE
Wrong `StarPos` enrichment for `Scan` event

### ISSUE THREAD

**Issue by bgol** [EDCD/EDMarketConnector#961]
- Version 4.2.5
 - Game Version 'Live'

**Describe the bug**
While listening to EDDN I found out that EDMC does sent out wrongly enriched `Scan` messages.
[EDMC-Scan-Enrichment-Bug_more.txt](https://github.com/EDCD/EDMarketConnector/files/6238704/EDMC-Scan-Enrichment-Bug_more.txt)

**To Reproduce**
1. Listen to EDDN
2. Compare known `StarPos` with sent one

**Expected behavior**
Don't send wrong data.

**Additional context**
https://github.com/EDCD/EDMarketConnector/blob/74a1ca6df81ff2a53b1c65ea8c73adbc72136fbd/plugins/eddn.py#L834-L837

```python

if 'StarPos' not in entry:
    if not this.coordinates:
        logger.warning("this.coordinates is None, can't add StarPos")
        return "this.coordinates is None, can't add StarPos"
    if entry['StarSystem'] != system:
        logger.warning("system is different from event StarSystem")
        return "system is different from event StarSystem"
```

**Comment by Athanasius** [comment]
FYI: I just reviewed the EDDN plugin handling of 'timestamp' and for this case it absolutely comes from the Journal timestamp.  So definitely looks like the game logged a delayed Scan even after FSDJump.  The only exceptions to that are for CAPI sourced data for commodites, outfitting and shipyard, when the timestamp comes from that in the CAPI data (which IIRC actually comes from the HTTP response headers).

**Comment by Athanasius** [comment]
Fix is in https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F4.2.6
