### ISSUE TITLE
intermittent authentication issues with EDMC client

### ISSUE THREAD

**Issue by timothyfox443** [EDCD/EDMarketConnector#993]
**Please check the [Known Issues](https://github.com/EDCD/EDMarketConnector/issues/618) in case this has already been reported.**

**Please also check if the issue is covered in our [Troubleshooting Guide](https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting).** It might be something with a known work around, or where a third party (such as EDSM) is causing logging that is harmless.

**Please complete the following information:**
 - Version [e.g. 4.0.6 - See 'Help > About E:D Market Connector'.  If running from source using git then please paste the output of `git log --decorate=full | head -1`]
 - Game Version [e.g. 'Live' or 'Odyssey Alpha']
 - OS: [e.g. Windows 10, Linux Debian 10.6, etc.]
 - OS Locale: [e.g. English, French, Serbian...]
 - If applicable: Browser [e.g. chrome, safari]
 - Please attach **BOTH** log files as follows:
     1. `%TEMP%\EDMarketConnector.log
[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/6292751/EDMarketConnector.log)
` from *immediately* after the bug occurs (re-running the application overwrites this file).
     1. %TEMP%\EDMarketConnector\EDMarketConnector-debug.log`.  See [Debug Log File](https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting#debug-log-files).  NB: If you don't have this log file then you're not running the latest version of the application and should update first to see if we already fixed the bug you're reporting.
   
   Use the Icon that looks like `_`, `|` and `^` all in one character towards the right of the toolbar above.

**Describe the bug**
-->upon attempting to authenticate EDMC, recently there have been problems in getting the client to authenticate.  I have had to re-authorize the client every time I open it.

**To Reproduce**
1.  open the client (double clicking the EDMC shortcut on my desktop linked to 
     "C:\Program Files (x86)\EDMarketConnector\")
2. a browser window in chrome will open and ask to authorize EDMC via Frontier 
    Development's portal.
3. Authentication succeeds.
4. close the application
5. repeat steps 1-4

**Expected behavior**
Authentication should be valid until the client is updated or FD closes the account or the client is no longer authorized.
[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/6292746/EDMarketConnector-debug.log)

**Screenshots**

**Additional context**

**Comment by Kirby207** [comment]
Just to add a second voice, this issue started for me last night suddenly. 

I *just* arrived at a "fix" (?) - I ran the program NOT AS ADMINISTRATOR and the authentication went through instantly. I imagine most of us force it to run as admin so EDMCOverlay works properly. After the auth went through I was able to close it and re-run as admin and it kept the 30 day Frontier API auth.

**Comment by Athanasius** [comment]
> I _just_ arrived at a "fix" (?) - I ran the program NOT AS ADMINISTRATOR and the authentication went through instantly.

From https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting#i-ran-the-program-with-quot-run-as-administrator-quot-and :

> Don't do that. There's zero reason to run ED Market Connector as Administrator and it will then be looking for, and storing, settings in "Administrator"'s registry section and will be looking for the game Journal files inside the Admin account's files, rather than your user's.
> That would then require you to run the game as Administrator as well, and there's also NO reason to do that.
> Just run things as your normal user. The installation of this application will throw up a UAC prompt as and when it needs extra privileges for the install. After that all file access in the installation folder is then read-only (any output is directed within your user's file area, or other location chosen by you).

EDMCOverlay needing to be run as Administrator is its own issue.  If you really must do that, then as above, you'll need to be running both EDMC and the game as Administrator as well so that things like Registry keys line up.

**Comment by Athanasius** [comment]
In the OP's case it was TCE using EDMC.exe (the command-line utility, not the main GUI program) in the background that was causing extra authentication attempts.

5.0.0-beta5 that just put out also has new code to double-check that the returned Access Token is actually for the current Commander and will inform you if it's not.
